### ISSUE TITLE
Links are not correctly recognized

### ISSUE THREAD

**Issue by Xebtria** [Kyusung4698/PoE-Overlay#100]
https://i.imgur.com/hFO5brZ.png
the item is a 4+2L, but the is incorrectly recognized as a 5L

https://i.imgur.com/YDMsojO.png
This one is a 2+2L, but is incorrectly recognized as a 3L

► only the highest link on an item should count for the filter, not the "combined" count

**Comment by Kyusung4698** [comment]
Fixed with 0.5.2
