### ISSUE TITLE
suggestion: itemlevel should not be default selected

### ISSUE THREAD

**Issue by Xebtria** [Kyusung4698/PoE-Overlay#101]
99% of all rare item pricing and 100% of all unique item pricing cases don't give a shit about item level, so don't have it be selected by default. 

also, if it is selected it is only the fixed item level (min and max are the same), which severely restricts the items found as well, at least have the max itemlevel open like with the other stats as well.

**Comment by Xebtria** [comment]
Note: same is true for the item base. restricting rare pricing on the specific item base of the item is not a good idea (at least not by default), so don't select this by default either.

**Comment by Kyusung4698** [comment]
![menu_0 5 2](https://user-images.githubusercontent.com/38520678/72761308-eb503400-3bdb-11ea-8889-70be315078ae.jpg)

Added with 0.5.2. Thanks for sharing.
