### ISSUE TITLE
Bug? Suggetion? Change search to online only or add option for it.

### ISSUE THREAD

**Issue by jbdaytona** [Kyusung4698/PoE-Overlay#102]
All of my searches are defaulting to "Any" instead of "Online Only". Most of my searches I do not care about users who are offline. It tends to fill the search results with items that are from the start of the league that are grossly under priced.  I don't see an option to change this anywhere? Maybe add a option to search for online only?

**Comment by Kyusung4698** [comment]
There is indeed an option for this. You can find it in the menu on the evaluate tab - it's called 'online only'
![Menu](https://raw.githubusercontent.com/Kyusung4698/PoE-Overlay/master/img/menu_0.5.0.jpg)

**Comment by Kyusung4698** [comment]
I'll close this issue for now. Please feel free to re-open if this does not fits your needs.
