### ISSUE TITLE
Allow option to open in default browser

### ISSUE THREAD

**Issue by jarekb84** [Kyusung4698/PoE-Overlay#103]
The ingame browser display is a nice touch, but allowing the search results to open in a new tab in the users default browser has other benefits
- can copy the url to share with others or save for later personal use
- can view in full window (useful when you have mutli monitors)
- can continue refining the selected settings in the overlay ui and not get the ding sound cause i'm not interacting with the window that's in focus

**Comment by Kyusung4698** [comment]
You can open the search in the default browser by using `CTRL + Click`. I've also added a title to the button text to better highlight this feature. I'll close this for now. Feel free to re-open if this solution doesn't meet your requirements.

**Comment by jarekb84** [comment]
Ah good to know. It wasn't listed in the readme. Are there any other undocumented shortcuts like this?
