### ISSUE TITLE
Add toggle to show online/offline in the popup ui

### ISSUE THREAD

**Issue by jarekb84** [Kyusung4698/PoE-Overlay#104]
There's a toggle in the settings to let you flip back and forth, but would be better to include this in the popup overlay since there are times when one option makes sense over another. 

online only makes more sense when the item being searched for has a high supply
including offline makes sense when there aren't many items up on search (sometimes none at all) but you can get an idea of price.

Including a symbol somewhere near the top to switch between the modes would be idea. The settings page setting could still define what the default value is, but a local instance can overwrite that when it makes sense.

**Comment by Kyusung4698** [comment]
I see. Seems like a good idea. Will be added. Thanks for posting!

**Comment by Kyusung4698** [comment]
![image](https://user-images.githubusercontent.com/38520678/73141292-dca5c900-4082-11ea-851d-68c1a35c6144.png)

Has been added with 0.5.8. Thanks for your suggestion! 🚀
