### ISSUE TITLE
Add action to clear all selected filters

### ISSUE THREAD

**Issue by jarekb84** [Kyusung4698/PoE-Overlay#105]
I often find myself hitting ctrl+d then unclicking the i level, item name, and sockets cause they're not relevant to the search. I could also see cases where I clicked a few of the mods, but they turned out to be useless, so a quick way to reset all filters would be nice.

**Comment by Kyusung4698** [comment]
![menu_0 5 2](https://user-images.githubusercontent.com/38520678/72760964-c14a4200-3bda-11ea-9616-a1866758fb68.jpg)

I've added a few more togglers to seperate item level, item type and sockets. Although a reset button seems reasonable.

**Comment by Kyusung4698** [comment]
![image](https://user-images.githubusercontent.com/38520678/73141285-be3fcd80-4082-11ea-8ce5-865d1cb7630b.png)

Thanks for your suggestion. Has been added with 0.5.8.
