### ISSUE TITLE
Suggestion:  Ctrl+F functionality for highlighting Items

### ISSUE THREAD

**Issue by mobaki** [Kyusung4698/PoE-Overlay#106]
Is it possible to add Ctrl+F functionality for highlighting items in the stash like in the og trade macro

![2](https://user-images.githubusercontent.com/59966897/72738185-53cdef80-3ba1-11ea-9acb-f2d5c8daea40.png)

**Comment by Kyusung4698** [comment]
Seems like a neat feature. I like it. Thanks for sharing!

**Comment by Kyusung4698** [comment]
Added with 0.5.3 (2020-01-21)
* add stash highlight (CTRL + F) (#106)
