### ISSUE TITLE
Suggestion: Addition on price check

### ISSUE THREAD

**Issue by S1ROZHA** [Kyusung4698/PoE-Overlay#109]
example: u have evaluation 2 currency (example: chaos and exalted).
if u check price on item and item have price < exalted = price view on chaos, if price >= exalted = price view on exalted.

**Comment by Kyusung4698** [comment]
So basically a mixed view? Graph shows Chaos AND Exalts values IF the value exceeds the minimum threshold. Correct?

**Comment by Kyusung4698** [comment]
Closed.
