### ISSUE TITLE
Blight Maps pull up the Blight Gems

### ISSUE THREAD

**Issue by Jakenoff** [Kyusung4698/PoE-Overlay#11]
As the title states, searching a Blight Map pulls up the Blight gem.

![image](https://user-images.githubusercontent.com/59591413/71866548-79a0c200-30d4-11ea-95c8-3e837af924b6.png)

**Comment by Kyusung4698** [comment]
I'll add a category check within the next upcoming version. Thanks for reporting.

**Comment by Kyusung4698** [comment]
0.4.2 now has category filter.
