### ISSUE TITLE
Suggestion: Ability to price check maps occupied by Elder & Shaper Guardians

### ISSUE THREAD

**Issue by ArkanePanda** [Kyusung4698/PoE-Overlay#110]
![Annotation 2020-01-21 163001](https://user-images.githubusercontent.com/60131175/72787810-952ad180-3c6b-11ea-9eb8-d89af340ced9.png)

As you can see from the picture, at the moment there's no option to price check elder & guardian maps so would greatly appreciate if you could add it in the future

**Comment by Kyusung4698** [comment]
Thanks for reporting. Those stats require extra handling as these are text options and none numeric values. I'll look into it.

**Comment by Kyusung4698** [comment]
## 0.5.11 (2020-01-30)

* add option based stat support (#110)
    * influenced by #
    * occupied by #

**Comment by WhiteFang5** [comment]
@Kyusung4698 perhaps you could look into auto-selecting these modifiers when price-checking the map? (Similar to how "total max life" is auto selected when searching)
