### ISSUE TITLE
Overlay does not work on non primary monitor

### ISSUE THREAD

**Issue by Supportic** [Kyusung4698/PoE-Overlay#112]
PoE-Overlay: v0.5.2
Windows 10 Pro v1909
Windowed Borderless Mode

**Comment by Kyusung4698** [comment]
The keybindings are only active if the game is focused. Can you please explain further your setup? Or what do you want to achieve. Thanks for reporting!

**Comment by Supportic** [comment]
I usually play on my second monitor because it's staying more towards me. In order to move games to my second screen I press SHIFT + ALT + Arrow to move the window. The game needs to run at least on windowed mode. When I send my game back to my main monitor, everythings works. I can click on my inventory and scroll tabs in my stash. As soon as I move the window to the other screen the functionality gets lost regardless if it's focused.

**Comment by Kyusung4698** [comment]
Ahh. I see. For now the overlay spawns on the primary monitor. May add a select display option in the future.

**Comment by Supportic** [comment]
I don't know how but I realized that my game properly scrolls on mouse wheel while being on the secondary monitor in the newest version (0.5.12).

**Comment by Kyusung4698** [comment]
> I don't know how but I realized that my game properly scrolls on mouse wheel while being on the secondary monitor in the newest version (0.5.12).

Probably related to #159. This changed the way of detecting the stash region.

**Comment by Supportic** [comment]
Since I didn't run anymore into this issue since then, I will close it.

**Comment by chet-manley** [comment]
Any further traction on this? For reasons not worth going into, my primary monitor and taskbar will always be different than the monitor games are run on, and this completely breaks the overlay, by it appearing on the wrong screen. Ideally, the overlay would programatically find the monitor PoE is active on and move there, but even just an option to manually choose the correct screen would make this usable for people with a multi-screen setup.
