### ISSUE TITLE
Currency Item Type is not added as filter if Default Item Type is toggled off.

### ISSUE THREAD

**Issue by Xebtria** [Kyusung4698/PoE-Overlay#113]
https://i.imgur.com/vfT4yif.png
this is true for all breach and all legion splinters.

**Comment by Xebtria** [comment]
UPDATE: something severly broke with currency because.... no currency works at all.

**Comment by Kyusung4698** [comment]
Thanks for reporting. There is currently an issue if Default Item Type is toggled off. It'll be fixed in the next version. For now currencies are only working with Default Item Type enabled. Sorry, for the inconvenience.

**Comment by Kyusung4698** [comment]
## 0.5.4 (2020-01-22)
* fix item type not set as filter if default item type toggle is off (#113)
