### ISSUE TITLE
CTRL + W closes the overlay application

### ISSUE THREAD

**Issue by crash0verwr1te** [Kyusung4698/PoE-Overlay#116]
MISC -> Open Wiki

CTRL + W = Options Close without save changes

**Comment by Kyusung4698** [comment]
CTRL + W is an reserved hotkey by Electron. This can be disabled tho. For now please use any other hotkey. Thanks for reporting!

**Comment by Kyusung4698** [comment]
## 0.5.4 (2020-01-22)
* fix `CTRL + W` closes the application (#116)
