### ISSUE TITLE
ctrl + c

### ISSUE THREAD

**Issue by crash0verwr1te** [Kyusung4698/PoE-Overlay#117]
ctrl + c do nothing when i try to use it for map info

**Comment by Kyusung4698** [comment]
Seems like you're having a lucky day. CTRL + C and CTRL + V are reserved keybindings for copy + paste. They should not be used as keybindings. I'll exclude them in the next version as possible keys. Please use any other key. Thanks for your understanding.

**Comment by Kyusung4698** [comment]
## 0.5.4 (2020-01-22)
* remove `CTRL + C` and `CTRL + V` as possible keybindings (#117)
