### ISSUE TITLE
Option to force ilvl greater or equal

### ISSUE THREAD

**Issue by WullaWullaWomba** [Kyusung4698/PoE-Overlay#118]
Hi there,
I'd like an option added change the initial required value for ilvl to behave like it did a version or two ago - If I actually filter by ilvl, I usually find the exact ilvl (or above) important to unlock certain modifiers.

**Comment by Kyusung4698** [comment]
This is actually supported with the mod ranges:
* de/increase value by `0.1` via `Alt + Wheel`
* de/increase value by `1` via `Wheel`
* de/increase value by `5` via `Shift + Wheel`
* de/enable via `Right Click`
* reset via `Wheel Click`
![exact](https://user-images.githubusercontent.com/38520678/72928419-3ee78c80-3d58-11ea-8216-855f5056ff28.gif)

**Comment by WullaWullaWomba** [comment]
I just would like the default to look for greater/equal ilvl (having to change it whenever i want to check for ilvl is a bit bothersome) 
I forgot to mention great job btw - the overlay is awesome!

**Comment by vadash** [comment]
Agree ilvl should be always same level as item and empty max range

**Comment by Kyusung4698** [comment]
## 0.5.5 (2020-01-23)
* update item level to be unmodified by the modifer settings and uncapped by default (#118)

Thanks for your suggestion this behaviour is now used as default.
