### ISSUE TITLE
map mod warnings

### ISSUE THREAD

**Issue by SchmutzigerStefan** [Kyusung4698/PoE-Overlay#120]
hey i totally love poe-overlay. the only thing thats missing atm for me to totally swap out trademacro is map mod warnings on map info with the ability to check/uncheck certain map mods in the options.

if this was mentioned eralier, pls ignore :P

**Comment by Kyusung4698** [comment]
Added with 0.5.4. Thanks for sharing!
![image](https://user-images.githubusercontent.com/38520678/72929871-fd0c1580-3d5a-11ea-89b2-d29c2a2f0d58.png)

**Comment by SchmutzigerStefan** [comment]
nice <3
