### ISSUE TITLE
Win automatic taskbar hiding

### ISSUE THREAD

**Issue by dikij-bec** [Kyusung4698/PoE-Overlay#122]
Cant realy use this overlay cos I used to "hide taskbar automatically" feature of windows and overlay blocks it

**Comment by benbaginski** [comment]
I have kind of the opposite of this issue, but I assume it's related with how the tool affects the taskbar. 

When I have this tool running and PoE running, if I alt-tab to any other window, my taskbar is invisible. I can press the windows key to bring focus to the taskbar and it will show up. But as soon as it loses focus it turns invisible again.

**Comment by Kyusung4698** [comment]
Probably related to #60. I'll add an auto-hide feature in the next version which will hide the overlay once the game is inactive. This should fix it.

**Comment by Kyusung4698** [comment]
## 0.5.5 (2020-01-23)
* add autohiding overlay if poe is not active (#60, #61, #122)

Please let me know if this fixes your issues! Thanks.
