### ISSUE TITLE
Overlay doeps not work on game relaunch

### ISSUE THREAD

**Issue by Dariisa** [Kyusung4698/PoE-Overlay#123]
When closing and opening poe the overlay does not work until I close and then open it.

**Comment by Kyusung4698** [comment]
Any specific error message? Or behaviour? Thanks for reporting! Also please make sure the game window is active. Otherwise the hotkeys are disabled.

**Comment by Dariisa** [comment]
No specific behavior, game window is active but the overlay text in the bottom left doesn't show and the hotkeys don't work until the program is relaunched.

**Comment by Kyusung4698** [comment]
Sorry, for the late response. I could not reproduce this bug. Is it still an issue for you? Also please make sure the version text is visible before using any hotkeys. Thanks for your patience.

**Comment by Kyusung4698** [comment]
I'll close this issue for now. Feel free to reopen.
