### ISSUE TITLE
clicking "copy whisper" in the overlay-browser (pathofexile/trade) should send the whisper ingame

### ISSUE THREAD

**Issue by HendrikHaase** [Kyusung4698/PoE-Overlay#125]
or at least one should be able to click right back into poe without closing the window first to paste & send the whisper.

**Comment by Kyusung4698** [comment]
Seems reasonable. Thanks for your suggestion. The 'without closing the window' should be no problem. I'll see what i can do.

**Comment by Kyusung4698** [comment]
Thank you for your patience. This is now possible with following steps:

1. Evaluate Item
2. Open in Browser
3. Minimize Browser
4. Close Evaluate Dialog
5. Restore minimized Browser
6. Click Copy Message
7. Click In-Game
8. Press `Enter` and then `CTRL + V`

**Comment by Albino2k** [comment]
Hi ,
it is possible to include the following function in POU overlay:
clicking "copy whisper" in the overlay-browser (pathofexile/trade) and poe overlay can with a shortcut send this automatically in game ? I have always used this function in mercury trade so far, unfortunately this product is no longer supported.
if it already exists, I would appreciate a brief explanation of how to set it up.

best wishes , stay safe
