### ISSUE TITLE
[0.5.5] trade search result window doesn't fit

### ISSUE THREAD

**Issue by WhiteFang5** [Kyusung4698/PoE-Overlay#131]
When searching an item, the search window appears on screen and doesn't adjust/reposition itself within bounds of the screen.
Sometimes it takes a while to load the bottom data (graph etc) and once that loads in, it's often out of bounds making it unreadable and useless.
This usually occurs when an item is positioned near the border of the screen. 

Side note: I use dual monitors, perhaps it's related (or not).

**Comment by WullaWullaWomba** [comment]
I had trouble with that or sth similar too - I use monitor 1 as my "right" monitor and monitor 2 as my "left".
After using windowed mode on my "left" monitor, where the tooltip was shown on the "right" monitor, when I changed back to windowed fullscreen on my "right" monitor I couldn't see the tooltip anymore (I believe it was out of bounds to the "right" of my "right" monitor. 
Going back to the "left" windowed and draggin the tooltip into the window (where it is hidden behind the game) and then swapping back to windowed fullscreen fixxed it.

**Comment by Kyusung4698** [comment]
All dialogs can be dragged and therefore moved. The position calculation is not perfect because the dialog bounds are known after the dialog has opened. This can definitely be improved but has no high priority for now.

**Comment by WhiteFang5** [comment]
As a user I would find it acceptable that, after the graph loaded, the window position is fixed/adjusted to fit within bounds.

Often I'm moving around and using skills while I picked up an item to quickly price-check. When that PC is loaded and it's out of bounds and that's an annoying and risky since I'd have to stop using skills to manually move the window to read the graph and determine to keep or drop it right away.

**Comment by Kyusung4698** [comment]
> As a user I would find it acceptable that, after the graph loaded, the window position is fixed/adjusted to fit within bounds.
> 
> Often I'm moving around and using skills while I picked up an item to quickly price-check. When that PC is loaded and it's out of bounds and that's an annoying and risky since I'd have to stop using skills to manually move the window to read the graph and determine to keep or drop it right away.

Thanks for your clarification. I'll see what I can do to improve this behavior.

**Comment by Kyusung4698** [comment]
I've added an estimation calculation for the dialog bounds. This should have improved the behaviour. Please let me know if this meets your requirements. Thanks!

**Comment by WhiteFang5** [comment]
> I've added an estimation calculation for the dialog bounds. This should have improved the behaviour. Please let me know if this meets your requirements. Thanks!

Looks good now, thanks for adding this feature so quickly.
