### ISSUE TITLE
Overlay appears on all windows with the title "Path of Exile"

### ISSUE THREAD

**Issue by anythinga** [Kyusung4698/PoE-Overlay#132]
In 0.5.5 the feature that hides the overlay when PoE isn't focussed this causes the following issue: If i open an explorer window and navigate to a folder with the name "Path of Exile" the overlay appears again.

**Comment by Kyusung4698** [comment]
Currently only the window title is checked. I'll add a executable check with the new version. This should fix it. Thanks for reporting!

**Comment by Kyusung4698** [comment]
0.5.6 checks the executable name now. Thanks again.
