### ISSUE TITLE
'Clipboard text was empty' dispite hovering over an item

### ISSUE THREAD

**Issue by milesjavis** [Kyusung4698/PoE-Overlay#133]
Hi,

I regulary get the message 'Clipboard was empty. Make sure the game the game is focused.' when trying to use the evaluate functionility via Ctrl+D.

I resolve this by 're-hovering' over the item or by repeatedly pressing the key combination.

Sometimes it works immediately without the message pop-up, somtimes I need up to 10 attempts to make it work. I wasn't able to identify a pattern, but I would say it happens more frequently on equipped or stashed items rather then items in my inventory, thogugh I highly doubt that there is any connection.

I run the app as an administrator and PoE is in windowed fullscreen.

**Comment by ArkanePanda** [comment]
I have been having the same issue and it seems to occur way frequently on 0.55 so I've been using 0.54 for now

**Comment by Rohatej** [comment]
Same issue here, problem started from version 0.5.5. My workaround is AltTab-out , then AltTab back in PoE

**Comment by pj4533** [comment]
Yeah +1 here too...seems like the hiding the overlay introduced this bug.  I found a workaround was to pick up the item in question then try again.   I run in windowed mode, and it does work fine on 0.5.4 and lower.

**Comment by Kyusung4698** [comment]
Thanks for reporting. I think I figured it out what is causing this new behavior. But it may take some time for me to resolve this. I'll release a new version with the fix as soon as possible. Thanks again and sorry for the inconveniences.

**Comment by Kyusung4698** [comment]
Should be fixed with 0.5.6. Please report back!

**Comment by milesjavis** [comment]
> Should be fixed with 0.5.6. Please report back!

Tested for a while, seems to be fixed, awesome job. 

Thanks, love your tool.

**Comment by Kyusung4698** [comment]
> Tested for a while, seems to be fixed, awesome job.
> 
> Thanks, love your tool.

Awesome! Thanks for your feedback. I will close this for now.
