### ISSUE TITLE
vaal gems not correctly identified

### ISSUE THREAD

**Issue by Xebtria** [Kyusung4698/PoE-Overlay#134]
https://i.imgur.com/gN096Pm.jpg
overlay thinks it's a normal gem, but it is a vaal gem

**Comment by Kyusung4698** [comment]
Vaal is currently an unsupported state. I'll add it soon. Thanks for reporting!

**Comment by Kyusung4698** [comment]
Has been added with 0.5.6. Please report back! 👍

**Comment by Kyusung4698** [comment]
I'll close this for now. Feel free to re-open if needed.
