### ISSUE TITLE
Suggestion: Pseudo stat: Total Energy shield

### ISSUE THREAD

**Issue by Xebtria** [Kyusung4698/PoE-Overlay#135]
Useful for belts mainly, /trade has the pseudo stat

**Comment by Kyusung4698** [comment]
Thanks for your suggestion. Seems reasonable.

**Comment by Rohatej** [comment]
Even other stats should be available as pseudo values, like spell damage, cold spell dmg, fire, lightning etc. 

(X)Implicit spelldmg + (Y)prefix spell damage + (Z)suffix cold damage can be treated as x+y+z cold spell damage

**Comment by Kyusung4698** [comment]
`Total Energy Shield` and `Increased Energy Shield` have been added with 0.5.6. 

> Even other stats should be available as pseudo values, like spell damage, cold spell dmg, fire, lightning etc.
> 
> (X)Implicit spelldmg + (Y)prefix spell damage + (Z)suffix cold damage can be treated as x+y+z cold spell damage

Please create an own issue for this and list all your missing and required pseudo. Pseudo mods need manual mapping and therefore not all were added. Thanks for making this tool better  🚀
