### ISSUE TITLE
Suggestion: Show armour/evasion/energy shield/dps with 20%

### ISSUE THREAD

**Issue by TrueEdge** [Kyusung4698/PoE-Overlay#136]
Like the poe trade macro does. Thats one of the most thinks i used with that script. Check dps of weapons with quality and chech es on items. I dont like to calculate that myself or use armourer/blacks just to check. 

Would be awesome if you could add this.

**Comment by Kyusung4698** [comment]
Sorry, i don't understand this request. The evaluate dialog shows the calculated DPS?
![image](https://user-images.githubusercontent.com/38520678/73122131-8bfa7700-3f81-11ea-8ad6-431ea60b13f4.png)

Can you please give me some examples? Thanks.

**Comment by fatings** [comment]
I think the request is that for uncorrupted items the quality of the item should be ignored and forced as 20% to better calculate the potential.

**Comment by TrueEdge** [comment]
It should calculate the current dps/armour/ev/es and when it has no quality it should calculate it with 20% q

**Comment by Kyusung4698** [comment]
> It should calculate the current dps/armour/ev/es and when it has no quality it should calculate it with 20% q

Ah, got it - thanks! I'll look into it.

**Comment by livejamie** [comment]
This is a critical issue, would love to see it addressed sooner rather than later. Thank you!

**Comment by Kyusung4698** [comment]
## 0.6.17 (2020-04-02)

- add armour/ evasion/ energy shield/ dps with 20% quality (#136)

**Comment by Razunter** [comment]
@Kyusung4698 is there a way to pre-select these values by default?
Plus they seem to ignore "min-max range" setting.

**Comment by Razunter** [comment]
Also it's broken when quality is >20%
![example](https://user-images.githubusercontent.com/362900/78337542-2ab6db80-75a2-11ea-93cb-69165315bf06.png)
