### ISSUE TITLE
Dangerous map mods missing some possibilities

### ISSUE THREAD

**Issue by Dagothur** [Kyusung4698/PoE-Overlay#138]
![image](https://user-images.githubusercontent.com/3249111/73121395-98fa7480-3f47-11ea-8842-f883eedfb521.png)
![image](https://user-images.githubusercontent.com/3249111/73121422-f1ca0d00-3f47-11ea-8e03-d10878455c37.png)

I wanted to add "Players have #% less recovery rate of life and energy shield" to the highlight list but it wasn't there.

**Comment by Kyusung4698** [comment]
Thanks for reporting. Actually these mods exists in two variants:
`"1|#": "Players have #% more Recovery Rate of Life and Energy Shield"`
and negated:
`"#|-1": "Players have #% less Recovery Rate of Life and Energy Shield"`
but by selecting any of the one it'll also check for the other one.

**Comment by Kyusung4698** [comment]
I've added the negated version if it's the default version in 0.5.7.

**Comment by Kyusung4698** [comment]
I'll close this for now. Feel free to re-open if needed. Thanks.
