### ISSUE TITLE
0.5.6 overlay doesn't show

### ISSUE THREAD

**Issue by Carrybag1** [Kyusung4698/PoE-Overlay#139]
0.5.5 the overlay shows fine in the bottom left and it all works

0.5.6 the overlay never appears on the bottom left and it doesn't seem to work

**Comment by Kyusung4698** [comment]
Thanks for reporting. Are you using the steam version? If not can you please tell me the .exe name of the game. Also make sure the overlay is running as administrator.

**Comment by Carrybag1** [comment]
Stand alone client/version.

PathOfExile_x64.exe

**Comment by Kyusung4698** [comment]
Thanks. I'll upload a fix soon. Currently just checking against "PathOfExile_x64Steam.exe".

**Comment by Carrybag1** [comment]
The other 32 bit client is "PathOfExile.exe"

**Comment by Kyusung4698** [comment]
I added both. Thanks again. Currently building. Uploading soon...

**Comment by Kyusung4698** [comment]
Should be fixed with 0.5.7. Please report back! 🚀

**Comment by Carrybag1** [comment]
Working, Thanks
