### ISSUE TITLE
Version checker says a new version is available but I'm on latest

### ISSUE THREAD

**Issue by qtbear** [Kyusung4698/PoE-Overlay#14]
Version checker says a new version is available but I'm on latest

I'm on version 0.4.0-alpha but I got the popup saying a new version is available (version 0.3.0)

![image](https://user-images.githubusercontent.com/6963676/71939271-24ba8580-3180-11ea-9b35-cf9b037d3bae.png)

**Comment by sicu** [comment]
That's because the latest stable release is 0.3.0.  Just cancel that pop-up until a 0.4.x version is updated without the pre-release tag :)

**Comment by Kyusung4698** [comment]
The version checker is pretty basic. Won't fix for now.
