### ISSUE TITLE
Suggestion: parsing/monitoring of client.txt file

### ISSUE THREAD

**Issue by pj4533** [Kyusung4698/PoE-Overlay#140]
Would be great to add some client.txt parsing functionality to help monitor efficiency while playing.  Other tools track things like entering/leaving maps, etc.   Would be very useful to have this information in a nicely integrated overlay.

**Comment by Kyusung4698** [comment]
Thanks for your suggestion. Parsing of this file will be added once i start developing on the trade ui.

**Comment by pj4533** [comment]
Awesome!   I figured it would be a future enhancement — just wanted to get it in the backlog.
