### ISSUE TITLE
(Exalted) Graph precision

### ISSUE THREAD

**Issue by WhiteFang5** [Kyusung4698/PoE-Overlay#145]
In my settings I have both Chaos and Exalted orbs selected as currencies.
When looking up an item that's only prices in exalted orbs, the graph tends to be far less precise compated to chaos graphs.
For example, when a chaos-prices item shows up on the graph with bars for 50/55/60 chaos, I can agree on a margin of 5 chaos.
In case of exalted orbs, I wouldn't want a 5-exalted margin because 1 exalt, or 6 exalt still is a huge difference. In such case, I'd expect a max margin of 0.1 exalted (as that's also what's accepted by the trade site).

I've come across this inprecision in the graph when looking up an specific item:
![image](https://user-images.githubusercontent.com/4527188/73137094-0a741900-4055-11ea-8868-22d1cf222e69.png)

In the above graph you can see there's 3 of them listed at "2 ex". When checking the trade page you can actually see the following:
![image](https://user-images.githubusercontent.com/4527188/73137083-e87a9680-4054-11ea-812e-7ff1a7eb4004.png)

2 are listed at 1.5 ex and one at 1.9 ex. With this particular item and price range a 0.1 ex difference can make a huge impact.  
  
My suggestion would be to have a precision rate **per currency** in the settings. That way a user can for example use a precision of 5 for chaos, and 0.1 for exalted orbs, etc...

**Comment by Kyusung4698** [comment]
Thanks for your suggestion. I think the best way to handle this is by grouping the values based on their chaos equivalent and still display the exalted orb value. I'll look into this.

**Comment by Kyusung4698** [comment]
With 0.5.10 the group by function now uses the chaos equivalent. Please report back if this meets your requirements. Thanks! 👍

**Comment by WhiteFang5** [comment]
The graph now splits in its Chaos equivalent, but also shows the Chaos value. I'd expect it to show the exalted value rather than the chaos value (specially when the chaos value is >= 1ex)

**Comment by Kyusung4698** [comment]
Thanks for your feedback. I've added the possiblity to change the currency while hovering by scrolling (same like above). Also i may add in the future another strategy to choose the displayed currency.
