### ISSUE TITLE
Stash Navigation zooms in/out on character

### ISSUE THREAD

**Issue by WhiteFang5** [Kyusung4698/PoE-Overlay#146]
When navigating the stash (using CTRL+Scroll) and your cursor is also within the "game area" (i.e. not over your bag or stash itself), it'll zoom in/out (depending on the scroll direction) on your character.  
  
My suggestion would be to block the zoom in/out on the character when the stash nav feature is being used.

**Comment by Kyusung4698** [comment]
There is currently no plan on developing a way of blocking the mouse input.

**Comment by Smeagol001** [comment]
another way would be  disabling zoom scrolling in poe itself
