### ISSUE TITLE
Set automatically b/o price on item when click on bars

### ISSUE THREAD

**Issue by kernelENREK** [Kyusung4698/PoE-Overlay#147]
For example, CTRL+D on an item on your **premium tab**:

![poe-over](https://user-images.githubusercontent.com/4211853/73137423-01387b80-4058-11ea-88e5-e1e8cd49d938.png)

When you clicked on the bar, automatically set 15c b/o (for example)

**Comment by Xebtria** [comment]
> 
> 
> i don't think pathofexile has an interface for what you're asking

I fear the same but BOY would it be a QoL if it would be possible

**Comment by kernelENREK** [comment]
Well...techically seems possible, because [EasyBuyout](https://github.com/siegrest/EasyBuyout) (discontinued) has this feature (from readme.md):

> Send note copies a buyout note (eg. ~b/o 5 chaos) to your clipboard and pastes it into the game's note field
> Send enter automatically presses enter after pasting the note, applying the price instantly

Thas was coded in C#, no idea if this can be done in angular/electron/node.js or whatever that PoE-Overlay is coded in

**Comment by Kyusung4698** [comment]
Seems like a neat feature. Thanks for your suggestion. Preview:
![value](https://user-images.githubusercontent.com/38520678/73209333-594eab00-4148-11ea-8fd0-ea17548858b9.gif)

**Comment by Xebtria** [comment]
holy shitballs
![grafik](https://user-images.githubusercontent.com/8898076/73214793-25c54e00-4153-11ea-9fdf-6b64d928a003.png)

**Comment by Kyusung4698** [comment]
Has been added with 0.5.9. Let me know if this meets your requirements. Thanks!

**Comment by Kyusung4698** [comment]
I'll close this for now. Feel free to re-open if needed.
