### ISSUE TITLE
Missing modifiers on items

### ISSUE THREAD

**Issue by 766b** [Kyusung4698/PoE-Overlay#149]
`Minions have 14% increased Attack Speed (crafted)` is missing from list of modifiers available for selection. 

One another note, there's no alerts or any error logs for mods that are silently omitted from results.

~~~~~~~
Rarity: Rare
Victory Bane
Demon's Horn
--------
Wand
Quality: +20% (augmented)
Physical Damage: 46-84 (augmented)
Critical Strike Chance: 7.00%
Attacks per Second: 1.20
--------
Requirements:
Level: 64
Int: 179
--------
Sockets: B 
--------
Item Level: 70
--------
34% increased Spell Damage (implicit)
--------
49% increased Mana Regeneration Rate
13% increased Stun Duration on Enemies
Minions deal 74% increased Damage
Minions have 5% chance to deal Double Damage
Minions have 14% increased Attack Speed (crafted)
Minions have 14% increased Cast Speed (crafted)

**Comment by Kyusung4698** [comment]
Has been fixed. Thanks for reporting! Your note is definitely true. But it's kinda hard to figure out if the text is an actual mod if it can't be parsed. May add an % in the future which indicates the parsed percentage based on the recognized char count.
