### ISSUE TITLE
any values of anything is not recognized initially

### ISSUE THREAD

**Issue by Xebtria** [Kyusung4698/PoE-Overlay#151]
found first with a q23 gem, thought that was a problem.
then found out, it happens with all gems, regardless of what level and/or quality they have.
then found out, it applies to everything:

initial: https://i.imgur.com/sprlXKs.png
then change anything in the tooltip of the tool and open query again: https://i.imgur.com/PigAiir.png

rares: https://i.imgur.com/okvuO1U.png
uniques: https://i.imgur.com/qwc8vlN.png

maybe this is a problem with pseudo stats?

should be recognized initially, not just after changing.... something in the tooltip. not so problematic for rares and the such, but very problematic/annoying for gems

**Comment by Kyusung4698** [comment]
Thanks for reporting. This is indeed an bug. Will be fixed with the next version.

**Comment by Kyusung4698** [comment]
Has been fixed with 0.5.9.
