### ISSUE TITLE
currency evaluation not working properly

### ISSUE THREAD

**Issue by ishinome** [Kyusung4698/PoE-Overlay#153]
It is currently showing the price of an exalt as exalts:

![image](https://user-images.githubusercontent.com/49497278/73204423-97979a80-4147-11ea-92a7-371fa9d75b5c.png)
 Propably something to do with the values that anything over and exalt should be displayed as an exalt?

**Comment by Kyusung4698** [comment]
Seems like a rounding mistake. You can change the used currency while hovering by scrolling:
![](https://user-images.githubusercontent.com/38520678/73140972-0a890e80-407f-11ea-8fbc-1c5ef79131bc.gif)
