### ISSUE TITLE
White Screen with open overlay in Windows7

### ISSUE THREAD

**Issue by freohr** [Kyusung4698/PoE-Overlay#154]
When opening any ingame window (Pricing, Map mods) or the settings via the taskbar icon , the overlay opens but the rest of the screen becomes entirely white, and the overlay stops responding until I kill the overlay (by right-clicking on the taskbar icon, then selecting "Exit").
When this happens with the Settings, I can still save or close the settings, and the white screen goes away.
The main PoE window is not affected by this (other than by being completed blocked by the white screen)

Version tested : 0.5.8
PoE Version : 3.9.2c, using Borderless Windowed mode
Happened on Windows 7

Steps to reproduce:
Start the overlay, and PoE (any order)
Either : Hover over an item, then press the shortcut to open the pricing window
Or : Hover over a map, then press the shortcut to analyse the map

**Comment by freohr** [comment]
Note : This happened on my girlfriend's PC, I personally use Windows10 and I have never seen this happen on my own PC.

**Comment by Kyusung4698** [comment]
Thanks for reporting. This is mostly caused by an disabled Aero / DWM on Win7. Please try enabling the windows feature: [How to enable or disable Aero in Windows 7](https://obsproject.com/wiki/How-to-enable-or-disable-Aero-in-Windows-7)

This is required in order to create a transparent window.

**Comment by freohr** [comment]
Yes, that was it, thank you.
