### ISSUE TITLE
Bug: Fingerless Silk Gloves and Silk Gloves

### ISSUE THREAD

**Issue by TheOne320** [Kyusung4698/PoE-Overlay#157]
Fingerless Silk Gloves get recognized as normal Silk Gloves even though they are a different base.
![image](https://user-images.githubusercontent.com/7705568/73220242-40e98b00-415e-11ea-97d6-0647559b343c.png)
![image](https://user-images.githubusercontent.com/7705568/73220285-519a0100-415e-11ea-98a5-22c4827b488f.png)

**Comment by Kyusung4698** [comment]
Thanks for reporting. I'll look into it.

**Comment by Kyusung4698** [comment]
Fixed with 0.5.10. Thanks again!
