### ISSUE TITLE
Suggestion: Provide language files to serve translated app versions

### ISSUE THREAD

**Issue by Supportic** [Kyusung4698/PoE-Overlay#158]
Also: NPM found 2 vulnerabilities, can I update dependencies without breaking everything? :D

**Comment by Kyusung4698** [comment]
Seems like a good idea. I can provide translations for English and German. For all other languages I can only use a translator.

Those vulnerabilities are hidden in some small config packages used in the angular environment. Once angular 9 is released I'll update all dependencies anyway.

**Comment by Kyusung4698** [comment]
I've updated those packages and added the translation feature / files. Also i've used [babeledit](https://www.codeandweb.com/babeledit) for translated values. This probably needs some tweaking. On another note it's not fully translateable yet. Just started. I'll add those continuously as it's quite some work.
