### ISSUE TITLE
Issue when trying to fast price items in far right stash slot

### ISSUE THREAD

**Issue by ParsHere** [Kyusung4698/PoE-Overlay#159]
Whenever I try to fast price an item on the far right of a stash tab I get the error that the item must be inside the stash tab. Works correctly when I move it one slot to the left though.
![fastpr](https://user-images.githubusercontent.com/41413704/73244405-7c408580-416f-11ea-9226-9dbcd69eaa10.PNG)

**Comment by Kyusung4698** [comment]
Thanks for reporting. The stash detection is based on your cursor position. Can you please post your resolution and/or a fullscreen screenshot with opened stash. Thanks! I'll look into it.

**Comment by Kyusung4698** [comment]
No problem. This should not be unfunctional by resolution. Anyway I've updated the stash width calculation with 0.5.10. Let me know if this fixes your issue. Thanks!

**Comment by ParsHere** [comment]
Works fine now. Thanks very much for the fix.
