### ISSUE TITLE
QoL: Close window after moving mouse a set distance

### ISSUE THREAD

**Issue by Hexogenx** [Kyusung4698/PoE-Overlay#160]
This used to be a feature in PoETradeMacro. Moving the cursor 50 pixels (default) after opening one of the windows (price check or stats info) closed the window, which was useful for quickly checking several items, for example checking several maps for dangerous mods. Currently, the overlay creates multiple windows that need to be closed with a click.
I understand that this functionality would be bad for the pricechecker, since it has many interactive elements in the tooltip itself, but for map checking, this would be really nice to have.

**Comment by Kyusung4698** [comment]
Thanks for your suggestion. I don't like the mentioned mouse move behavior - But I've added two new hotkeys:
* ESC - Closes the last shown dialog (Can also be hold)
* Space - Closes all dialogs

Let me know if this is also acceptable. Thanks!
