### ISSUE TITLE
On space window closing

### ISSUE THREAD

**Issue by 766b** [Kyusung4698/PoE-Overlay#162]
While space behavior is intended, if uses opens a browser and types anything then presses `Space` window will be closed.

So now nobody can type anything in browser, be that modifying mods in search results or using Wiki and typing anything in search bar.

**Comment by Kyusung4698** [comment]
Thanks for reporting! Will be fixed with the next release.

**Comment by Kyusung4698** [comment]
## 0.5.11 (2020-01-30)
* fix space closing window outside of the game (#162)
