### ISSUE TITLE
Total Maxium life

### ISSUE THREAD

**Issue by StevenLeonK** [Kyusung4698/PoE-Overlay#163]
How do I make it account for the strength? in the total maximum life value.

![ApplicationFrameHost_cRPvSVfEw3](https://user-images.githubusercontent.com/5069549/73463188-7353dd80-4342-11ea-8d91-c4e33af9c505.png)

**Comment by Kyusung4698** [comment]
## 0.5.11 (2020-01-30)
* fix attributes not recognized in pseudo parser (#163)

Thanks for reporting. The attributes were not recognized by the pseudo parser and therefore the additional maxium life could not get calculated. Please let me know if it's working now 🚀

**Comment by StevenLeonK** [comment]
This is what it looks like after the latest version but I still believe it's wrong. Isn't it suppose to be 91 life total?

42/10
= 4.2

4.2*5
= 21

70+21
= 91

Every 10 strength grants an additional 5 maximum life.

![YoloMouse_4i030j0XQj](https://user-images.githubusercontent.com/5069549/73501525-cb630200-438b-11ea-8539-ad0e9b6365f9.png)

**Comment by StevenLeonK** [comment]
![YoloMouse_sj4cOhAY0e](https://user-images.githubusercontent.com/5069549/73501583-f9e0dd00-438b-11ea-8019-d6433819299c.png)

**Comment by StevenLeonK** [comment]
Oh I see yeah its fixed.

Thanks
