### ISSUE TITLE
Maps - Filter by base & detect Blighted

### ISSUE THREAD

**Issue by fatings** [Kyusung4698/PoE-Overlay#164]
Would be nice to be able to filter by the map base (Terrace, Beach, etc) by clicking on the name, same logic that's present in the rare items.

Would be good as well to detect blighted maps and filter by it by default as well. Right now seems to be misleading, it seems to be ignoring the prices of the blighted versions (which is correct for non-blighted maps),

**Comment by Kyusung4698** [comment]
The maps are filtered by the map base by default. All blighted maps are identified by the following mod. Just add it to your default preselect like so:
![image](https://user-images.githubusercontent.com/38520678/73480960-25b78f00-439b-11ea-8535-88dbc44c92e5.png)

**Comment by fatings** [comment]
Awesome, thanks.
