### ISSUE TITLE
Listing age - Personalize inside item

### ISSUE THREAD

**Issue by fatings** [Kyusung4698/PoE-Overlay#165]
Would be good to be able to jump between the age configurations (without overwriting the default) when clicking:

![image](https://user-images.githubusercontent.com/39002567/73480092-29deaf00-4391-11ea-89c3-eaa59d544bf5.png)

**Comment by Kyusung4698** [comment]
The value can be changed by hovering and scrolling.

**Comment by fatings** [comment]
Yeah, I was feeling there should be a purpose for the value to be there, I just didn't try the scroll wheel.
Much appreciated.

**Comment by Kyusung4698** [comment]
No problem. Glad i could help. Also the UI follows this principal: 'Range Values' are scrollable, 'Toggle Values' are clickable.
