### ISSUE TITLE
Using a shortcut on the stash activates a skill ingame instead

### ISSUE THREAD

**Issue by fatings** [Kyusung4698/PoE-Overlay#167]
I'm not able to use the ALT+W (and others) shortcut on stash items, all the ingame panels close and the char performs the skill bound to W and the "Clipboard text was empty. Make sure the game is focused" is displayed.

**Comment by Kyusung4698** [comment]
All hotkeys are passive and therefore they do not block the user input. Please use another hotkey or use while inside the city were no skill are allowed.
