### ISSUE TITLE
Filter value (Decimal) on item not changing

### ISSUE THREAD

**Issue by fatings** [Kyusung4698/PoE-Overlay#168]
I'm unable to change the following value using the mouse wheel:

![image](https://user-images.githubusercontent.com/39002567/73484069-8c877900-4398-11ea-9d6c-1e6e17d39812.png)

min is 0.4 and max 0.6

**Comment by Kyusung4698** [comment]
* add mod ranges with ±10% (#54, #83)
    * de/increase value by `0.1` via `Alt + Wheel`
    * de/increase value by `1` via `Wheel`
    * de/increase value by `5` via `Shift + Wheel`
    * de/enable via `Right Click`
    * reset via `Wheel Click`

`Alt + Wheel` let's you change the value with smaller steps for such cases.

**Comment by Kyusung4698** [comment]
Continued in #173
