### ISSUE TITLE
Enhancement: Option to Auto Check All Modifiers on Unique Items

### ISSUE THREAD

**Issue by Infernal7** [Kyusung4698/PoE-Overlay#172]
When searching a unique item the main thing you want to know is if the rolls you have are worth anything. An option to auto check all modifiers on unique items would allow very quick price checks. It could listen to the +/- mod range settings as well.

**Comment by Supportic** [comment]
Yeah would be great if the tool can auto select the possible rolls and search +-# you set up in the settings. :)

**Comment by Kyusung4698** [comment]
## 0.6.7 (2020-03-18)

- add unique select all (#360)
