### ISSUE TITLE
Mouse wheel not changing values

### ISSUE THREAD

**Issue by fatings** [Kyusung4698/PoE-Overlay#173]
I'm able to use the CTRL+SCROLL to navigate the stash tabs, but it doesn't work to change values. Left click and right click are ok.

![image](https://user-images.githubusercontent.com/39002567/73567607-9ffd1780-445e-11ea-9670-4c7c7003c011.png)

**Comment by Kyusung4698** [comment]
I do not think this is an actual bug. As the min value will never exceed the actual value and the max value will never be lower than the actual value.  Let me know if this was the issue. Thanks!

**Comment by fatings** [comment]
I've tried with several items and several kinds of mods and I'm not able to
change a single value with the wheel, not up or down.
This was a new install on a Win7 machine.

**Comment by Kyusung4698** [comment]
Okay. Could you post the item data of those failing items (CTRL + C) and the corresponding mods? Or does it not work at all?

**Comment by fatings** [comment]
this is the CTRL+C of the item in the image on the original post:

Rarity: Rare
Bramble Shell
Astral Plate
--------
Quality: +28% (augmented)
Armour: 910 (augmented)
--------
Requirements:
Level: 72
Str: 180
Dex: 48
Int: 159
--------
Sockets: R-B-R-B-R-R 
--------
Item Level: 83
--------
+12% to all Elemental Resistances (implicit)
--------
+102 to maximum Life
+23% to Fire Resistance
+26% to Cold Resistance
+34% to Lightning Resistance
Reflects 1 Physical Damage to Melee Attackers
+1 to maximum number of Raised Zombies (crafted)
+1 to maximum number of Skeletons (crafted)

**Comment by fatings** [comment]
Let me add that I don't think this is item related, because I can't change anything that it's mouse wheel related. An example of this is the listing age of an item after evaluating and going to the upper left corner.

**Comment by Kyusung4698** [comment]
Do you use any other tools besides this one? If so could you please close them and test again. Also do any of the other key modifiers work? Like `Alt + Scroll`, `Shift + Scroll`.

**Comment by fatings** [comment]
I've closed anything I can think of and it still doesn't work.
I've also realized that the software captures the wheel, because with the evaluate open and hovering a numeric value I'm able to change the stash tabs by using CTRL+SCROLL
Other modifiers don't work as well (ALT+SCROLL and SHIFT+SCROLL)

**Comment by fatings** [comment]
This problem was solved by upgrading from Win7 to Win10, so I won't be able to give more support on this.

**Comment by Kyusung4698** [comment]
> This problem was solved by upgrading from Win7 to Win10, so I won't be able to give more support on this.

Alright. I'll close this issue for now.
