### ISSUE TITLE
Skill Gems

### ISSUE THREAD

**Issue by StevenLeonK** [Kyusung4698/PoE-Overlay#174]
When trying to scroll on the level/quality of a gem it won't go past what the gem is. I want to be able to search for corrupted gems by scrolling on the text to go to level 21, or quality 23 or even both but also just being able to scroll past what the gem level/quality is so you can search.

Trademacro POE lets me do this.

I hope this makes sense.

**Comment by Kyusung4698** [comment]
Closed in favour of #270
