### ISSUE TITLE
Suggestion: Show a tooltip with all pseudo stats of the item

### ISSUE THREAD

**Issue by Xebtria** [Kyusung4698/PoE-Overlay#175]
similar to OG trade macro: no price check, just a "summary" of the item, including p/e/c/tDPS of the weapon (with current and with 20% qual).

ctrl-c because of a) og trade macro used that as well and b) with ctrl+c you copy the item's stats into the clipboard anyways (which was also why og trade macro did it with this shortcut), but in theory of course it can be any shortcut. like alt-c or anything else really.

**Comment by Kyusung4698** [comment]
I've modified the evaluate dialog behaviour to only display mods which are not bundled as pseudo. The 20% quality issue is tracked at #136
