### ISSUE TITLE
Herald of Thunder - Evaluate - An Error Occured

### ISSUE THREAD

**Issue by fatings** [Kyusung4698/PoE-Overlay#176]
Trying to evaluate Herald of Thunder Lv1 Q15
![image](https://user-images.githubusercontent.com/39002567/73591056-c7e18f00-44e1-11ea-96e3-002f1eaed1a4.png)

Other gems load ok
![image](https://user-images.githubusercontent.com/39002567/73591066-d760d800-44e1-11ea-90c0-6fab7c70356b.png)

**Comment by Kyusung4698** [comment]
## 0.5.12 (2020-02-03)

* fix `herald of thunder` wrong item category (#176)
