### ISSUE TITLE
Explain features in readme

### ISSUE THREAD

**Issue by l3enjay** [Kyusung4698/PoE-Overlay#179]
At the moment I don't feel many of the features are well explained/noted in the readme.
For example:

- Scrolling stats up/down
- Clicking to open a browser window (ctrl for one in actual browser)

And a few others which have been added, couldn't see an open issue for this so sorry if there is one I missed! :)

**Comment by Kyusung4698** [comment]
Hi, i'm currently working on a video showcasing most features and a wiki for an in depth description of features. So stay tuned! 😄

**Comment by Kyusung4698** [comment]
Hi, again. The first version of the [wiki](https://github.com/Kyusung4698/PoE-Overlay/wiki) is now available. Though still some work ahead.

**Comment by Kyusung4698** [comment]
Video with Features Showcase has been released:
https://www.youtube.com/embed/_cJmW8QkQnM
