### ISSUE TITLE
Map Info (Cards, Layout, Bosses etc.)

### ISSUE THREAD

**Issue by Eodar** [Kyusung4698/PoE-Overlay#18]
Can you add map info and mod  warnings similar to Trade Macro? 
It takes Info from http://pathofexile.gamepedia.com/Map via script made by  aRTy42  called scrape_poe_info.
https://github.com/aRTy42/scrape_poe_info

![obraz](https://user-images.githubusercontent.com/29659679/72003803-6fa0cf80-324a-11ea-8475-69320d0ba599.png)

**Comment by bMiquelin** [comment]
Would be nice if it was kinda optional (even if enabled by default)

**Comment by TheOne320** [comment]
More than the warnings for dangerous mods, I like being able to see which layout and bosses appear on the map. The Map Info feature is the only reason I am still sticking to the old TradeMacro.

**Comment by Kyusung4698** [comment]
![image](https://user-images.githubusercontent.com/38520678/72840632-f31fdf00-3c94-11ea-8bc0-bdd0167fddc4.png)

Ratings, Layout, Bosses and Items have been added. Mod warnings are planned.

**Comment by Kyusung4698** [comment]
![image](https://user-images.githubusercontent.com/38520678/72930090-76a40380-3d5b-11ea-88ef-169d48c4ebc1.png)

## 0.5.4 (2020-01-22)
* add map mod warnings (#120, #18)

**Comment by TheOne320** [comment]
![image](https://user-images.githubusercontent.com/7705568/72931461-2e3a1500-3d5e-11ea-8a77-17e7397c02d5.png)
How does this page work? What do the arrows in the middle mean? What are the affixes on the left and the right? What does checking the checkboxes do? How do I add something to the warnings line?

**Comment by Kyusung4698** [comment]
![image](https://user-images.githubusercontent.com/38520678/72931888-f41d4300-3d5e-11ea-81a3-2f7e2a95003f.png)

I made a quick gif to showcase this control. 

![selector](https://user-images.githubusercontent.com/38520678/72932240-ab19be80-3d5f-11ea-8ac5-e29593c8892c.gif)

**Comment by TheOne320** [comment]
Thanks!
