### ISSUE TITLE
Missing quick-search data for essences

### ISSUE THREAD

**Issue by WhiteFang5** [Kyusung4698/PoE-Overlay#180]
The quick-search shows no data for essences:
![image](https://user-images.githubusercontent.com/4527188/73610792-833a1e80-45db-11ea-8327-b871f03e5bf0.png)

**Comment by Kyusung4698** [comment]
Essences are currently not supported. The search page is missing the category 'essence' and therefore the items are not marked as essence. I'll see what i can do.

**Comment by Kyusung4698** [comment]
## 0.5.12 (2020-02-03)
* add essence support (#180)
