### ISSUE TITLE
Overlay not showing for Kakao versions.

### ISSUE THREAD

**Issue by Fatcow007** [Kyusung4698/PoE-Overlay#181]
Overlay is not appearing for non-steam, kakao versions.
Issue might be similar to #139 and I confirmed it working with PathOfExile_x64.exe and PathOfExile.exe.
Kakao versions have PathOfExile_KG.exe and PathOfExile_x64_KG.exe as its name.

**Comment by Kyusung4698** [comment]
Thanks for reporting. I'll add those.

**Comment by Kyusung4698** [comment]
## 0.5.12 (2020-02-03)

* add kakao client support
