### ISSUE TITLE
Count single attribute as pseudo

### ISSUE THREAD

**Issue by vadash** [Kyusung4698/PoE-Overlay#182]
Item
```
Rarity: Rare
Corpse Hold
Unset Ring
--------
Requirements:
Level: 57
--------
Sockets: G 
--------
Item Level: 81
--------
Has 1 Socket (implicit)
--------
+59 to maximum Life
+15 to maximum Mana
+35% to Cold Resistance
+43% to Lightning Resistance
+27 to Strength (crafted)
```
Doesnt search +str as pseudo attribute so it will provide misleading price
![image](https://user-images.githubusercontent.com/1397582/73679289-26b62c80-46cb-11ea-8f1a-801ee3f5dcd7.png)
Is it possible to force pseudo search here ?

**Comment by Kyusung4698** [comment]
## 0.5.13 (2020-02-04)
* update pseudo mod behaviour
    * use pseudo value instead of single value (#182)
    * remove stat from list if used as pseudo stat (#175)

Please let me know if this matches your expectations. Thanks! 👍

**Comment by Xebtria** [comment]
not OP, but for me it looks like it's working nice now. pseudo mods all over the place. :)

**Comment by Kyusung4698** [comment]
Thanks for your feedback. I'll close this issue for now.
