### ISSUE TITLE
Logging in on In-Game Browser causes almost constant "An Error Has Occurred" when searching prices

### ISSUE THREAD

**Issue by DunklesTier** [Kyusung4698/PoE-Overlay#185]
This makes it very difficult to remove price-fixers from your search results when determining item prices, not sure how to give you error details but I have confirmed the issue only started happening when i logged in to the in-game browser and stopped immediately after i logged out.

**Comment by Kyusung4698** [comment]
Thanks for reporting. Seems like the rate limits are lower on authenticated requests. I'll add a retry with additional delay.

**Comment by DunklesTier** [comment]
Thanks for looking into this.  Your project is otherwise great and the fact that you're developing it so actively is refreshing.

**Comment by Kyusung4698** [comment]
## 0.5.13 (2020-02-04)
* fix authenticated request hitting rate limit (#185)

Should be fixed. Please report back! 🚀

**Comment by DunklesTier** [comment]
Thanks so much for the quick turn-around. My initial testing has been flawless, although it does take slightly more time to get the item information than before, which I expected.  You can mark this as resolved :)
