### ISSUE TITLE
Evaluate - Exchange Rate - 6L items

### ISSUE THREAD

**Issue by fatings** [Kyusung4698/PoE-Overlay#187]
It seems that sometimes the value in the Exchange Rate section might be mismatching.

Example 1
![image](https://user-images.githubusercontent.com/39002567/73772785-c1b91000-4778-11ea-9edc-9e63eb67214a.png)
![image](https://user-images.githubusercontent.com/39002567/73772829-df867500-4778-11ea-957b-c1dcc14028a3.png)

Example 2
![image](https://user-images.githubusercontent.com/39002567/73772960-15c3f480-4779-11ea-8804-e4e39db6e2ab.png)
![image](https://user-images.githubusercontent.com/39002567/73773000-2f653c00-4779-11ea-93d1-da5d1104c8f7.png)

Example 1 seems to be matching with the 6L when the item doesn't have 6L and Example 2 seems to be ok since the item is not 6L

**Comment by Kyusung4698** [comment]
Nice catch. Thanks for reporting! Will be fixed in the next version.

**Comment by Kyusung4698** [comment]
## 0.5.13 (2020-02-04)
* fix exchange rate using 6L if no links are present (#187)

**Comment by fatings** [comment]
Another example, now between 5L and 6L. Running 0.5.13

![image](https://user-images.githubusercontent.com/39002567/74083519-eb19ba80-4a5c-11ea-9aa6-34f5708188d6.png)
![image](https://user-images.githubusercontent.com/39002567/74083528-0684c580-4a5d-11ea-8b9e-7d4ef25f3efc.png)

**Comment by Kyusung4698** [comment]
## 0.5.14 (2020-02-08)
* fix exchange rate using wrong link count (#187)

**Comment by Kyusung4698** [comment]
I'll close this for now. Feel free to reopen. Thanks again for your help! 🚀
