### ISSUE TITLE
clear clipboard before executing any command like hideout shortcut

### ISSUE THREAD

**Issue by Xebtria** [Kyusung4698/PoE-Overlay#188]
the problem I sometimes have is that whenever I press my shortcut for my hideout (which I put to ctrl-h), it does the last thing I have in the clipboard again,  so I end up sending a message again even though I have finished the trade, or I have something whatever in the clipboard from outside the game, and I press my shortcut and it sends that thing to the last person I whispered, it is kind of weird, does not happen all the time, usually only when I press the shortcut very quickly, at least it seems like that.

the easiest solution would be to clear the clipboard always before the tool does anything, I guess. then this can't happen ever.

**Comment by Kyusung4698** [comment]
I've increased the delay before reseting the clipboard to the original value. This should fix it. Please report back! Thanks.

**Comment by Xebtria** [comment]
at first glance seems to be fixed, but I'd like to observe this some time more, especially when combined with doing actual trades instead of just trying with pseudo things in the clipboard :)

**Comment by Kyusung4698** [comment]
> at first glance seems to be fixed, but I'd like to observe this some time more, especially when combined with doing actual trades instead of just trying with pseudo things in the clipboard :)

Sure. No problem. I'll close this issue tho. Feel free to reopen if this is still an issue for you.
