### ISSUE TITLE
Suggestion: Negotiable pricing

### ISSUE THREAD

**Issue by Hexogenx** [Kyusung4698/PoE-Overlay#191]
When clicking a bar to quickly tag an item with a price, it would be nice to have an option to set negotiable asking price instead of exact price. Maybe per rightclick on the bar, or something in the options.

**Comment by Kyusung4698** [comment]
The graph does not support the right click event. How about ALT + Click?

**Comment by Hexogenx** [comment]
Sure, the way you implement is up to you, ALT+Click should be fine!

**Comment by Kyusung4698** [comment]
## 0.5.19 (2020-02-20)

- add negotiable pricing on double click (#191)

`ALT + Click` was also not supported...but i've added negotiable pricing on double click! thanks for your suggestion! 👍

**Comment by Kyusung4698** [comment]
__
