### ISSUE TITLE
Evaluate - Exchange Rate - Oils

### ISSUE THREAD

**Issue by fatings** [Kyusung4698/PoE-Overlay#192]
The Exchange rate section always shows **No Data Found** when evaluating oils.

Example:
![image](https://user-images.githubusercontent.com/39002567/73857327-ac062200-482e-11ea-8fe0-76aff940f5fe.png)

**Comment by Kyusung4698** [comment]
## 0.5.14 (2020-02-08)
* add oil exchange rate support (#192)
