### ISSUE TITLE
Missing quick-search data for shards and oils 

### ISSUE THREAD

**Issue by WhiteFang5** [Kyusung4698/PoE-Overlay#194]
The quick-search shows no data oils or shards (note the no data found at the top) similar to how it used to be for essences (#180):
![image](https://user-images.githubusercontent.com/4527188/73882025-afff6780-4861-11ea-860e-0aca309f2ecf.png)
 
![image](https://user-images.githubusercontent.com/4527188/73882069-bf7eb080-4861-11ea-911a-728122ae0d0a.png)

**Comment by Kyusung4698** [comment]
Shards are not supported as they are not included in the poe ninja data set. https://poe.ninja/challenge/currency

Oils will be tracked here at #192

**Comment by WhiteFang5** [comment]
![image](https://user-images.githubusercontent.com/4527188/74087455-b32a6b80-4a8c-11ea-906f-dea14f5fd3fc.png)

@Kyusung4698 as seen in the screenshot above, you can clearly see that shards ARE actually included in the https://poe.ninja/challenge/currency page. (Although it's only annulment, exalted and mirror shards)
