### ISSUE TITLE
Item value UX

### ISSUE THREAD

**Issue by dusty071** [Kyusung4698/PoE-Overlay#196]
I love this app, but i cannot get behind the way you chose to present current item listings - the graph, min, max and averages. In pricing items in PoE these things mean next to nothing. Those numbers can be somewhat trusted in a game like WoW (with TSM addon) because of the nature of the auction house but definitely not in PoE's wild west trading system.

Example i just tried pricing unique Darkscorn assasin bow
- min value 40.00c
- max value 1,847.20c
- mean 486.46c
- median 249.37c
- mode 185.00
- graph goes from 40 to 1800c but i can only guess if the first listings are price fixers or not. The true value might be 70c if i assume the first few listings are fake. I cannot discern this from the tooltip info.

So i didnt get any useful information except the min value and even that i cannot blindly trust if i want to dodge potential price fixing. So i am forced to open it in the browser and there i can see the **names of the sellers** and the **posted times** and i see that the item is most likely not being price fixed due to many different sellers and low posted times.

Suggestion: just show us the first ~20 item listings in a simple table (something like in trade apps "Lunaris" and "Awakened PoE Trade") but you can improve it like **group same seller together** with option of expanding the seller group, show afk status, show the Poe.ninja estimate at the top.

| Price             | Seller name   | Posted time  |
| ------------- | ------------- | ------------- |
|  30c              | fixer123        | 5 h ago         | 
|  30c              | fixer123        | 5 h ago         | 
|  30c              | fixer123        | 5 h ago         |  
|  40c              | CoC12          | 15 min ago   |
|  41c              | Zerker543     | 1 hour ago   |

In my opinion it is much easier to quickly discern the value of the item from a simple table of prices, seller names and times. And i believe most people have gotten used to this way of pricing because it is how PoE trade websites are built. You could maybe even make an option in settings whether the user wants the "graph" way or "simple table" way.

Thats my feedback. Thanks for your hard work, keep it up.

**Comment by Kyusung4698** [comment]
Thanks for your great feedback! 🚀 The next update will focus on making price fixers less harmful.

**Comment by Kyusung4698** [comment]
## 0.5.14 (2020-02-08)

* add account listing count threshold (#196)
* add listing age mean to tooltip (#196)
* add `price fixing rating` (*** > 75%, ** > 50%, * > 25%)
* add alternate evaluate list view (#196)

![list](https://user-images.githubusercontent.com/38520678/74093436-096dcd80-4ad2-11ea-91d8-0a49a98bca69.png)
