### ISSUE TITLE
Evaluate - Attributes missing

### ISSUE THREAD

**Issue by fatings** [Kyusung4698/PoE-Overlay#197]
Not possible to filter by dex, int or total attributes in the following example:

![image](https://user-images.githubusercontent.com/39002567/74093063-ceb16880-4ac4-11ea-93f7-8a8b4a527173.png)

**Comment by Kyusung4698** [comment]
## 0.5.14 (2020-02-08)
* remove pseudo count filter (#197)

Thanks for reporting. I've removed most count filters. Should be available as filter now!
