### ISSUE TITLE
New Shortcut - poedb

### ISSUE THREAD

**Issue by fatings** [Kyusung4698/PoE-Overlay#199]
Would be nice to have a shortcut that opens the podb.db webpage for the hovered item.

Example:
![image](https://user-images.githubusercontent.com/39002567/74101144-8e86d000-4b2e-11ea-996c-843b50c779b3.png)
would open:
https://poedb.tw/us/mod.php?cn=Gloves&an=str_armour

**Comment by Supportic** [comment]
or POE Wiki

**Comment by Kyusung4698** [comment]
Thanks for your suggestion 👍 

> or POE Wiki

The PoE Wiki is already supported. See following wiki entry:
https://github.com/Kyusung4698/PoE-Overlay/wiki/Misc#wiki

**Comment by Kyusung4698** [comment]
## 0.5.15 (2020-02-10)

* add poe db (ALT + G) (#199)

Has been added. Please let me know if this meets your requirements as i do not know this website. A supported **rare item** will open the mod section. All others will open their detail page.

**Comment by Kyusung4698** [comment]
I'll close this issue for now. Feel free to reopen if needed.
