### ISSUE TITLE
Unique armour local energy shield %

### ISSUE THREAD

**Issue by Medifri501** [Kyusung4698/PoE-Overlay#201]
While evaluating unique armour wrong stat is used: "#% total increased maximum Energy Shield"
instead of "#% increased Energy Shield (Local)".

![Untitled](https://user-images.githubusercontent.com/60852485/74106901-78e7c980-4b73-11ea-9c63-cccd9bbffaec.png)

**Comment by Kyusung4698** [comment]
## 0.5.15 (2020-02-10)

* fix local mod used as pseudo (#201)

Thanks for reporting. Should be fixed. Please report back! 👍

**Comment by Medifri501** [comment]
Tested multiple different items and the issue seems to be fixed. Thank you! =3
