### ISSUE TITLE
Hide PoE-Overlay label in the bottom left

### ISSUE THREAD

**Issue by Quotae** [Kyusung4698/PoE-Overlay#205]
I keep seeing the label in the corner of my eye when I look at my health and it's a little distracting. I'd like an option to just stop it from showing at all.

Why is this even there, out of curiosity?

**Comment by Kyusung4698** [comment]
## 0.5.15 (2020-02-10)

* add version toggle (#205)

It's used as an indicator - "I'm running and my hotkeys are active".
