### ISSUE TITLE
Suggestion: Add a way to bind a website to hotkey

### ISSUE THREAD

**Issue by kad22** [Kyusung4698/PoE-Overlay#206]
Would be faster and more convenient than using it with standard browser.
tyvm

**Comment by Kyusung4698** [comment]
## 0.5.15 (2020-02-10)

* add poe db (ALT + G) (#199)
* add poe ninja by clicking on the exchange rate (#206)

what should poelab do? just open the page on hotkey?

**Comment by kad22** [comment]
thank u for the update! 
for me personally it would be enough to just be able to open the poelab page per shortcut, as i mostly just run lab for ascendancy or the occasional enchant and can navigate the page from there on out, i dont know if active lab runners would prefer more specific options
tyvm

**Comment by kad22** [comment]
just tried the ALT+G command, doesnt seem to work for me as it opens up the atlas before it opens up poedb

**Comment by kad22** [comment]
poe.ninja works fine that way though!

**Comment by kad22** [comment]
ALT-G works if u open ur inventory over ur atlas, so i guess it just needs another hotkey

**Comment by kad22** [comment]
*default hotkey, changed it to F and works fine now

**Comment by kad22** [comment]
u really should advertise that it doesnt use the standard browser, for me and my potato pc at least it is a life changer, it is so much faster. If u dont want to overpromise and risk backlash just say that someone said so, feel free to reference me :). Love this tool and really want to see it succeed.

**Comment by Kyusung4698** [comment]
> thank u for the update!
> for me personally it would be enough to just be able to open the poelab page per shortcut, as i mostly just run lab for ascendancy or the occasional enchant and can navigate the page from there on out, i dont know if active lab runners would prefer more specific options
> tyvm

Okay. I'll add a new menu where you can add as many links as you want and configure a hotkey. Same as commands.

**Comment by kad22** [comment]
That sounds great, thank you.
One more thing, i realised that u cant maneuver the game when the browser is minimized, it always needs to be closed first. Could that be changed? Even for just trading would be nice to not having to open it everytime if u wanna buy  something from more than one seller for example.

**Comment by Kyusung4698** [comment]
> One more thing, i realised that u cant maneuver the game when the browser is minimized, it always needs to be closed first. Could that be changed? Even for just trading would be nice to not having to open it everytime if u wanna buy something from more than one seller for example.

This feature can be tracked here: #219

**Comment by Kyusung4698** [comment]
## 0.5.16 (2020-02-13)

- add bookmark module (#206)
    - `https://www.poelab.com/` on `num1`
    - `https://wraeclast.com/` on `num2`
