### ISSUE TITLE
Configured postion of overlay (x,y pos)

### ISSUE THREAD

**Issue by asarkiro** [Kyusung4698/PoE-Overlay#210]
Can we have an x,y setting for the top left of the dialog as it overlays over my items and maps and I would like to go through maps quickly to check the mods. Thanks.

**Comment by Kyusung4698** [comment]
Should all dialogs spawn at the same position?

**Comment by xeske** [comment]
I'd like to add to this thread (probably issues are connected) that me personally would prefer item tooltip always open at the same position - center of the screen (to avoid interference with gear/other items on the background). Cheers!

**Comment by barbarolucente** [comment]
> I'd like to add to this thread (probably issues are connected) that me personally would prefer item tooltip always open at the same position - center of the screen (to avoid interference with gear/other items on the background). Cheers!

Same here.
Sometimes the overlay spawn out of the screen if you check items at screen edges.
Thank you.

**Comment by Kyusung4698** [comment]
## 0.5.22 (2020-03-08)

- add dialog spawn position as general setting (Cursor, Center) (#210)

![dialog-spawn](https://user-images.githubusercontent.com/38520678/76162104-6e9cf900-613a-11ea-8b31-78ce406603cb.png)

**Comment by Kyusung4698** [comment]
I'll close this issue. Feel free to re-open if needed.
