### ISSUE TITLE
UX design + App signature

### ISSUE THREAD

**Issue by Supportic** [Kyusung4698/PoE-Overlay#211]
Hello, I know that developers don't care a lot about UX design but I found some things which I wanted to address. Maybe there is a chance that you can agree on some points, lets see. :)

First of all lets talk about the checkbox switches. As I see your active state sets the switch bubble to the right and vice versa. What I want to point out here is that a active state is commonly brighter than the inactive state. Same as a hover effect, the button should stand out more.
In this case the active state is darker and indicates more of a inactive state compared to the inactive state where it's clearly brighter. I think it's related to your theme because the bubble color would match some other elements.

![switches](https://user-images.githubusercontent.com/20886239/74200299-e163a300-4c66-11ea-94bf-a40f011e5a52.png)

Number two on the list is the resizable window. In the picture I tried to illustrate where the eye position of the user is, after entering a bigger window size. The user needs to refocus on the right element again after almost every tab. It would be quite convinient to keep it the same size.  

![window size](https://user-images.githubusercontent.com/20886239/74200445-4a4b1b00-4c67-11ea-9b9c-9c38d3e96896.png)

The third one bugged me the first time I saw it. The list is filled with tons of items but there is **no scroll bar** to get to the right elements if the list is sorted of course.

![scrollbar](https://user-images.githubusercontent.com/20886239/74200504-69e24380-4c67-11ea-8c8b-af616b65ed16.png)

And the last point covers a topic which I'm not sure about how I would do it but every time I download the latest version, windows is telling me to accept that program might not be safe and I have to manually agree on it when I want to use it at my own risk. I guess this will just solve if you implement the built in updater in 1.0. But for now I think it has something to do with signing your application.

Hopefully this is somehow usefull for you.
Great work so far! Cheers.

**Comment by Kyusung4698** [comment]
> Hello, I know that developers don't care a lot about UX design but I found some things which I wanted to address. Maybe there is a chance that you can agree on some points, lets see. :)

Nah, UX is really important. But there is some truthness in that statement. 😄 

> First of all lets talk about the checkbox switches. As I see your active state sets the switch bubble to the right and vice versa. What I want to point out here is that a active state is commonly brighter than the inactive state. Same as a hover effect, the button should stand out more.
> In this case the active state is darker and indicates more of a inactive state compared to the inactive state where it's clearly brighter. I think it's related to your theme because the bubble color would match some other elements.
> 
> ![switches](https://user-images.githubusercontent.com/20886239/74200299-e163a300-4c66-11ea-94bf-a40f011e5a52.png)

Great suggestion. I've tried to catch the PoE theme but it's quite dark and not really high in contrast. I'll try some different color schemes. There is also this website: https://materialtheme.arcsine.dev/ where you can generate a theme. So maybe you can come up with something and share a link?

> Number two on the list is the resizable window. In the picture I tried to illustrate where the eye position of the user is, after entering a bigger window size. The user needs to refocus on the right element again after almost every tab. It would be quite convinient to keep it the same size.
> 
> ![window size](https://user-images.githubusercontent.com/20886239/74200445-4a4b1b00-4c67-11ea-9b9c-9c38d3e96896.png)

Hmm, seems reasonable. Personally this does not bother me. But it's quite an easy fix...so. 

> The third one bugged me the first time I saw it. The list is filled with tons of items but there is **no scroll bar** to get to the right elements if the list is sorted of course.
> 
> ![scrollbar](https://user-images.githubusercontent.com/20886239/74200504-69e24380-4c67-11ea-8c8b-af616b65ed16.png)

I've hidden the scrollbars because they were ugly as shit - but i agree this is not a great user experience. I'll look into it.

> And the last point covers a topic which I'm not sure about how I would do it but every time I download the latest version, windows is telling me to accept that program might not be safe and I have to manually agree on it when I want to use it at my own risk. I guess this will just solve if you implement the built in updater in 1.0. But for now I think it has something to do with signing your application.

The application is currently not signed. Trusthworthy certificates are quite expensive and hard to aquire as single developer without a registered company. This should hopefully only be required once with the installer version.

> Hopefully this is somehow usefull for you.
> Great work so far! Cheers.

Yes! Absolutely. Thanks for your feedback. 🚀

**Comment by Supportic** [comment]
Yellow tone: [link](https://materialtheme.arcsine.dev/?c=eyJwYWxldHRlIjp7InByaW1hcnkiOnsibWFpbiI6IiNmZmYyNzciLCJsaWdodGVyIjoiI2ZmZmJkNiIsImRhcmtlciI6IiNmZmVjNWEifSwiYWNjZW50Ijp7Im1haW4iOiIjZmZmMjc3IiwibGlnaHRlciI6IiNmZmZiZDYiLCJkYXJrZXIiOiIjZmZlYzVhIn0sIndhcm4iOnsibWFpbiI6IiNlNjQ2NDYiLCJsaWdodGVyIjoiI2Y4YzhjOCIsImRhcmtlciI6IiNkYjJmMmYifSwibGlnaHRUZXh0IjoiIzAwMDAwMCIsImxpZ2h0QmFja2dyb3VuZCI6IiNmYWZhZmEiLCJkYXJrVGV4dCI6IiNlM2UzZTMiLCJkYXJrQmFja2dyb3VuZCI6IiMyMDIyMjUifSwiZm9udHMiOlt7InRhcmdldCI6ImRpc3BsYXktNCJ9LHsidGFyZ2V0IjoiZGlzcGxheS0zIn0seyJ0YXJnZXQiOiJkaXNwbGF5LTIifSx7InRhcmdldCI6ImRpc3BsYXktMSJ9LHsidGFyZ2V0IjoiaGVhZGxpbmUiLCJmYW1pbHkiOiJSYWxld2F5In0seyJ0YXJnZXQiOiJ0aXRsZSIsImZhbWlseSI6IlJhbGV3YXkifSx7InRhcmdldCI6InN1YmhlYWRpbmctMiIsImZhbWlseSI6IlJhbGV3YXkifSx7InRhcmdldCI6InN1YmhlYWRpbmctMSIsImZhbWlseSI6IlJhbGV3YXkifSx7InRhcmdldCI6ImJvZHktMiIsImZhbWlseSI6IlJhbGV3YXkifSx7InRhcmdldCI6ImJvZHktMSIsImZhbWlseSI6IlJhbGV3YXkifSx7InRhcmdldCI6ImJ1dHRvbiIsImZhbWlseSI6IlBvcHBpbnMifSx7InRhcmdldCI6ImNhcHRpb24iLCJmYW1pbHkiOiJSYWxld2F5In0seyJ0YXJnZXQiOiJpbnB1dCIsImxpbmVIZWlnaHQiOjEsInNpemUiOm51bGx9XSwiaWNvbnMiOiJGaWxsZWQiLCJsaWdodG5lc3MiOmZhbHNlfQ==)
Green tone: [link](https://materialtheme.arcsine.dev/?c=eyJwYWxldHRlIjp7InByaW1hcnkiOnsibWFpbiI6IiMwZmEzNzkiLCJsaWdodGVyIjoiI2I3ZTNkNyIsImRhcmtlciI6IiMwODg4NWMifSwiYWNjZW50Ijp7Im1haW4iOiIjMGZhMzc5IiwibGlnaHRlciI6IiNiN2UzZDciLCJkYXJrZXIiOiIjMDg4ODVjIn0sIndhcm4iOnsibWFpbiI6IiNlNjQ2NDYiLCJsaWdodGVyIjoiI2Y4YzhjOCIsImRhcmtlciI6IiNkYjJmMmYifSwibGlnaHRUZXh0IjoiIzAwMDAwMCIsImxpZ2h0QmFja2dyb3VuZCI6IiNmYWZhZmEiLCJkYXJrVGV4dCI6IiNlM2UzZTMiLCJkYXJrQmFja2dyb3VuZCI6IiMyMDIyMjUifSwiZm9udHMiOlt7InRhcmdldCI6ImRpc3BsYXktNCJ9LHsidGFyZ2V0IjoiZGlzcGxheS0zIn0seyJ0YXJnZXQiOiJkaXNwbGF5LTIifSx7InRhcmdldCI6ImRpc3BsYXktMSJ9LHsidGFyZ2V0IjoiaGVhZGxpbmUiLCJmYW1pbHkiOiJSYWxld2F5In0seyJ0YXJnZXQiOiJ0aXRsZSIsImZhbWlseSI6IlJhbGV3YXkifSx7InRhcmdldCI6InN1YmhlYWRpbmctMiIsImZhbWlseSI6IlJhbGV3YXkifSx7InRhcmdldCI6InN1YmhlYWRpbmctMSIsImZhbWlseSI6IlJhbGV3YXkifSx7InRhcmdldCI6ImJvZHktMiIsImZhbWlseSI6IlJhbGV3YXkifSx7InRhcmdldCI6ImJvZHktMSIsImZhbWlseSI6IlJhbGV3YXkifSx7InRhcmdldCI6ImJ1dHRvbiIsImZhbWlseSI6IlBvcHBpbnMifSx7InRhcmdldCI6ImNhcHRpb24iLCJmYW1pbHkiOiJSYWxld2F5In0seyJ0YXJnZXQiOiJpbnB1dCIsImxpbmVIZWlnaHQiOjEsInNpemUiOm51bGx9XSwiaWNvbnMiOiJGaWxsZWQiLCJsaWdodG5lc3MiOmZhbHNlfQ==)
Turquoise tone: [link](https://materialtheme.arcsine.dev/?c=eyJwYWxldHRlIjp7InByaW1hcnkiOnsibWFpbiI6IiMwYmE1OWUiLCJsaWdodGVyIjoiI2I2ZTRlMiIsImRhcmtlciI6IiMwNjhhODIifSwiYWNjZW50Ijp7Im1haW4iOiIjMGJhNTllIiwibGlnaHRlciI6IiNiNmU0ZTIiLCJkYXJrZXIiOiIjMDY4YTgyIn0sIndhcm4iOnsibWFpbiI6IiNlNjQ2NDYiLCJsaWdodGVyIjoiI2Y4YzhjOCIsImRhcmtlciI6IiNkYjJmMmYifSwibGlnaHRUZXh0IjoiIzAwMDAwMCIsImxpZ2h0QmFja2dyb3VuZCI6IiNmYWZhZmEiLCJkYXJrVGV4dCI6IiNlM2UzZTMiLCJkYXJrQmFja2dyb3VuZCI6IiMyMDIyMjUifSwiZm9udHMiOlt7InRhcmdldCI6ImRpc3BsYXktNCJ9LHsidGFyZ2V0IjoiZGlzcGxheS0zIn0seyJ0YXJnZXQiOiJkaXNwbGF5LTIifSx7InRhcmdldCI6ImRpc3BsYXktMSJ9LHsidGFyZ2V0IjoiaGVhZGxpbmUiLCJmYW1pbHkiOiJSYWxld2F5In0seyJ0YXJnZXQiOiJ0aXRsZSIsImZhbWlseSI6IlJhbGV3YXkifSx7InRhcmdldCI6InN1YmhlYWRpbmctMiIsImZhbWlseSI6IlJhbGV3YXkifSx7InRhcmdldCI6InN1YmhlYWRpbmctMSIsImZhbWlseSI6IlJhbGV3YXkifSx7InRhcmdldCI6ImJvZHktMiIsImZhbWlseSI6IlJhbGV3YXkifSx7InRhcmdldCI6ImJvZHktMSIsImZhbWlseSI6IlJhbGV3YXkifSx7InRhcmdldCI6ImJ1dHRvbiIsImZhbWlseSI6IlBvcHBpbnMifSx7InRhcmdldCI6ImNhcHRpb24iLCJmYW1pbHkiOiJSYWxld2F5In0seyJ0YXJnZXQiOiJpbnB1dCIsImxpbmVIZWlnaHQiOjEsInNpemUiOm51bGx9XSwiaWNvbnMiOiJGaWxsZWQiLCJsaWdodG5lc3MiOmZhbHNlfQ==) - favourite

**Comment by Kyusung4698** [comment]
![image](https://user-images.githubusercontent.com/38520678/74371343-ee080880-4dd8-11ea-92e9-15021c81987f.png)

I've used the poe purple and added a custom scrollbar.

**Comment by Supportic** [comment]
Jepp, jepp that's nice.
