### ISSUE TITLE
Nearby Enemies have -9% to Chaos Resistance is misidentified

### ISSUE THREAD

**Issue by krage** [Kyusung4698/PoE-Overlay#213]
On a helm with both `+25% to Chaos Resistance` and `Nearby Enemies have -9% to Chaos Resistance` these values are getting wrapped into a single `% total to Chaos Resistance` pseudo stat.  For that helm the filter value in the evaluate window can't be increased beyond their combined "total" of 16%.

Same issue on a helm that has the nearby -9% chaos mod without +% chaos resistance on it.  Doesn't seem to be a problem for helms with the other elemental -9% delve mods (eg. helm with +lightning resist and nearby enemies have -9% lightning resist works fine).

Sample item:

```
Rarity: Rare
Woe Veil
Siege Helmet
--------
Quality: +20% (augmented)
Armour: 332 (augmented)
--------
Requirements:
Level: 69
Str: 101
Int: 134
--------
Sockets: B-R-R-B 
--------
Item Level: 85
--------
Scourge Arrow creates an additional spore pod at Maximum Stages
--------
+95 to maximum Life
+25% to Chaos Resistance
Regenerate 1% of Life per second
Nearby Enemies have -9% to Chaos Resistance
20% increased Armour (crafted)
+16 to maximum Life (crafted)
```

**Comment by Kyusung4698** [comment]
Thanks for reporting. I'll look into it. Seems like a mismatching problem of the "Nearby Enemies have -9% to Chaos Resistance" stat.

**Comment by Kyusung4698** [comment]
## 0.5.16 (2020-02-13)

- fix nearby enemies counted as chaos resistance (#213)
