### ISSUE TITLE
Scaling UI

### ISSUE THREAD

**Issue by ThorTheGray** [Kyusung4698/PoE-Overlay#214]
After a quick glance it doesn't seem like this has been mentioned. I play on 3440x1440 and the UI is quite small. Would it be hard to implement a scaling feature?

Also is it normal for the graphics to become pixelated as the window sits? As soon as I move the window again the pixelation goes away.

**Comment by Kyusung4698** [comment]
Thank you for creating an issue. Scaling should work but there are some things i need to adjust to make it 100% functional. 

The pixelated issue has not been adressed yet. How bad is it? Can you attach an screenshot? You can try to run the overlay with the provided `run-without-gpu.bat`. Maybe this fixes the issue.

**Comment by ThorTheGray** [comment]
I will try the run-without-gpu..bat and see if that fixes the issue with the pixelation. 

Fantastic! If you get the scaling working I think I may switch to it full time.

**Comment by Kyusung4698** [comment]
## 0.5.17 (2020-02-16)

- add ui scaling (#214)

Basic ui scaling has been implemented. Looking forward to your feedback!

**Comment by xFiloo** [comment]
Hello @Kyusung4698 , thanks for your work, I love this addon so far. I just upgraded to the latest version (.5.17) a few minutes ago, and I've to say, everything is waaay too little (same results with or without .bat)! My screen resolution is 5120x2880, and scaling works only for the item evaluation. I'll post here some screenshots so you can understand better what I'm facing!
`https://imgur.com/a/TgGbyI0`

**Comment by Kyusung4698** [comment]
> Hello @Kyusung4698 , thanks for your work, I love this addon so far. I just upgraded to the latest version (.5.17) a few minutes ago, and I've to say, everything is waaay too little #214 (same results with or without .bat)! My screen resolution is 5120x2880, and scaling works only for the item evaluation. I'll post here some screenshots so you can understand better what I'm facing!
> `https://imgur.com/a/TgGbyI0`

Next release will set the in-game browser scale as well. Also fixed the pixelated/anti aliasing issue. Unfortunately scaling the tray menu seems not possible.

**Comment by Kyusung4698** [comment]
## 0.5.18 (2020-02-19)

- add browser use same scale as app (#214)
- fix blurry text after drag-drop (#214)

**Comment by xFiloo** [comment]
Here I'm with new feedback for #214.
Version: 0.5.18

- Settings interface window is still small ([img](https://imgur.com/3IXaqp8)) 
- Same goes for in-game-browser ([img](https://imgur.com/3qXExmU)). Another problem came across is that since the browser window is small, it doesn't load the results ([img](https://imgur.com/yAlOcSE)). But I think this will get auto-fixed when the window size will be big enough

**Comment by Kyusung4698** [comment]
## 0.5.19 (2020-02-20)

- add browser use 70% of primary monitor size (#214)

@xFiloo thank you for your fast feedback! 🚀 The browser window should now scale using the actual display size.

**Comment by Kyusung4698** [comment]
I'll close this issue now. Thank you for your suggestion!
