### ISSUE TITLE
blighted map ctrl+D only shows the base map

### ISSUE THREAD

**Issue by nkstnkst** [Kyusung4698/PoE-Overlay#216]
title

**Comment by fatings** [comment]
Please check the following post by the developer:
https://github.com/Kyusung4698/PoE-Overlay/issues/164#issuecomment-580404023

**Comment by Kyusung4698** [comment]
> Please check the following post by the developer:
> [#164 (comment)](https://github.com/Kyusung4698/PoE-Overlay/issues/164#issuecomment-580404023)

Thank you! This is indeed the intended behaviour. Please include the actual implict mod which identifies the map as Blighted.
