### ISSUE TITLE
Commands work about 70% of the time

### ISSUE THREAD

**Issue by toddf2p** [Kyusung4698/PoE-Overlay#217]
I use custom commands frequently and they only work about 70% of the time. I have a very fast PC, so I don't think that's the problem. Anything I can do?

I pressed it 6 times here and only 4 of them went through

https://gfycat.com/JovialRevolvingElephantseal

**Comment by Kyusung4698** [comment]
There is a built in throttle of 350ms. So 1 command per 350ms. But you can hold down the button and it will send the command every 350ms. (If the button doesn't use any modifiers like CTRL, ALT)

**Comment by toddf2p** [comment]
Ah, I'm using modifier keys.

**Comment by Kyusung4698** [comment]
I'll close this issue for now. Feel free to reopen if needed.
