### ISSUE TITLE
Suggestion : Force evaluate by link if 6-link

### ISSUE THREAD

**Issue by Nyab59** [Kyusung4698/PoE-Overlay#218]
Usually I don't want to evaluate with links or sockets, but for the 6-link items I want to.
It would be very much appreciated if there is a settings like this.

---

Thanks in advance and thank you very much for the great tool.

**Comment by fatings** [comment]
to be honest I think the sockets options in the settings should have this in consideration.
I think that most of the times you'd want to select sockets/links is with 6L

**Comment by Kyusung4698** [comment]
I think the best way to deal with this is by preselecting the sockets if this is a "best match". for example:
one handed weapon: 3 sockets -> enabled
ring: 1 socket -> enabled
armour: 5 socket -> not enabled
armour: 6 socket -> enabled
gloves: 4 socket -> enabled
etc...
what do you think?

**Comment by fatings** [comment]
To be honest I never search for sockets, only links. And for links I only search for 5L (league start) and 6L.
I don't know what you intend for the purpose of this feature, but for me I would suggest a new toggle for "Auto select 5/6L items". This allows you to keep this Sockets feature something else you might want.

**Comment by Kyusung4698** [comment]
## 0.5.19 (2020-02-20)

- add preselect links (always, 5-6, 6, never) (#218)
- remove preselect sockets
