### ISSUE TITLE
Suggestion : Make search browser to a non-modal window

### ISSUE THREAD

**Issue by Nyab59** [Kyusung4698/PoE-Overlay#219]
Currently Search Browser is a Modal Window.
But I sometimes want to check my items in the game during the search.
Is it possible to make a search browser to a non-mordal window?

I know I can use my default browser, but for the quick check tool's search browser is very useful.

Thank you very much in advance.

**Comment by Kyusung4698** [comment]
## 0.5.17 (2020-02-16)

- remove modal flag after minimizing browser (#219, #243 

Let me know if this addresses your issue! Thanks for reporting.

**Comment by Kyusung4698** [comment]
I'll close this issue. Thank you for your suggestion 👍
