### ISSUE TITLE
Error When Searching For Multi-Mod

### ISSUE THREAD

**Issue by Chundy** [Kyusung4698/PoE-Overlay#22]
Getting "An Unexpected Error Has Ocurred" when clicking "Can Have Up To 3 Crafted Modifiers" on an item.

**Comment by Kyusung4698** [comment]
Thanks for reporting. Can you please post the copied item here? (CTRL+C while hovering). I'll look into it.

**Comment by Kyusung4698** [comment]
Fixed with 0.5.0-alpha.0. Mods without values were falsy processed.
