### ISSUE TITLE
Suggestion: Count as Statistic of number of returned items given search/filter

### ISSUE THREAD

**Issue by IeUDE** [Kyusung4698/PoE-Overlay#220]
Another useful statistic near the Mean, Median, Mode, Min and Max, would be to have a 'Count' of returned items in the selected filter – e.g. with the selected filter/socket count/link there has been 34 items found, i.e. 'Count: 34' ...

**Comment by Kyusung4698** [comment]
Currently the total count is displayed while hovering a graph bar. But a Count figure makes total sense. Thanks!

**Comment by l3enjay** [comment]
@Kyusung4698 Would I be ok to pick this up?

**Comment by Kyusung4698** [comment]
> @Kyusung4698 Would I be ok to pick this up?

Yes, please. Go ahead 👍

**Comment by l3enjay** [comment]
![image](https://user-images.githubusercontent.com/44820756/74368127-ee010c00-4dca-11ea-8503-c891ab5c555f.png)
![image](https://user-images.githubusercontent.com/44820756/74368205-138e1580-4dcb-11ea-8552-db45b90fa51c.png)
![image](https://user-images.githubusercontent.com/44820756/74368363-649e0980-4dcb-11ea-9241-52921d1b2178.png)

Trying to think where makes most sense placement wise, feels a little cluttered no matter where I put it. Any opinions/other ideas?

**Comment by Kyusung4698** [comment]
Try combining Min and Max. Like 10-20 and without a label. Then move the count to the right after the currency icon.

**Comment by IeUDE** [comment]
I like it, but i got say we do not need decimal points at all in the count ...
I like the most the second/last option

**Comment by l3enjay** [comment]
![image](https://user-images.githubusercontent.com/44820756/74467326-c1172c80-4e90-11ea-9098-b1a7570bec09.png)
All done, PR coming up now

**Comment by Kyusung4698** [comment]
## 0.5.16 (2020-02-13)

- add count to evaluation results (#220)
