### ISSUE TITLE
6L search and mods orders

### ISSUE THREAD

**Issue by ngtrungkhanh** [Kyusung4698/PoE-Overlay#224]
Can we have a quick way (like a button) to chose 6L instead of click all 5 linked line?
Also can you separate normal mod and psuedo mod like trade marco?

**Comment by Kyusung4698** [comment]
All sockets/links can be selected at once by clicking while holding shift. See: https://github.com/Kyusung4698/PoE-Overlay/wiki/Evaluate#sockets

This is an intended behaviour to keep the clutter small. Therefore all mods which are aggregate as pseudo will be removed from the view. But i may add a "toggle hidden mods" in the future.

**Comment by Kyusung4698** [comment]
The hidden mods issue will be continued here #224.
