### ISSUE TITLE
Poe Website - Dedicated button (When CTRL+D) to put selected filters into a browser search.

### ISSUE THREAD

**Issue by Nirvaxstiel** [Kyusung4698/PoE-Overlay#225]
Title. I understand that clicking on the currency button will open the integrated browser, but no one really knows that at first glance unless you watched the video properly. 

Main issue is that some times item would be listed as "No Data" when inputting the same filters brings results on the website. Not sure if connection or using Poe.Trade instead of pathofexile.com/trade

**Comment by Kyusung4698** [comment]
The "No Data" text can also be clicked. Same behaviour as the currency icon. Also i assume the "No Data" is caused by the default search filters (Online Only, 3 Days Indexed). See this part of the video for visualization: https://youtu.be/_cJmW8QkQnM?t=234
