### ISSUE TITLE
Force Escape macro support?

### ISSUE THREAD

**Issue by Byngalo** [Kyusung4698/PoE-Overlay#229]
Will Force Escape Macro be added?

**Comment by Kyusung4698** [comment]
Hmm. Do you mean this #209?

**Comment by Byngalo** [comment]
Maybe...

**Comment by Norby93** [comment]
> Hmm. Do you mean this #209?

yes.

**Comment by Kyusung4698** [comment]
> > Hmm. Do you mean this #209?
> 
> yes.

Thanks. I'll close this now. Duplicate of #209
