### ISSUE TITLE
Include rare and magic items when price checking normal bases (and vice versa)

### ISSUE THREAD

**Issue by dafillio** [Kyusung4698/PoE-Overlay#231]
Most people don't care to differentiate between normal/magic/rare version of an item base if they're only concerned with ilvl. As far as I know there isn't a way to search for normal/magic/rare versions of the same base with a specific ilvl in the overlay and it's a pain (and costs currency) to scour them to normal.

**Comment by vadash** [comment]
Agree. You will almost never want to use fixed rarity. Please change item rarity to Any

**Comment by Kyusung4698** [comment]
## 0.5.20 (2020-02-23)

- update query to use rarity only for uniques (#231)

Has been changed. Thanks for reporting! 🚀
