### ISSUE TITLE
PoE in Window mode and PoE-Overlay Window

### ISSUE THREAD

**Issue by Byngalo** [Kyusung4698/PoE-Overlay#233]
Hello! I play PoE in a 1280x680 window and I have a check mark on the "Confine Mouse to Window" function. Often, when I open a price check, part of this window is outside the PoE window and in order to add or remove some items from the search, you need to move this window. Constantly moving it back and forth is not very convenient and is wasting time in the long run. Is it possible to ensure that the PoE overlay window can be locked within the PoE window and automatically adjust its size or give the opportunity to manually adjust all the sizes of all windows and to what places they were attached at the time of appearance?
P.S. Google translator was used.

**Comment by Kyusung4698** [comment]
Thank you for your request. Currently the overlay uses the primary display size. Adjustable size may come with the #214 issue.

**Comment by Byngalo** [comment]
> Thank you for your request. Currently the overlay uses the primary display size. Adjustable size may come with the #214 issue.

run-without-gpu.bat did not solve the problem. In the new version(0.5.16), the settings window generally became smaller in width and a lower scroll bar appeared.

**Comment by Kyusung4698** [comment]
## 0.6.3 (2020-03-15)

- add support for windowed mode by moving the overlay on top of poe (#233)
