### ISSUE TITLE
Close search tooltip when opening searchbrowser with it?

### ISSUE THREAD

**Issue by kad22** [Kyusung4698/PoE-Overlay#236]
Hi,

first of all thanks for the bookmark option, works great.
What i found is that if u open a webpage that way u are still able to move ingame if u minimize it other than if u open it via the search tooltip, so im guessing the search tooltip is denying that?
No idea how that works though, so sry if useless suggestion.
tyvm

**Comment by Kyusung4698** [comment]
This indeed works. In the next update once you minimize the dialog you can interact with the game again.

**Comment by Kyusung4698** [comment]
## 0.5.17 (2020-02-16)

- remove modal flag after minimizing browser (#219, #236)
