### ISSUE TITLE
Some items ignore the "disable max range" and slider settings

### ISSUE THREAD

**Issue by joe7dust** [Kyusung4698/PoE-Overlay#238]
I tried "disable max range" and using slider all the way right to +75% but when I click on No Data Found it puts the EXACT value into the search filter. Terrible way to try and find similar or better items.

Example, the flat armour, dex AND strength on Deidbell.

**Comment by Kyusung4698** [comment]
Thank you for reporting. Could you please provide some additional screenshots? I'll look into it!

**Comment by joe7dust** [comment]
Posted screens on the other issue. Suggestion, allow matching sockets by color.

**Comment by Kyusung4698** [comment]
Will be continued here #237
