### ISSUE TITLE
Evaluate - Negative mods should be reversed

### ISSUE THREAD

**Issue by fatings** [Kyusung4698/PoE-Overlay#239]
I don't know if this applies to all the negative mods, but I think that usually you want the "less bad" with negatives.

Example:
![image](https://user-images.githubusercontent.com/39002567/74569266-ec257d00-4f71-11ea-8140-51743e49fb86.png)

The filter should be <= 11 and not >=11

Opening the window I had to change:
![image](https://user-images.githubusercontent.com/39002567/74569362-25f68380-4f72-11ea-8c39-c059ccc83c5e.png)
to:
![image](https://user-images.githubusercontent.com/39002567/74569341-1c6d1b80-4f72-11ea-9687-4ac136661358.png)

**Comment by Kyusung4698** [comment]
Thank you for reporting. I'll look into it. It's not relate to all mods. There are certain which are "negated" by default. Those need extra handling.

**Comment by Kyusung4698** [comment]
## 0.5.17 (2020-02-16)

- fix non negated negative mods flipped (#239)

**Comment by Kyusung4698** [comment]
Closed. Feel free to reopen if needed.

**Comment by fatings** [comment]
Another example:
![image](https://user-images.githubusercontent.com/39002567/75607094-66fea400-5aeb-11ea-8bb8-d7e0e5c23ed7.png)
![image](https://user-images.githubusercontent.com/39002567/75607097-71b93900-5aeb-11ea-8aa5-9ff4224f764a.png)
![image](https://user-images.githubusercontent.com/39002567/75607100-7b42a100-5aeb-11ea-8d25-c101001238f4.png)

Correct filter should be from -999 to -6

**Comment by fatings** [comment]
More examples:

1.
![image](https://user-images.githubusercontent.com/39002567/76768372-cec31900-6792-11ea-8fa6-be37a33377ab.png)
![image](https://user-images.githubusercontent.com/39002567/76768445-eb5f5100-6792-11ea-8c46-0d82e3d99ad2.png)

2.
![image](https://user-images.githubusercontent.com/39002567/76768542-0f229700-6793-11ea-99b3-e8b587908d26.png)
![image](https://user-images.githubusercontent.com/39002567/76768631-311c1980-6793-11ea-9976-d38f173b0280.png)

@Kyusung4698 I don't see an option to reopen the ticket so I'm tagging you just to make sure you don't miss it.
