### ISSUE TITLE
Can't check other stat of dual-mod

### ISSUE THREAD

**Issue by Eodar** [Kyusung4698/PoE-Overlay#24]
My gloves have crafted +12 max life and 79 in base. But either I can't select +91 Life nor +12 AND +79. Also looks like it doesn't search dual mod at all cause as you can see in STAT FILTERS there is no #% Increased Energy Shield
![obraz](https://user-images.githubusercontent.com/29659679/72020069-3cbb0380-326b-11ea-801b-0c67f4ddb87d.png)

**Comment by Kyusung4698** [comment]
Seems odd. Multiple filters are definitely possible. Can you share your copied item please? (CTRL+C while hovering)
Total modifiers are not supported yet.

**Comment by Eodar** [comment]
Sure ;)

Rarity: Rare
Ghoul Hold
Fingerless Silk Gloves
--------
Quality: +20% (augmented)
Energy Shield: 60 (augmented)
--------
Requirements:
Level: 70
Str: 111
Int: 95
--------
Sockets: R-R-R-B 
--------
Item Level: 85
--------
14% increased Spell Damage (implicit)
--------
Adds 6 to 9 Physical Damage to Attacks
+79 to maximum Life
Regenerate 9.4 Life per second
+47% to Fire Resistance
+32% to Cold Resistance
19% increased Energy Shield (crafted)
+12 to maximum Life (crafted)

**Comment by Kyusung4698** [comment]
Fixed with 0.5.0-alpha.0.
