### ISSUE TITLE
default keyboard shortcuts not released on change

### ISSUE THREAD

**Issue by azra1l** [Kyusung4698/PoE-Overlay#244]
i switched several keyboard shortcuts, afterwards at least some commands seem to work with both, old and new shortcuts. i am currently unable to release the old shortcuts, which renders the tool basically useless because it messes with the ingame shortcuts for the alternate skill keybinds, like CTRL+T

and i would rather not change my ingame keybinds...

i really hope this can be fixed somehow, because i am already addicted to this tool :S

**Comment by Kyusung4698** [comment]
Thank you for creating an issue. Please try to restart the overlay after saving new hotkeys. This should fix it as a workaround. I'll look into it.

**Comment by azra1l** [comment]
i started using version .16, updated to .17, the issue was present the
whole time.
restarting the script does not work :(

**Comment by Kyusung4698** [comment]
i'm unable to reproduce this issue. some follow-up questions: 

* have you restarted your pc since then? is this still present? 
* what keybindings have you changed? and what are the new hotkeys?

Thanks in advance!

**Comment by azra1l** [comment]
hi,


yes, i restarted several times by now.

f. e. i bind translate from default CTRL+T to F3.

so essentially F3 and CTRL+T are both bound to translate. When i bind
translate to F4,
then F4 and CTRL+T are both bound to translate.

i use QWERT as key binds for my ingame skill bar, combined with CTRL for
the alternate skill bar.
so when i want to use my 5th alternate skill, it won't work because the
overlay intercepts the key bind.

i had an unfortunate accident when that first happened xD luckily i don't
play hardcore so it's all good.


Lars Grünheid
