### ISSUE TITLE
Feature Request: Seperate Min-Max sliders

### ISSUE THREAD

**Issue by sclient** [Kyusung4698/PoE-Overlay#249]
If Im hunting for upgrades, I dont want to find items that are 10% worse than my current item. I requested this on reddit, but I thought it would be a good idea to put a reminder here. Thanks!

**Comment by Kyusung4698** [comment]
## 0.5.19 (2020-02-20)

- add min/ max modifier range (#249)

**Comment by sclient** [comment]
Amazing work. One day till its implemented and released. You guys are killing it!

**Comment by Kyusung4698** [comment]
You're welcome! Looking forward to your feedback 👍
