### ISSUE TITLE
Feature Request - add a small incubator icon to items which have incubators on them

### ISSUE THREAD

**Issue by Bastil12** [Kyusung4698/PoE-Overlay#253]
Everyone uses incubators and after 10 or so, it gets tedious to remember which item has an incubator applied to them. Maybe add a small progress bar which fills from 0 to 100 as well?

**Comment by Kyusung4698** [comment]
Thanks for creating an issue. Can you describe your idea a little more? Like where should this icon go. Should it be searchable etc. Maybe add a screenshot with a marker. Thanks!

**Comment by Bastil12** [comment]
I was thinking about small icons around the items themselves, here's a rough idea of it - https://i.imgur.com/vkxdK3F.jpg - maybe making it half-transparent or putting it in a corner of an item could be a better idea though.

Also while I have your attention, one feature doesn't work - trying to bulk-price an item (example - fossil: https://i.imgur.com/e4N5z5x.png ) and pressing bulk price option (10c in this example) sets singular item  at the price of bulk (1 fossil for 10c) instead of bulk for bulk price (5 for 10c or chaos 10/5)

**Comment by Kyusung4698** [comment]
## 0.5.20 (2020-02-23)

- add bulk price support for fast tagging (#253)

I do like this feature but i think for now this is not possible. I retrieve the item data while hovering the item and (ctrl + c) and then parsing this copied data. 

...but one possibility would be using the public stash api. this has some flaws like calculating the item on screen position (x,y) and i'd need to know if the inventar is open or not. i guess you'd be better asking GGG for this feature.
