### ISSUE TITLE
Suggestion: Filename for releases

### ISSUE THREAD

**Issue by mintjustin** [Kyusung4698/PoE-Overlay#254]
I'm using autohotkey script to start up the client and this script and it's a hassle to have to change the script or filename every time there is an update.

I suggestion is to keep the .exe file inside the zip file consistent so we can just override the old file after each updates.

**Comment by Kyusung4698** [comment]
Hi, the name of the executable is now `poe-overlay.exe`. Thanks for creating an issue!
