### ISSUE TITLE
Too much decimal

### ISSUE THREAD

**Issue by LongJohnDude** [Kyusung4698/PoE-Overlay#255]
Decimal, decimal everywhere! 

![image](https://user-images.githubusercontent.com/34474044/74967345-76159000-5421-11ea-8686-aafa2fcb67a8.png)
Too much and excessively accurate. Who need for example +5.2 Strength? These numbers are too difficult to perception. 

In fact, there are a maximum of a dozen percentage mods that really need decimal: leech (life/mana/ES), % regen (life/mana/ES), spells/attacks have X% to critical strike chance (suffix and corrupt implicit) and maybe few unique mod (like Bottled Faith have) and they all similar to listed above. 

And all flat added attack/spell/all damage requires accuracy not exceeding 0,5 (coz an increase mod by the minimum possible value, i.e. one, changes the average value to 0.5). So for the case when "Modifier range" enable we can use rounding to the nearest whole (or at least to nearest x*0.5), and in case this option disable this problem will be absent. 

For all other values, this only complicates the perception and does not bear any practical value.

P.S. The order of all elemental total mods is reversed to the usual (to what is in the game - fire->cold->lightning)

P.P.S. About redundancy - some mods do not require all types of total that it can produce. For example (see image above) all this "increased lightning/cold/fire spell damage" not need if they are not inherited from two or more mods (for example increased spell damage + increased cold damage). But! for example total resistance still very useful even if it is inherited from one mod. So this proposal may require more careful consideration and for sure this is luxury enhancement not basic functionality.

**Comment by Kyusung4698** [comment]
## 0.5.19 (2020-02-20)

- add ceiling/ flooring for mod ranges if possible (#255)
- update pseudo elemental order (fire > cold > lightning) (#255)
- remove some pseudo redundancies (#255)
