### ISSUE TITLE
[BUG] Ctrl+wheel doesn't work anymore after 5.16

### ISSUE THREAD

**Issue by xFiloo** [Kyusung4698/PoE-Overlay#257]
I'll provide more info about it if needed, for now, all I can say is that v5.16 allows me to scroll stash tabs with ctrl+wheel, v5.17+ don't.

E1: Checked both 5.17 .exe and .bat with admin rights
E2: To be sure there's no conflict with other addons such as trade-companion, all tests have been made with all addons off

I'm the same guy who posted in #214

**Comment by Kyusung4698** [comment]
Thanks for creating an issue. I think this is related to the UI scaling. Can you give it a try with 100% scale? Thanks! I'll look into it.

**Comment by xFiloo** [comment]
> Thanks for creating an issue. I think this is related to the UI scaling. Can you give it a try with 100% scale? Thanks! I'll look into it.

Yes at 100% it work

**Comment by rixanXD** [comment]
Having this issue as well. What I've gathered is - if you ctrl+wheel while your cursor is INSIDE the stash window area, it scrolls through each tab as normal. However, if you try ctrl+wheel again while your cursor is outside of stash window area, it skips a tab on each scroll.

I tested this @ 100% scale and with no other addons running.

**Comment by xFiloo** [comment]
It works now, thanks
