### ISSUE TITLE
Evaluate Doesn't Work on Pure Talent (Unique Jewel)

### ISSUE THREAD

**Issue by herofromhyrule** [Kyusung4698/PoE-Overlay#258]
Using the Evaluate Command on the Pure Talent Unique Jewel never pops up the Evaluate UI. I see the mouse cursor change to my System Cursor (as opposed to the in-game cursor) but the UI never pops up. I'm using version 0.5.19

**Comment by Kyusung4698** [comment]
## 0.5.20 (2020-02-23)

- fix evaluate dialog out of overlay bounds (#258)

Thanks for reporting! The mentioned item uses a single stat for seven values. This resulted in a (too) large dialog width. Should be fixed 👍
