### ISSUE TITLE
[BUG] Using Alt as a shortcut modifier closes all open windows

### ISSUE THREAD

**Issue by TgDn32** [Kyusung4698/PoE-Overlay#259]
Using any of the shortcut keys with Alt as a modifier will close all open programs including PoE Overlay. The CTRL modifier shortcuts work fine, and any shortcut that closed programs using ALT work fine if remapped to CTRL.

Running Windows 10 and Overlay Version 0.5.19, also tested version 0.5.18.

**Comment by Kyusung4698** [comment]
Thank you for creating an issue. I could only reproduce this with `ALT + F4` which is a system hotkey to close the current window. Therefore i removed it as possible hotkey. Can you post your faulty hotkeys? Thanks!

**Comment by TgDn32** [comment]
Tested a few more hotkeys, and the issue MIGHT be that they coincide with secondary skill bar in PoE.

I set the wiki shortcut to ALT+A, and it worked fine with no crash. If I set it to ALT+Q/W/E/R/T, which are my secondary skill bar hotkeys, I get the window closing.

**Comment by Kyusung4698** [comment]
Thank you for your follow up. I'll close this issue now.
