### ISSUE TITLE
[BUG] Implicits not showing

### ISSUE THREAD

**Issue by jix91** [Kyusung4698/PoE-Overlay#260]
If an item has more than 2 implicits they are not shown... 

https://imgur.com/a/NTnQ2nW

**Comment by Kyusung4698** [comment]
Thanks for creating an issue. Seems like your imgur image is broken. Can you please reupload? Thanks!

**Comment by jix91** [comment]
Hey,

I was just testing any 3 implicit high Templar gloves. I believe you have a limit on implicits? Mine had +1 frenzy, ats and base attack crit. Can’t upload right now sorry.

Brgs,
Jix

**Comment by Kyusung4698** [comment]
Hi, I've tried some high template gloves from the trade marketplace. They all seemed to work. To be fair i've only test like 2-3 with high implicit count. 
Also there is not limit on implicits. I think it's mostly related to some mods which are not supported yet.
Therefore looking forward to your image/item data.

**Comment by Kyusung4698** [comment]
I'll close this issue for now. Feel free to reopen with attached item data.
