### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by thorsten-passfeld** [Kyusung4698/PoE-Overlay#261]
Hey there!

I really enjoy playing Path of Exile and there just haven't been that many alternatives for the popular trade macro for Linux users, which is a bummer.

I'm wondering if PoE-Overlay already works on Linux or if you feel like some things related to window-popups can't work the same on Linux as they do on Windows. For the next league, I would really want to try another overlay that saves me the trouble of manually price checking my good items, which can take 5-15 minutes sometimes.

Overall, me and probably many other Linux users would love to have more choice when it comes to Trade-Macro alternatives. I could probably even assist with testing and maybe even fixing certain bugs or pin-pointing their location somewhat.

Initially, I wanted to just build and try out this program, but you mentioned having to use Windows-build-tools:

> npm install --global --production windows-build-tools

Since I've never really done anything related to Nodejs, I'm wondering if there is an alternative for Linux that I can use (there must be one). From looking at some of your code, I haven't really found any platform-specific code, so I got my hopes up somewhat!

Can we get PoE-Overlay working on Linux? It's already such a useful program that I would not want to miss out on it!

**Comment by Kyusung4698** [comment]
Hi,

Electron itself is compatible with Linux. But in order to gain access to certain feature - you must use something called a 'native module' which basically wraps those things in a c/c++ module and provide a node js api. For now i'm using two:

* robotjs (simulate mouse & keyboard) - this one is compatible with Linux.
* hotkeys (capture mouse input, check if poe is active) - not compatible because a community member and i wrote it. 

So in order to provide this tool on Linux - which i'd love to do so! - a Linux port of this module would be required but my c++ skills are pretty lacking. The module can be found here: 
https://github.com/Kyusung4698/hotkeys

Unless i find a way around using my hotkeys module - there won't be any Linux support in the near future.

Best regards

**Comment by thorsten-passfeld** [comment]
Hey, thank you for this very helpful insight!

I've taken a look at the code in question and even though I'm quite experienced with C++, I'm not very familiar with the libraries you used. But because this mostly only seems to be a single file we'd need to rewrite/overhaul, I feel like it would be a good start for you to document every single function and just state what exactly it expects as an input, what exactly it may output and what exactly its task is. From looking at it, I think I understood most functions, but this will greatly help when reimplementing the individual functions.

To me it is still a bit confusing how exactly C++ can just be used in combination with Javascript/Node.js. But I definitely see that "hotkeys.cc" includes Windows-specific libraries. It may get a little bit tricky, but I feel like we can definitely achieve this rather small Linux port if we can verify that every new function still does the same as before after reworking it.

**Comment by Kyusung4698** [comment]
Hi,
the current state is quite bad. i'll clean it up and add some comments. once this is done i'll hit you up. also the library used for binding node js with native:
https://github.com/nodejs/node-gyp

**Comment by thorsten-passfeld** [comment]
I've done a bit more research into this and we'll need to write some Linux/X11-specific code from what I could gather to e.g. get the currently active window, its title, etc. 

That's why I would suggest to create a second "hotkeys_linux.cc" file and detect the OS just before deciding which one to use. Personally, I haven't yet worked with window handles (Windows) or similar equivalents in Linux, so my knowledge on this is a bit limited. But once I understand exactly what each function really needs to be doing in detail, I feel like this will make researching what to use quite a bit easier!

**Comment by Kyusung4698** [comment]
Yes! My plan is to create a separat file for each env and one main file which will handle all the common logic. Then we can use MACROS to import the correct env functions. Because each env would require a own build. 

A project for Linux/Windows input:
https://github.com/wilix-team/iohook

What's your discord tag? I'll add you there.

**Comment by thorsten-passfeld** [comment]
Can you give me yours? I'm using my real name here. :D

**Comment by Kyusung4698** [comment]
Hi,

just a quick update. i completely removed the hotkeys dependency but i can not get it to work at linux (debian) cause my skills for linux are quite lacking. anyway all native dependencies are now linux compatible.

add me on discord `kyusung4698#1125` and we may get it to work together.

**Comment by Kyusung4698** [comment]
just got it working!!! 🚀 still needs some work tho.

![image](https://user-images.githubusercontent.com/38520678/76162985-b0ca3880-6142-11ea-8de4-fe7eae92cf96.png)

**Comment by thorsten-passfeld** [comment]
Nice! Good job on this! I sent you a friend request. If you need help regarding Linux, I can probably help you pinpoint issues.

**Comment by tylerreisinger** [comment]
Linux support would be amazing. I know C++ well and Xorg to some level, but not electron. If you need assistance on the linux side, I'd also be able to help.

**Comment by fatino** [comment]
I would love to see Linux support. I'm up for testing if you need any.

**Comment by thorsten-passfeld** [comment]
I already use it for POE on Linux. It's not perfect and not everything works (like pressing F5 for example for the hideout), but the CTRL+D shortcut also didn't seem to work at first, because the popup window wasn't clickable. Turns out you have to tab out of the game window (doesn't have to minimize it) and then the popup window is clickable and usable as expected.

Having to CTRL+C before pressing CTRL+D is mildly annoying though. And I wish that on pressing CRTL+D it would basically trigger a CTRL+C at your cursor position before running the code for CTRL+D.

Other than that, I'm quite happy with how it works. Price checking is so much better now.

**Comment by tylerreisinger** [comment]
@thorsten-passfeld How do you get it to attach properly? I have it running successfully in the same prefix as path of exile, but it doesn't ever load in the game window.

**Comment by thorsten-passfeld** [comment]
> @thorsten-passfeld How do you get it to attach properly? I have it running successfully in the same prefix as path of exile, but it doesn't ever load in the game window.

First of all, you don't need to be running this Overlay in the same prefix at all!
Clone this repository somewhere in your home folder or anywhere really.

You will need to install the following on your PC (not sure what distro you're using):
https://github.com/nodejs/node-gyp#on-unix
https://robotjs.io/docs/building
Then, through apt, pacman, yay or whatever package manager you're using, install these packages:

libxtst-dev
libpng++-dev

Keep in mind that Arch/Manjaro don't split their packages into -dev subpackages as far as I know. These are included in e.g. libxtst and libpng++ or however they are similarly called

Then you need this: https://wilix-team.github.io/iohook/manual-build.html

And for the rest, basically follow the instructions for developers here: https://github.com/Kyusung4698/PoE-Overlay

Then on starting this application, a developer console should come up. If it does, you can minimize it and press F7 to launch the configuration window if you need it.
Other than that, just go ingame, hover over an item, press CTRL + C, then CTRL + D and a pop up window should come up with details about that item. For some reason, it is unclickable, because the window is not in focus, even if it is on top.
The workaround is to quickly press ALT + Tab, which for me makes it so that popup is on top and I can interact with it without minimizing POE in the process. But this of course depends on if you're also using KDE or if you use e.g. Gnome instead.
I hope this helps.

**Comment by fatino** [comment]
@thorsten-passfeld yeah I have similar experience. 
But for me it needs desktop effects to be enabled. I use steam proton and KDE. When I run the overlay with effects disabled(steam automatically disables them) then all I can see is black screen with poe overlay text in a corner. But if I run the game with effect enabled, I can see the game.

**Comment by Kyusung4698** [comment]
Hi, thanks for your feedback. I'll close this issue now because i've create a new Milestone named 'Linux'. Please create new issues (one for each!) and add this Milestone. Once all issues are completed i'll release a public version.
