### ISSUE TITLE
"%Increased Experience gain" returns nothing - Perandus Signet

### ISSUE THREAD

**Issue by MalakaJones** [Kyusung4698/PoE-Overlay#262]
First image is without "%Increased Experience gain" (returns a couple listings) but when I add it to the filter, it wont return any listing. Since it's a non-variable mod, it should not behave that way.

![image](https://user-images.githubusercontent.com/15826583/75115341-741f1d00-562b-11ea-899f-ef4b086a4121.png)

![image](https://user-images.githubusercontent.com/15826583/75115392-235bf400-562c-11ea-9426-6cbaac3a0670.png)

So I went looking on the official website to check what mod was actually selected and this is what showed up:

![image](https://user-images.githubusercontent.com/15826583/75115436-877eb800-562c-11ea-82d3-350286a45d13.png)

The overlay does not select the right mod. "%Increased Experience gain (maps)" won't work with Perandus Signet. the right one is the one without "(maps)" tag

**Comment by Kyusung4698** [comment]
Thank you for creating an issue. Maps mods are not supported for now. They do behave the same as local ones. Therefore i'm looking forward building a generic solution. Will keep this issue update!
