### ISSUE TITLE
[BUG] ALT + F not working for me

### ISSUE THREAD

**Issue by DeepLake** [Kyusung4698/PoE-Overlay#264]
I have had this problem after 0.5.17 update. 
Before the 0.5.17 update, I can use Ctrl+F to make the highlight hotkey. 
But now, ALT + F or Ctrl+ F is not working.
I also try running it as admin, and use latest version 0.5.19.

**Comment by Kyusung4698** [comment]
Thanks for reporting! I could not reproduce this issue but there were some issue regarding the `ALT` modifier prior 0.5.20. Could you give the new version a try? Thanks!

**Comment by DeepLake** [comment]
Works fine now. Thank you very much for the fix.

**Comment by Kyusung4698** [comment]
> Works fine now. Thank you very much for the fix.

Awesome!
