### ISSUE TITLE
[BUG] cannot fast tag item anymore v 0.5.20

### ISSUE THREAD

**Issue by xFiloo** [Kyusung4698/PoE-Overlay#266]
I'm the same guy who opened #257. I'm no longer able to fast price items in the stash, things don't change if I set 100% zoom. Sometimes the mouse moves at top left corner of the stash and sometimes the addon says that only item in stash can be fast tagged.

Stash is a normal premium one 12x12

**Comment by Kyusung4698** [comment]
Thanks for reporting. I'll release a new version soon ~20min.

**Comment by Kyusung4698** [comment]
## 0.5.21 (2020-02-23)

 - fix fast tag not working on multiple monitor set-up (#266)

**Comment by xFiloo** [comment]
Maybe I was doing something wrong with 5.20 because for fast price tag I was used to move your alt+d interface away from the item then fast price tag it, now I noticed that I don't have to do it, and if I do it, its get bugged. Anyway, without moving the window is quite better, we can close I guess

**Comment by Kyusung4698** [comment]
> Maybe I was doing something wrong with 5.20 because for fast price tag I was used to move your alt+d interface away from the item then fast price tag it, now I noticed that I don't have to move it. We can close I guess

No, 5.20 was definitely broken. Glad it's working now!
