### ISSUE TITLE
Can't assign "|" the button left of 1 to any macro

### ISSUE THREAD

**Issue by dubcat** [Kyusung4698/PoE-Overlay#269]
Can't assign "|" the button left of 1, I use this button as my /exit macro.
Would be awesome if you could add support for | and <

**Comment by Kyusung4698** [comment]
Thank you for your suggestion. Should be no issue to add. I'll look into it.

**Comment by patrickracicot** [comment]
> Thank you for your suggestion. Should be no issue to add. I'll look into it.

First of all thanks for this great tool!!

Now I've just forked and cloned the repo to start and read the sources.  The source of the issue here is inside the `accelerator.component.ts`.  You have a regex to test the allowed `KEY_CODES` which only accepts F!-F34, A-Z and 0-9.

**Comment by Kyusung4698** [comment]
Thanks for the compliments! 👍 That's right. If you'd like you can update the regex. See [electron documentation](https://www.electronjs.org/docs/api/accelerator) for allowed key codes. I've tried to add those requested keycodes but i have a hard time testing it with my german QWERTZ layout.

**Comment by patrickracicot** [comment]
I'm currently at work on a macOS,  I will try it, if it doesn't work I'll setup myself during the week on my windows machine back home.

**Comment by patrickracicot** [comment]
I've just sent out a new PR #291 which adds the a fix for this.

**Comment by patrickracicot** [comment]
@Kyusung4698  I think we can close this unless you prefer to have @dubcat to validate it =)

**Comment by Kyusung4698** [comment]
@patrickracicot Thanks for your PR. I'll close this issue once it's provided in an actual release.

**Comment by patrickracicot** [comment]
@Kyusung4698 🤦‍♂ what was I thinking hehe.

**Comment by Kyusung4698** [comment]
## 0.6.0 (2020-03-12)

- update accelerators to support `|< (#269)

@patrickracicot Closed. 😏
