### ISSUE TITLE
Implicit items apearing on prefix and sufix

### ISSUE THREAD

**Issue by diegoSloth** [Kyusung4698/PoE-Overlay#272]
![image](https://user-images.githubusercontent.com/61520652/75554859-e623a780-5a19-11ea-9aba-2f0d420ec79c.png)

**Comment by Kyusung4698** [comment]
Thank you for creating an issue. Could you please elaborate what's your expected behaviour? And please add the actual item data (ctrl + c). Thank you!

**Comment by diegoSloth** [comment]
instead appearing life gain on hit, there must be global critical strike chance

**Comment by Kyusung4698** [comment]
> instead appearing life gain on hit, there must be global critical strike chance

I'm sorry but i do not understand your issue. The screenshot shows the Global Crtical Strike Chance modifier. All grey modifiers are pseudo modifiers which are aggregates regardless of the source of the mod (implicit/ explicit).

**Comment by Kyusung4698** [comment]
Okay. I understand it now. This issue will be followed here #287.
