### ISSUE TITLE
Suggestion: Toggle League/Standard

### ISSUE THREAD

**Issue by jix91** [Kyusung4698/PoE-Overlay#273]
I'd love to have a toggle to switch between my currently selected league and the fitting standard league.  
E.g. Metamorph SC -> Standard  
Metamorph HC -> Perm. HC

**Comment by Kyusung4698** [comment]
## 0.6.11 (2020-03-24)

- add league as fast toggle option

![image](https://user-images.githubusercontent.com/38520678/77449399-2cd6a880-6df2-11ea-9494-b26e8a013c66.png)
