### ISSUE TITLE
Timeless jewels no longer offering keystone choices

### ISSUE THREAD

**Issue by dafillio** [Kyusung4698/PoE-Overlay#274]
Here's example: [glorious vanity](https://i.imgur.com/WtnNqK1.png)

It used to be the case that you could select which keystone figure it had but it's no longer offered. This is important because prices vary depending on the name.

**Comment by Kyusung4698** [comment]
Thank you for creating an issue. Can you please attach the actual item data (ctrl + c) aswell. Thank you! I'll look into it.

**Comment by dafillio** [comment]
This is an example of a glorious vanity jewel ctrl+c:

Rarity: Unique
Glorious Vanity
Timeless Jewel
--------
Limited to: 1 Historic
Radius: Large
--------
Item Level: 86
--------
Bathed in the blood of 4248 sacrificed in the name of Doryani
Passives in radius are Conquered by the Vaal
Historic
--------
They believed themselves the pinnacle of civilisation, but that height toppled their empire.
--------
Place into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.
--------
Note: ~price 99 chaos

**Comment by Kyusung4698** [comment]
## 0.5.22 (2020-03-08)

- fix timeless jewels missing keystone (#274)
