### ISSUE TITLE
Recalibrate Window

### ISSUE THREAD

**Issue by mgerb** [Kyusung4698/PoE-Overlay#275]
I really appreciate the effort put in here, the UI is beautiful and it works great!

I do seem to have an issue. Let me try to explain. I'm running on a 3 monitor setup at the moment with 2x 1080p and 1x 3440x1440 ultra wide. When I leave the overlay running and go afk my computer goes into sleep mode. This causes my monitors to flicker and temporarily mess up which monitor the game is running on when I awaken it (pun intended). This also causes the overlay calibration to be off. When the overlay pops up it then shows on another one of my monitors. I can drag it around and it disappears about half way through my main one.

Currently to resolve this when I have POE open is to open task manager and close the overlay from there, because I can't right click it from the tray in the bottom right (POE seems to cover up the popup).

I have two suggestions that would really help me out:

- option somewhere in the UI (maybe in the misc tab) to re-calibrate the window coordinates
- option somewhere in the UI to close the overlay (so I don't have to close with task manager without close POE)

Thanks again for your hard work!

**Comment by Kyusung4698** [comment]
Thank you for your suggestion. I'll add a new tray menu button 'Relaunch'. Which will relaunch the overlay. Also try clicking the tray menu twice this should move the popup to the front.

**Comment by mgerb** [comment]
Double clicking the tray icon works great and brings up the full window. I play in windowed full screen and for some reason right clicking the tray icon the menu is covered up by my game.

**Comment by Kyusung4698** [comment]
> Double clicking the tray icon works great and brings up the full window. I play in windowed full screen and for some reason right clicking the tray icon the menu is covered up by my game.

I actually meant right clicking twice (not as double click). The second action should move the popup to the front. But as your PR will add those buttons to the menu - double clicking will also work 😄 Thanks for your contribution!
