### ISSUE TITLE
Suggestion: Close settings shortcut

### ISSUE THREAD

**Issue by abelgoodwin1988** [Kyusung4698/PoE-Overlay#279]
Hi!
I don't think an issue has been filed on this feature request yet. I think it would be intuitive to close the settings menu with a shortcut, such at esc key.

Point me to where I can find some of the code for this and I could hack around on it as well.

Thanks for the great app!

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Currently there are to action to be performed `Save` and `Cancel`. Unless we open another dialog to choose the actual choice i don't think a shortcut would be a good idea.
