### ISSUE TITLE
adding option to filter out item base + influence

### ISSUE THREAD

**Issue by howardgod** [Kyusung4698/PoE-Overlay#28]
influence: shaper/elder/warlord/redeemer/hunter/cursaor

basically poe.ninja's base type category

thanks

**Comment by howardgod** [comment]
Single influence

1. crusador

Rarity: Rare
Empyrean Jack
Necromancer Silks
--------
Energy Shield: 160 (augmented)
--------
Requirements:
Level: 64
Int: 160
--------
Sockets: B-B 
--------
Item Level: 84
--------
37% increased Energy Shield
+28% to Fire Resistance
Recover 6% of Energy Shield on Kill
14% increased Stun and Block Recovery
Regenerate 0.6% of Energy Shield per second
--------
Crusader Item

2. redeemer

Rarity: Rare
Soul Knuckle
Murder Mitts
--------
Evasion Rating: 145 (augmented)
Energy Shield: 35 (augmented)
--------
Requirements:
Level: 67
Dex: 51
Int: 51
--------
Sockets: B-G G 
--------
Item Level: 83
--------
+55 to Dexterity
+24 to Evasion Rating
+11 to maximum Energy Shield
8% Global chance to Blind Enemies on hit
Adds 8 to 10 Physical Damage if you've dealt a Critical Strike Recently
--------
Redeemer Item

3. hunter
Rarity: Rare
Eagle Hide
Necromancer Silks
--------
Energy Shield: 131 (augmented)
--------
Requirements:
Level: 66
Int: 160
--------
Sockets: B-B B 
--------
Item Level: 83
--------
+26 to Intelligence
+14 to maximum Energy Shield
+76 to maximum Life
+18 to maximum Mana
+8% to Fire Resistance
12% of Physical Damage from Hits taken as Chaos Damage
--------
Hunter Item

4. warlord

Rarity: Rare
Blood Gorget
Lapis Amulet
--------
Requirements:
Level: 59
--------
Item Level: 84
--------
+26 to Intelligence (implicit)
--------
+49 to Dexterity
+35 to Intelligence
+7 to maximum Energy Shield
4% increased Damage per Endurance Charge
--------
Warlord Item

**Comment by howardgod** [comment]
multiple influences

1. crusador + redeemer

Rarity: Rare
Victory Jack
Vaal Regalia
--------
Quality: +30% (augmented)
Energy Shield: 212 (augmented)
--------
Requirements:
Level: 76
Int: 194
--------
Sockets: B-B-B-B-B-B 
--------
Item Level: 100
--------
+40% to Cold Resistance
10% chance to gain a Frenzy Charge on Hit
Killed Enemies Explode, dealing 3% of their Life as Physical Damage
Can have up to 3 Crafted Modifiers (crafted)
+78 to maximum Life (crafted)
Gain 10% of Maximum Life as Extra Maximum Energy Shield (crafted)
--------
Crusader Item
Redeemer Item

**Comment by Kyusung4698** [comment]
Awesome! Thank you. I've just wrapper your stuff in a Code.

**Comment by Kyusung4698** [comment]
preview:
![image](https://user-images.githubusercontent.com/38520678/72091847-6890c480-3311-11ea-806e-d79a59d4c6a7.png)

**Comment by Kyusung4698** [comment]
Item base will be continued here #29

**Comment by howardgod** [comment]
I must say good job!!!
