### ISSUE TITLE
Javascript error with newest version (0.5.22)

### ISSUE THREAD

**Issue by ParsHere** [Kyusung4698/PoE-Overlay#283]
I keep getting the same error when I try to launch 5.22. I can launch the previous version with no issues.

![image](https://user-images.githubusercontent.com/41413704/76168944-eae70a80-6141-11ea-8170-6f624cd20326.png)

**Comment by Kyusung4698** [comment]
Thanks for creating an issue. Could you please tell me your OS and if its x86 or x64? Thanks! Also in the meantime try installing the [visual c support libraries](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) (vc_redist.x64.exe/vc_redist.x86.exe).

**Comment by ParsHere** [comment]
Installing the csupport library fixed the issue, thanks! Just for the record I am on Windows 10 x64

**Comment by Kyusung4698** [comment]
> Installing the csupport library fixed the issue, thanks! Just for the record I am on Windows 10 x64

Awesome! Thanks for your feedback. I'll add it as requirement at the README. Closed.
