### ISSUE TITLE
Search directly in divination tab

### ISSUE THREAD

**Issue by markuchi** [Kyusung4698/PoE-Overlay#285]
ctrl+d directly in divination tab doesnt work

**Comment by Kyusung4698** [comment]
I do not own a divination tab so i can not test it. Are there any errors? If so please attach an screenshot (if needed). Thanks!

**Comment by markuchi** [comment]
When you ctrl+d on the div tab it just says something about copying down the bottom. ill get a screenshot later.

**Comment by BLumbye** [comment]
Ctrl+c doesn't work in a divination tab, so i doubt it will be possible to get this working.

**Comment by markuchi** [comment]
It works with trademacro currently so not sure why it wouldnt be possible.

**Comment by Kyusung4698** [comment]
Hi, i've bought the divination tab and `CTRL + C` does not work. Also the TradeMacro does no longer support it. See: https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/673
