### ISSUE TITLE
Scroll to navigate through stash tabs zooms in and out

### ISSUE THREAD

**Issue by fagitomania** [Kyusung4698/PoE-Overlay#288]
If when you try to navigate your stash with scroll wheel and ctrl and then cursor in the middle of the screen (ie not inside the inventory or stash windows) the camera zooms in and out as you scroll through your stash tabs and it can be quite annoying

**Comment by Kyusung4698** [comment]
> There is currently no plan on developing a way of blocking the mouse input.

See #146 - but you can disable the in game zoom in the game settings for now.
