### ISSUE TITLE
Expand search parameters for rares

### ISSUE THREAD

**Issue by 766b** [Kyusung4698/PoE-Overlay#29]
Version: 0.4.0 (2020-01-08)

Current search parameters use item base name by default, this severely limits search results. I think most people would want to search by category to get approximate value for an item. For example instead of search results (unless user selects base specifically) for "Two-Stone Ring", results from "Ring" category would be more appropriate.

This will require a bit more work in background, for example breaking up implicit mods from Two-Stone Ring into pseudo mods (related to #7), but overall quality of results should be much better.

**Comment by Kyusung4698** [comment]
0.5.1 now supports both requests. Please report back if this meets your requirements. Also as this process can't be automated i did not include all available pseudo filters. Make sure to report back if you need any other. Thanks for making this tool better!

**Comment by Kyusung4698** [comment]
I'll close this for now. Feel free to re-open.
