### ISSUE TITLE
Suggestion: Add an item highlight option like POE.trade macro

### ISSUE THREAD

**Issue by ZeroCool940711** [Kyusung4698/PoE-Overlay#293]
It would be nice to be able to press Ctrl+F when your mouse is over an item and your stash is open to copy and paste the item's name onto the stash search box like POE trade macro does, this helps a lot when trying to find similar items like fragments or cards inside a stash tab, I think its the only thing missing from POE Overlay that forces me to still use POE trade macro, would be nice to have that so I can finally stop using POE Trade Macro once and for all.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This feature is actually implemented but with another shortcut `ALT + F`. Can be enabled at Miscs:

![image](https://user-images.githubusercontent.com/38520678/76565410-d04ac380-64aa-11ea-85e1-c081316f0564.png)

**Comment by ZeroCool940711** [comment]
Oh, how could I have missed that on the UI?, im pretty sure I checked multiple times to see if it was on the UI somewhere .-. , is there any chance it could be changed to Ctrl+F instead of Alt+F or be added as something we could change like the other shortcuts in that same tab?

**Comment by Kyusung4698** [comment]
I'd love to support `CTRL + F` but it's unreliable because it's the game hotkey for selecting the search field and may cause an invalid result because my copy command was not fast enough to executed. Therefore `ALT + F` was used. This is 100% reliable.

**Comment by ZeroCool940711** [comment]
What if you delay it for a second or two and just then paste the text on the search box as it will be already selected or make it so you have to press Ctrl+F twice?

**Comment by ZeroCool940711** [comment]
Also you could add a customizable delay for pasting the text onto the search box, that way if for example the command is not fast enough or it's too slow we can customize that value and adjust it until it works, a positive value will delay the action and a negative value speed it up.

**Comment by Kyusung4698** [comment]
Once the search field is selected sending `CTRL + C` will copy the content of this field. This is my race condition. Adding delay would not improve this.

**Comment by ZeroCool940711** [comment]
I understand, Im going to make some research and see if I can find something that could help with that and leave it here if I find something, I wonder how POE Trade Macro does this, it works there correctly, maybe they have some workaround or maybe its because of autohotkey.

**Comment by ZeroCool940711** [comment]
@Kyusung4698 I think I know how we can make this work but requires some work, what I propose to do is block the Ctrl+F keys while POE is focused so the game doesn't receive the key combination until we send it to the game from POE Overlay, this way when we press Ctrl+F POE Overlay will intercept that input, then it will copy the item and then after that it will send teh Ctrl+F command to select the search box and then paste there the text, it should work but you should take care of making sure the game is the focused window so it doesn't interrupt anything else like your browser or something else, I found how to do this on python but since POE Overlay is using typescript I have to do some more research and see if I can find something you could use. Give me a few more minutes and I will have some more info for you.

**Comment by ZeroCool940711** [comment]
Couldnt find anything useful for typescript, maybe someone else have more luck than me, at least you have the idea on my previous comment, that could solve a lot of problems if it could be done but I have no idea how to do it since i dont know typescript, another solution would be to implement the keyboard intercept and release on python as a single script and turn that into an exe or something you could call from typescript.

**Comment by Kyusung4698** [comment]
## 0.6.13 (2020-03-25)

- add `CmdOrCtrl + F` as supported accelerator (#293, #454)
