### ISSUE TITLE
Suggestion: Range value on top mods

### ISSUE THREAD

**Issue by cantriz** [Kyusung4698/PoE-Overlay#294]
How searching top mods with range value like this? thx 
![557](https://user-images.githubusercontent.com/62120913/76572913-72c76e80-64cc-11ea-95ff-7ea97d999374.PNG)

**Comment by Kyusung4698** [comment]
Hello, thanks for creating an issue. This is currently not possible. Mod ranges were added after this section was developed. I'll add it soon.

**Comment by Kyusung4698** [comment]
## 0.6.6 (2020-03-17)

- add dps mod range (#294)
