### ISSUE TITLE
breaks on tabbing

### ISSUE THREAD

**Issue by gradeso** [Kyusung4698/PoE-Overlay#295]
If I alt-tab to me second monitor then regain focus with the game on my first monitor the overlay that was previously working stops working entirely

**Comment by gradeso** [comment]
A janky solution I've figured out is that as long as a minimize whatever I tabbed into before returning to POE then it will either work or I can get around the "out of focus" error message by typing (ctrl + c -> ctrl +d)

**Comment by Suddow** [comment]
Also having the issue that it disappears as soon as the window loses focus.

**Comment by Tadiian** [comment]
Similar problem here. If i Alt+Tab out of PoE and switch back to PoE with just simply moving my mouse into the PoE windows Overlay doesn't work anymore correctly. Still can open Settings menu with the hotkey. Closing the menu seems to reset Overlay back to working again.

Another wierd thing: If I switch back to PoE with Alt+Tab it works too. maybe there is something wrong with the active window detection?

**Comment by ArkanePanda** [comment]
Same problem here but neither tadiian nor gradeso's solution works for me

**Comment by Kyusung4698** [comment]
Hello, thanks for creating an issue. I think @Tadiian  is onto something. The active window detection runs on clicks/ keyboard input. Try sending some keys prior using the overlay. Also please enable the Version Display and make sure the version is displayed if not - then this is your problem. The active detection has not been run.

**Comment by ArkanePanda** [comment]
I've tried all of the solutions you've mentioned and I play PoE in windowed mode and I can see the UI pop up underneath so I'm unable to interact with it 
![Annotation 2020-03-15 132531](https://user-images.githubusercontent.com/60131175/76695969-8b987580-66c0-11ea-980e-e0bec0a6257a.png)

**Comment by Kyusung4698** [comment]
## 0.6.3 (2020-03-15)

- fix breaking on tab by settings window on top after tabbing back (#295)

**Comment by Kyusung4698** [comment]
I'll close this issue. Feel free to re-open if needed.
