### ISSUE TITLE
Ability to choose install path

### ISSUE THREAD

**Issue by Charmeleomander** [Kyusung4698/PoE-Overlay#296]
Can we get an option to choose the install path? I would prefer to not have this on my C drive.

**Comment by Kyusung4698** [comment]
Will be added with the new version. You may need to uninstall first.

**Comment by Kyusung4698** [comment]
## 0.6.1 (2020-03-13)

- add allow user to change install path (#296, #300)

`poe-overlay-Setup-0.6.1.exe` to install locally. This supports auto update/ auto launch.
`poe-overlay-0.6.1.exe` portable version. This does not support auto update/ auto launch.
