### ISSUE TITLE
How copy item for PoB? Like ctrc+c in poetrade.

### ISSUE THREAD

**Issue by followmesenpai** [Kyusung4698/PoE-Overlay#299]
Hello, ty for good program, but how copy item for PoB? Like ctrc+c in poetrade. ty

**Comment by chet-manley** [comment]
Ctrl-C on items is a standard part of PoE.

**Comment by Kyusung4698** [comment]
`CTRL + C` is a standard feature of PoE. Should work out of the box! 👍

**Comment by remd** [comment]
Is there an issue already for provided the information dialog that PoE-TradeMacro shows when you `CTRL + C` an item?

I am using PoE-Overlay for the first time this league and during leveling I often double-check the max socket count on an item before rolling it with Jeweler's Orbs. With PoE-TradeMacro that max socket count is shown as part of the information displayed when you `CTRL + C` an item. There are other nice things in that information display as well, like the DPS of the item and DPS at 20% quality.
