### ISSUE TITLE
Choose Installation Path or provide a ZIP

### ISSUE THREAD

**Issue by Medivha** [Kyusung4698/PoE-Overlay#300]
I really really dont like that i cant choose now where it installs with the new release

**Comment by chet-manley** [comment]
I like the idea of a zip to make it portable. The fewer things I have to install in Windows, the better.

**Comment by Kyusung4698** [comment]
Thanks for creating an issue. Seems similar to #300. The ability to choose the installation path will be added in the next version. I can also provide a portable version if needed. Although some features like auto update/ auto launch are probably not compatible with this mode.

**Comment by Kyusung4698** [comment]
## 0.6.1 (2020-03-13)

- add allow user to change install path (#296, #300)

`poe-overlay-Setup-0.6.1.exe` to install locally. This supports auto update/ auto launch.
`poe-overlay-0.6.1.exe` portable version. This does not support auto update/ auto launch.
