### ISSUE TITLE
This app can't run on your PC

### ISSUE THREAD

**Issue by FrankieMania** [Kyusung4698/PoE-Overlay#301]
I am getting this message with the latest release .exe (0.6.0). I can unpack run the previous .zip without any issues.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I need some additional information in order to help you.

* A screenshot of the error message.
* Basic information about your system (OS, x32/x64)

Thank you!

**Comment by FrankieMania** [comment]
I am running Windows 64 bit
![](https://i.imgur.com/JfnVVzJ.png)

**Comment by tuanster1119** [comment]
Seeing this on my system too. Also running Windows 10 x64.

**Comment by Superstrainz** [comment]
I also have this issue, I was able to download the 6.0 version and run it, but both 6.1 & 6.2 give me this error - Windows 10 64 bit

**Comment by Carrybag1** [comment]
My error was slightly different, it was say it was blocked/unrecognized.

I'm however no longer getting this.

**Comment by FrankieMania** [comment]
@Carrybag1 This is something different. You should be fine as your computer just needs your permission.

**Comment by Kyusung4698** [comment]
> Getting something similar on W10 with 0.6.0 and up. Not sure if you care, but it shows your name

That's fine. The app is officially signed using my name. Once the certificate get's more trust the SmartScreen warning should go away.

Please try following steps:

1. unblock app
![can run](https://user-images.githubusercontent.com/38520678/76689342-3d8a6000-6635-11ea-9219-30bf040e8319.png)
2. try again
3. copy setup.exe
4. try copied setup.exe
5. [disable smartscreen](https://www.maketecheasier.com/disable-smartscreen-filter-windows10/)
6. try again

**Comment by dobrelaurentiu** [comment]
> 
> 
> > Getting something similar on W10 with 0.6.0 and up. Not sure if you care, but it shows your name
> 
> That's fine. The app is officially signed using my name. Once the certificate get's more trust the SmartScreen warning should go away.
> 
> Please try following steps:
> 
>     1. unblock app
>        ![can run](https://user-images.githubusercontent.com/38520678/76689342-3d8a6000-6635-11ea-9219-30bf040e8319.png)
> 
>     2. try again
> 
>     3. copy setup.exe
> 
>     4. try copied setup.exe
> 
>     5. [disable smartscreen](https://www.maketecheasier.com/disable-smartscreen-filter-windows10/)
> 
>     6. try again

I encountered the same issue. 
Tried your suggestions but I don't have the "Unblock" available and disabling smartscreen did not solve the issue. 
Also, version 0.6.1 is working.

**Comment by Superstrainz** [comment]
I have tried disabling smart screen and that didn't work, also there is no security line in the general properties of the program, or any other tab; so I haven't been able to find the spot to uncheck the "block option"

**Comment by Kyusung4698** [comment]
Alright. This is kinda hard to fix without been able to reproduce. Could you check the Windows Event Log? Maybe there is a hint. 
As a last resort you could use the portable version for now.

**Comment by Superstrainz** [comment]
I can confirm the portable version works for me. Looking in event viewing I can tell you it was a security issue, what other information do you need?

**Comment by Kyusung4698** [comment]
> I can confirm the portable version works for me. Looking in event viewer I can tell you it was a security issue, what other information do you need?

Good to know. The actual event details would be nice. Thanks for your investigation.

**Comment by Superstrainz** [comment]
This is what is in the details:

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-a5ba-3e3b0328c30d}" /> 
  <EventID>4672</EventID> 
  <Version>0</Version> 
  <Level>0</Level> 
  <Task>12548</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8020000000000000</Keywords> 
  <TimeCreated SystemTime="2020-03-15T20:33:58.983848400Z" /> 
  <EventRecordID>41512</EventRecordID> 
  <Correlation ActivityID="{9a4590cb-f93d-0002-8491-459a3df9d501}" /> 
  <Execution ProcessID="828" ThreadID="5208" /> 
  <Channel>Security</Channel> 
  <Computer>LAPTOP-N0QNG6T4</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="SubjectUserSid">S-1-5-18</Data> 
  <Data Name="SubjectUserName">SYSTEM</Data> 
  <Data Name="SubjectDomainName">NT AUTHORITY</Data> 
  <Data Name="SubjectLogonId">0x3e7</Data> 
  <Data Name="PrivilegeList">SeAssignPrimaryTokenPrivilege SeTcbPrivilege SeSecurityPrivilege SeTakeOwnershipPrivilege SeLoadDriverPrivilege SeBackupPrivilege SeRestorePrivilege SeDebugPrivilege SeAuditPrivilege SeSystemEnvironmentPrivilege SeImpersonatePrivilege SeDelegateSessionUserImpersonatePrivilege</Data> 
  </EventData>
  </Event>

**Comment by Superstrainz** [comment]
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-a5ba-3e3b0328c30d}" /> 
  <EventID>4672</EventID> 
  <Version>0</Version> 
  <Level>0</Level> 
  <Task>12548</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8020000000000000</Keywords> 
  <TimeCreated SystemTime="2020-03-15T20:33:58.983848400Z" /> 
  <EventRecordID>41512</EventRecordID> 
  <Correlation ActivityID="{9a4590cb-f93d-0002-8491-459a3df9d501}" /> 
  <Execution ProcessID="828" ThreadID="5208" /> 
  <Channel>Security</Channel> 
  <Computer>LAPTOP-N0QNG6T4</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="SubjectUserSid">S-1-5-18</Data> 
  <Data Name="SubjectUserName">SYSTEM</Data> 
  <Data Name="SubjectDomainName">NT AUTHORITY</Data> 
  <Data Name="SubjectLogonId">0x3e7</Data> 
  <Data Name="PrivilegeList">SeAssignPrimaryTokenPrivilege SeTcbPrivilege SeSecurityPrivilege SeTakeOwnershipPrivilege SeLoadDriverPrivilege SeBackupPrivilege SeRestorePrivilege SeDebugPrivilege SeAuditPrivilege SeSystemEnvironmentPrivilege SeImpersonatePrivilege SeDelegateSessionUserImpersonatePrivilege</Data> 
  </EventData>
  </Event>

**Comment by Superstrainz** [comment]
- Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- System>
  Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-a5ba-3e3b0328c30d}" /> 
  EventID>4672</EventID> 
  Version>0</Version> 
  Level>0</Level> 
  Task>12548</Task> 
  Opcode>0</Opcode> 
  Keywords>0x8020000000000000</Keywords> 
  TimeCreated SystemTime="2020-03-15T20:33:58.983848400Z" /> 
  EventRecordID>41512</EventRecordID> 
  Correlation ActivityID="{9a4590cb-f93d-0002-8491-459a3df9d501}" /> 
  Execution ProcessID="828" ThreadID="5208" /> 
  Channel>Security</Channel> 
  Computer>LAPTOP-N0QNG6T4</Computer> 
  Security /> 
  /System>
- EventData>
  Data Name="SubjectUserSid">S-1-5-18</Data> 
  Data Name="SubjectUserName">SYSTEM</Data> 
  Data Name="SubjectDomainName">NT AUTHORITY</Data> 
  Data Name="SubjectLogonId">0x3e7</Data> 
  Data Name="PrivilegeList">SeAssignPrimaryTokenPrivilege SeTcbPrivilege SeSecurityPrivilege SeTakeOwnershipPrivilege SeLoadDriverPrivilege SeBackupPrivilege SeRestorePrivilege SeDebugPrivilege SeAuditPrivilege SeSystemEnvironmentPrivilege SeImpersonatePrivilege SeDelegateSessionUserImpersonatePrivilege</Data> 
  /EventData>
  /Event>

**Comment by dobrelaurentiu** [comment]
I tried version 0.6.4 and everything seems to be working fine. Don't know why it didn't like that previous version.
