### ISSUE TITLE
NSIS Error

### ISSUE THREAD

**Issue by Rhyyn** [Kyusung4698/PoE-Overlay#302]
Hi, i get this error while trying the 0.6.0 version 
![poe-overlay-Setup-0 6 0_2020-03-13_16-13-54](https://user-images.githubusercontent.com/32547725/76634829-c2e31700-6546-11ea-9af3-c99fe740b76a.png)

**Comment by Kyusung4698** [comment]
Hi, is this also an issue with the laters versions?

**Comment by Rhyyn** [comment]
Fixed in 0.6.2
