### ISSUE TITLE
No poe-overlay-setup-0.6.1.exe

### ISSUE THREAD

**Issue by RFTPS3** [Kyusung4698/PoE-Overlay#304]
Installed the vc_redist
Downloaded the Overlay 0.6.1 .zip
Extracted the .zip
There are no .exe files in the folder

**Comment by Kyusung4698** [comment]
Thanks for creating an issue. I think you may have downloaded the source code zip. Please download this file [`poe-overlay-Setup-0.6.1.exe`](https://github.com/Kyusung4698/PoE-Overlay/releases/download/v0.6.1/poe-overlay-Setup-0.6.1.exe) instead.

**Comment by RFTPS3** [comment]
oh that was it. thanks!
