### ISSUE TITLE
How to display currency as listed by the seller?

### ISSUE THREAD

**Issue by Booblord** [Kyusung4698/PoE-Overlay#308]
when price check, is it possible to show price as listed by the seller. Not chaos/ex equivalent etc.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Unfortunately this is currently not possible. Where would you like to see the original price? At the List view should be no problem.

**Comment by varazir** [comment]
I'm looking for something like that. I have selected few different curences and the price type shown in the overlay isn't the same as on the trade site.

**Comment by Booblord** [comment]
> Hi, thanks for creating an issue. Unfortunately this is currently not possible. Where would you like to see the original price? At the List view should be no problem.

Ya it would be great to be able to see the original price at the list view. Its how the original trade macro worked

**Comment by Kyusung4698** [comment]
## 0.6.8 (2020-03-19)

- add evaluate original currency (#308)

![image](https://user-images.githubusercontent.com/38520678/77106388-49a06400-6a1f-11ea-9167-0f65dc3441b5.png)

**Comment by WhiteFang5** [comment]
@Kyusung4698 It seems that the addition of this feature broke the "Displayed Currency", I can no longer open the drop down and evaluation fails.
