### ISSUE TITLE
Evaluate - Harbinger piece Category missmatch

### ISSUE THREAD

**Issue by fatings** [Kyusung4698/PoE-Overlay#309]
Example:
![image](https://user-images.githubusercontent.com/39002567/76687499-7a962880-661c-11ea-800e-777a8151fc06.png)

![image](https://user-images.githubusercontent.com/39002567/76687504-88e44480-661c-11ea-8bc2-e0d0a055fc30.png)

Changing to any in the search shows results.

**Comment by Kyusung4698** [comment]
@fatings glad you're still around. I'll look into it. Thanks for reporting!

**Comment by Kyusung4698** [comment]
## 0.6.4 (2020-03-15)

- fix unique framgents category mismatched as unique map fragmente (#309)
