### ISSUE TITLE
ctrl+mousewheel stash tab changes

### ISSUE THREAD

**Issue by Dariisa** [Kyusung4698/PoE-Overlay#31]
An implementation like trade macro where ctrl and scrolling the mouse wheel changes stash tabs regardless of where the mouse is on the screen would be very useful

**Comment by Kyusung4698** [comment]
0.4.2 now supports this! Thanks for sharing.

**Comment by emrearapoglu** [comment]
Scrolling through stash tabs using this method jumps 2 tabs with a single scroll. So it skips 1 tab.

**Comment by Kyusung4698** [comment]
GGG added scrolling through stash tabs while hovering over the stash. This should only be used if you like to scroll while being outside of the stash tab.

**Comment by scrangos** [comment]
> 
> 
> GGG added scrolling through stash tabs while hovering over the stash. This should only be used if you like to scroll while being outside of the stash tab.

POE-trade figured a way around this, as they have the same feature of using ctrl+wheel anywhere, but it doesnt double scroll while hovering on the stash.

**Comment by vhbert** [comment]
I guess you could check the coordinates of the cursor, set an area of the width of the stash UI, and disable the command if the cursor is in that area?
