### ISSUE TITLE
Scrolling in stash

### ISSUE THREAD

**Issue by seal2105** [Kyusung4698/PoE-Overlay#310]
hello, i have tried this overlay for a couple of hours. first i had some problems with it skipping tabs when scrolling, when i had the mouse outside the stash window. 
turns out the Lutbot i had running also, had the same option, making it skip tabs. 

now i have turned it off, and it dont skip tabs, but now it zooms while scrolling too. it that supposed to happen? i dont have anything other that Poe overlay running :)

thanks in advance.

seal

**Comment by seal2105** [comment]
seems like its only happening when the mouse is in the middle and not in either inventory or stash window :)

**Comment by Kyusung4698** [comment]
Duplicate #288
