### ISSUE TITLE
Add support for /whois

### ISSUE THREAD

**Issue by ZeroCool940711** [Kyusung4698/PoE-Overlay#311]
As the title says it would be nice to have support for the `/whois CharacterName` command, I can't find a way to do it as a simple command from the `Command` tab as I don't know how to get the name of the last character I whispered with a single command, POE Overlay probably have access to the POE log file or can use the chat to combine multiple commands to get the name of the whoever we whispered before and then write the `/whois` command to get information for that character. 

Note: Keep in mind that for it to work we first have to whisper someone, if using the log file we could also be able to get the command working for people whispering us as the chat is saved to the log file. If implementing this using the log file would be nice to have a toggle option to chose if we want to get information for the people whispering us as probably not everyone wants to have that by default.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. The tool is currently not reading from the log file. As soon a this is implement I'll add an placeholder to the commands like: `@lastwhisper`.

**Comment by Kyusung4698** [comment]
I'll close this issue for following #126
