### ISSUE TITLE
Support for cluster jewel mods needed

### ISSUE THREAD

**Issue by Xebtria** [Kyusung4698/PoE-Overlay#313]
all mods are available on trade, see: 
https://i.imgur.com/Ku68d9t.png

But overlay doesn't support them yet, so price check of jewels is impossible.

**Comment by Kyusung4698** [comment]
Thanks for creating an issue. I think they were not available as I soon as the game was updated. So this is the reason they are missing. I'll add them soon.

**Comment by Kyusung4698** [comment]
## 0.6.3 (2020-03-15)

- add 3.10 stats (#311)

**Comment by Xebtria** [comment]
Hi, thanks for the so far implementation, but still not all stats are supported:
https://i.imgur.com/YeZZaJg.jpg

- the "enchant" is missing
- the "# small passives is a jewel socket" is missing

**Comment by Kyusung4698** [comment]
Holy Moly they finally added the echant flag as text. This needs some refactoring.

**Comment by Kyusung4698** [comment]
![image](https://user-images.githubusercontent.com/38520678/76703854-14211100-66d5-11ea-9411-3fa1e2e52eac.png)

Gosh. They fucked it up badly. No wonder my export did not work. They've mixed stats with client strings. Nonetheless we now got languages mixed with english stats.

**Comment by Kyusung4698** [comment]
## 0.6.4 (2020-03-15)

- add support for canonical stats variation (#313)
- add support for `Added Small Passive Skills grant` stat (#313)
