### ISSUE TITLE
Kakao version - not detecting game window

### ISSUE THREAD

**Issue by haralla** [Kyusung4698/PoE-Overlay#314]
I launch the kakao version of the game through https://poe.game.daum.net as it seems the only way I can connect to the korean servers. However, overlay is unresponsive as it seems it doesn't detect the game is open. I have the normal poe version also installed and it works fine with that.

**Comment by Kyusung4698** [comment]
Hello, thanks for creating an issue. The game detection is based on the game executable name. Could you check it for me please? Thanks I'll add it.

**Comment by haralla** [comment]
Here are all the applications in the folder: 

- PathOfExile_x64_KG
- PathOfExile_x64
- PathOfExile_KG
- PathOfExile
- Client
- POE_Launcher
- PathOfExile_Setup

**Comment by Kyusung4698** [comment]
Hi, all of these should be working. Are running the overlay as administrator? This tool requires the same privileges as the game itself.

**Comment by PROdotes** [comment]
I'm having the same issue but i'm running it through steam, E:\SteamLibrary\steamapps\common\Path of Exile\PathOfExile_x64Steam.
Works fine when I'm running it at work but at home it doesn't recognize when the game is running.
