### ISSUE TITLE
Centering dialog option is scaling with zoom

### ISSUE THREAD

**Issue by AgathiaKimiya** [Kyusung4698/PoE-Overlay#315]
The center dialog option won't work properly if zoom is set to something different than 100%. If set to 150%, it will go towards the lower right, and lower than 100% will go towards higher left.

Also, I feel the center setting should be by default, cursor is basically impractical all the time for me.

**Comment by Kyusung4698** [comment]
## 0.6.3 (2020-03-15)

- fix dialog spawns not centered if zoomed (#315)
