### ISSUE TITLE
Evalulate enchants 

### ISSUE THREAD

**Issue by varazir** [Kyusung4698/PoE-Overlay#320]
Hello, if Trade macro you can select the values you like to evaluate. 

I tried to evaluate some boots that had a LAB enchant but  I didn't get the enchantmanet evaluted.

**Comment by Kyusung4698** [comment]
## 0.6.4 (2020-03-15)

- fix enchant stats not working (#320)

**Comment by livejamie** [comment]
I think this is still occurring in 0.6.4

![image](https://user-images.githubusercontent.com/49513/76761536-d19b1b00-674c-11ea-9ecd-e6d0365efff4.png)

**Comment by Kyusung4698** [comment]
## 0.6.5 (2020-03-16)

- fix singular/ plural stats (#320)
