### ISSUE TITLE
A JavaScript Error ocurred in the main process

### ISSUE THREAD

**Issue by kernelENREK** [Kyusung4698/PoE-Overlay#321]
Screen Shot:

![PoeOverlayError](https://user-images.githubusercontent.com/4211853/76704310-60218500-66d8-11ea-8845-8cc056aefc9c.png)

Fails on 0.5.22 and also all 0.6.x versions.

Possible **Hint**: A couple of days ago, Windows 10 updated from version 1903 : 18362.70 to 1909 : 18363.720 version. Last version i ran correctly was 0.5.22 on Win10 1903

Edit: Error translation: "**Error: Cannot find the specified module**"

**Comment by Kyusung4698** [comment]
Thanks for creating an issue. Please install [vc_redist](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) to fix this issue. Those support libraries are required to run the program.

**Comment by kernelENREK** [comment]
I just say my friend install the **vc_redist.x64.exe** from the link you provided and now 0.6.3 runs fine.

He are saying me give you a lot of +1  :)

This can be closed

**Comment by Kyusung4698** [comment]
Awesome! 🚀
