### ISSUE TITLE
Needs to handle missing VC++ redist (iohook error)

### ISSUE THREAD

**Issue by 3789037** [Kyusung4698/PoE-Overlay#325]
Hello, 
As noted in [#298](https://github.com/Kyusung4698/PoE-Overlay/issues/298)
I installed the 0.6.4 version of the overlay and got this :
[error](https://cdn.discordapp.com/attachments/264966727652081665/688845674527326256/unknown.png)
As noted in that issue, it is resolved by installing the VC++ overlay.
Is it possible to handle this error at load time and display a useful error message to the user? Or prompt them to install the VC++ runtime if it does not exist when installing the application? (I am primarily a linux developer so I don't know if that's really possible on windows).

Thanks,
Numbers

**Comment by Kyusung4698** [comment]
## 0.6.5 (2020-03-16)

- add iohook vc redist error handling (#325)
