### ISSUE TITLE
PoE-Overlay + AHK

### ISSUE THREAD

**Issue by nikidino8** [Kyusung4698/PoE-Overlay#328]
I'm using a batch file to start my needed programs for playing POE and if there is an AHK File starting before PoE-Overlay it will use the console to check for updates:

![image](https://user-images.githubusercontent.com/13020561/76712174-68001a00-6716-11ea-872a-69f7677451f5.png)

If I close the console PoE-Overlay will close too.

**Comment by JusKillmeQik** [comment]
Is your batch file launching PoE-Overlay? If so, then it's probably just the parent process in Windows and so it closes all children processes when you kill the console. There isn't much that PoE-Overlay could change to fix that.

**Comment by Kyusung4698** [comment]
> Is your batch file launching PoE-Overlay? If so, then it's probably just the parent process in Windows and so it closes all children processes when you kill the console. There isn't much that PoE-Overlay could change to fix that.

This. I think you can start any tool without waiting. So it does not intercept with the cmd it was started from - but i'm no ahk expert and therefore i can't help you.

**Comment by nikidino8** [comment]
So I will try to explain it with an example batch files:
```
start <Path>"poe-overlay.exe"
start <Path>"POE Trades Companion.ahk"
```
Both will start but the console will remain open with the messages which programs to start and the content in the picture above.
If I close the console POE Overlay will close too.

```
start <Path>"POE Trades Companion.ahk"
start <Path>"poe-overlay.exe"
```
The console will close normally.

```
start <Path>"poe-overlay.exe"
start <Path>"Path of Building.exe"
```
The console will close normally.

```
start <Path>"Path of Building.exe"
start <Path>"poe-overlay.exe"
```
The console will close normally.
