### ISSUE TITLE
Aero enabled, white background blocking everything, trails when moving graph (video included)

### ISSUE THREAD

**Issue by Starknesses** [Kyusung4698/PoE-Overlay#329]
The YouTube video should sum everything up about this bug.

https://youtu.be/Jo1_T0nV4FQ

**Comment by Kyusung4698** [comment]
Hi, thank you for creating an issue. This seems indeed like a hardware acceleration issue. I'm currently working on a solution to disable this without the missing `run-without-gpu.bat` - also a quick heads up win7 is not fully compatible with this tool.

**Comment by Kyusung4698** [comment]
## 0.6.5 (2020-03-16)

- add hardware acceleration toggle as tray option (#329, #327)
- add aero is enabled check
