### ISSUE TITLE
Ctrl+D should work with the item's links

### ISSUE THREAD

**Issue by JettPanopio** [Kyusung4698/PoE-Overlay#33]
User should be able to ctrl+d an item and it would return the price with the links preselected.
For example if I have a 6 link item, when I ctrl+d it, instead of showing the price of it unlinked, it should show the price of it as 6 links.

Please delete this if you're already had plans for this, or if it is already implemented.
Thank you for your hard work!

**Comment by Kyusung4698** [comment]
I'll add a basic default query per item type. In 0.5.1 there'll be a customisable version. See #13
