### ISSUE TITLE
Close all open windows on focus

### ISSUE THREAD

**Issue by JusKillmeQik** [Kyusung4698/PoE-Overlay#330]
When I open a bunch of windows to check map mods, I have to click in the game to close every one of them. You had an issue earlier to close all on pressing ESC, but that does not work for me. I think having a configurable hotkey to close all open overlays would be helpful. Thank you.

**Comment by Kyusung4698** [comment]
Hello, thanks for creating an issue. `SPACE` closes all open windows except for the active browser. `ESC` closes the latest one.

**Comment by Kyusung4698** [comment]
## 0.6.5 (2020-03-16)

- update readme (esc/ space) (#330)
