### ISSUE TITLE
Suggestion: Show actual stat value

### ISSUE THREAD

**Issue by luka189** [Kyusung4698/PoE-Overlay#335]
Hello,

There have been a few things i have been missing:

On the evaluate screen i think it would be useful if you could see the numeric value of the stat you currently have on the item, instead of only the upper and lower bounds of the searched value. Maybe in brackets at the end of the like or something.

Second, the evaluate screen does not take missing quality into account and just gives you the dps of your weapon as it currently is, it would be useful if for weapon and armour that are not 20% and that arent corrupted there would be the 20% quality values displayed, again perhaps in brackets next to the non quality value. This is very detrimental when searching by dps.

Third, related to the second, you cannot set a range when searching by dps and atack speed and crit chance on weapons, (or ES / Armour on armour) which is again something i would like to see, currently if you select to filter by dps it sets it exactly your dps on higher.

Thank you for developing this tool other than the listed "issues" it works very well.

**Comment by Kyusung4698** [comment]
Hi, thank you for your feedback. 

> On the evaluate screen i think it would be useful if you could see the numeric value of the stat you currently have on the item, instead of only the upper and lower bounds of the searched value. Maybe in brackets at the end of the like or something.

This has already been requested. Just don't now yet how to properly implement it.

> Second, the evaluate screen does not take missing quality into account and just gives you the dps of your weapon as it currently is, it would be useful if for weapon and armour that are not 20% and that arent corrupted there would be the 20% quality values displayed, again perhaps in brackets next to the non quality value. This is very detrimental when searching by dps.

Will be adressed by this issue #136

> Third, related to the second, you cannot set a range when searching by dps and atack speed and crit chance on weapons, (or ES / Armour on armour) which is again something i would like to see, currently if you select to filter by dps it sets it exactly your dps on higher.

## 0.6.6 (2020-03-17)

- add dps mod range (#294)
- add weapon, shield and armour props as mod range (#335)

**Comment by Kyusung4698** [comment]
## 0.6.13 (2020-03-25)

- add display default values while holding right click (#335)
