### ISSUE TITLE
Installation Aborted

### ISSUE THREAD

**Issue by Smooshface** [Kyusung4698/PoE-Overlay#336]
Everytime POE Overlay updates or I try to install it, I get "Installation Aborted, Setup was not completed successfully. 

This is almost instant after I choose an installation location. This happens if I go to the default location, or if I attempt to install it in a new directory.

**Comment by Marucci** [comment]
This happened to me when I installed it and moved the installation folder to another location. I fixed it uninstalling the application and reinstalling it again. Have you tried that already?

**Comment by Smooshface** [comment]
So, I fixed it, and what I had to do was literally go into my registry and delete an entry for 6.1 that somehow didn't get removed properly.

Hopefully this doesn't happen with future versions (I've had this problem a while and had just started using the stand-alone client because of it)

Thanks for the tip, uninstalling pointed me to the registry since 6.1 showed up in add/remove programs, but couldn't be removed since it was already gone.

**Comment by Kyusung4698** [comment]
Hi, glad you got it working. The auto update feature was broken prior 0.6.2 so maybe this caused the corrupted registry. Please let me know if this happens again. Thanks! I'll close this issue for now.
