### ISSUE TITLE
map info doesn't work

### ISSUE THREAD

**Issue by eunsoori** [Kyusung4698/PoE-Overlay#338]
map info doesn't work. other features work well.
there's always a "항목을 파싱하지 못했습니다. 올바른 언어를 선택했는지 확인하십시오. (Item could not be parsed. Please make sure you have the correct language selected)" message.

kakao client / client language Korean / poe-overlay language Korean

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Does the evaluate command work on those item? Could you please provide the copied item info (CTRL + C). Thanks! I'll look into it.

**Comment by eunsoori** [comment]
evaluate also doesn't work and same message.

아이템 희귀도: 희귀
음산한 연결부
박물관 지도(Museum Map)
--------
지도 등급: 3
아틀라스 지역: 티른의 끝자락
아이템 수량: +49% (augmented)
아이템 희귀도: +30% (augmented)
몬스터 무리 규모: +19% (augmented)
--------
아이템 레벨: 72
--------
몬스터의 생명력 20% 증폭
명중 시 몬스터가 권능 충전 획득
몬스터의 카오스 저항 +15%
몬스터의 원소 저항 +20%
플레이어가 근접 사격 보유
--------
전용 지도 장치에서 해당 아이템을 사용해 지도 안으로 이동할 수 있습니다. 한 번만 사용할 수 있습니다.

**Comment by Kyusung4698** [comment]
## 0.6.6 (2020-03-17)

- fix regex not working with unicode (#338, #340)

**Comment by Kyusung4698** [comment]
I'll close this issue for now. Feel free to re-open if needed.
