### ISSUE TITLE
Searching flasks on russian client does not trigger a pop up

### ISSUE THREAD

**Issue by Lokeras** [Kyusung4698/PoE-Overlay#340]
as mentioned in the title, while trying to search flasks in russian language you get a language error, searching other items works, have not noticed any other bugs.

**Comment by Kyusung4698** [comment]
Hi, thank you for creating an issue. Could you please provide the copied item data (CTRL + C) of those items? I'll look into it. Thanks!

**Comment by Lokeras** [comment]
Редкость: Волшебный
Непрерывный Ртутный флакон согревания
--------
Длится 4.00 сек.
Расходует 20 из 50 зарядов при использовании
Содержит зарядов: 0
40% повышение скорости передвижения
--------
Требования:
Уровень: 3
--------
Уровень предмета: 15
--------
29% повышение скорости восстановления зарядов
Иммунитет к заморозке и охлаждению во время действия эффекта флакона
При использовании снимает заморозку и охлаждение
--------
Щелкните ПКМ, чтобы выпить. Содержит заряды только когда висит на поясе. Пополняется по мере убийства монстров.

the error basically says that ’’ item cannot be analyzed, make sure you selected the correct language, ‘’
so it might be something related to translating flask names maybe?

**Comment by Kyusung4698** [comment]
## 0.6.6 (2020-03-17)

- fix regex not working with unicode (#338, #340)

**Comment by Kyusung4698** [comment]
I'll close this issue for now. Feel free to re-open if needed.
