### ISSUE TITLE
Feature: Ability to search the list of affixes and mod warnings

### ISSUE THREAD

**Issue by JusKillmeQik** [Kyusung4698/PoE-Overlay#342]
Having to scroll through all of the affixes to select the ones I want to be default takes a really long time. If I know I want to highlight "curse with assassins mark on hit", let me search for that and select it. Same could be done for map mods input.

Thanks

**Comment by Kyusung4698** [comment]
Hello, thanks for creating an issue. Those list are already searchable. There is a gif at the wiki:
https://github.com/Kyusung4698/PoE-Overlay/wiki/Map#stat-warnings

**Comment by JusKillmeQik** [comment]
Thank you! I missed it, but that makes it so much easier!
