### ISSUE TITLE
Ability to open poe trade with selected options

### ISSUE THREAD

**Issue by evilstiefel** [Kyusung4698/PoE-Overlay#344]
I'm really enjoying the tool, the only option missing is opening the browser to POE trade or the official trade site after getting price predictions. Would you be interested in implementing that?

**Comment by evilstiefel** [comment]
Nevermind, I was just not aware clicking the currency icon was doing exactly that. Found an older issue explaining that.

**Comment by Kyusung4698** [comment]
Glad to found it by yourself. There is also a wiki entry about this:

https://github.com/Kyusung4698/PoE-Overlay/wiki/Evaluate#figures
