### ISSUE TITLE
Windows Defender SmartScreen blocks setup.exe

### ISSUE THREAD

**Issue by NoFailer** [Kyusung4698/PoE-Overlay#345]
![defender](https://user-images.githubusercontent.com/53854947/76887512-afa3b480-6882-11ea-8ea1-590c19b22cba.PNG)
First time seeing this on my computer. I know your software is not anything malicious. Just wanted to open an issue because I have not found another one similar to this or anything related to it in your readme file. So yeah just in case other people run into this, they will see I already reported it!

Keep up the good work!

NoFailer

Version used: 0.6.5
File used: poe-overlay-Setup-0.6.5.exe

**Comment by Kyusung4698** [comment]
This is okay. My executables are signed using a Code Signing Certificate. Currently my certificate is not trusted by SmartScreen. Therefore you'll get the following pop-up.

> ![image](https://user-images.githubusercontent.com/15611586/76681990-0ba2da80-65f0-11ea-8b65-ad3cabbadd75.png)

Once my certificate is trusted by SmartScreen (this takes a while...) the warning will go away. To skip it -> click on "More Info":

> ![image](https://user-images.githubusercontent.com/15611586/76681984-ffb71880-65ef-11ea-803d-8f92d08e34f6.png)

Run anyway. But make sure the Publisher is "Nicklas Ronge". This ensures i've signed this executables and no one could altered it.

**Comment by NoFailer** [comment]
Thank you very much for the quick answer!
