### ISSUE TITLE
pricing

### ISSUE THREAD

**Issue by kobalt7926** [Kyusung4698/PoE-Overlay#346]
the overlay seems to not want to price things properly for me . some crap items are telling me its work a lot and some good items are worth nothing. i never changed anything in the evaluation settings, what should i do?

**Comment by Kyusung4698** [comment]
The top data column is based on the values of poe.ninja. If you think there is a mismatch of item please let me know. 

The bottom data column is based on the values of the actual trade website with all your filters selected.
