### ISSUE TITLE
We need DPS check and poe.trade

### ISSUE THREAD

**Issue by leet0rz** [Kyusung4698/PoE-Overlay#347]
We need to be able to see dps for physical damage and elemental damage for attack weapons. Also  it would be great to be able to open the searches in poe.trade as the main trade site recently limited the live searches to 20 from 80. A lot of players did not like that change and are going back to poe.trade. Hope to see these features implemented, thanks!

**Comment by Kyusung4698** [comment]
DPS check is provided. Please see following wiki entry:
https://github.com/Kyusung4698/PoE-Overlay/wiki/Evaluate#properties

poe.trade won't be supported in the near future.
