### ISSUE TITLE
Rare Item search is item base specific

### ISSUE THREAD

**Issue by Tanmiezel** [Kyusung4698/PoE-Overlay#352]
The searches for rare items aren't accurate in pricing for the mods. The problems stem from the cause that when you do search an item for pricing it includes the base type in the search criteria which restricts a wider search result.

Example:
I have a ring I want to price check (stats):
Paul Ring Base
+66 to Maximum Life
+56 to Total Resistance
+4-9 added fire damage
+20 to Maximum Mana

Now if I tried to search rings for 66 max life and 56 total resistance, the app will try to either search for those stats for all the items, in any slot, with those stats or higher or search for Paul Ring base in specific with those stats or higher. This makes that the result will not include other base types in rings and thus the predicted pricing would be inaccurate.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. The item type (Paul Ring, Unset Ring, etc...) can be disabled but it will still search with the base item type (ring, gloves, etc..)

![item_type_active](https://user-images.githubusercontent.com/38520678/76935519-8a9a5a80-68f1-11ea-9e6b-9761cfa19d78.png)
_Item type active._

![item_type](https://user-images.githubusercontent.com/38520678/76935562-97b74980-68f1-11ea-89df-6877cab31bd1.png)
_Item type not active by clicking on the item type._

![settings_item_type](https://user-images.githubusercontent.com/38520678/76935586-a43ba200-68f1-11ea-9800-90e1d1c83dd9.png)
_item type settings to disable auto select._

**Comment by Kyusung4698** [comment]
I'll close this issue for now. Feel free to re-open if needed.
