### ISSUE TITLE
Add an option to disable auto searching socket colors

### ISSUE THREAD

**Issue by harboja1** [Kyusung4698/PoE-Overlay#353]
Most of the time it doesn't matter what color your sockets are only how many links there are. Please and a setting to turn off auto socket searching items. 

Ps thanks for making such a cool tool :)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. The colors of sockets are ignored. Only the selected count will be searched. Currently the sockets and links are connect with following setting:

![settings_item_link](https://user-images.githubusercontent.com/38520678/76935652-c46b6100-68f1-11ea-936a-57d865ef85d7.png)

**Comment by harboja1** [comment]
Sorry I had an issue that I thought had been created by that. Thanks for make such a cool tool :)

**Comment by Kyusung4698** [comment]
> Sorry I had an issue that I thought had been created by that. Thanks for make such a cool tool :)

No problem. Glad you like my tool! :rocket:
