### ISSUE TITLE
Can the size of the setting page change?

### ISSUE THREAD

**Issue by TLR-Dreamer** [Kyusung4698/PoE-Overlay#354]
![f8857fad-bcad-45b3-bd54-d17ae45f3bb2](https://user-images.githubusercontent.com/62328378/76940996-2fd72200-6936-11ea-9fa0-a191c19c2dea.jpg)
As My monitor bought like 10 years ago,My screen ratio is 4:3.Therefore,when i open the setting pages, the interface is too large to my screen,so is there any way to zoom the interface to fit to my screen?
Btw, Thx for making this useful tool for us.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. There is a zoom settings:

![settings_zoom](https://user-images.githubusercontent.com/38520678/76942485-1c0fc980-68fe-11ea-920a-147e26e627b1.png)

Unfortunately the settings width can't be adjusted and is not responsive yet.
