### ISSUE TITLE
Bookmarks Open in Microsoft Edge not Default Browser (firefox)

### ISSUE THREAD

**Issue by fierycabbage** [Kyusung4698/PoE-Overlay#355]
I'm not sure if there's a way to change it in the app itself, but I couldn't find it. 

I checked my own settings and firefox is default. All the shortcuts in overlay open in Edge.

I didn't see another way to ask questions besides here.+

It only seems to happen with bookmarks. The issues option opens in firefox like it should

**Comment by Kyusung4698** [comment]
Prior 0.6.8 bookmarks could only be opened in the internal browser. With the new update there is a flag called "external" checking these will open the bookmark in the default browser. Hope this helps.
