### ISSUE TITLE
A JavaScript Error ocurred in the main process

### ISSUE THREAD

**Issue by jasonqiu19841216** [Kyusung4698/PoE-Overlay#356]
![error](https://user-images.githubusercontent.com/62335734/76956291-b39d0880-694e-11ea-829d-268e21a47f2c.JPG)

When I run this app, Show this error message
Can tell me how to solve this error ,tks

**Comment by Kyusung4698** [comment]
Hi, thank you for creating an issue, I think you need to enable Aero. This windows feature is required in order to create transparent windows.

**Comment by jasonqiu19841216** [comment]
thanks so much, I can run this app
