### ISSUE TITLE
can't search resistance option in korean client

### ISSUE THREAD

**Issue by macolite** [Kyusung4698/PoE-Overlay#359]
![bug](https://user-images.githubusercontent.com/48879273/76987159-0fcf4f00-6986-11ea-86c9-0923c53fd758.png)
In the picture, that option is fire resistance

In korean client, cant search only the resistance options 
psudo searching is work. only blue letters are not work

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Could you please provide the copied item data (CTRL + C). Thanks! I'll look into it.

**Comment by macolite** [comment]
아이템 희귀도: 희귀
혼란스러운 차양
태양의 관
--------
퀄리티: +8% (augmented)
에너지 보호막: 168 (augmented)
--------
요구사항:
레벨: 62
민첩: 60
지능: 122
--------
홈: B-B-B-B 
--------
아이템 레벨: 71
--------
역학 폭발 효과 범위 16% 증가 (enchant)
--------
에너지 보호막 75% 증가
생명력 최대치 +62
화염 저항 +18%
냉기 저항 +31%
기절 및 막기 회복 16% 증가
에너지 보호막 최대치 +35 (crafted)

not the same item in the picture. but all of item have same problem.

**Comment by Kyusung4698** [comment]
Hi, thanks for the item data. i've found the error:

```
base_fire_damage_resistance_%
%1$+d%% to Fire Resistance
화염 저항 %1$+d%%

fire_damage_resistance_is_%
Fire Resistance is %1%%%
화염 저항 %1%%%
```

There are two stats with the same translation (in korean). This requires quite some effort to get resolved. I'll provide a quick workaround in the next version

**Comment by Kyusung4698** [comment]
## 0.6.8 (2020-03-19)

- fix temporary damage_resistance mismatched with damage_resistance_is (#359)

**Comment by macolite** [comment]
Now it works! 
Always feel thanks for using this. thank you!
