### ISSUE TITLE
Add an option to check all attributes by default

### ISSUE THREAD

**Issue by Rottenbeer** [Kyusung4698/PoE-Overlay#360]
I would like to have the option to check all explicits on an item by default, so I can just Ctrl + D an unique item and see it's price range for it's rolls.
Thanks!

**Comment by Kyusung4698** [comment]
## 0.6.7 (2020-03-18)

- add unique select all (#360)

![settings_stats_unique_check_all](https://user-images.githubusercontent.com/38520678/77000942-6d00db80-6959-11ea-9dd0-e6f2b86572e3.png)

**Comment by Rottenbeer** [comment]
Nice thanks!
