### ISSUE TITLE
"1" in the numpad opens poe.lab and there is no way to remove it

### ISSUE THREAD

**Issue by Messinae** [Kyusung4698/PoE-Overlay#362]
I love using numpad to numerise my sellings and other stuff but everytime I press one it doesn't even write anything and instantly opens poe.lab, which I don't care about at all. I've looked in the program and haven't found a single way to remove the bind. (I'm pretty sure there are other binds hidden but I don't know yet I installed the program recently) so I'm asking if it could be possible to have a way to remove it or show me the way where I can do so. Otherwise I'll have to get rid of this very good program and I'd be very sad. Thanks !

**Comment by Kyusung4698** [comment]
Hi, numpad1 and numpad2 is bound at the bookmarks menu. I'll change the default hotkeys in the next version. See #312
