### ISSUE TITLE
Trade-Website: Currently under Maintenance - Overlay will be working soon again!

### ISSUE THREAD

**Issue by maximeDeBr** [Kyusung4698/PoE-Overlay#365]
When choosing list as default over Graph view whenever you try to evaluate an item it returns an "error occurred" label. Not sure if there is an error log available in the application. Returning the default result back to Graph solves the problem.

**Comment by Kyusung4698** [comment]
Hi, the trade site is currently under maintenance. Should be resolved as soon as the page is up again. Please see following screenshot:

![image](https://user-images.githubusercontent.com/38520678/77002774-5ad46c80-695c-11ea-8ecd-9cd8d4a4aada.png)

**Comment by kr0t3** [comment]
can you change  from "an error ocurred" to "trade site is under maitenance" ?

**Comment by Kyusung4698** [comment]
Maintenance is done. You may need to relaunch the tool. Thanks for your patience.

> can you change from "an error ocurred" to "trade site is under maitenance" ?

I can't really differentiate those errors. Could also be a local network issue.

**Comment by kr0t3** [comment]
I relaunched the tool and it still give me error w an error occurred while parsing the item.
