### ISSUE TITLE
An Error Occurred While Parsing the Item

### ISSUE THREAD

**Issue by ChrispyChris** [Kyusung4698/PoE-Overlay#366]
When I hit ctrl+d over an item, this pops up and that's basically all that happens for me. The program was working last night, but not this morning randomly.

**Comment by Symerizer** [comment]
I have the same issue, go have a look at the settings (F7), is the league selection box empty just like mine? And once I click on it, there is nothing appearing.

![image](https://user-images.githubusercontent.com/4822937/77003677-2c429b80-6934-11ea-8df5-636cc3af1cd5.png)

**Comment by Kyusung4698** [comment]
Hi, there is currently a maintenance. Should be working soon again. https://github.com/Kyusung4698/PoE-Overlay/issues/365
