### ISSUE TITLE
Error with language message when evaluating prophecies

### ISSUE THREAD

**Issue by bMiquelin** [Kyusung4698/PoE-Overlay#37]
**Description:**
Overlay does not support any prophecy, and a wrong error message appears (Assuming the error is always because of wrong language).
Items like "Offering to the goddess" also does not work, but do not have this kind of error message

**Pre-conditions:**

- Game on "English"
- Plugin settings on "English"
- Have a prophecy orb in your inventory

**Repro steps:**
1. Mouseover the prophecy
2. Press CTRL+D
3. Error appears: "Copied item could not be parsed. Make sure you have the correct language selected"

**Item data:**
```
Rarity: Normal
Fire from the Sky
--------
Fire rains down across the land. Beware the path you take.
--------
You will discover an area with an Infernal Tempest
--------
Right-click to add this prophecy to your character.

```

**Comment by Kyusung4698** [comment]
Thank you for reporting. Prophecies were missing in my base-item export. Will be fixed with 0.4.2.
