### ISSUE TITLE
Need "open in poe.trade or pathofexile.com/trade" function

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [Kyusung4698/PoE-Overlay#370]
Hello,

while the quick search is very nice, as much faster than trademacro, it is seriously mandatory to be able to open the current search in poe.trade or pathofexile.com/trade to be able to add/remove mods or alter values to do more searches. This is highly important to be able to examine a real value, sadly currently it's only for really quick-checks but for everything else trademacro is sadly better in quality of life.

**Comment by sisco1986** [comment]
+1

**Comment by Kyusung4698** [comment]
Hello, this is already possible. Please check following wiki entry:

> Clicking the currency icon will open the search in an in-game browser. Holding Ctrl while clicking opens the default browser instead.

https://github.com/Kyusung4698/PoE-Overlay/wiki/Evaluate#figures

**Comment by sisco1986** [comment]
we mean without opening the main overlay window and not in a internal browser but in the default browser defined by windows

**Comment by Kyusung4698** [comment]
Like #284?

**Comment by AkumaNoTsubasa** [comment]
Now that is what I call hidden. Thanks!

Would be nice to have a kind of switch to be able to chose (maybe by holding shift?) to rather use poe.trade for the search.
