### ISSUE TITLE
Application doesn't auto restart after update.

### ISSUE THREAD

**Issue by bgriffs** [Kyusung4698/PoE-Overlay#371]
After installing update and clicking re-launch app the app updates and then closes instead of restarting automatically.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Can you please provide some information about:

## 🌍  Your Environment

- OS:  e.g. Win7 x64
- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by bgriffs** [comment]
OS: Win10 x64
Version: 0.6.4-9
PoE: Standalone 3.10.0E English.

**Comment by Kyusung4698** [comment]
This seems related to #411. I'll close this issue.
