### ISSUE TITLE
Evaluate - Map tier mismatch between poe.ninja info and search results

### ISSUE THREAD

**Issue by fatings** [Kyusung4698/PoE-Overlay#372]
Example below:
In the evaluate window the poe.ninja match is done to the T14 while the search results are matched for T2 (working as expected).

![image](https://user-images.githubusercontent.com/39002567/77018619-0b029f00-6976-11ea-80b4-4f9633020d95.png)

![image](https://user-images.githubusercontent.com/39002567/77018744-7e0c1580-6976-11ea-9a46-f2db46f7dc06.png)

**Comment by Kyusung4698** [comment]
## 0.6.8 (2020-03-19)

- fix missing map tier filter (#372)
