### ISSUE TITLE
Stat Range

### ISSUE THREAD

**Issue by crash0verwr1te** [Kyusung4698/PoE-Overlay#375]
Hi, 

gut wäre es wenn noch die echte Stats Range des Items zu sehen. Da sich sonst diverse Fenster überlappen wenn ich mit der Maus auf das Item gehe mit alt. 

Also entweder im Trade selber oder vlt ein kleines item Info Fenster wo nochmal die Stats zu sehen sind.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This is relate to #35. I'll close this issue for now. Also please use English as your issue language. This helps other users to find relevant issue.
