### ISSUE TITLE
Overlay unusable with Hardware Acceleration enabled

### ISSUE THREAD

**Issue by TripleOmega** [Kyusung4698/PoE-Overlay#378]
OS: Windows 10 x64
CPU: AMD Ryzen 5 2600 @ 3,4Ghz
GPU: Radeon RX 580 8GB
RAM: 16GB
Resolution Screen 1: 2560x1440 (PoE runs on this)
Resolution Screen 2: 1920x1080

After I first installed PoE Overlay everything was working fine until I tried Ctrl+d. The overlay popped up extremely slowly and was unresponsive. The focus would often stay on the game allowing me to move while the overlay was up. Occasionally I managed to get a response from the overlay after many seconds of waiting.

Disabling Hardware Acceleration fixed all the issues.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Please see following explanation:

> Hardware acceleration may causes issues because the chrome version may not be compatible with the used hardware/ drivers. As there are finite possibilities of hardware/ drivers etc. the easiest way to solve this is by disabling the hardware acceleration. Another user with this problem disabled for example NVIDIA G-Sync to resolve his issues.

Glad you got it working. I'll close this issue for now. Feel free to reopen if needed.
