### ISSUE TITLE
Veiled suffixes are being ignored

### ISSUE THREAD

**Issue by bMiquelin** [Kyusung4698/PoE-Overlay#38]
**Description:**
The "Veiled Suffix" mod is being ignored.
Mod does not appear on the UI after CTRL+D
Mod does not is used when evaluating item price

**Item sample:**
```
Rarity: Rare
Rapture Scarab
Agate Amulet
--------
Requirements:
Level: 48
--------
Item Level: 80
--------
+19 to Strength and Intelligence (implicit)
--------
+21 to all Attributes
Adds 1 to 2 Cold Damage to Attacks
+37% to Lightning Resistance
Veiled Suffix
--------
Note: ~b/o 2 chaos

```

**Comment by Kyusung4698** [comment]
Hi,
i need help on this one. Based on my research the item data only holds `Veiled Prefix` or `Veiled Suffix` but the stat filter on the trade data has a lot more values:
- of the Veil
- Veiled
- of Aisling's Veil
- Leo's Veiled
- of Cameria's Veil
- Korell's Veiled
- of Janus' Veil
- of Jorgin's Veil
- Elreon's Veiled
- of Hillock's Veil
- Catarina's Veiled
- Haku's Veiled
- Guff's Veiled
- of Riker's Veil
- It That Fled's Veiled
- Vagan's Veiled
- Gravicius' Veiled
- Rin's Veiled
- Vorici's Veiled
- Tora's Veiled

Is this based on the item type/id/category? Otherwise i think there is an `Veiled` filter in the `Miscellaneous`. Would this be enough? Or do you need it based on the stat? Thank you!

**Comment by bMiquelin** [comment]
> ased on my research the item data only holds Veiled Prefix or Veiled Suffix

False. Items usually have veiled prefix or veiled suffix, but there are some rare ones, like `Catarina's Veiled`.

Item type/category does not change which type of veil it can hold. (By type/category I mean helmet/ring/etc).

I do need some search on my samples to find out why the ingame mod name is "Veiled Suffix" but the stat filter has only "Veiled"

Im during work. In ~7h I can update this thread with some samples.

**Comment by bMiquelin** [comment]
I guess it may not be possible to do this type of search with the CTRL+C info.
Trade-macro does not support this because poe.trade does not have a veiled filter (Just a yes/no).
Official trade website does have the veiled mods, but they arent specific on CTRL+C info.

`Veiled Suffix` may mean `of the Veil`
`Veiled Prefix` may mean `Veiled`
`Veiled Prefix` could also mean `Tora's Veiled`


Here are some samples:
![image](https://user-images.githubusercontent.com/8808338/72372808-d6f4ce80-36e5-11ea-9832-1f8456e1eabc.png)

```
Rarity: Rare
Maelström Slicer
Legion Sword
--------
One Handed Sword
Physical Damage: 60-116 (augmented)
Critical Strike Chance: 5.00%
Attacks per Second: 1.20
Weapon Range: 11
--------
Requirements:
Level: 62
Str: 122
Dex: 104
--------
Sockets: R 
--------
Item Level: 69
--------
40% increased Global Accuracy Rating (implicit)
--------
Adds 7 to 18 Physical Damage
+26% to Fire Resistance
+344 to Accuracy Rating
Veiled Prefix
--------
Note: ~b/o 2 chaos
```

----------------

![image](https://user-images.githubusercontent.com/8808338/72372861-f4c23380-36e5-11ea-85bf-092b7982ea04.png)
```
Rarity: Rare
Blood Bane
Headman's Sword
--------
Two Handed Sword
Physical Damage: 47-109
Elemental Damage: 77-142 (augmented)
Critical Strike Chance: 5.00%
Attacks per Second: 1.30
Weapon Range: 13
--------
Requirements:
Level: 57
Str: 106
Dex: 89
--------
Sockets: R-R-R-G 
--------
Item Level: 81
--------
+400 to Accuracy Rating (implicit)
--------
Adds 77 to 142 Fire Damage
+36% to Fire Resistance
+4 Life gained for each Enemy hit by Attacks
Veiled Prefix
--------
Note: ~b/o 3 chaos
```


--------------------------------

![image](https://user-images.githubusercontent.com/8808338/72372921-14f1f280-36e6-11ea-9744-a522f30d580d.png)
```
Rarity: Rare
Damnation Thirst
Harpy Rapier
--------
One Handed Sword
Physical Damage: 31-72
Elemental Damage: 39-71 (augmented), 44-78 (augmented), 2-25 (augmented)
Critical Strike Chance: 5.70%
Attacks per Second: 1.40
Weapon Range: 14
--------
Requirements:
Level: 70
Dex: 212
--------
Sockets: B 
--------
Item Level: 84
--------
+35% to Global Critical Strike Multiplier (implicit)
--------
Adds 39 to 71 Fire Damage
Adds 44 to 78 Cold Damage
Adds 2 to 25 Lightning Damage
Veiled Suffix
--------
Note: ~b/o 2 chaos

```

**Comment by Kyusung4698** [comment]
Thank you for your report. I've decided to add atleast the basic `Veiled` filter in [0.5.0](https://github.com/Kyusung4698/PoE-Overlay/releases/tag/0.5.0).
![veiled](https://user-images.githubusercontent.com/38520678/72470784-b5790d00-37e1-11ea-8d31-68c8dfac02e2.gif)
