### ISSUE TITLE
Redeemer Trapper Mits error

### ISSUE THREAD

**Issue by TheOne320** [Kyusung4698/PoE-Overlay#383]
I am getting an error price checking these gloves. Are there log files saved somewhere?

![image](https://user-images.githubusercontent.com/7705568/77090833-04246c80-6a08-11ea-85fc-fec2b7d85fd1.png)

**Comment by Kyusung4698** [comment]
Hi, can you post the copied item data? (CTRL + C) They maybe changed something at the trade api. I'll look into it.

**Comment by TheOne320** [comment]
Rarity: Rare
Oblivion Claw
Trapper Mitts
--------
Evasion Rating: 65
Energy Shield: 13
--------
Requirements:
Level: 58
Dex: 29
Int: 29
--------
Sockets: B-G 
--------
Item Level: 73
--------
+21 to Dexterity
Adds 1 to 5 Lightning Damage to Attacks
+86 to maximum Life
Adds 1 to 57 Lightning Damage if you've dealt a Critical Strike Recently
--------
Redeemer Item

**Comment by Kyusung4698** [comment]
Hm, just checked another redeemer item myself - works fine. I guess there was a short downtime of the trade api. Is this still not working?

**Comment by TheOne320** [comment]
Weird now it works. I checked that the api works by testing other items. What would cause it to sometimes error?

**Comment by Kyusung4698** [comment]
I guess they are currently working at the trade api. There was downtime yesterday as well.
