### ISSUE TITLE
Windows Defender Detected a "Trojan"

### ISSUE THREAD

**Issue by xinnir** [Kyusung4698/PoE-Overlay#387]
Most likely a false positive as it deals with the updater, although I thought I'd bring it to attention.
![tMeGm8u (1)](https://user-images.githubusercontent.com/4484977/77106660-b1818b00-69dc-11ea-9c0c-306d62acc479.png)

**Comment by stevietv** [comment]
having the same issue here, as are a number of people, see #388 and #389

**Comment by Goldensteev** [comment]
![poeoverlay-threat](https://user-images.githubusercontent.com/14848329/77107035-5a050e80-6a20-11ea-8eba-a0a8e4688c21.png)

same for me

**Comment by conspi** [comment]
same for me, last automatic download of the setup.exe

![poe overlay setup](https://user-images.githubusercontent.com/11374209/77107447-ffb87d80-6a20-11ea-9b29-09e30f65cd6e.png)

win7 up2date - win defender

**Comment by Kyusung4698** [comment]
Hi, i can assure that this is a false cause. There is currently a issue with the used application packager. I'm sorry for the inconvenience. 
https://github.com/electron-userland/electron-builder/issues/4793

**Comment by stevietv** [comment]
thanks @Kyusung4698

**Comment by Kyusung4698** [comment]
I'll mark the new release as pre-release. Currently trying to downgrade the electron packager.

**Comment by xinnir** [comment]
Thanks for the response.

**Comment by Kyusung4698** [comment]
Update: Microsoft has removed/ approved the false Detection. Please see following Submission:
https://www.microsoft.com/en-us/wdsi/submission/69113a4a-0fc7-423d-80ad-f6ed0cf128ad

They'll roll out a new definition file of the Windows Defender soon which will prevent this false flaggen.

**Comment by Goldensteev** [comment]
Great thanks!
