### ISSUE TITLE
Windows 10 recognizes new update as trojan

### ISSUE THREAD

**Issue by niklaas-0rbit** [Kyusung4698/PoE-Overlay#389]
Just got that message from my Windows 10 when PoE-Overlay wanted to download the latest setup file:

Threat detected: Trojan:Win32/Bulta!rfn
Alert level: Severe
file: C:\Users\...\AppData\Local\poe-overlay-updater\pending\temp-poe-overlay-Setup-0.6.8.exe

**Comment by stevietv** [comment]
Duplicate of #387
