### ISSUE TITLE
Still can't check some wather's eye/fragments/scarabs/timeless emblem/offering/vessel

### ISSUE THREAD

**Issue by Evilinex** [Kyusung4698/PoE-Overlay#39]
```
Rarity: Unique
Watcher's Eye
Prismatic Jewel
--------
Limited to: 1
--------
Item Level: 85
--------
4% increased maximum Energy Shield
6% increased maximum Life
5% increased maximum Mana
Unaffected by Burning Ground while affected by Purity of Fire
Unaffected by Temporal Chains while affected by Haste
--------
One by one, they stood their ground against a creature 
they had no hope of understanding, let alone defeating,
and one by one, they became a part of it.
--------
Place into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.
```
![PathOfExile_x64_2020-01-10_09-32-33](https://user-images.githubusercontent.com/19516390/72134252-38d2d280-338c-11ea-8e46-deecf965a872.jpg)

**Comment by Evilinex** [comment]
Rarity: Normal
Fragment of the Chimera
--------
Enter the crucible. The nexus of
nothingness and equilibrium of eternity.
--------
Can be used in a personal Map Device.
![poe-overlay_2020-01-10_09-56-27](https://user-images.githubusercontent.com/19516390/72135575-800e9280-338f-11ea-98cd-b2957104632f.png)

**Comment by Evilinex** [comment]
Rarity: Normal
Gilded Bestiary Scarab
--------
Area contains Einhar
Area contains 3 additional Red Beasts
--------
The Order was your clan in life, Agnar, Beastmaster, but the First Ones call
back their favoured son. The gift of their Visions will pass to another.
--------
Can be used in a personal Map Device to add modifiers to a Map.
![poe-overlay_2020-01-10_10-04-54](https://user-images.githubusercontent.com/19516390/72136099-b1d42900-3390-11ea-9d57-26948a870260.png)

**Comment by 766b** [comment]
For scarabs, item rarity should be set to `Any`

**Comment by ChrisFiftyTwo** [comment]
> For scarabs, item rarity should be set to `Any`

This is true for pretty much all items in the fragment tab. If set to `Any` instead of `Normal` they all seem to work and give results.

**Comment by Kyusung4698** [comment]
Thank you for reporting. Will be fixed with 0.4.2.

**Comment by Kyusung4698** [comment]
0.4.2 is now released and it should be fixed. Let me know if works!

**Comment by Evilinex** [comment]
watcher's eye/fragments/scarabs/timeless emblem/offering/vessel work great thx!
