### ISSUE TITLE
0.6.8 Unable to select any league

### ISSUE THREAD

**Issue by TgDn32** [Kyusung4698/PoE-Overlay#392]
After this update, all league choices have disappeared.
![image](https://user-images.githubusercontent.com/61363706/77108724-1d71ec80-69f9-11ea-9535-a645d4339ffe.png)

**Comment by Kyusung4698** [comment]
Hi, GGG is now using cloudflare to protect their api. i'm working on a solution.

![image](https://user-images.githubusercontent.com/38520678/77109385-17ddcc00-6a24-11ea-8081-67e24d2eef4b.png)

**Comment by FeralRage7** [comment]
Interesting that this juts got applied to the API. They've been using CloudFlare for a bit. You the 5 second DDoS checker when you log into your account.

Thanks for jumping on this. PoE is almost unplayable without your pricing tool!

**Comment by WhiteFang5** [comment]
> Hi, GGG is now using cloudflare to protect their api. i'm working on a solution.
> 
> ![image](https://user-images.githubusercontent.com/38520678/77109385-17ddcc00-6a24-11ea-8081-67e24d2eef4b.png)

The solution seems simple, and is given on the first line of the screenshot: Enable cookies.
In order to pass a cloudflare challenge you need both cookies and javascript enabled, see cloudflare docs here: https://support.cloudflare.com/hc/en-us/articles/200170136

**Comment by WhiteFang5** [comment]
@Kyusung4698 if it's of any help, look into the Electron Browser Window's session attribute.
> session Session (optional) - Sets the session used by the page. Instead of passing the Session object directly, you can also choose to use the partition option instead, which accepts a partition string. When both session and partition are provided, session will be preferred. Default is the default session.
  
https://github.com/electron/electron/blob/master/docs/api/session.md#class-session

**Comment by FKPX3118** [comment]
Hi, I just changed the language into Chinese and changed it back to English then it has the proper league selected. I don't know why but it works for me now.

**Comment by vadash** [comment]
fuck flippers, thanks for fast update. I am all in for hardening GGG API

**Comment by Kyusung4698** [comment]
> fuck flippers, thanks for fast update. I am all in for hardening GGG API

You're welcome. Glad it's working now.

**Comment by MusicalPulse** [comment]
I'm having this issue after the 0.6.16 update.
