### ISSUE TITLE
League Dropdown is empty or null

### ISSUE THREAD

**Issue by eriksch2709** [Kyusung4698/PoE-Overlay#395]
![image](https://user-images.githubusercontent.com/20409256/77109322-17304000-69fa-11ea-9879-04ba44f4687e.png)

League drop down has no options and is unable to be clicked to expand it. I think this is causing down stream effects as evaluations are erroring out intermittently and no evaluation is able to contact the trade api and return a result.

windows 10 64bit

**Comment by Kyusung4698** [comment]
Duplicate of #392
