### ISSUE TITLE
0.6.8 Infinite loading or Error  while parsing item

### ISSUE THREAD

**Issue by Chocapic** [Kyusung4698/PoE-Overlay#396]
I had the same issue on 0.6.7: updated to 0.6.8 and still unable to use it. I either get a bottom red text "Error while parsing" or the popup opens but fetch forever and doesnt return any info. Any idea ?

**Comment by ChyrkunArtsiom** [comment]
Same for me

**Comment by crudd03** [comment]
I'm getting the same errors-- either "error while parsing" or infinite loading.

**Comment by Assmodey32** [comment]
Me too

**Comment by eriksch2709** [comment]
This is likely related to #392 and it's just showing the issue with contacting GGGs api's in various ways

**Comment by florougier** [comment]
Same but I am still on 0.6.7 despite the fact that I saw the new version popup and try to relaunch, I cant update to 0.6.8

**Comment by acidreian666** [comment]
Same issue here was working fine for few hours then Kyusung pushed the 0.6.8 update and it started having this error.

**Comment by Ninjaskill** [comment]
same, i'm getting this error too

**Comment by Achtas** [comment]
I've noticed a slight oddity, when I relaunched it on 0.6.7. it did the update but when hovering over the icon, it still shows 0.6.7 so either a typo or possibly the update failed. Yet, when launching the downloaded setup exe for 0.6.8, it does not start to reinstall, instead it launches 0.6.7. Closing it and launching the installed version still launches 0.6.7. Plenty of weirdness.

**Comment by gtstrullo99** [comment]
> Same but I am still on 0.6.7 despite the fact that I saw the new version popup and try to relaunch, I cant update to 0.6.8

Exact same problem

**Comment by florougier** [comment]
I just got the prompt to update to the latest 0.6.9, no problem instaling it, and no more errors while parsing! thx for the update

**Comment by Kyusung4698** [comment]
Should be fixed with #392
