### ISSUE TITLE
0.6.7 causing extreme input lag in all applications while PoE overlay is open

### ISSUE THREAD

**Issue by dcollinsn** [Kyusung4698/PoE-Overlay#397]
Hello,

Since restarting after the auto update to 0.6.7, I have been experiencing extreme input lag intermittently while the overlay app is running. It looks like the mouse and keyboard input is only being processed every 500ms or so. When you move the mouse, the actual cursor will move in small "steps" every 500ms, and will continue moving even after the mouse is stopped, as though there is extreme input buffering. Similarly, the keyboard input is delayed. This occurs regardless of whether any PoE overlay screens are actually visible, and regardless of whether the game is focused or not. Closing PoE Overlay, or downgrading to 0.6.6, resolves this issue.

**Comment by Kyusung4698** [comment]
Please try 0.6.9 after a fresh pc restart. There was an issue with 0.6.8 which required me to remove it as installable version. I assume the update process got kinda stuck.

**Comment by dcollinsn** [comment]
0.6.9 does seem to have sorted the problem. Thanks!
