### ISSUE TITLE
Use the offical PoE Trade site instead of poe.trade

### ISSUE THREAD

**Issue by xenadmin** [Kyusung4698/PoE-Overlay#4]
poe.trade is and was awesome, but the official site has been getting much better and more responsive aka faster. If you develop such a sophisticated tool, you should consider using the offical site as a backend. 

https://www.pathofexile.com/trade/

**Comment by zaafar** [comment]
I created a c# lib few years ago for official pathofexile trading website. Feel free to look at it to get the information of available official API.

https://github.com/zaafar/PoeTradeSharp

**Comment by Kyusung4698** [comment]
Duplicate of #3
