### ISSUE TITLE
Auto-update without going to download page

### ISSUE THREAD

**Issue by pj4533** [Kyusung4698/PoE-Overlay#40]
Would be awesome if the version detection would download the latest version and update it in-place, rather than having to go to the download page.  (And adding the version checking/updating to the settings page)

**Comment by Kyusung4698** [comment]
Thanks for your suggestion. I added it to the 1.0.0 milestone.

**Comment by MisterDDT** [comment]
This is major important, I know a few people stopped using this because of it. You do a great job updating, which causes a lot of manual download/installs.

**Comment by Kyusung4698** [comment]
Will be added soon. I've applied to an certificate agency. Currently working myself through their validation process. You can check my https://www.patreon.com/kyusung4698 for updates. The current goal is to reach 25€ to insure that the certificate running cost are covered.

**Comment by Kyusung4698** [comment]
## 0.6.0 (2020-03-12)

- add auto update (#40)
