### ISSUE TITLE
Bug: Flask evasion option searching isn't work

### ISSUE THREAD

**Issue by macolite** [Kyusung4698/PoE-Overlay#402]
![buggg](https://user-images.githubusercontent.com/48879273/77131858-9d06c680-6aa0-11ea-97ca-3e1a553b4ac6.png)

```
아이템 희귀도: 고유
씬의 부활(Sin's Rebirth)
휘안석 플라스크
--------
5.00초 지속
사용 시 30 중 10 소모
현재 용량: 0
회피 100% 증가
--------
요구사항:
레벨: 14
--------
아이템 레벨: 83
--------
사용 시 연막 생성 (implicit)
--------
플라스크 효과를 받는 동안 불경한 힘 획득
플라스크 효과를 받는 동안 점화에 면역
사용 시 화상 제거
--------
그리고 그는 잿더미에서 피는 먹구름처럼 부활했다.
한 사람의 죄악이 많은 이의 죄악이 되었다.
--------
마시려면 우클릭하십시오. 허리띠에 장착 중일 때만 충전이 유지됩니다. 몬스터를 처치하면 충전량이 차오릅니다.
```

If the option is not checked, searching is works (it is not max option. that option is locked option)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I'll look into it. I think this was broken by fixing following: #368
