### ISSUE TITLE
Suggestion: Add Support Tray Menu Icon Scaling

### ISSUE THREAD

**Issue by Galimka** [Kyusung4698/PoE-Overlay#403]
Hi,
My computer is with a 32" screen and 3840x2160 resolution. I have poor eyesight and so my windows 10 settings are on 200% interface scale.

Ingame the overlay works and looks great. 

Only problem : the menu when you rightclick the taskbar icon, it is veryyyyyyyyyyyy small on my configuration. (like 2x3cm)
Any way to have it scaling with windows setting or to make it bigger ? 

Just a very little issue, i won't be using that menu very often ! 

But anyway, thanks for the great work, that tool of yours is excellent !

**Comment by Kyusung4698** [comment]
> Hi,
> My computer is with a 32" screen and 3840x2160 resolution. I have poor eyesight and so my windows 10 settings are on 200% interface scale.
> 
> Ingame the overlay works and looks great.
> 
> Only problem : the menu when you rightclick the taskbar icon, it is veryyyyyyyyyyyy small on my configuration. (like 2x3cm)
> Any way to have it scaling with windows setting or to make it bigger ?
> 
> Just a very little issue, i won't be using that menu very often !
> 
> But anyway, thanks for the great work, that tool of yours is excellent !

Hi, thanks for creating an issue. Glad you like my tool! I'll look into it.

**Comment by Kyusung4698** [comment]
## 0.6.10 (2020-03-22)

- update use ico instead of png as tray icon (#403)

Looking forward to your feedback! 👍

**Comment by Galimka** [comment]
Hello,
Thanks for getting into this, but i thing there is a missunderstanding : i was talking about the menu size and not the icon itself. 
![taskbar menu](https://user-images.githubusercontent.com/62414531/77291174-fe67a900-6cdd-11ea-8330-91d31c366d63.png)
Here it's a screenshot of my desktop, the menu is in bottom right on the taskbar. See the difference of size between the menu and the clock, the shortcut names or the search bar bottom left. I get windows interface scalling 200%, making all stuff literraly twice bigger. The menu from right clicking on the taskbar icone (now a big cool one icone :D ) is not affected by that scaling and so is half sized (or not made twice bigger).
