### ISSUE TITLE
Problems with PoE-Trade-macro.

### ISSUE THREAD

**Issue by Sklifan** [Kyusung4698/PoE-Overlay#404]
Greetings,

the tool looks nice and works fine and fast, but there is currently a behavior that is really annoying.
If I check the price on item, the additional info (from Poe-Trade-macro-tool) is shown 
![2020-03-20 04_34_01-YoloCursorOverlay](https://user-images.githubusercontent.com/34965008/77137920-1fc35d80-6a70-11ea-970a-371411c685cb.png)
The strange part is, even when I change the hotkeys it's still the same result.
This behavior does not occcur when PoE-Overlay isn't running.

Maybe you have an idea how to solve this.

In any case, keep up the good work :)

**Comment by Kyusung4698** [comment]
Hi, trademacro has a keybinding on CTRL + C. This needs to be disabled. My tool sends CTRL + C in order to get the item data of the hovered item and therefore triggering the trademacro keybinding.
