### ISSUE TITLE
Feuture request: price prediction

### ISSUE THREAD

**Issue by Mar-vo** [Kyusung4698/PoE-Overlay#406]
Poe trademacro lets you easily pricecheck rares, without selecting mods or applying ranges. Poe overlay is better when you want to quickly enter ranges or select mods (and better overall) - but the generic "price check" functionality of trademacro is really nice to have when you either:

1. don't know what mods are relevant to select
2. don't know if the item is valuable
3. don't want to spend more then 1 second on an item

I kind of miss the convenience it brought. The price prediction window even tells you what the valuable mods are - and how much they contribute to the predicted price. I think they use poeprices.info for predicting the price, which uses a neural net for the predictions. 

I would love it if this was implemented here!

**Comment by Kyusung4698** [comment]
Duplicate of #178
