### ISSUE TITLE
Windows7 and scroll function

### ISSUE THREAD

**Issue by se7enek** [Kyusung4698/PoE-Overlay#410]
Not sure if this is the cause but as far as i tested, using Windows 7 and scrolling over the mod (to change values) doesnt seem to work. Tested on 3 machines.
 Windows 10 works correctly.

**Comment by se7enek** [comment]
However scrolling using CTRL to move through stashtabs works correctly on both versions

**Comment by Kyusung4698** [comment]
Duplicate of #319
