### ISSUE TITLE
Bug: Relaunch App Button throws Error

### ISSUE THREAD

**Issue by TheOne320** [Kyusung4698/PoE-Overlay#411]
When the app detects an update it displays a message telling me to relaunch the app to update. When I click on the "Relaunch App" button it only closes the App. Sometimes a JavaScript Error pops up, but most often it just closes the App and does not relaunch. When not updating the App the "Relaunch App" button works normally.

![relaunch](https://user-images.githubusercontent.com/7705568/77185636-08b55780-6ad2-11ea-9a71-d88d4ddc9726.png)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Could you please provide additional information about your system? Thanks!

## 🌍  Your Environment

- OS:  e.g. Win7 x64
- Version:  e.g. 0.6.9 portable

Also are you using the tray menu button or the button at the settings menu?

**Comment by TheOne320** [comment]
OS: Windows 10 x64 1909
Version: Installed version. Default location: C:\Program Files\poe-overlay; Version number not relevant as this concerns updating, but it happened since auto updating was introduced. I manually updated to 0.6.9 now.  

I was using the button in the settings menu.

**Comment by Kyusung4698** [comment]
> OS: Windows 10 x64 1909
> Version: Installed version. Default location: C:\Program Files\poe-overlay; Version number not relevant as this concerns updating, but it happened since auto updating was introduced. I manually updated to 0.6.9 now.
> 
> I was using the button in the settings menu.

Thank you. I assume this was caused by those uncaught exceptions. I catch them now. Should be working after the next update.

**Comment by Kyusung4698** [comment]
## 0.6.10 (2020-03-22)

- fix uncaught exceptions thrown after app relaunch (#411)
