### ISSUE TITLE
Offical GGG statement - can I get banned?

### ISSUE THREAD

**Issue by Wasabi375** [Kyusung4698/PoE-Overlay#412]
Is there any statement by GGG that ensures that using this tool won't get me banned? I know that GGG has allowed similar tools to this one, but I'd prefere to see an official statement from GGG about this project before using it. 
Also something like this should probably be linked in the wiki/readme.

**Comment by michaelobr** [comment]
Don't see why this is needed, there are hundreds of other tools out there that people have never been banned over which never had an official GGG endorsement. Furthermore, PoE-Overlay does not give any speed or competitive advantage inherently.

**Comment by magus424** [comment]
This doesn't do anything that violates the terms of service, so there's basically no possibility of being banned for using it.

**Comment by mt89vein** [comment]
> This doesn't do anything that violates the terms of service, so there's basically no possibility of being banned for using it.

What about auto-trade? You can for one click set price to item from lookup price info. Normally it takes 4-5 clicks. Of cource, it's not affecting gameplay and survival, but it's macro, that GGG dont like.

**Comment by magus424** [comment]
What about it? It's only one server action. That is totally fine.
