### ISSUE TITLE
Suggestion: Add missing translations

### ISSUE THREAD

**Issue by Traf27** [Kyusung4698/PoE-Overlay#413]
### 1. Evaluate -> Result Window :

- Graph
- List

![example](https://i.imgur.com/Cto5zxR.png)

### 2. Misc -> Stash navigation : 

- Disabled
- Normal
- Inverse

![example](https://i.imgur.com/XGN1Anm.png)

### 3. Dialog window:

- "amount"  when mouse is over mini graph

![example](https://i.imgur.com/uCbxm8t.png)

- Amount, Seller, Age in dialog values list view

![example](https://i.imgur.com/7cXrkSN.png)

- bars when mouse over
  - _ Hours ago
  - _ Minutes ago
  - few second ago

![example](https://i.imgur.com/pwJaXJL.png)

- when mouse over Orb "Click' = In-Game Browser, 'CTRL + Click' Default Browser"

![example](https://i.imgur.com/cybqnkF.png)

### 4. Corner online indicator
also is it suppose to be changable to other time amount ?

![example](https://i.imgur.com/w4O2F0w.png)

### 5. In panel "Command", separate key for element "command" above shortkey

![example](https://i.imgur.com/PmhsQiH.png)

### 6. Can menu in tray also be translated ?

**Comment by Kyusung4698** [comment]
> ### 1. Evaluate -> Result Window :
> * Graph
> * List

✔️ 

> ### 2. Misc -> Stash navigation :
> * Disabled
> * Normal
> * Inverse

✔️ 

> ### 3. Dialog window:
> * "amount"  when mouse is over mini graph

✔️ 

> * Amount, Seller, Age in dialog values list view

✔️ 

> * bars when mouse over
>   
>   * _ Hours ago
>   * _ Minutes ago
>   * few second ago

✔️ Automatically translated by [momentjs](https://momentjs.com/). 

> * when mouse over Orb "Click' = In-Game Browser, 'CTRL + Click' Default Browser"

✔️

> ### 4. Corner online indicator
> also is it suppose to be changable to other time amount ?

❌ No, not for now. Yes, it's changeable via scrolling.

> ### 5. In panel "Command", separate key for element "command" above shortkey

✔️ 

> ### 6. Can menu in tray also be translated ?

❌ No, not for now. Unfortunately this requires quite some effort.

**Comment by Traf27** [comment]
The ammount of daily effort you put into this project amazes me. Thank you very much!

You mentioned you used BabelEdit for translations, I looked into it because of curiosity. How did you generated JSON files out of it ? I've seen only excel,cvs export format.

**Comment by Kyusung4698** [comment]
The export format can be select during the creation of a project. See attached screenshot. I'm using the ngx-translate variance. 
![image](https://user-images.githubusercontent.com/38520678/77251810-cfefbc80-6c50-11ea-9be8-75c58bb0ae8d.png)
