### ISSUE TITLE
Bug: Multiple "Programs and Features" entries

### ISSUE THREAD

**Issue by MakiabelMFE** [Kyusung4698/PoE-Overlay#414]
The program creates multiple uninstall entries, I had both 0.6.7 and 0.6.9, tried to uninstall 0.6.7 and uninstalled everything.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I think this was related due to the 0.6.8 version was marked as prelease after it got released so the update process was stuck. Please let me know if this happens again at the with the next version.
