### ISSUE TITLE
Suggestion: Add ability to evaluate prophecies from Navali prophecy menu.

### ISSUE THREAD

**Issue by 4444N** [Kyusung4698/PoE-Overlay#416]
I think it would be a good feature addition to add a way to evaluate a prophecy while hovering over it in Navali's prophecy GUI to be able to price check before sealing it.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I dunno if this is even possible. I'll look into it and let you know.

**Comment by Noshei** [comment]
This would only be possible if you read the details from the screen.  ctrl + c doesn't get any information from prophecies in the prophecy window, only when they are items in your inventory.

**Comment by Pegoth** [comment]
I tried to do it with OCR, but it is pretty bad, you would have to train one with the prophecy font for it to work (example: Tesseract can be trained I think, but you would still need to create a prophecy font). This is too much work I think.

Other solution would be  to open a custom search input field and let people type in what they want to search for, much easier to implement.

**Comment by Kyusung4698** [comment]
> I tried to do it with OCR, but it is pretty bad, you would have to train one with the prophecy font for it to work (example: Tesseract can be trained I think, but you would still need to create a prophecy font). This is too much work I think.

Thank you for your input. On top of the OCR thing i'd also need to support Chinese / Korean / Russian / German (üäö) etc. This is really out of scope for this project for now. 

> Other solution would be to open a custom search input field and let people type in what they want to search for, much easier to implement.

This seems like a great solution. Will be added with #374
