### ISSUE TITLE
Suggestion: Creating named seller-lists for different purposes

### ISSUE THREAD

**Issue by Traf27** [Kyusung4698/PoE-Overlay#417]
It would be handy to have blacklist for pricefixers, bots, people that list items without intent to sell them, etc Which could be created by ourself or even community driven.

Whitelist for favourite sellers, favourite crafters etc. 
Just an idea floating in my head, the other day. :)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This seems more like a feature request for GGG 😄

Can you please describe what behaviour do you expect? Whispers can't be filter from the UI afaik.

**Comment by Traf27** [comment]
After a bit of thinking, it would be rather mundane work on user part. So not so needed.
