### ISSUE TITLE
Data for sales MASSIVLY off for me.

### ISSUE THREAD

**Issue by resistance125** [Kyusung4698/PoE-Overlay#418]
I will CTRL D a unique and often says 2-5 chaos with only 1 at 1 chaos,  then if i look the same item up on POE homesite trade, they are like 1 alch...... wtf?

**Comment by vadash** [comment]
Offtop but stop picking up trash man. Dont trade for items below 5c value, use strict loot filter

**Comment by resistance125** [comment]
using Very strict.  its not about what i am picking up, its about having faith in the Data being shown in what i discard is actuall bad, or what i think is good based on the DATA is actually dogshit.

**Comment by RDogPinK** [comment]
Just started, but sounds like i.e. alch are simply not shown. 
You can add them under "Evaluate -> Displayed Currencies" I´d guess.

**Comment by Kyusung4698** [comment]
Duplicate of #346
