### ISSUE TITLE
Spell Crit not recognized

### ISSUE THREAD

**Issue by Isareth** [Kyusung4698/PoE-Overlay#42]
As title says, the price distribution doesn't work at all for me. I have to click on "No matches found" to see the items listed.

Also Spell Crit on Shaper Chest isn't recognized as a mod when the window comes up for the item.

**Comment by Isareth** [comment]
After restarting the overlay the price distribution started working. Spell crit still not being recognized though

**Comment by Kyusung4698** [comment]
Can you please share the item data (CTRL + C while hovering)? Thanks! I'll look into it.

**Comment by Isareth** [comment]
Rarity: Rare
Grim Carapace
Vaal Regalia
--------
Quality: +20% (augmented)
Energy Shield: 196 (augmented)
--------
Requirements:
Level: 70
Str: 68
Dex: 105
Int: 194
--------
Sockets: R-B-B-G-R-B 
--------
Item Level: 84
--------
+113 to maximum Life
+28% to Chaos Resistance
Spells have +1.5% to Critical Strike Chance 
Gain 10% of Maximum Life as Extra Maximum Energy Shield (crafted)
--------
Shaper Item
![spell crit](https://user-images.githubusercontent.com/59747927/72207922-182d7a00-346b-11ea-81f1-798c4d9a572a.png)

**Comment by vtsvashan** [comment]
It's the same with attack crit. It also misses the -15 to mana. I think the error might be that the program has problems handling both the "." and the "-" in searches.

![missing fields](https://user-images.githubusercontent.com/59789259/72216029-b711af00-351b-11ea-9cd8-59b222d7e648.png)

**Comment by Kyusung4698** [comment]
Seem related to: #62 . Can you please check 0.4.4? Thank you!

**Comment by vtsvashan** [comment]
It fixed the crit, but not the mana cost.

![missing fields2](https://user-images.githubusercontent.com/59789259/72218229-f8fd1e00-3538-11ea-9209-93449f0d3f75.png)

**Comment by Xebtria** [comment]
Not fixed for me with 0.4.4
https://i.imgur.com/azknF6l.png
maybe it is a problem also with the localized dot or comma for decimal places? although it does handle the life regen which is also a decimal place.

**Comment by bMiquelin** [comment]
The following mod is also missing (using 0.4.3):
#% increased Movement Speed if you've Killed Recently

`Rarity: Rare
Hollow Iridescence
Hypnotic Eye Jewel
--------
Abyss
--------
Requirements:
Level: 41
--------
Item Level: 82
--------
Adds 13 to 18 Cold Damage to Spells
+30 to maximum Life
3% increased Movement Speed if you've Killed Recently
--------
Place into an Abyssal Socket on an Item or into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.
`

**Comment by Kyusung4698** [comment]
> The following mod is also missing (using 0.4.3):
> ![image](https://user-images.githubusercontent.com/8808338/72221859-3fed1280-353d-11ea-9d52-b0dbc5312d6d.png)

Thank you! There was an error at the parser. It will be fixed in the next alpha version.

**Comment by Kyusung4698** [comment]
Fixed with [0.5.0](https://github.com/Kyusung4698/PoE-Overlay/releases/tag/0.5.0). Thank you for reporting this issue!
