### ISSUE TITLE
Changes to "Map > Stats Warnings" are not saving.

### ISSUE THREAD

**Issue by Dgc2002** [Kyusung4698/PoE-Overlay#425]
# 🐞 bug report

**Describe the bug**
Map Stats Warnings settings are not being saved.

**To Reproduce**

[Video on Streamable showing steps taken to reproduce the issue](https://streamable.com/jp4s8) (had issues uploading a GIF)

**Expected behavior**
Settings should be saved.

**Screenshots**
See above

## 🌍  Your Environment

- OS:  Windows 10 64x
- Version:  0.6.9 full install
- PoE:  Steam 3.10.0/e English

**Comment by Traf27** [comment]
Checkbox on every Map Stat, is only to select this stat so you could move it between **Unselected**, and **Selected**

**Comment by Dgc2002** [comment]
Ahh I see. The headings for each section don't really stand out. I think the flat design really hurts UX here. I honestly hadn't even realized the two columns meant anything important as it could have just been a design decision to have two columns for all mods instead of one long one. Also there's nothing on the mod elements that would indicate that it's movable.  
  
Might I suggest maybe a design with two columns with arrows in between? Once an element is selected the button with an arrow pointing to the opposite column is enabled. It's a pretty common design but I'm not sure exactly what it's called.

**Comment by Kyusung4698** [comment]
> Checkbox on every Map Stat, is only to select this stat so you could move it between **Unselected**, and **Selected**

Thank you for your response! 

> I think it would be helpful for the arrows to react(enable/disable) when items are selected/deselected.

I'll add a short transition. Thanks for the feedback.

**Comment by Kyusung4698** [comment]
## 0.6.10 (2020-03-22)

- update disable arrow if no mod selected (#425)
