### ISSUE TITLE
Suggestion: Don't instantly search again after adjustment of search parameter.

### ISSUE THREAD

**Issue by DasKashi** [Kyusung4698/PoE-Overlay#426]
In light of the current performance issues, that the official trade site has, I guess, that trying to lower the number of request, that the site is bombarded with each minute aint bad.

Even slight adjustment of a value immediately triggers a new search request each time. Most of the time, I'm finetuning multiple parameters, before I'm in need of being presented by another set of results. The initial search being instant is fine, but after that, I think, having to trigger a new search by yourself, should at least be an option, maybe even the default.

See screenshot for possible UI.
![PoE_Overlay_New_Search_Mockup](https://user-images.githubusercontent.com/2964361/77235114-6e2d4500-6bb3-11ea-97a1-4e716f536774.png)

**Comment by Kyusung4698** [comment]
## 0.6.10 (2020-03-22)

- add trade search configurable debounce time with now support (#426)

**Comment by jer-lim** [comment]
This is a bad feature. I thought something was wrong with the application and uninstalled it to install 0.6.9. There should be a configurable timer in the settings rather than having to press "now" every time.

**Comment by IdrisQe** [comment]
You say it's a configurable time but I can't seem to find the configuration in 0.6.10?
The current time to wait (or the default, if it IS configurable) seems a bit overly long, and the "now" button is kind of annoying to click due to its placement and blending in.

**Comment by tonpix** [comment]
I'm wondering too, first time I saw it, it threw me off, thought something was off with app or trade api, but that makes sense for some people/trade api load, but definitely a adjustable timer is needed, I personally would set myself around 1s.

**Comment by Kyusung4698** [comment]
Hi, thanks for your feedbacks! The default value is probably to high. I'll adjust it in the next version. In the meantime you can change the setting here:

![image](https://user-images.githubusercontent.com/38520678/77293228-31ac3700-6ce2-11ea-81bd-6b3ed263ee5b.png)

**Comment by DasKashi** [comment]
I think 1.5s or 2s for the default seems fair. A slider might be better suited for this option or at least an info next to the options about how long each is like "Normal (5s)".

**Comment by Kyusung4698** [comment]
## 0.6.11 (2020-03-24)

- update default debounce time to 1s
