### ISSUE TITLE
Bug: Search is not working in Traditional Chinese server 

### ISSUE THREAD

**Issue by Halftune** [Kyusung4698/PoE-Overlay#427]
server:Traditional Chinese (Garena)

In debug mode  it's have data return from correct api:
![1](https://user-images.githubusercontent.com/29658265/77243180-3c16f400-6c42-11ea-83f1-85bc8da87259.PNG)

But final UI is  empty, every item search are same result:
![2](https://user-images.githubusercontent.com/29658265/77243210-8ef0ab80-6c42-11ea-94f2-6f36ab5d3285.PNG)

setting:
![3](https://user-images.githubusercontent.com/29658265/77243221-a039b800-6c42-11ea-9eec-9318a18e1559.PNG)

### 
example item query data:
```
稀有度: 寶石
彈片砲塔
--------
攻擊, 投射物, 圖騰, 物理, 弓箭
等級: 1
魔力消耗: 5
攻擊速度: 基礎的 50%
附加傷害效用: 38%
品質: +12% (augmented)
經驗值: 1 / 841
--------
需求:
等級: 4
敏捷: 16
--------
召喚一個砲塔，發射多支有極大壓力的箭矢並將箭矢粉碎至碎片。敵人可被同次攻擊擊中多次。
--------
圖騰持續 8 秒
造成 38% 基本傷害
召喚砲塔圖騰最大數量 +2
附加 2 至 3 攻擊物理傷害
發射 2 個額外箭矢
增加 12% 投射物速度
--------
將其放置於物品上同樣顏色的插槽來獲得這項技能。點擊右鍵從插槽中取出。
```

------------------------------------------------------------------------------------------------------
Thanks for ur help,other feature are working properly,and this is truly an outstanding tool .

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This is relate with poe.ninja. I'm using their data to convert currencies. Their api does not return any data for the selected Chinese league. I guess they do not support the Chinese version of the game. What are you using to convert currencies?

**Comment by Halftune** [comment]
Thank you for getting back to me. I can't find any convert currencies api for garena server :<  . So I think using poe.ninja 's data  is acceptable now.  I don't know Angular's syntax very well,so what I'm doing now is hardcode two ts's leagueId to get search feature working at local test.  Thank you again for everything you’ve done.

currency-chaos-equivalents.provider.ts   - 35  fetch
item-category-values.provider.ts - 199  fetchItem

![1](https://user-images.githubusercontent.com/29658265/77642216-4580c300-6f98-11ea-8abc-190680b03b62.PNG)
![2](https://user-images.githubusercontent.com/29658265/77642222-474a8680-6f98-11ea-9c77-059c682a31f3.PNG)
