### ISSUE TITLE
[LINUX] Poe overlay covers the screen with black foreground when not using desktop effects.

### ISSUE THREAD

**Issue by fatino** [Kyusung4698/PoE-Overlay#431]
# 🐞 bug report

**Describe the bug**

Poe Overlay covers POE with black foreground when not using desktop effects in KDE Plasma. Steam in Linux when launching a game automatically disables desktop effects at startup of a game. Playing with desktop effects introduces lag.
I tried with Hardware Acceleration on and off in app settings.
It looks like its similar to #154, but the game with desktop effects enabled is unplayable.
**To Reproduce**

1. Start Poe Overlay
2. Click start Poe in steam
3. Poe launches with a sound playing in the background, but the whole screen is black. Cursor is visiable
4. To get rid of the black foreground press shift+alt+F12, which enables desktop effects. Poe is visiable.

**Expected behavior**

Poe Overlay works properly with desktop effects disabled.

**Screenshots**

Normal startup:
![normal_startup](https://user-images.githubusercontent.com/408612/77250000-353db080-6c45-11ea-999d-15a4a9907904.png)
After enabling effects:
![after_enabling_effects](https://user-images.githubusercontent.com/408612/77250038-4be40780-6c45-11ea-8363-d63cb924f4de.png)

## 🌍  Your Environment

- OS:  Arch Linux, KDE 5.18.3, Linux 5.5.6-fsync, mesa-aco-git 20.0.0.20200226.7a965bd4c38-7, dxvk 1.5.3-async, proton 5.4-GE/proton 5.0.5
- Version:  0.6.9 (master:59ac8dd8792939f3668d46dc8f10b5e7184d0123)
- PoE:  Steam 3.10.0/e English

**Comment by fatino** [comment]
I dug a bit deeper and found out that it's impossible to draw transparency without compositing in X11. Your delay fix already takes care of the issue for use with compositing. But playing with compositing in Linux introduces noticeable performance dip. It's not even less fps, it's just delay as compositing is trying to synchronize frames.

**Comment by thorsten-passfeld** [comment]
I have this issue as well, but my workaround solution was to press F8 to close POE-Overlay, kill the process by pressing CTRL+C in the terminal and then simply running `npm run start` a second time. Then it behaved normally, for whatever reason. I'm also using KDE and I'm on Manjaro.

One thing to note is that I disabled any games from disabling compositing, because I hated having my widgets on my second monitor freeze after some time. My PC can definitely handle it, but it's of course not recommended for everybody.

**Comment by fatino** [comment]
@thorsten-passfeld isn't that an old KDE bug? It was fixed, wasn't it? I haven't noticed it for a while.

I guess I might be picky when it comes to latency. But a window mode would be interesting. We could just put the app in a second monitor.
