### ISSUE TITLE
[LINUX] Poe Overlay is not aware of POE window. 

### ISSUE THREAD

**Issue by fatino** [Kyusung4698/PoE-Overlay#432]
# 🐞 bug report

**Describe the bug**
Poe overlay prints itself all the time, not only on top of POE window. It also suppresses key shortcuts in other apps such as ctrl+t in a browser.

**To Reproduce**
1. Start Poe overlay
2. Start POE
3. Alt+tab from the game and try to ctrl+t in a web browser of your choice. Instead of a new tab you get info "Clipboard was empty. Please make sure the game is focused"

**Expected behavior**
Poe overlay should work only when Poe window is focused.

**Screenshots**
![ctrl+t](https://user-images.githubusercontent.com/408612/77250686-e9413a80-6c49-11ea-89a0-6256cdfdda33.png)
![overlay_text](https://user-images.githubusercontent.com/408612/77250807-95832100-6c4a-11ea-8bc7-dd81d4e10491.png)

## 🌍  Your Environment

- OS:  Arch Linux, KDE 5.18.3, Linux 5.5.6-fsync, mesa-aco-git 20.0.0.20200226.7a965bd4c38-7, dxvk 1.5.3-async, proton 5.4-GE/proton 5.0.5
- Version:  0.6.9 (master:59ac8dd8792939f3668d46dc8f10b5e7184d0123)
- PoE: Steam 3.10.0/e English

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This is the intended behavior for running the app in debug mode. Please use `npm run electron:local` instead. Thanks!

**Comment by fatino** [comment]
Ok, I'm a newbie when it comes to electron apps. Could you provide an instruction to run this app in Linux?
I tried now with:
1. Clone repo
2. npm install 
3. npm run electron:rebuild
4. npm run electron:local
The app starts and shows in a taskbar. I can access settings etc. but now it doesn't show at all when I launch POE. I also tried skipping 3. step. The same result.
If I use npm run electron:local it prints at the end:
```WARNING in budgets: Exceeded maximum budget for initial. Budget 10 MB was not met by 7.61 MB with a total of 17.6 MB.
15:51:41.175 › App starting...
15:51:41.179 › App checking for animation flag: /home/fatino/.config/poe-overlay/animation.flag.
15:51:42.139 › App Version:  0.6.9
15:51:42.203 › Checking for update
15:51:42.244 › Error: Error: ENOENT: no such file or directory, open '/home/fatino/programowanie/tests/PoE-Overlay/dev-app-update.yml'
(node:27250) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/fatino/programowanie/tests/PoE-Overlay/dev-app-update.yml'
(node:27250) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/fatino/programowanie/tests/PoE-Overlay/dev-app-update.yml'
(node:27250) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27250) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27250) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:27250) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
It seems like it's still now aware of the POE window. In debug mode I could at least ctrl+c and then ctrl+d to show items. Now it doesn't do anything and doesn't print "Poe Overlay" text over POE window.

**Comment by Kyusung4698** [comment]
Looks fine. The app is just not tested on Linux. I assume you need to adjust following line: https://github.com/Kyusung4698/PoE-Overlay/blob/master/hook.ts#L61

electron:local uses the production build and therefore checks the poe window. This works by checking against the file name.

**Comment by fatino** [comment]
This is what this library returns if Path of Exile is focused:
```{
  platform: 'linux',
  title: 'Path of Exile',
  id: 232783877,
  owner: {
    name: 'steam_app_238960',
    processId: 6471,
    path: '/mnt/twardy/SteamLibrary/steamapps/common/Proton 5.0/dist/bin/wine64-preloader'
  },
  bounds: { x: 0, y: 551, width: 1920, height: 1080 },
  memoryUsage: 1012076544
}
```
If I change line 61 to 
`active = test.endsWith('wine64-preloader');`
It works properly. It activates when Poe is focused and tucks away when I alt+tab.

It might be better to use title var, because on Linux many paths can end with that name "wine64-preloader"
I think that window title for steam and standalone version on linux would be the same.

**Comment by Darksider3** [comment]
Actually funny, im running PoE through Lutris(and with the exact same system with OP as i use latest arch and KDE too), here it's `pathofexile_x64steam.exe`. Just as a sidenote: When i switch to steam only with Proton, it's the same behaivour that OP has.

**Comment by fatino** [comment]
@Kyusung4698 the new library you are using, node-window-manager, doesn't support Linux. :(

**Comment by Kyusung4698** [comment]
> @Kyusung4698 the new library you are using, node-window-manager, doesn't support Linux. :(

![](https://media.tenor.com/images/755e00a560bbafa4418abfb2c8a2969e/tenor.gif)

I was chatting with another Linux user and we were debugging this too. Unfortunately i did not check it on Linux. I'll provide an alternative soon.
