### ISSUE TITLE
Waterways T3 pricecheck wrong results

### ISSUE THREAD

**Issue by TheOne320** [Kyusung4698/PoE-Overlay#433]
# 🐞 bug report

**Describe the bug**

Price checking the map in the screenshot gives wrong results. When I directly mark the name it works. Should the Overlay automatically recognize which map is getting checked?

**To Reproduce**

Use Ctrl-D on the Map in the screenshot without selecting anything else.

**Expected behavior**

Other maps give only results for that map and the correct tier, so I assume that this should also be done with the Waterways map.

**Screenshots**

![Waterways](https://user-images.githubusercontent.com/7705568/77252378-ce73c380-6c53-11ea-8ba7-6413d9546a73.png)
## 🌍  Your Environment

- OS:  Windows 10 x64 1909
- Version:  0.6.9 installed
- PoE:  Steam 3.10.0/e English

**Comment by TheOne320** [comment]
Ctrl-C results:

Rarity: Magic
Ceremonial Waterways Map
--------
Map Tier: 3
Atlas Region: Tirn's End
Item Quantity: +10% (augmented)
Item Rarity: +6% (augmented)
Monster Pack Size: +4% (augmented)
--------
Item Level: 74
--------
Area contains many Totems
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I assume you have disabled the `Item Type` and therefore the type is not selected at the dialog. This results in a query just searching for items with base type `map`. I think this is wrong and i'll add flasks and maps as items where the item type is mandatory for it's price.

**Comment by TheOne320** [comment]
You are right. I now enabled item type. I was puzzled because normal maps it is not possible to select the map name.

**Comment by Kyusung4698** [comment]
## 0.6.10 (2020-03-22)

- update always use the item type of maps and flasks as query param (#433)
