### ISSUE TITLE
Suggestion: Open item, with selected parameters on trade site, before prise will be loaded

### ISSUE THREAD

**Issue by AndersonDev** [Kyusung4698/PoE-Overlay#436]
#🚀 feature request

**Is your feature request related to a problem? Please describe.**
I want to open item, with selected parameters on trade site, before prise and avaliable options will be displayed. Mostly for items which not presented in stock. I want just fill params in site and ajust directly there.

**Describe the solution you'd like**
Abbility to navigate to site on seperate button or hotkeys imediatly after choosing params. Not wait a price check.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. You can cancel the detail search after the initial search is done. The initial search is required because this returns the actual search url to open. After canceling the detail search you open the results in the browser normally.

Closed in favor of #284
