### ISSUE TITLE
Suggestion: Search scarabs by name instead of "map fragment"

### ISSUE THREAD

**Issue by thor-kiessling** [Kyusung4698/PoE-Overlay#437]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

No
**Describe the solution you'd like**

Search scarabs by name so it doesn't search the generic map fragment category. for example a rusted sulphite scarab was showing as only worth .3c when right now it's 5c
**Describe alternatives you've considered**

dunno

**Comment by Kyusung4698** [comment]
## 0.6.11 (2020-03-24)

- fix remove typeId only on weapon, armour and accessory
