### ISSUE TITLE
[Windows] requireAdminstrator set

### ISSUE THREAD

**Issue by Panoptis** [Kyusung4698/PoE-Overlay#439]
Why?
I'd consider this a major security issue as the app is parsing data it can not trust.

This seems to work perfectly fine:
`C:\Windows\System32\cmd.exe /min /C "set __COMPAT_LAYER=RUNASINVOKER && start "" "F:\Games\poe-overlay\poe-overlay.exe"`

Thanks for the great app, keep it up!

**Comment by Kyusung4698** [comment]
Duplicate of #361
