### ISSUE TITLE
Weird behaviour of "Evaluate" feature

### ISSUE THREAD

**Issue by rockafellah1** [Kyusung4698/PoE-Overlay#441]
# 🐞 bug report

**Describe the bug**
When looking up some items using the Evaluate feature (Ctrl/Alt + D) it seems to behave in a way that appears to be malfunctioning. Specifically when looking up "Mortal Hope" it shows the right value on the top half of the window but weird 0-0.3c listings on the bottom. When clicking on the currency icon it shows that the evaluated item was not "Mortal Hope" but map fragments in general. 
After pressing the reset button (or clicking the name filter) in the "Evaluate" window, it shows the correct listings with the correct prices. (I am not sure if this is an error on my part and it's supposed to show map fragments as a whole, but that seems unliekly.)
Similarly when looking up "Atziri's Promise", it shows the correct value for the poe.ninja part but says there are no results on the bottom part. Pressing reset (or manually disabling all mod filters) - again - fixes the issue but looking up the item again yields the same result. 

After testing a bit more it seems that most - if not all - map fragments show this behaviour so it might be intended (and if so, sorry for wasting your time).

/edit: The faulty mod for the Atziri's Promise seems to be the "Total to Chaos Resistance". Disabling that filter fixes the issue temporarily.

**To Reproduce**

1. Press Ctrl+D while hovering over Mortal Hope / Atziri's Promise

**Expected behavior**
It should be showing the poe.ninja price in the top half (working correctly) and the current trade listings on the bottom part (not working until you press the reset button).

**Screenshots**
https://i.imgur.com/FtbT7SU.png    -  Result when evaluating Mortal Hope
https://i.imgur.com/uU3LZ6u.png -   Result after pressing the "reset" button

https://i.imgur.com/QN1BUnH.png - Result when evaluating Atziri's Promise
https://i.imgur.com/QcII6ti.png  - Result after pressing the "reset" 

## 🌍  Your Environment

- OS: Windows 10 (64bit) Pro
- Version: 0.6.10 (Setup)
- PoE: Steam (current version)

**Comment by Kyusung4698** [comment]
## 0.6.11 (2020-03-24)

- fix remove typeId only on weapon, armour and accessory
