### ISSUE TITLE
Highlight keybind not working properly

### ISSUE THREAD

**Issue by Jerome48** [Kyusung4698/PoE-Overlay#442]
When using the highlight command, it does not allow you to bind a ctrl+ anything bind

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. There is blacklist of following keybindings which are not bindable:

  'CmdOrCtrl + C'
  'CmdOrCtrl + V'
  'CmdOrCtrl + F'

All others should work fine.
