### ISSUE TITLE
Suggestion: Item Highlight in Quad Stashtabs while Selling

### ISSUE THREAD

**Issue by sastrugas** [Kyusung4698/PoE-Overlay#443]
Hi there, 
You already have the Item highlight on normal premium stashtabs while selling.

And i was Wondering if it would be possible to do the same at Quad Stashtabs.

I am mostly sell through Quad Tabs. 

Thanks alot if you would consider that.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I'm able to use the highlight command also on Quad Stashtabs. Are you getting any error?

**Comment by sastrugas** [comment]
Hey, 
no it is kind of working but the highlighted square is not on the item its rather 10 spaces down or to the left or right. and it wasn a one time issue.

**Comment by Kyusung4698** [comment]
Hm, the highlight function is part of the game. My tool only copies the item text into the search box. Could you please provide a screenshot?
