### ISSUE TITLE
Suggestion: Any possibility for non-Aero Support? And why is Aero needed in the first place, out of curiosity?

### ISSUE THREAD

**Issue by Guffinn** [Kyusung4698/PoE-Overlay#445]
See title I guess.
Just a quick thought because I was hyped to see the program, but less than thrilled that I'd have to enable Aero.

No biggie though, and I get that you wouldn't make any changes for a single minor case.

**Comment by Traf27** [comment]
Aero is needed to create transparent windows. As I understand it enables to create overlay on top of the game itself.

**Comment by Kyusung4698** [comment]
> Aero is needed to create transparent windows. As I understand it enables to create overlay on top of the game itself.

https://www.electronjs.org/docs/api/system-preferences#systempreferencesisaeroglassenabled-windows

Basically this. There is currently no workaround but i may release a fullscreen solution later on which will not require this. See my [Patreon ](https://www.patreon.com/kyusung4698) goals for this.
