### ISSUE TITLE
Keybinds are blocking Alt Gr key

### ISSUE THREAD

**Issue by fneto** [Kyusung4698/PoE-Overlay#446]
# 🐞 bug report

The software uses Alt and Alt Gr for keybinds, the issue is, it blocks other Alt Gr uses, in my keyboard, to type a questionmark I need no use Alt Gr + W, and can't do it.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Please see following [thread](https://github.com/Kyusung4698/PoE-Overlay/issues/177#issuecomment-602032378). 
tldr: `ALT + W` is bound to the `Open wiki` feature. This can be changed at the menu > misc.
