### ISSUE TITLE
Mod: missing added small passive skills mods in cluster jewel

### ISSUE THREAD

**Issue by eunsoori** [Kyusung4698/PoE-Overlay#447]
# 🛸 Item modifier report

**Current item modifier**
```
nothing
```

**Expected item modifier**
```
추가된 소형 패시브 스킬 효과: 'ALL MODS'
(Added Small Passive Skills also grant: 'ALL MODS')
```

**Copied item data**

```
아이템 희귀도: 일반
대형 스킬 군 주얼
--------
아이템 레벨: 62
--------
패시브 스킬 12개 추가 (enchant)
추가된 소형 패시브 스킬 효과: 냉기 피해 12% 증가 (enchant)
--------
패시브 스킬 트리에서 포인트를 할당한 대형 주얼 슬롯에 장착하십시오. 추가된 패시브 스킬은 주얼 반경과 상호작용하지 않습니다. 우클릭하면 슬롯에서 제거됩니다.

```

**Screenshots**

## 🌍  Your Environment

- Version:  0.6.10
- PoE:  Kakao 3.10 Korean

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This has been fixed by GGG/ me with the new version 0.6.13. The trade website was not correctly translated. 

![image](https://user-images.githubusercontent.com/38520678/77576209-148b8a00-6ed5-11ea-9968-9dc09bd2360b.png)
