### ISSUE TITLE
prophecy searching does not work in KR

### ISSUE THREAD

**Issue by eunsoori** [Kyusung4698/PoE-Overlay#448]
# 🛸 Item modifier report

every prophecy searching does not work in kakao client.
i think this is official trade site issue.
'the twins' - 'the twins prophecy'
'쌍둥이' - '쌍둥이 예언'

**Copied item data**

```
아이템 희귀도: 일반
쌍둥이
--------
하나였던 것이 둘이 되었다. 강자는 머릿수를 통해 더 강한 힘을 추구한다.
--------
그대는 강력한 몬스터들을 복제하는 지역에 들어갈 것이다.
--------
우클릭으로 이 예언을 캐릭터에 추가하십시오.
```

## 🌍  Your Environment

- Version: 0.6.10
- PoE: kakao 3.10 KR

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I think this got fixed. See screenshot below. Could you please confirm? Thanks!

![image](https://user-images.githubusercontent.com/38520678/77575920-83b4ae80-6ed4-11ea-8828-af2741317099.png)
