### ISSUE TITLE
data is stale

### ISSUE THREAD

**Issue by mrDimMak** [Kyusung4698/PoE-Overlay#449]
# 🐞 bug report

**Describe the bug**
Every time I adjust search parameters the programs informs the data is stale and gives a skippale four second delay to the query.

**To Reproduce**
 e.g. Win7 x64
- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This is an intended behavior. Please see #426. There is also an screenshot of the setting you need to change in order to "fix" this.

**Comment by mrDimMak** [comment]
Thank you for your swift response, this completely fixes my issue.
I tried searching for the keyword stale beforehand but didnt find the issue.

Op di 24 mrt. 2020 om 11:38 schreef Nicklas <notifications@github.com>:

**Comment by Kyusung4698** [comment]
No worries. I've messed the default value up. It'll be changed in the next version.
