### ISSUE TITLE
Make default search not select ilv, sockets, links

### ISSUE THREAD

**Issue by howardgod** [Kyusung4698/PoE-Overlay#45]
I think most people won't select ilv, sockets and links when searching, instead they incline to select modifiers in it.

Current default search criteria makes results more restrict and didn't reflect what it is on the market.

**Comment by Reaver01** [comment]
Second this. additionally searches are too strict and should use ranges instead of exact numbers

**Comment by Kyusung4698** [comment]
I've added an option to disable this in the user settings for now. There'll be later a customisable item default filter. Thanks for sharing!
