### ISSUE TITLE
Any way to remove delay for "fetching data" ?

### ISSUE THREAD

**Issue by se7enek** [Kyusung4698/PoE-Overlay#450]
Im really worried after some update.
It started showing "Data is stale. Fetching again in 5s... Now?" Which is annoying as fuck to keep clicking. Any way to remove this function and/or make it automatically search without 5second delay?
Literally all people i knew already stopped using that program cuz 5+ second searches are annoying.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This is an intended behavior. Please see #426. There is also an screenshot of the setting you need to change in order to fix this.
