### ISSUE TITLE
App positioning is off

### ISSUE THREAD

**Issue by Ninjaskill** [Kyusung4698/PoE-Overlay#453]
Since update 0.6.11 the app positioning is off and setting is cut off

![image](https://user-images.githubusercontent.com/10984882/77450042-02d1b600-6df3-11ea-8843-2fdce918e8e2.png)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Sorry, but i'm unable to view your attached screenshot. Could you upload it to imgur?

**Comment by Ninjaskill** [comment]
https://i.imgur.com/HWhKxru.jpg

**Comment by Kyusung4698** [comment]
> https://i.imgur.com/HWhKxru.jpg

Okay, does retabbing into the game fixes it?

**Comment by Ninjaskill** [comment]
Nope i think something broke into the positioning usually it's centered but now its cut off notice the version of the app is also different before it was at the very bottom left of the screen.

**Comment by Kyusung4698** [comment]
The overlay normally takes the same position as the game. But these seems way of in your screenshots. Just as a test - Could you try normal windowed mode?

**Comment by Ninjaskill** [comment]
A little update when price checking an item around this area where it cuts off. Still same issue in windowed mode
here's a screenshot to show the issue more clearly

![image](https://user-images.githubusercontent.com/10984882/77451778-6b219700-6df5-11ea-9b86-997f7790e2db.png)

**Comment by Kyusung4698** [comment]
> A little update when price checking an item around this area where it cuts off. Still same issue in windowed mode
> here's a screenshot to show the issue more clearly
> 
> ![image](https://user-images.githubusercontent.com/10984882/77451778-6b219700-6df5-11ea-9b86-997f7790e2db.png)

I'll release a new version soon but i'll be marked as pre release. So you need to update it yourself. If everything works i'll remove the prerelease tag.

**Comment by Ninjaskill** [comment]
Where do i find the pre release version?

**Comment by Kyusung4698** [comment]
It'll be visible here: https://github.com/Kyusung4698/PoE-Overlay/releases but it's not released yet.

**Comment by anarchyx99x** [comment]
Having the exact same issue. Positioning of the overlay is just shifted upwards

**Comment by distermaer** [comment]
I have exactly the same issue, using windowed fullscreen and switching to fullscreen has the same cropping issue. Was fine in the previous version.

**Comment by Kyusung4698** [comment]
## 0.6.12 (2020-03-24)

- fix not covering the game correctly

Hi, i've provide a [pre-release](https://github.com/Kyusung4698/PoE-Overlay/releases/tag/v0.6.12). Please let me know if it's working now and i'll release it.

**Comment by Ninjaskill** [comment]
Seems to be working for me

**Comment by Kyusung4698** [comment]
Perfect. Thanks for your feedback.
