### ISSUE TITLE
[BUG] CTRL+F not working

### ISSUE THREAD

**Issue by KELPOE** [Kyusung4698/PoE-Overlay#454]
Settings > Misc > stash > highlight > I type CTRL+F but it is not working.
CTRL+"another letter" is working
"F" is working
but CTRL+F is not working.
I mean, it's like i didnt type anything, as if it was not accepted.

I always used CTRL+F in POE, it worked fine.

**Comment by ThorTheGray** [comment]
I'm experiencing the same thing as well. It seems PoE loses focus. If I hit the windows key and then come back to PoE the overlay is there. Something got bugged in the last update.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. `Ctrl + F` is currently a not supported keybinding. Please see #293

**Comment by KELPOE** [comment]
Why not simply deactivate this feature in poe overlay, since it is already native in POE ? I don't understand.

**Comment by Kyusung4698** [comment]
## 0.6.13 (2020-03-25)

- add `CmdOrCtrl + F` as supported accelerator (#293, #454)
