### ISSUE TITLE
4k resolution bag

### ISSUE THREAD

**Issue by tulalive** [Kyusung4698/PoE-Overlay#456]
# 🐞 bug report

in 4K resolution, the evaluation window POPs up in the left corner and you can't move it anywhere else. and you can't deploy it on a normal scale.

![222](https://user-images.githubusercontent.com/62614526/77456220-fa39a980-6e0b-11ea-9d7f-266b1efafe8a.png)

**Comment by Kyusung4698** [comment]
## 0.6.12 (2020-03-24)

- fix not covering the game correctly

Hi, i've provide a [pre-release](https://github.com/Kyusung4698/PoE-Overlay/releases/tag/v0.6.12). Please let me know if it's working now and i'll release it.

**Comment by Galimka** [comment]
Hi, the fix works for me ! (4K and same bug) :)

> 
> ## 0.6.12 (2020-03-24)
> 
>     * fix not covering the game correctly
> 
> 
> Hi, i've provide a [pre-release](https://github.com/Kyusung4698/PoE-Overlay/releases/tag/v0.6.12). Please let me know if it's working now and i'll release it.

Hi, the fix works for me ! (4K and same bug) :)

**Comment by Kyusung4698** [comment]
> Hi, the fix works for me ! (4K and same bug) :)
> 
> > ## 0.6.12 (2020-03-24)
> > ```
> > * fix not covering the game correctly
> > ```
> > 
> > 
> > Hi, i've provide a [pre-release](https://github.com/Kyusung4698/PoE-Overlay/releases/tag/v0.6.12). Please let me know if it's working now and i'll release it.
> 
> Hi, the fix works for me ! (4K and same bug) :)

Alright. Thanks for your feedback! 🚀
