### ISSUE TITLE
Spacebar closes built-in browser. Cant type in affixes with spaces

### ISSUE THREAD

**Issue by Juts2** [Kyusung4698/PoE-Overlay#461]
# 🐞 bug report

**Describe the bug**

**To Reproduce**

**Expected behavior**

## 🌍  Your Environment

- OS:  e.g. win10 64
- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by Kyusung4698** [comment]
## 0.6.13 (2020-03-25)

- fix spacebar closes built in browser by disabling keyboard support (#461)
