### ISSUE TITLE
Bug: Can't install the new release 0.6.12

### ISSUE THREAD

**Issue by TallTimbers95** [Kyusung4698/PoE-Overlay#463]
# 🐞 bug report

**Describe the bug**

The client wont update.
using the installer gerates the message 
installations aborted setup was not completed successfully.
**To Reproduce**

Try to update from client.
Try to download and install.

**Expected behavior**

**Screenshots**

## 🌍  Your Environment

- OS: Win10 x64
- Version:  poe-overlay-Setup-0.6.12.exe
- PoE:   Steam 3.10.0f English

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This seems related to #336. Please see the [solution](https://github.com/Kyusung4698/PoE-Overlay/issues/336#issuecomment-600087939) given there.

**Comment by TallTimbers95** [comment]
Thank you, I had not noticed that I had to uninstall the program and thought deleting its folder in program file would have been sufficient, that's my fault. I didn't have to go into the registry like in #336 

Thank you for your patience and hard work. 

Remedy: (tested on 0.6.13)
Go to control panel > uninstall > reinstall
