### ISSUE TITLE
Opened tooltips not visible until "reset zoom" on the tray icon.

### ISSUE THREAD

**Issue by DuHastMeinSkill** [Kyusung4698/PoE-Overlay#464]
When I use Ctrl + D to search items, sometimes the tooltip does not appear. Once in this state, it will not start working again unless I relaunch the application, or hit "reset zoom" on the tray icon. It breaks again pretty quickly. When I use the "reset zoom" trick I often have several tooltips show up that I have to click to close. My suspicion since I don't see anyone else complaining is that my non-standard monitor size is contributing.

**To Reproduce**
One way to guarantee it breaks for me is to open the browser by clicking on something on the tooltip, however it also frequently breaks if I have clicked anything in the tooltip.

**Expected behavior**
I expect the tooltips to not stop appearing.

- OS: Windows 10 x64
- PoE:  Steam 3.10.0/e English
Monitor: 3440x1440 Ultrawide (dual monitors)

**Comment by SinisterGenocide** [comment]
same thing is happening to me. thought i was crazy and it kept crashing. have you found a workaround for this?

**Comment by SinisterGenocide** [comment]
just downgraded to old version. works fine

**Comment by TheOne320** [comment]
I do not know if it is related, but I am having problems with the overlay staying on top of the PoE window after alt-tabbing with the newest version. Before everything was fine.

**Comment by Kyusung4698** [comment]
## 0.6.13 (2020-03-25)

- fix tooltips not visible by disabling keyboard support (#464)

**Comment by Suddow** [comment]
I'm on the latest, with keyboard support disabled, and I'm still getting the alt-tab refocus issue.
