### ISSUE TITLE
stale data

### ISSUE THREAD

**Issue by SinisterGenocide** [Kyusung4698/PoE-Overlay#467]
when selecting different stats on an item after using ctrl+d it says stale data fetching info then counts down from 5 seconds. this did not happen in previous versions. what is causing this?

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This is an intended behavior. Please see #426. There is also an screenshot of the setting you need to change in order to fix this. Also in the new version 0.6.12 the default value is significantly lower.
