### ISSUE TITLE
PoE not gaining focus correctly after closing/hiding applications

### ISSUE THREAD

**Issue by barbarolucente** [Kyusung4698/PoE-Overlay#469]
# 🐞 bug report

**Describe the bug**

After hiding or closing external application (browsers, ecc.), PoE is not gaining focus, this cause applications like Poe Trades Companion to not work until I click twice on PoE in the app bar.
**To Reproduce**

**Expected behavior**

**Screenshots**

## 🌍  Your Environment

- OS:  e.g. Win10 x64
- Version:  e.g. 0.6.12 setup
- PoE:  e.g. Steam 3.10.0/e English

**Comment by Kyusung4698** [comment]
Duplicate of #460
