### ISSUE TITLE
Suggestion: Add a change log to the application.

### ISSUE THREAD

**Issue by Riboe** [Kyusung4698/PoE-Overlay#471]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

New releases are published very often and it's quite annoying to have to go to the Releases page on GitHub to find out what's changed. If there were significantly longer between releases, it would be less of an issue, but I feel like the high frequency of releases makes the issue worse.

**Describe the solution you'd like**

When the program starts after having been updated, show a window with the latest changes. Also add tray menu item to open the change log window on demand.

**Describe alternatives you've considered**

I imagine that there are plenty of people who would prefer not to be bothered by the change log window automatically opening, so just adding the aforementioned menu item would be an acceptable solution.

Another acceptable short term solution would be make the change log window, simply be a web browser window that opens the Releases page on GitHub.

**Additional context**

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This seems like a good idea. I'll add in the next version.

**Comment by Riboe** [comment]
That would be amazing. Thanks for all the work you do!

**Comment by Kyusung4698** [comment]
## 0.6.14 (2020-03-26)

- add changelog as tray entry and show after update (#471)
