### ISSUE TITLE
Map warning numbers wrong dark colour

### ISSUE THREAD

**Issue by TheOne320** [Kyusung4698/PoE-Overlay#472]
# 🐞 bug report

**Describe the bug**

The numbers in the map warning are now suddenly in a blackish colour (see screenshot), making it very hard to read them.

**To Reproduce**

Check map warning with number values.

**Expected behavior**

Numbers in any light colour.

**Screenshots**

![image](https://user-images.githubusercontent.com/7705568/77581589-41906a80-6ede-11ea-975d-c93eadeed05d.png)

## 🌍  Your Environment

- OS:  Windows 10 x64 1909
- Version:  0.6.13 installed
- PoE:  Steam 3.10.0f English

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Will be fixed in the next version.

**Comment by Kyusung4698** [comment]
## 0.6.14 (2020-03-26)

- fix invisible values at map info (#472)
