### ISSUE TITLE
Auto update doesnt work for me.

### ISSUE THREAD

**Issue by Raiwulf** [Kyusung4698/PoE-Overlay#474]
When I get the notification regarding an update. It says I need to relaunch the app. Tried admin mode/normal mode. Relaunching doesnt work even if its ended downloading the new version.

Also a suggestion: I would like to see browser results even if the app has found results

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Could you please attach the latest logs of the application. They can be found at: %appdata%/poe-overlay/logs/main.log Thanks!

**Comment by AbrahamLincooln** [comment]
[main.log](https://github.com/Kyusung4698/PoE-Overlay/files/4388314/main.log)
Got the same problem. Relaunching app doesn't update it. With every launch comes notification about update.

**Comment by GregoryGH** [comment]
Had same issue. Only installed new version after I quitted running POE-Overlay.

**Comment by Kyusung4698** [comment]
Thanks for the logs. A follow up question. How do you restart the application? Quit/ Relaunch? Thanks!  I've added a "install updates" even on quit in the 0.6.14. Maybe this fixed it for the 0.6.15 update.

**Comment by Raiwulf** [comment]
> Thanks for the logs. A follow up question. How do you restart the application? Quit/ Relaunch? Thanks! I've added a "install updates" even on quit in the 0.6.14. Maybe this fixed it for the 0.6.15 update.

Tried both, relaunch button in the app or manually exiting/relaunching

**Comment by GregoryGH** [comment]
Seems fixed in some version. But there is no indication when update download finished.
