### ISSUE TITLE
Iohook is required to run PoE Overlay

### ISSUE THREAD

**Issue by Robrownn** [Kyusung4698/PoE-Overlay#476]
# 🐞 bug report

**Describe the bug**
When launching PoE Overlay I get an error saying "Iohook could not be loaded. Please make sure you have vc_redist installed and try again". I have installed the latest vc_redist for my operating system.

**To Reproduce**
1. Go to poe overlay install folder
2. Click on poe-overlay.exe
3. See error

**Expected behavior**
The application to launch

**Screenshots**
https://imgur.com/OuinkyI

## 🌍  Your Environment

- OS: Win10 x64
- Version: 6.12 non-portable
- PoE: Steam 3.10.0/e English

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Could you please attach the latest logs of the application. They can be found at: %appdata%/poe-overlay/logs/main.log Thanks!

**Comment by Robrownn** [comment]
No problem! Here's my latest logs:

[2020-03-25 21:24:47.647] [info] App starting...
[2020-03-25 21:24:47.659] [info] App checking for animation flag: C:\Users\Rob\AppData\Roaming\poe-overlay\animation.flag.
[2020-03-25 21:24:47.691] [info] App args []
[2020-03-25 21:24:47.699] [info] App served false
[2020-03-25 21:24:48.143] [error] An unexpected error occured while registering iohook {
  constructor: 'Error',
  stack: 'Error: \\\\?\\V:\\PoE Tools\\PoE Overlay\\resources\\app.asar.unpacked\\node_modules\\iohook\\builds\\electron-v76-win32-x64\\build\\Release\\iohook.node is not a valid Win32 application.\r\n' +
    '\\\\?\\V:\\PoE Tools\\PoE Overlay\\resources\\app.asar.unpacked\\node_modules\\iohook\\builds\\electron-v76-win32-x64\\build\\Release\\iohook.node\n' +
    '    at process.func (electron/js2c/asar.js:140:31)\n' +
    '    at process.func [as dlopen] (electron/js2c/asar.js:140:31)\n' +
    '    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)\n' +
    '    at Object.func (electron/js2c/asar.js:140:31)\n' +
    '    at Object.func [as .node] (electron/js2c/asar.js:149:18)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:816:32)\n' +
    '    at Module._load (internal/modules/cjs/loader.js:728:14)\n' +
    '    at Module._load (electron/js2c/asar.js:717:26)\n' +
    '    at Function.Module._load (electron/js2c/asar.js:717:26)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:853:19)'
}

**Comment by Kyusung4698** [comment]
Thanks for attaching the logs. It seems like you are using a x86/32-bit system. Is this correct? I'm currently only providing a binary for x64.

**Comment by Robrownn** [comment]
I'm using a 64-bit system. I've tried running the program with the x86 and x64 vcredists

**Comment by Prodanov8906** [comment]
Same problem here, im leaving my report:

[2020-03-30 18:36:45.494] [info] App starting...
[2020-03-30 18:36:45.500] [info] App checking animation flag: false.
[2020-03-30 18:36:45.501] [info] App checking keyboard flag: false.
[2020-03-30 18:36:45.550] [info] App args []
[2020-03-30 18:36:45.553] [info] App served false
[2020-03-30 18:36:46.056] [error] An unexpected error occured while registering iohook {
  constructor: 'Error',
  stack: 'Error: The specified module could not be found.\r\n' +
    '\\\\?\\C:\\Program Files\\poe-overlay\\resources\\app.asar.unpacked\\node_modules\\iohook\\builds\\electron-v76-win32-x64\\build\\Release\\iohook.node\n' +
    '    at process.func (electron/js2c/asar.js:140:31)\n' +
    '    at process.func [as dlopen] (electron/js2c/asar.js:140:31)\n' +
    '    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)\n' +
    '    at Object.func (electron/js2c/asar.js:140:31)\n' +
    '    at Object.func [as .node] (electron/js2c/asar.js:149:18)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:816:32)\n' +
    '    at Module._load (internal/modules/cjs/loader.js:728:14)\n' +
    '    at Module._load (electron/js2c/asar.js:717:26)\n' +
    '    at Function.Module._load (electron/js2c/asar.js:717:26)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:853:19)'
}
[2020-03-30 18:43:53.420] [info] App starting...
[2020-03-30 18:43:53.427] [info] App checking animation flag: false.
[2020-03-30 18:43:53.428] [info] App checking keyboard flag: false.
[2020-03-30 18:43:53.430] [info] App checking version: 0.6.15 -> 0.6.15, false
[2020-03-30 18:43:53.470] [info] App args []
[2020-03-30 18:43:53.472] [info] App served false
[2020-03-30 18:43:53.837] [error] An unexpected error occured while registering iohook {
  constructor: 'Error',
  stack: 'Error: The specified module could not be found.\r\n' +
    '\\\\?\\C:\\Program Files\\poe-overlay\\resources\\app.asar.unpacked\\node_modules\\iohook\\builds\\electron-v76-win32-x64\\build\\Release\\iohook.node\n' +
    '    at process.func (electron/js2c/asar.js:140:31)\n' +
    '    at process.func [as dlopen] (electron/js2c/asar.js:140:31)\n' +
    '    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)\n' +
    '    at Object.func (electron/js2c/asar.js:140:31)\n' +
    '    at Object.func [as .node] (electron/js2c/asar.js:149:18)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:816:32)\n' +
    '    at Module._load (internal/modules/cjs/loader.js:728:14)\n' +
    '    at Module._load (electron/js2c/asar.js:717:26)\n' +
    '    at Function.Module._load (electron/js2c/asar.js:717:26)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:853:19)'
}
[2020-03-30 18:45:47.528] [info] App starting...
[2020-03-30 18:45:47.533] [info] App checking animation flag: false.
[2020-03-30 18:45:47.534] [info] App checking keyboard flag: false.
[2020-03-30 18:45:47.536] [info] App checking version: 0.6.15 -> 0.6.15, false
[2020-03-30 18:45:47.562] [info] App args []
[2020-03-30 18:45:47.564] [info] App served false
[2020-03-30 18:45:47.916] [error] An unexpected error occured while registering iohook {
  constructor: 'Error',
  stack: 'Error: The specified module could not be found.\r\n' +
    '\\\\?\\C:\\Program Files\\poe-overlay\\resources\\app.asar.unpacked\\node_modules\\iohook\\builds\\electron-v76-win32-x64\\build\\Release\\iohook.node\n' +
    '    at process.func (electron/js2c/asar.js:140:31)\n' +
    '    at process.func [as dlopen] (electron/js2c/asar.js:140:31)\n' +
    '    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)\n' +
    '    at Object.func (electron/js2c/asar.js:140:31)\n' +
    '    at Object.func [as .node] (electron/js2c/asar.js:149:18)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:816:32)\n' +
    '    at Module._load (internal/modules/cjs/loader.js:728:14)\n' +
    '    at Module._load (electron/js2c/asar.js:717:26)\n' +
    '    at Function.Module._load (electron/js2c/asar.js:717:26)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:853:19)'
}
[2020-03-30 18:47:58.721] [info] App starting...
[2020-03-30 18:47:58.732] [info] App checking animation flag: false.
[2020-03-30 18:47:58.739] [info] App checking keyboard flag: false.
[2020-03-30 18:47:58.746] [info] App checking version: 0.6.15 -> 0.6.15, false
[2020-03-30 18:47:58.780] [info] App args []
[2020-03-30 18:47:58.788] [info] App served false
[2020-03-30 18:47:59.164] [error] An unexpected error occured while registering iohook {
  constructor: 'Error',
  stack: 'Error: The specified module could not be found.\r\n' +
    '\\\\?\\C:\\Users\\Asus\\AppData\\Local\\Temp\\1ZiBKQ743az7jyId5LzUMf7yKDO\\resources\\app.asar.unpacked\\node_modules\\iohook\\builds\\electron-v76-win32-x64\\build\\Release\\iohook.node\n' +
    '    at process.func (electron/js2c/asar.js:140:31)\n' +
    '    at process.func [as dlopen] (electron/js2c/asar.js:140:31)\n' +
    '    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)\n' +
    '    at Object.func (electron/js2c/asar.js:140:31)\n' +
    '    at Object.func [as .node] (electron/js2c/asar.js:149:18)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:816:32)\n' +
    '    at Module._load (internal/modules/cjs/loader.js:728:14)\n' +
    '    at Module._load (electron/js2c/asar.js:717:26)\n' +
    '    at Function.Module._load (electron/js2c/asar.js:717:26)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:853:19)'
}

**Comment by Kyusung4698** [comment]
## 0.6.18 (2020-04-08)

- update run iohook only if required (stash navigation)

iohook is now no longer required to run the overlay. The only feature that relies on this module is the stash navigation (Ctrl + Scroll). This has been disabled by default. Please let me know if this fixes your issue.
