### ISSUE TITLE
Evaluate is looking up uniques when the item being evaluated is just magic

### ISSUE THREAD

**Issue by joe7dust** [Kyusung4698/PoE-Overlay#477]
I don't know if this is because of the new version, but I've been using for months without ever noticing this problem until I just finally updated recently... -.-

It is devastating for looking at Quicksilver flasks with Adrenaline suffix which is quite expensive/valuable for what it is, because you're going to get a bunch of cheapo 1c or less Rotgut on the results.

One of the options on evaluate should be related to item rarity to fix this.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Will be fixed with the new version. If i recall correctly the "nonunique" filter was not available at the start of this tool. So thanks for the heads up! 🚀

**Comment by Kyusung4698** [comment]
## 0.6.14 (2020-03-26)

- add nonunique rarity support (#477)

**Comment by joe7dust** [comment]
I'm not sure this got implemented the way it should have. If we are searching on a magic item it should probably only look at magic items, there could be a toggle icon on the search window for this or in options.

It works fine for the flask example since there are no rares, but for other magic items not so much.
