### ISSUE TITLE
0.4.2 - Rare Item search - only unidentified items are found.

### ISSUE THREAD

**Issue by Arkanion** [Kyusung4698/PoE-Overlay#48]
Hey,

the new Update 0.4.2 bricks the item search for rare's.
The BaseType is pasted as text into the search bar and not actually as a item base type, this results in a problem where only unidentified items are actually searched for.

**Comment by Kyusung4698** [comment]
Can you share an example rare? (CTRL + C while hovering)

**Comment by Evilinex** [comment]
+++ smt broken

**Comment by Arkanion** [comment]
Steps to reproduce: 
Use any rare for search, as soon as you select any mod the search is empty.
If you open the internal browser and manually select the Item base-type in the search bar (e.g. "Two-Toned Boots" in this example) the search suddenly has results. 

Example rare:
```
Rarity: Rare
Rune League
Two-Toned Boots
--------
Quality: +30% (augmented)
Armour: 164 (augmented)
Evasion Rating: 164 (augmented)
--------
Requirements:
Level: 70
Str: 155
Dex: 68
Int: 73
--------
Sockets: R-B-R-R 
--------
Item Level: 87
--------
14% reduced Mana Cost of Skills if you've been Hit Recently
--------
+12% to Fire and Cold Resistances (implicit)
--------
+18 to Dexterity
+66 to maximum Life
You have Tailwind if you have dealt a Critical Strike Recently
Can have up to 3 Crafted Modifiers (crafted)
20% increased Movement Speed (crafted)
Cannot be Chilled (crafted)
Cannot be Frozen (crafted)
--------
Redeemer Item
Hunter Item

```

**Comment by Kyusung4698** [comment]
Thank you. I'm working on fix right now. Probably ~15min.

**Comment by Kyusung4698** [comment]
0.4.3 is now available. Please let me know if it's fixed!

**Comment by Evilinex** [comment]
now work =)
