### ISSUE TITLE
Search is not finding all the mods

### ISSUE THREAD

**Issue by RockyBalboaIsOnGithub** [Kyusung4698/PoE-Overlay#480]
Hi! Im new to this plz dont hate ^^

# 🐞 bug report
**Describe the bug**
When searching for an item's price only a few mods are searched (3 or 4) when the item has 5-6 mods. Thoses missing mods have a big impact on the value of the item. So it renders the overlay unusable. I tried rebooting and reinstalling i also reset the options... nothing worked. Am I missing something?

**To Reproduce**
CTRL+D

**Expected behavior**
Search should work for all the item mods

**Screenshots**
I will provide one if you want

**Comment by RockyBalboaIsOnGithub** [comment]
![Untitled](https://user-images.githubusercontent.com/62707702/77660658-fd3db280-6f4f-11ea-9f13-27e040c87a02.png)

its missing important mods like movement speed but it will search for 5 armour? ....

**Comment by Carrybag1** [comment]
you change the settings / click what mods you want to search.

**Comment by RockyBalboaIsOnGithub** [comment]
That dosnt seem to work.

Im talking about the blue mods showed in the pop-up. I was able to see all the mods yesterday. Didnt change any setting and today im only able to see 3 or sometimes 4.

If i add the mods in the settings, it adds them under the blue mods which is kinda irrelevant because ill now have a crazy list of 50+ mods....

Even on youtube, its not showing like this? whats going on?

**Comment by Kyusung4698** [comment]
Most stats are converted into pseudo mods (the greyish mods). Please see the screenshot below.

![image](https://user-images.githubusercontent.com/38520678/77702111-0cf0e180-6fb8-11ea-8fc1-a80fb38c774e.png)
