### ISSUE TITLE
Blight map ctrl + D search as normal map

### ISSUE THREAD

**Issue by s1cked05** [Kyusung4698/PoE-Overlay#483]
# 🐞 bug report
**Describe the bug**
Option ctrl+D doesn't see that map is blight, it search only for normal map without blight prefix.

**To Reproduce**
1. Use ctrl+D on blighted map

**Expected behavior**
1. Search for blighted version of map instead normal.

## 🌍  Your Environment

- OS: . Win10 x64
- Version:
- PoE: Steam English

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This is a duplicate of #216.
