### ISSUE TITLE
When alt tabing out of the game, taskbar doesnt show

### ISSUE THREAD

**Issue by fagitomania** [Kyusung4698/PoE-Overlay#485]
# 🐞 bug report

**Describe the bug**

This started possibly after the latest nvidia driver update. If i alt tab out of the game, the taskbar doesnt display and all i can see is the poe bottom part of the screen. If i close poe overlay the issue goes away
Edit: Seems to happen with mercury trade as well although not 100% of the time.

**To Reproduce**

**Expected behavior**

**Screenshots**

https://prnt.sc/rni9hh

## 🌍  Your Environment

- OS:  Win10 x64
- Version:  latest
- PoE:  3.10.1 standalone x64

**Comment by eunsoori** [comment]
same problem after update 0.6.14

**Comment by spluhvag** [comment]
Same, and if I alt tab into my browser and press Ctrl+t to open another window poe-overlay gives me the "clipboard empty. you may need to start poe.....etc" instead of opening a new browser tab

**Comment by Carmonaaa** [comment]
Same happens to me.

**Comment by Vindexus** [comment]
Same.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. It'll be fixed with the next version. Thank you for your patience.

**Comment by Kyusung4698** [comment]
## 0.6.15 (2020-03-27)

- fix poe overlay does not recognize if poe is no longer active (#485, #486)
