### ISSUE TITLE
Keybinds are system wide

### ISSUE THREAD

**Issue by orcasauce** [Kyusung4698/PoE-Overlay#486]
# 🐞 bug report

**Describe the bug**

The default hotkeyfor "Evaluate Translate Settings" conflicts with Chrome's new tab hotkey. PoE-Overlay should release hotkeys if Path of Exile is not focused to allow other applications to receive these hotkeys.

Additionally, it does not appear possible to unbind a default hotkey. For features that won't be used some junk hotkey must be used, reducing the total number of available hotkeys for other functions. This may seem like a non-issue, but the number of times I've accidentally activated nVidia recording for accidentally bumping into its junk hotkey is too damn high.

**To Reproduce**

Use PoE-Overlay bound hotkeys in other applications.

**Expected behavior**

Other application should receive the key event.

## 🌍  Your Environment

- OS: Windows 10 x64
- Version: 0.6.14
- PoE: release tags/3.10.1 (standalone)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This is related to #485 . A fix will be provided with the next version.

**Comment by Kyusung4698** [comment]
## 0.6.15 (2020-03-27)

- fix poe overlay does not recognize if poe is no longer active (#485, #486)
