### ISSUE TITLE
Overlay window obscures active window/process

### ISSUE THREAD

**Issue by orcasauce** [Kyusung4698/PoE-Overlay#487]
# 🐞 bug report

**Describe the bug**

Once the PoE-Overlay settings window has been opened applications that monitor the active window's process no longer detect the correct process name. This prevents applications like Razer Synapse and Corsair's iCue from swapping to process bound profiles when Path of Exile becomes focused.

**To Reproduce**

Install an application that activates profiles based on the active window, such as iCue. Setup a default profile and a profile to be selected when Path of Exile becomes focused. Observer the automatic swapping when the game client is activated. Open PoE-Overlay. Observe the profile still swaps. From the tool tray open the PoE-Overlay settings window, change nothing, and close it by pressing "save". Observe the Path of Exile profile is no longer automatically activated when focusing the game client.

**Expected behavior**

Active window should not be obscured by PoE-Overlay to other processes. 

## 🌍  Your Environment

- OS: Windows 10 x64
- Version: 0.6.14
- PoE: Standalone 3.10.1

**Comment by orcasauce** [comment]
Running the app with "Keyboard support" also causes this without the need to open the settings window.

**Comment by Kyusung4698** [comment]
> Hi, thanks for creating an issue. The new update 0.6.11 introduced keyboard support. In order to be able to support this i had to change my main window to be [focusable](https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions).
> 
> I'll provide a way of disabling this in the next version. Please keep in mind that this will also disable the keyboard support. There is no way to handle keyboard input without the (external) application having focus and therefore removing the focus of PoE. This is only possible if my application is injected into PoE - which is a planned feature but will take time to develop and get approved by GGG.
> 
> In the meantime i hope i can develop a way of only losing the focus once the dialog is open but this will also take some time because some refactoring is required.
> 
> Thanks again for giving me this important input!
> 
> Best regards

Hi, thanks for creating an issue. Keyboard Support is experimental and does currently not support ICuE. Please see the explanation above #460.

Also to follow up there is currently a bug which leaves the PoE Overlay active even if PoE is not the active window. This will be fixed with the next version. See #486, #485. Thank you for your patience.

**Comment by orcasauce** [comment]
This was not fixed by 0.6.15. Opening the settings window still breaks profile switching with iCue.

**Comment by Kyusung4698** [comment]
> This was not fixed by 0.6.15. Opening the settings window still breaks profile switching with iCue.

Yes, because the settings window requires focus in order to capture hotkeys.

**Comment by orcasauce** [comment]
Closing the window should release the focus though. Even after clicking save/cancel iCue is unable to detect window changes for automatic profile swapping.
