### ISSUE TITLE
Pressing Spacebar closes the in-game browser

### ISSUE THREAD

**Issue by Decoder9** [Kyusung4698/PoE-Overlay#488]
# 🐞 bug report

**Describe the bug**
While the in-game browser is in focus, I press Spacebar and the browser closes.

After pressing Ctrl+D on an item, I go to add a stat filter and when writing the

**To Reproduce**
1. Press Ctrl+D on an item.
2. Click the chaos orb that pops up the in-game browser .
3. Press Spacebar

**Expected behavior**
The in-game browser closes

**Screenshots**
N/A

## 🌍  Your Environment

- OS: Win10 x64 
- Version: 10.0.18363.720
- PoE: Steam 3.10.1

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. There is currently a bug which leaves the PoE Overlay active even if PoE is not the active window. This will be fixed with the next version. See #486, #485. Thank you for your patience.
