### ISSUE TITLE
Cant set price

### ISSUE THREAD

**Issue by Ambros1a** [Kyusung4698/PoE-Overlay#489]
Hi, 
when i want to set a price. i press ctrl d open the item and i click on as an example 1chaos on the graph or the listing.

Then he wont set the instead he opens the chat (pressing enter)

How to fix this ?

**Comment by ITesserakt** [comment]
Hello! It seems, that you need a premium tab to set prices on items. 
If @Kyusung4698 don't mind, I can make module for trading from any tab (via forum)

**Comment by Kyusung4698** [comment]
> Hello! It seems, that you need a premium tab to set prices on items.

That's true. Only on premium tab the item has a extra menu to set the price. As this does not exist on none premium tabs the enter to set the price opens the chat instead.

> If @Kyusung4698 don't mind, I can make module for trading from any tab (via forum).
> Same as [Acquisition](github.com/xyzz/acquisition/), but using features of poe-overlay

That'd be awesome. If never used the forum tho. Could you explain a bit further how this would work? Thanks!

**Comment by ITesserakt** [comment]
> Could you explain a bit further how this would work? Thanks!  
- Firstly, we should know POESESSID - a token to login from the user's account. 
- Secondly, we should know an id of a forum thread in the [trading part](https://www.pathofexile.com/forum/view-forum/standard-trading-shops). 
This is all requirements. 
For all requests, POESESSID should be used as a cookie. We edit thread, URL of which will be like this: https://ru.pathofexile.com/forum/edit-thread/{id}/, forming list of items as [linkItem location="Stash name" league="..." x="..." y="..."]
