### ISSUE TITLE
The app sends input event even if the game window in backgroud

### ISSUE THREAD

**Issue by kirillp** [Kyusung4698/PoE-Overlay#492]
Its quite trivial to check that the game window is in foreground 

[GetForegroundWindow](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getforegroundwindow)

findWindowEx(0, 0, "POEWindowClass", 0)

if (getForegroundWindow() == window) sendInputs(...)

so that the aplication stop sending to other apps.

Poe trade macro does the job well.

**Comment by Kyusung4698** [comment]
Duplicate of #486
