### ISSUE TITLE
Settings under Map does not apply

### ISSUE THREAD

**Issue by Ripchip93** [Kyusung4698/PoE-Overlay#496]
# 🐞 bug report

**Describe the bug**

When i try to select a specific Stat under the Map region like "Players have no Life or Mana regeneration" and then check the box to apply it and press save it dont regonize it.
After open the Map region again for checking it the box is empty.
In the game nothing appear to the maps like it should.
A friend of mine have exact the same issue

## 🌍  Your Environment

- OS: Windows 10 x64
- Version:  latest updated from today 27.03.20
- PoE:  3.10.1 Steam english

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Please see the following entry at the wiki:
https://github.com/Kyusung4698/PoE-Overlay/wiki/Map#stat-warnings
