### ISSUE TITLE
Mod: Cannot be stunned

### ISSUE THREAD

**Issue by Z0ld3n** [Kyusung4698/PoE-Overlay#498]
# 🛸 Item modifier report

**Current item modifier**
 
%chance to avoid being stunned

**Expected item modifier**

Cannot be stunned

**Copied item data**
```
Rarity: Unique
Eye of Chayula
Onyx Amulet
--------
Requirements:
Level: 20
--------
Item Level: 85
--------
+12 to all Attributes (implicit)
--------
20% reduced maximum Life
30% increased Rarity of Items found
Cannot be Stunned
--------
Never blinking, always watching.

This item can be transformed with a Blessing of Chayula

```

- Version:   0.6.15
- PoE:  Steam 3.10.1b English

**Comment by FeralRage7** [comment]
@Kyusung4698 Eye of Chayula is still not parsing correctly and I think it has to do with the **Cannot Be Stunned** mod. Once I unclick that, it matches the searched number of items that the official trade site returns in the browser.
![chayula with stunned](https://user-images.githubusercontent.com/61394919/78689136-d87c0000-78aa-11ea-9064-118dd89e9c45.png)
![chayula without stunned](https://user-images.githubusercontent.com/61394919/78689138-d9149680-78aa-11ea-95b0-5a53d5ddacd9.png)
