### ISSUE TITLE
Since 0.6.14, overlay is extremely slow while PoE has focus

### ISSUE THREAD

**Issue by goudekid** [Kyusung4698/PoE-Overlay#499]
I'm talking control+d for a lookup, the UI itself fades in slowly over the course of about 15 seconds. 
Additionally, the UI is VERY sluggish and responds very slowly to mouse events (hover, click, etc) and also takes forever to go away when dismissed with escape.
On 6.14 I was able to alt tab to put the overlay in focus which would basically make it appear instantly which was fine enough, but now with 6.15 that doesn't seem to work anymore.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Can you confirm this is still an issue with the latest version? Thanks!

**Comment by Yves-Geib** [comment]
Hi, I have a similar problem. The overlay opens up pretty quickly, but the connection to pathofexile.trade takes about 10 seconds to load, even if it's unique items. With TradeMacro it took 1 second at most for unique items. I am in PoE focus as well.
