### ISSUE TITLE
CTRL+scroll tab scrolling skips a tab

### ISSUE THREAD

**Issue by Jebroer** [Kyusung4698/PoE-Overlay#50]
Hi,

I was thrilled to see you added the CTRL+Scroll function, that was the only thing I missed so far. However, when I scroll my inventory, it skips a tab every scroll I do. So instead of going 1-2-3-4-5-6 it does 1-3-5-7 or 2-4-6-8. Setting my mouse (Logitech G502) to 'free scrolling' shows the same behaviour.

**Comment by Kyusung4698** [comment]
GGG added CTRL + Scroll through stash tabs while hovering over the stash. If you use this tool while also hovering the stash it'll skip a tab. This was meant to add the outside stash experience back.
Nonetheless I've added throttling in 0.4.3 to improve performance.

**Comment by Evilinex** [comment]
now work

**Comment by Jebroer** [comment]
I found out why it works botched, I use POE Trades Companion for easier trading, which has the same  scrolling function. When I close POE Trades Companion it works correct when hovering either stash and inventory. 
Inpatiently waiting for the release that includes trading now! ;-)

**Comment by RHBallistic** [comment]
Mine still double-tabs with no other scripts or tools running.

**Comment by SudhanshuAggarwal** [comment]
I am running 0.4.3 and seeing this issue as well.
