### ISSUE TITLE
Cant click on popup

### ISSUE THREAD

**Issue by shadowe30** [Kyusung4698/PoE-Overlay#500]
When i use ctrl+D for the popup menu i can no longer click on the bars to change how long an item was listed. I also cant select and deselect mods i want to prioritize. the only interaction i have with the menu is scrolling to change the values i can see. This bug is only present on the current versions. I am using version 0.6.5 because on this version i can use the pop up menu fully but on later versions i cannot.

- OS: Win 10 64bit
- Version: 0.6.5(works) anything later is bugged
- PoE: Steam

**Comment by thorsten-passfeld** [comment]
Not sure if this is a workaround to your problem on Windows, but for me on Linux, I currently have to alt-tab with no window in the background of POE and it will make the overlay's popup clickable for me.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Could you please confirm that this issue is still present in the latest version? Thanks!

**Comment by thorsten-passfeld** [comment]
Funny thing is, I played yesterday and could no longer click on the popup and I get lots of error messages (probably unrelated to this, but still). Apart from that, it still works. But it's now much less usable for me

**Comment by thorsten-passfeld** [comment]
I really want to be able to click on the popup again, even if I have to ALT-Tab for now. But right now it doesn't work anymore. Something must have changed in the last week or two?

**Comment by shadowe30** [comment]
For me the issue has been resolved just tested with current patch of 0.6.22 and am able to click and interact with the pop up menu fully again. Thank you @Kyusung4698 .

**Comment by Kyusung4698** [comment]
> For me the issue has been resolved just tested with current patch of 0.6.22 and am able to click and interact with the pop up menu fully again. Thank you @Kyusung4698 .

Glad it's working now. Thanks for your feedback! 👍 

> I really want to be able to click on the popup again, even if I have to ALT-Tab for now. But right now it doesn't work anymore. Something must have changed in the last week or two?

The new update will add a new setting "focusable" which needs to be disable on Linux.
