### ISSUE TITLE
Map settings aren't save

### ISSUE THREAD

**Issue by koslord** [Kyusung4698/PoE-Overlay#501]
Hi,

first a big thank you for providing PoE-Overlay.
I got an issue with the stats warnings for maps not being saved.
 - Open map settings
 - Select "Monsters reflect #% of Physical Damage"
 - Save
 - Close UI
  - Reopen UI
 - Open map settings
 - Checkbox for "Monsters reflect #% of Physical Damage" is unselected
I tried to run PoE-Overlay with and without admin rights. Didn't change a thing.
Am I missing something?

Kind regards
Thomas

**Comment by Kyusung4698** [comment]
Duplicate of #496

**Comment by koslord** [comment]
Ok, now I got it. Sorry, for being a bit slow.

**Comment by Kyusung4698** [comment]
> Ok, now I got it. Sorry, for being a bit slow.

No worries. Glad you figured it out! 🚀
