### ISSUE TITLE
Cannot search with maximum value settings

### ISSUE THREAD

**Issue by randomuser2389547924** [Kyusung4698/PoE-Overlay#502]
Hello,

Can we please have an option to NOT have maximum values, and to keep the item minimum?  It is killing searches when you input both the minimum and the maximum.

![image](https://user-images.githubusercontent.com/5048330/77823949-3e130400-70d5-11ea-8d53-a63d47edf124.png)

![image](https://user-images.githubusercontent.com/5048330/77823953-4a975c80-70d5-11ea-9af2-f59842f522d3.png)

**Comment by TgDn32** [comment]
Go into the settings under the Evaluate tab, scroll all the way to the bottom and move the slider all the way to the right:
![image](https://user-images.githubusercontent.com/61363706/77824079-3dc73880-70d6-11ea-9cb6-29f415df3b30.png)

**Comment by ribonuge** [comment]
You can also just right-click the maximum value and it will change to # symbol. This means it will search with no upper bounds.

**Comment by randomuser2389547924** [comment]
Thanks, I'll try it some more.  I thought I attempted that before, and it sets the values to 9999 on the trade site.  It was messing up some searches, but I'll test some more.

![image](https://user-images.githubusercontent.com/5048330/77824516-9946f580-70d9-11ea-812d-294c2e98d21e.png)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I'll close this issue for now. Thanks to @TgDn32 and @ribonuge 🚀
