### ISSUE TITLE
Unsearchable rare item

### ISSUE THREAD

**Issue by LongJohnDude** [Kyusung4698/PoE-Overlay#506]
# 🐞 bug report

**Describe the bug**

 
Rare return empty result even if uncheck all search options

**To Reproduce**

```
Rarity: Rare
Soul Mantle
Chain Hauberk
--------
Armour: 281
Energy Shield: 55
--------
Requirements:
Level: 66
Str: 75
Int: 75
--------
Sockets: R-B-B-R 
--------
Item Level: 83
--------
10% increased Dexterity
+118 to maximum Life
+28% to Fire Resistance
+30% to Cold Resistance
--------
Elder Item
```

**Expected behavior**

All other armor w/o any search options selected at least return... something? Like 100k in search result.

**Screenshots**

![image](https://user-images.githubusercontent.com/34474044/77840550-8132ad00-7191-11ea-946e-31d7f26f2b49.png)

BTW if open search in browser it will empty too and does not contain any suspicious superfluous or mutually exclusive settings. https://www.pathofexile.com/trade/search/Delirium/242BLkGFk
I had an idea that this is because of the name of the item, but this search input field is blank.

## 🌍  Your Environment

- OS:   Win10 x64
- Version:  0.6.15 installed
- PoE:  standalone 3.10.1/b English

**Comment by Kyusung4698** [comment]
## 0.6.16 (2020-03-31)

- fix rare armour searched with type and name instead of term (#506)
