### ISSUE TITLE
Suggestion: Don't zoom in/out while pressing ctrl + mwheelup/down on the stash tab

### ISSUE THREAD

**Issue by dennisjongebloed** [Kyusung4698/PoE-Overlay#510]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

 Frustrated when i zoom in when when not having my mouse on top of my stash/inventory

**Describe the solution you'd like**

 Don't zoom in/out while pressing ctrl + mwheelup/down on the stash tab

**Describe alternatives you've considered**

 None

**Additional context**

 Just do it like poetrade Macro.

**Comment by Kyusung4698** [comment]
Duplicate of #369
