### ISSUE TITLE
Suggestion: Do not abort search query when not toggled modifier is changed.

### ISSUE THREAD

**Issue by 766b** [Kyusung4698/PoE-Overlay#512]
Right now if search is being run and user interacts with un-toggled modifier, search is aborted and rerun. Since modifier is not toggled, then it wont affect final search results and thus search should complete. Unless user toggles modifier then it makes sense to abort and do it over.

**Comment by Kyusung4698** [comment]
## 0.6.16 (2020-03-31)

- update untoggled modifier do now not cancel the search (#512)
