### ISSUE TITLE
Compatibility issue with MercuryTrade

### ISSUE THREAD

**Issue by mwmorais** [Kyusung4698/PoE-Overlay#514]
# 🐞 bug report
MercuryTrade's "Whisper Helper" function allows a user to bind a key to hold down when clicking on a trade on the official site. On release of hotkey, it will copy and paste the trade string after bringing PoE to the foreground. 
After the latest Overlay update, it no longer brings PoE to the foreground nor pastes the copied string.

I realize this may be a bug on MercuryTrade's end, however this error never happened until latest Overlay update. 

Latest changelog has "fix poe overlay does not recognize if poe is no longer active (#485, #486)" which sounds like a culprit. Is there a way to disable this feature? 

EDIT:
I can workaround the issue by holding the "Whisper Helper" keybind, then clicking to PoE main window and releasing. 

## 🌍  Your Environment

- OS:  e.g. Win7 x64
- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Could you please confirm that this issue is still present at the latest version?

**Comment by mwmorais** [comment]
Confirmed it still is a problem. I have been avoiding it by holding my
whisper helper key from MercuryTrade, and clicking back in PoE window
before I release. Hopefully this helps.
