### ISSUE TITLE
Searching takes way longer now

### ISSUE THREAD

**Issue by joe7dust** [Kyusung4698/PoE-Overlay#515]
I'm not sure exactly what got changed but the core function of the app (evaluate) is almost unusable for me now. There's never a need to fully "fetch" thousands of entries, the site should be doing that work and then only giving up to 200 results at a time. (& This might further be trimmed down by having an option for "only check top X number of results")

Also when you already have "5,000 results" or whatever, and then you decide to check one more box, there MIGHT be a way to just trim down those results instead of having to re-fetch everything again and be as slow as an entirely new search.

I think yet another great option would be able to assign a spot for the overlay information besides center/cursor and have it ONLY go away by hitting Escape or similar key, this way if it really has to remain bog slow like it is now at least we could continue doing other things while it is working.

**Comment by joe7dust** [comment]
What is the oldest version that supports cluster jewels? I want to revert until this is fixed. Cluster jewel was the only reason I updated from 5.x, and I regret it.

**Comment by Dgc2002** [comment]
It's taking so long because PoE's API/Trade site are being slow. You can usually check the subreddit to confirm this.

**Comment by joe7dust** [comment]
I think there's more to this than "oh just the API being slow" because it wasn't an issue until I recently updated. I'll do some direct comparison tests later tonight to confirm this and post back.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. The actual workflow looks like this:

1a request search with given params
1b response with total count and a list of detail ids

2a 5x requests to fetch the detail information of the trade offers (20 per request; so **100 total**)
2b merge those responses and display information

The first version with supported cluster jewels was [0.6.5](https://github.com/Kyusung4698/PoE-Overlay/blob/master/CHANGELOG.md#065-2020-03-16)

And yes, the API was slow during the weekend. Thanks @Dgc2002 for your help! 👍
