### ISSUE TITLE
Suggestion: let us bind non-commands

### ISSUE THREAD

**Issue by RandomHero13** [Kyusung4698/PoE-Overlay#519]
hi
(i guess this is way to much in the grey area but) let us bind non-commands for example "1234" :P

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This should already be possible. The default value of `/` is overwrite-able.

**Comment by RandomHero13** [comment]
i saw that and overwrote it, but it still went into the chat and didnt simulate teh keypresses :(
