### ISSUE TITLE
Cannot evaluate

### ISSUE THREAD

**Issue by thehackedone** [Kyusung4698/PoE-Overlay#521]
The previous version was working, but for whatever reason now my hotkey for evaluate doesn't work at all.... I haven't changed anything but overlay was updated. I'm using num9 for my hotkey.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. There were some problems with the official trade website lately. Could you confirm this is still an issue for you? Cause those problems seems to be resolved.
