### ISSUE TITLE
Suggestion: Disable Debounce

### ISSUE THREAD

**Issue by foldedcorner** [Kyusung4698/PoE-Overlay#522]
**The Purpose:**
When editing an item, we don't need to search again after every edit. This is especially true when selecting and unselecting an item with many mods

**The Implementation**
Currently we can only delay the debounce by 10s. Change the time to -1 or include a checkbox to disable.

**The Consequences**
Having the ability to disable this would mean the user would need to click "Filter has been changed. Fetching again.. now?" to start another search. I don't believe any additional UI work would need to happen.

**Comment by Kyusung4698** [comment]
## 0.6.16 (2020-03-31)

- add disabled debounce time on max value (#522)

**Comment by foldedcorner** [comment]
Wow, you work fast!
