### ISSUE TITLE
Super slow load times after update

### ISSUE THREAD

**Issue by dmack152** [Kyusung4698/PoE-Overlay#526]
Everything is loading super slow for me after the recent update. Any reason for this? Program was working a lot better yesterday.

Anyway appreciate all your hard work i just switched over from the poe trade macro and this tool is very powerful as long as it loads. Thank you!

**Comment by PezeM** [comment]
It's official trading site API problem.

**Comment by dmack152** [comment]
> It's official trading site API problem.

yea it seems poe trade macro is loading a lot better using the poe.trade website. Maybe putting the option to choose between the two would be better. crazy how a 3rd party site can load better then the games website..

**Comment by dmack152** [comment]
At this point i can't even get it to load at all. Stays stuck on "loading" anyone else having issues?

**Comment by dmack152** [comment]
Seems to be back to loading amazingly fast! man i love it when it works like this. not sure what the issue was

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Pretty much the Trade API was at it's limit. GGG seems to have this resolved for now.
