### ISSUE TITLE
Tab scrolling also zooms in&out when cursor is not within inventory/stash window

### ISSUE THREAD

**Issue by patys3** [Kyusung4698/PoE-Overlay#528]
While stash tab navigating with ctrl+scroll wheel, unless the cursor is within the inventory/stash window, the camera will also zoom in and out. This does not happen in other macros I have used so far and I appreciate such functionality.

poe-overlay-0.6.16.exe (portable), latest POE on GGG launcher, Windows 10

**Comment by Kyusung4698** [comment]
Duplicate of #510
