### ISSUE TITLE
Can't choose both defense on hybrid (ev/es) armour 

### ISSUE THREAD

**Issue by LongJohnDude** [Kyusung4698/PoE-Overlay#529]
# 🐞 bug report

**Describe the bug**

 You cant select evasion on this types of armour. It # and if you manually change it on desirable value it resets value anyway 

**To Reproduce**

Just try select EV first and ES after

**Expected behavior**

```
Rarity: Rare
Fate Hide
Crypt Armour
--------
Quality: +20% (augmented)
Evasion Rating: 1228 (augmented)
Energy Shield: 298 (augmented)
--------
Requirements:
Level: 68
Dex: 82
Int: 82
--------
Sockets: G-G-G-B-B-G 
--------
Item Level: 100
--------
+46 to Intelligence
+208 to Evasion Rating
118% increased Evasion and Energy Shield
+65 to maximum Energy Shield
9% increased Stun and Block Recovery
+20% to Fire and Lightning Resistances (crafted)
```

**Screenshots**

![image](https://user-images.githubusercontent.com/34474044/78066865-64b79000-739e-11ea-8b81-b23b4e7d14a5.png)

## 🌍  Your Environment

- OS: . Win10 x64
- Version:  0.6.16 installed
- PoE:  standalone 3.10.1/b English

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I'm unable to reproduce this. Could you please provide a short gif?

**Comment by LongJohnDude** [comment]
Sure,
https://imgur.com/9T48Zp8
