### ISSUE TITLE
Improvement - Save position/borders (dimensions) of the internal browser.

### ISSUE THREAD

**Issue by Arkanion** [Kyusung4698/PoE-Overlay#53]
For me it would be a massive QoL Upgrade to have the browser dimensions and positioning beeing saved. 
As im currently running a WQHD (2560x1440) Monitor the default window is pretty small, and its even smaller on my 2nd Monitor that is running 4K Resolution.

**Comment by Kyusung4698** [comment]
Sure can be added. For now you can also use CTRL + Click to open up in the default browser.
