### ISSUE TITLE
win7 mouse scroll

### ISSUE THREAD

**Issue by divinitaz** [Kyusung4698/PoE-Overlay#531]
After update 0.6.11 the win7 scroll wheel worked fine as the patch notes suggest.
I don't exactly know which version broke it again,.. but i guess it was the one directly after that one.

Win7 mouse wheel scroll to adjust the values is not working since the mentioned update.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. For win7 you need to enable the experimental keyboard support at the tray menu.

**Comment by divinitaz** [comment]
thanks for the fast reply! i kinda feel stupid now.... :D 
now back to hoping for a fast fix on the other problems!
thanks!
