### ISSUE TITLE
An error occured while parsing the item

### ISSUE THREAD

**Issue by fagitomania** [Kyusung4698/PoE-Overlay#532]
Trade api seems to work, why we get this? Search doesnt even begin

**Comment by kurocygnus** [comment]
Apparently, this started after last update.

**Comment by fagitomania** [comment]
yep, can i downgrade?

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. GGG restarted the trade servers. Please try relaunching the application.

**Comment by fagitomania** [comment]
Lol i tried several times, now it works after relaucnh ty
