### ISSUE TITLE
Suggestion: Obtain item values before sending API request 

### ISSUE THREAD

**Issue by BradleyXVIII** [Kyusung4698/PoE-Overlay#535]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

Too many requests are being sent to the API leading to service disruption.
**Describe the solution you'd like**

Instead of sending multiple requests each time the user changes a value, send one once the user has specified the values. 

**Describe alternatives you've considered**

Adding a "Search" button in for the user to press once they are finished configuring the values they wish to send with the request.
The only issue with this would be the user having to press the button even if the item they wish to search for has no mod values.

**Additional context**

**Comment by thor-kiessling** [comment]
This is related to the debounce time. It was 5 seconds default in a previous release, and recently became .5s default. It is user configurable.  

My suggestion is to combine this feature request with a mandatory, non-configurable 5 second bounce time. This will alleviate API pressure while allowing people to lock in searches they know they want.

**Comment by BradleyXVIII** [comment]
Yeah, that sounds like a sensible solution, It would certainly reduce the amount of requests and the frequency at which they're sent enormously.

**Comment by dmack152** [comment]
> This is related to the debounce time. It was 5 seconds default in a previous release, and recently became 1.5s default. It is user configurable.
> 
> My suggestion is to combine this feature request with a mandatory, non-configurable 5 second bounce time. This will alleviate API pressure while allowing people to lock in searches they know they want.

i like this idea. Could the error occured problems be related to too many request sent at that time? I raised the debounce time so i had time to adjust the settings because otherwise it was refreshing way too fast

**Comment by ghr74** [comment]
Agree with the required search button you press after selecting mods but a mandatory 5 seconds timer seems a bit long for responsiveness for experienced players that already know which mods they'll want to lock and take maybe a second or two to select them. Being too restrictive here could lead to users migrating to another tool with less restrictions and ultimately an increase in API load.

In addition to the search button, I'd like to add the request for it to be Hotkeyable, in the old AHK-TradeMacro this was the default hotkey Alt-S ( _S_earch)

**Comment by ljere** [comment]
I agree with @ghr74 : If the overlay already has the right attributes selected after I press ctrl+d, I want it to display the results immediately, and  not wait for 5 seconds.

**Comment by ITesserakt** [comment]
You can click 'Now' button near debounce timer to show results immediately. At least this was in the release with 5-second timer by default.

**Comment by BradleyXVIII** [comment]
Right, the issue is how frequently the application sends requests to the trade API (Every time a value is changed pretty much). Another possible workaround could be 1 request when CTRL + D is pressed then a subsequent request once the user has selected ALL the mods they wish to compare. 

This wouldn't impact the speed for items with no modifiers (Currency) and would give the user enough time to provide all their input before sending another request.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This has been added with #522. Setting the debounce time to it's max value will disable the automatically re-search on change. Also please see my [response](https://github.com/Kyusung4698/PoE-Overlay/issues/538#issuecomment-607298528) here regarding the flooding.

**Comment by ghr74** [comment]
Hello, thanks for the clarification. It's good to see the issue is "technically" fixed. If you can spare the dev time, the two requests regarding this I would have:
a) When setting to max debounce, make the "skip debounce" button more prominent, or change the wording to make it a bit more clear/easy to hit.
b) Add a configurable keybind for the "skip debounce" button (at least I couldn't find one), again for easy of use with max debounce.

**Comment by BradleyXVIII** [comment]
Much appreciated, Thanks!
