### ISSUE TITLE
Scroll bug while trying to adjust item values

### ISSUE THREAD

**Issue by EverydayIsDayOne** [Kyusung4698/PoE-Overlay#536]
Currently when i try to adjust the values after price checking an item by scrolling my mouse up or down it doesnt respond at all.
Ive tried holding down Ctrl, shift alt etc and it just doesnt change the value.

Is it possible to add a feature where we can choose how we want to change the value? for example up or down arrow keys (While holding alt + arrow key it goes up/down by 1 and while holding shift up/down by 0.1).

hope this makes sense because the mouse scroll just isnt responding at all

**Comment by KingJerbear** [comment]
I am also having a similar issue. I simply get my camera POV zooming in and out but do not get any changes in the values. The scroll wheel works for switching between stash tabs though without issue (CTRL+Scroll)

**Comment by dmack152** [comment]
works for me but sometimes up will go down or down will go up. Make sure you are scrolled over the window of the text. otherwise it won't work

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. You could try the new experimental keyboard support. This needs to be enabled at the tray menu first. Certain OSs also do not support mouse input without this mode. Please let me know if this works. Thanks!

**Comment by Padde01** [comment]
Hello.

I have the same problem. I tried the experimental keyboard feature, but that didnt fix anything either.

Anyhow, i noticed that i can interact with the window for about one second by clicking in it. So then i can scroll list/chance values. After some extensive clicking it works as intended; i guess then the popup is permanently focused. It also shows me my windows bar at the bottom over poe window. But when i then discard the popup it kinda stays open (or another instance of it), and the only way to disable it is by initiating another search. 

Seems like the popup behaves as if it was behind my poe window until i click it repeatedly. Then it gets the needed focus. I have win 7 and poe is running as windowed fullscreen, one screen. Stash scroll ingame works as intended.

Great work btw.

Hope you get what i mean, sorry for bad english.

**Comment by Destrictor** [comment]
I'm having the same issue as Padde01, if I click in the overlay window, I can edit the values for a very short time (<0.5 secs), until on average after ~10 clicks when it sticks.

This is after enabling experimental keyboard support, without it no amount of clicking affects the values, and i just scroll the ingame zoom.

I'm running Windows 10 Pro version 1909.

**Comment by EverydayIsDayOne** [comment]
Hey Kyusung4698

thanks for the response i tried out the keyboard support and that did the trick for me! really happy with this app btw poe trade macro was getting very old, bad pricing and extremely slow. Will definately be supporting you and this app in the future! hope you keep at it and soon everyone will be using it

**Comment by Kyusung4698** [comment]
Hi, thanks for your feedbacks. Can you please confirm that this is still an issue with the latest version? The keyboard support feature has been integrated into the app.

**Comment by EverydayIsDayOne** [comment]
Hey Kyusung,

I havent had anymore issues recently ever since the updates everything seems to be running smoothly!

________________________________

**Comment by Kyusung4698** [comment]
> Hey Kyusung, I havent had anymore issues recently ever since the updates everything seems to be running smoothly!

Thanks for your reply! Closed.
