### ISSUE TITLE
an error occurred

### ISSUE THREAD

**Issue by neo6633** [Kyusung4698/PoE-Overlay#537]
![2020-04-01_09-23-36_poe-overlay](https://user-images.githubusercontent.com/1337267/78087201-459b1b80-73fb-11ea-9a78-d81334cce5ae.png)

version 0.6.16

im win10 and 

korean kakaoserver.

**Comment by dmack152** [comment]
yea it happens to me alot. it will be working flawlessly then nothing but error occured. Tried restarted relaunching still gettting it. it usually goes away eventually

**Comment by Borningstar** [comment]
Speculation: if poe overlay cant get through to the trade server (because it's getting hit hard) it would give this kind of error

**Comment by Kyusung4698** [comment]
> Speculation: if poe overlay cant get through to the trade server (because it's getting hit hard) it would give this kind of error

Basically this. I've adjusted the error display to include the actual reason in the next version.

**Comment by Woif1990** [comment]
Here's a weird one though, it works for me, but my spouse on the same network only gets the error. Would this be something happening on GGG's side?

**Comment by kMose** [comment]
It looks like GGG is limiting frequent searches in a small timed window on the official trade site.  I search lots of things in my drop tab in quick succession. After about 5 POE-Overlay searches I get an error. If I go to the official trade site right after I get "Failed to get next set of trade items". The "ban" started at 2:02PM EST and ended at 2:08PM EST.

It seems like the window is 5 searches in less than 8-10 seconds. If you too quickly parse items you'll be "banned" from searches on pathofexile.com/trade for about 5 minutes.

A 3-4 second cooldown between searches is enough to stop this from happening. 2 seconds triggers the "ban".

**Comment by Kyusung4698** [comment]
> Here's a weird one though, it works for me, but my spouse on the same network only gets the error. Would this be something happening on GGG's side?

The api rate is enforced by ip or account. You can try to log into your account using the internal browser this should allow you to separate your requests.

**Comment by Kyusung4698** [comment]
## 0.6.17 (2020-04-02)

- update evaluate search error display to include the actual reason (#537)

**Comment by Woif1990** [comment]
Well, updated to the new version. Still just "An error occurred".

**Comment by Kyusung4698** [comment]
> Well, updated to the new version. Still just "An error occurred".

Hi, can you please post your log. It can be found at `%appdata%/poe-overlay/logs/main.log`. This error should only happen on extreme cases. Also i assume the `An error occurred` is displayed at the bottom of the dialog. Please correct me if this is wrong.

**Comment by cgault11** [comment]
Hello! first off, LOVE the app. By far the best one of it's kind.

A few day ago i started getting this error message. I just downloaded the most recent version and the same thing is happening. Here is the log - 

[2020-04-03 20:38:16.383] [info] App starting...
[2020-04-03 20:38:16.392] [info] App checking animation flag: false.
[2020-04-03 20:38:16.393] [info] App checking keyboard flag: false.
[2020-04-03 20:38:16.394] [info] App checking version: 0.6.16 -> 0.6.17, true
[2020-04-03 20:38:16.436] [info] App args []
[2020-04-03 20:38:16.439] [info] App served false
[2020-04-03 20:38:18.044] [info] Checking for update
[2020-04-03 20:38:18.146] [info] Session cache has been cleared.
[2020-04-03 20:38:18.158] [info] Session host resolver cache has been cleared.
[2020-04-03 20:38:19.769] [info] Update for version 0.6.17 is not available (latest version: 0.6.17, downgrade is disallowed).
[2020-04-03 20:38:24.612] [info] set bounds to:  { x: 0, y: 0, width: 2560, height: 1080 }
[2020-04-03 20:38:47.407] [warn] {
  constructor: 'SyntaxError',
  stack: 'SyntaxError: Unexpected end of JSON input\n' +
    '    at JSON.parse (<anonymous>)\n' +
    '    at a.project (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:18003332)\n' +
    '    at a._tryNext (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16931268)\n' +
    '    at a._next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16931170)\n' +
    '    at a.next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919301)\n' +
    '    at a._next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919630)\n' +
    '    at a.next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919301)\n' +
    '    at a._next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:17060310)\n' +
    '    at a.next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919301)\n' +
    '    at a.notifyNext (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16931705)'
}
[2020-04-03 20:39:03.859] [warn] {
  constructor: 'SyntaxError',
  stack: 'SyntaxError: Unexpected end of JSON input\n' +
    '    at JSON.parse (<anonymous>)\n' +
    '    at a.project (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:18003332)\n' +
    '    at a._tryNext (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16931268)\n' +
    '    at a._next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16931170)\n' +
    '    at a.next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919301)\n' +
    '    at a._next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919630)\n' +
    '    at a.next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919301)\n' +
    '    at a._next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:17060310)\n' +
    '    at a.next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919301)\n' +
    '    at a.notifyNext (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16931705)'
}
[2020-04-03 20:42:16.053] [warn] {
  constructor: 'SyntaxError',
  stack: 'SyntaxError: Unexpected end of JSON input\n' +
    '    at JSON.parse (<anonymous>)\n' +
    '    at a.project (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:18003332)\n' +
    '    at a._tryNext (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16931268)\n' +
    '    at a._next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16931170)\n' +
    '    at a.next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919301)\n' +
    '    at a._next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919630)\n' +
    '    at a.next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919301)\n' +
    '    at a._next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:17060310)\n' +
    '    at a.next (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919301)\n' +
    '    at a.notifyNext (file:///C:/Users/Gault/AppData/Local/Temp/1a02NUG3BSz62PV7WMe2AkwbbKz/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16931705)'
}
[2020-04-03 20:43:18.047] [info] Checking for update
[2020-04-03 20:43:18.597] [info] Update for version 0.6.17 is not available (latest version: 0.6.17, downgrade is disallowed).

**Comment by Kyusung4698** [comment]
@cgault11 this seems related to poe.ninja. Are you able to access the website via your normal browser? I'll add some extra error handling at the next version.

**Comment by cgault11** [comment]
@Kyusung4698 Hey! Yes I am. I have the site up and use it frequently.

**Comment by Woif1990** [comment]
Sorry it took so long, but here's my spouses error log too. 

[2020-04-06 09:03:11.645] [info] App starting...
[2020-04-06 09:03:11.651] [info] App checking animation flag: false.
[2020-04-06 09:03:11.653] [info] App checking keyboard flag: false.
[2020-04-06 09:03:11.655] [info] App checking version: 0.6.17 -> 0.6.17, false
[2020-04-06 09:03:11.690] [info] App args []
[2020-04-06 09:03:11.692] [info] App served false
[2020-04-06 09:03:14.949] [info] Checking for update
[2020-04-06 09:03:15.069] [info] Session cache has been cleared.
[2020-04-06 09:03:15.270] [info] Session host resolver cache has been cleared.
[2020-04-06 09:03:18.054] [info] Update for version 0.6.17 is not available (latest version: 0.6.17, downgrade is disallowed).
[2020-04-06 09:03:18.828] [info] set bounds to:  { x: 0, y: 0, width: 1920, height: 1080 }
[2020-04-06 09:03:20.904] [warn] {
  constructor: 'SyntaxError',
  stack: 'SyntaxError: Unexpected end of JSON input\n' +
    '    at JSON.parse (<anonymous>)\n' +
    '    at a.project (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:18003332)\n' +
    '    at a._tryNext (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16931268)\n' +
    '    at a._next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16931170)\n' +
    '    at a.next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919301)\n' +
    '    at a._next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919630)\n' +
    '    at a.next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919301)\n' +
    '    at a._next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:17060310)\n' +
    '    at a.next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919301)\n' +
    '    at a.notifyNext (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16931705)'
}

Looks like it may be the same poe.ninja error. 

They can access poe.ninja too just fine.
