### ISSUE TITLE
Suggestion: Add a search button

### ISSUE THREAD

**Issue by ljere** [Kyusung4698/PoE-Overlay#538]
EDIT: The issue was alredy identified in the: https://github.com/Kyusung4698/PoE-Overlay/issues/535#issue-591495674

POE-Overlay is flooding the official trade site with useless search  requests. Each time someone presses CTRL-D a search query is sent. On each mouse  scroll (to change the attribute value) a search request is sent, each time one changes anything in the item overlay, a query is sent.

Instead of flooding the poe servers  on each user change, add a submit button!

official GGG note https://www.pathofexile.com/forum/view-thread/2817139:

> Our Trade API is currently under very high load, and a lot of this load appears to be due to third-party programs that are not respecting reasonable rate-limits. In addition to our ongoing work on Trade API performance, we are also temporarily rate-limiting or blocking programs that are spamming our API with too many requests too quickly. This should provide better performance for users making a reasonable number of requests.

> Our rate-limit rules should be considered flexible and will be tweaked to maintain service reliability. If your tool is not working, make sure you're running the latest version and if you're a tool developer, implement backoffs when you receive an unsuccessful response.

**Comment by oddalicious** [comment]
Also to note that you could just wait a couple seconds per attribute change in case they make rapid changes.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I've added certain countermeasures in the latest versions to make sure my tool is not flooding the trade api with requests. 

1. a configurable debounce time. this can be changed at the evaluate settings menu. it's basically the delay after a user changed a mod prior sending a new requests. It's default value is 1.5s which is quite reasonable. **also you can set it to it's max value and you'll never send a request automatically (like a search button)**
2. a configurable fetch item count. the value was 100 prior my latest update and hitted the api rate limits after GGG lowered them. therefore i've lowered the item count to 30 which met the latest api rate limits.
3. a "backoff" strategy after getting a response with status 429 (rate limit reached). resulting in retrying the request after a certain amount of delay.
