### ISSUE TITLE
With new 0.6.16 update no longer able to use with different titled POE window.

### ISSUE THREAD

**Issue by acidreian666** [Kyusung4698/PoE-Overlay#539]
Long story short 
I have to use 2 separate internet connections to play poe which i have been for years.
I use this program to force POE to only connect through my wifi
https://github.com/falahati/NetworkAdapterSelector

Sense the latest update 0.6.16 I'm unable to keep POE.overlay on top of the poe window and function.

Previously I would start Overlay without GPU using batch file as I have a Gsync monitor on my Alienware laptop thats not compatible.

Once started I would inject the DLL that forces poe to connect to wifi using the program listed above.
The overlay would normally stay on top of the poe window and function perfect.

Now the overlay disappears because somewhere in the latest code you have added a feature were it continuously searching for the " Pathofexile " window name <--- now that mines shows 
"Pathofexile <---> 192.x.x.x" because of the program I'm required to do the overlay is hidden as if poe is closed or not running.

Can you either add a feature to enter the poe window name or allow a simple force overlay to stay active even when closing poe? 
I would continue using the older version of overlay but this morning it gave me errors while searching items or i would have never updated.

## 🌍  Your Environment

- OS: . Win10 x64
- Version: 0.6.16 
- PoE: Regular 3.10.1

**Comment by acidreian666** [comment]
would like to know if this was possible?

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I'll add an exception for "Path of Exile <---> " in the next version.

**Comment by Kyusung4698** [comment]
## 0.6.23 (2020-04-18)

- add alternative poe titles support (#539)
