### ISSUE TITLE
Improvement - Mod value ranges and Socket/Link settings.

### ISSUE THREAD

**Issue by Arkanion** [Kyusung4698/PoE-Overlay#54]
It would be a big upgrade for the stats system if you could set the range of mod values that are beeing searched for and not the current stat value as a fixed minimum.
Also it would be a bonus if you can just search for the mod, without its value, this is helpful for specific mods like "X Curse on Hit" or "#% chance to get Elusive on Critical Strike"

And finally, i would like to see a option in the settings if links,sockets or item level should be selected automatically or not.

**Comment by Kyusung4698** [comment]
Added with [0.5.0](https://github.com/Kyusung4698/PoE-Overlay/releases/tag/0.5.0). Even with the bonus ;)
![item_filter_0 5 0](https://user-images.githubusercontent.com/38520678/72469985-84e4a380-37e0-11ea-9399-67338a210484.jpg)

> And finally, i would like to see a option in the settings if links,sockets or item level should be selected automatically or not

Can be toggled off in the settings. Also with [0.5.0](https://github.com/Kyusung4698/PoE-Overlay/releases/tag/0.5.0) you can fast select with `Shift + Click`
![image](https://user-images.githubusercontent.com/38520678/72470262-c5442180-37e0-11ea-88cb-272fa97155d9.png)
