### ISSUE TITLE
Win 8.1

### ISSUE THREAD

**Issue by abdukulov-talgat** [Kyusung4698/PoE-Overlay#541]
Will you planning support it?
Atm doesnt work scrolling (adjusting mod values)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. A user of my patrons uses Win 8.1 with the latest version and have no issues. Could you please confirm this issue is still present at the latest version? Thanks!

**Comment by abdukulov-talgat** [comment]
Yes, after update it's working fine. Thank you. Regards

сб, 18 апр. 2020 г. в 14:02, Nicklas <notifications@github.com>:

**Comment by Kyusung4698** [comment]
> Yes, after update it's working fine. Thank you. Regards
Awesome! Closed.
