### ISSUE TITLE
unable to select a league and constanly saying that the new update is avaible but its unable to update

### ISSUE THREAD

**Issue by fislysandi** [Kyusung4698/PoE-Overlay#542]
# 🐞 bug report

**Describe the bug**
the app will not update and will not pricecheck items generally dont work.it tries to downgrade itself
![Screenshot_105](https://user-images.githubusercontent.com/45166203/78165177-9b031700-7453-11ea-9a6d-f35d51b3554f.png)

**To Reproduce**
idk its just stopped working i spotted in my uninnstaller that this app was installed twice like the 0.6.4 and 0.6.1 version

**Expected behavior**
i expected the app to work properly and able to select a league and pricecheck items.and update

**Screenshots**
![Screenshot_104](https://user-images.githubusercontent.com/45166203/78163969-bec55d80-7451-11ea-9641-08af4022c4b9.png)

## 🌍  Your Environment

- OS: win10 proffesional x64
- Version: e.g. 0.6.4 portable
Steam 3.10.0/e English
heres the log file:
[main.log](https://github.com/Kyusung4698/PoE-Overlay/files/4416581/main.log)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Skimming though the log it seems like there were some network issue which caused this behavior. Could you please confirm this is still an issue with the latest version? Thanks!
