### ISSUE TITLE
Suggestion: Add poeprices.info for rare items

### ISSUE THREAD

**Issue by JusKillmeQik** [Kyusung4698/PoE-Overlay#544]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**
I brought this up in other issues but they were all closed so I wanted to highlight my concern in it's own tracked way. Rare items are hard to price if you don't know which mods are valuable at what ranges. Poeprices has a very simple api that allows for an estimated price of your rare item to determine if further research is necessary. I would like if for rare item searches an estimated price was shown near the bottom of the ui.

**Describe the solution you'd like**
In a perfect world clicking on this estimate would show you the confidence level and which affixes affected the price. But even with a rough estimate it would be easier to determine if an item is worth selling. The estimate can be anywhere in the ui, as long as it's clearly different from the trade search results.

**Describe alternatives you've considered**
TradeMacro uses poeprices so I can use that as an alternative for now, but I'd like to stop running it as well as this program. The only other alternative right now while using your program is to guess which affixes are important and hope the range returns similar results that are currently available. Poeprices uses historical information and wide ranges to guess an item's worth range with a level of confidence that no other program does

**Additional context**
I'd like to add more details to make this happen quickly. I know there are a lot of Issues right now with the trade site changing, but this is the last feature I need to make the switch completely to this tool, so I'll do what I can to help push it along.

All you need to do is take the exact item text:

```
Rarity: Rare
Armageddon Dash
Crusader Boots
--------
Quality: +20% (augmented)
Armour: 174 (augmented)
Energy Shield: 42 (augmented)
--------
Requirements:
Level: 70
Str: 62
Dex: 111
Int: 155
--------
Sockets: G-B-B-B 
--------
Item Level: 86
--------
+39 to Strength
+24 to Armour
+11 to maximum Energy Shield
+45 to maximum Mana
35% increased Movement Speed
+19% to Fire and Cold Resistances (crafted)
```

And Base64 Encode it:

UmFyaXR5OiBSYXJlCkFybWFnZWRkb24gRGFzaApDcnVzYWRlciBCb290cwotLS0tLS0tLQpRdWFsaXR5OiArMjAlIChhdWdtZW50ZWQpCkFybW91cjogMTc0IChhdWdt
ZW50ZWQpCkVuZXJneSBTaGllbGQ6IDQyIChhdWdtZW50ZWQpCi0tLS0tLS0tClJlcXVpcmVtZW50czoKTGV2ZWw6IDcwClN0cjogNjIKRGV4OiAxMTEKSW50OiAxNTUK
LS0tLS0tLS0KU29ja2V0czogRy1CLUItQiAKLS0tLS0tLS0KSXRlbSBMZXZlbDogODYKLS0tLS0tLS0KKzM5IHRvIFN0cmVuZ3RoCisyNCB0byBBcm1vdXIKKzExIHRv
IG1heGltdW0gRW5lcmd5IFNoaWVsZAorNDUgdG8gbWF4aW11bSBNYW5hCjM1JSBpbmNyZWFzZWQgTW92ZW1lbnQgU3BlZWQKKzE5JSB0byBGaXJlIGFuZCBDb2xkIFJl
c2lzdGFuY2VzIChjcmFmdGVkKQo=

Then you just call:

https://www.poeprices.info/api?l=Delirium&i=

with the encoded data at the end. The result is the following:

```
{"min": 126.80000000000001, "max": 190.2, "currency": "chaos", "warning_msg": "", "error": 0, "pred_explanation": [["#% increased Movement Speed", 0.4779926914048482], ["+# to Armour", 0.012649660313265457], ["+# to maximum Energy Shield", -0.006291516611199043], ["(pseudo) (total) +#% to Fire Resistance", -0.012760051650222898], ["(pseudo) (total) +# to maximum Mana", -0.015129163944862535], ["(pseudo) (total) +#% to Cold Resistance", -0.022618440656696232], ["(pseudo) (total) +# to maximum Life", -0.21180212605299517], ["(pseudo) +#% total Elemental Resistance", -0.24075634936591048]], "pred_confidence_score": 74.22185352597826, "error_msg": ""}
```

If all you had was the min/max and currency from the first result that would be a huge help. The API does take a few seconds to call, so definitely make it asynchronous to the other information appearing.

**Comment by JusKillmeQik** [comment]
It looks like you already have a section in the UI for poe.ninja information. Since rare items will never have poe.ninja data, you could reuse that section to return the estimate.

Thank you!

**Comment by TheOne320** [comment]
You could also look at the awakened-poe-trade source code in 

> awakened-poe-trade/src/web/price-check/price-prediction/poeprices.ts

there on line 28 the prediction is implemented and it shouldn't be too hard to port it. I think the UI would be more work.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I'm sorry for not answering to this topic earlier. My app supports all available client languages - poeprices.info does not. Therefor i'd need to translate the copied item info into English which i'm currently not 100% capable of. I'll implement an English only version soon.

**Comment by TheOne320** [comment]
From my understanding when the user uses "Ctrl-C" on an item the item info is copied into the clipboard. This information is always in English, even in the different regional versions.

**Comment by Kyusung4698** [comment]
> From my understanding when the user uses "Ctrl-C" on an item the item info is copied into the clipboard. This information is always in English, even in the different regional versions.

No, it's not. The game only loads the current selected language. Therefore all translations are in this language.

**Comment by TheOne320** [comment]
You are right. I just switched to German and it was all in German. I was sure that in the past it was different. Sorry.

**Comment by Kyusung4698** [comment]
## 0.6.22 (2020-04-13)

- add poeprices.info price prediction (#544)

![image](https://user-images.githubusercontent.com/38520678/79132207-2f517000-7daa-11ea-9168-84ff9447f201.png)
