### ISSUE TITLE
Random Crashes of Poe Overlay

### ISSUE THREAD

**Issue by azarel41** [Kyusung4698/PoE-Overlay#546]
hi i just like to feedback that i found out that poe overlay has been causing multiple crashes of my poe instance. i was previously experiencing 1 crash per map that i run (or even teleporting from safe house to town etc or alt - tabbing to check something on a browser) and this went away after i stopped running it.

it probably happened after the prev GGG patch but ever since i stopped running poe overlay i have yet to experience a crash in 30 maps.

my details:

cpu: amd ryzen 3600
gpu: nvidia RTX2080
ram: 32gb ddr4

OS: e.g. Win10 x64
Version: e.g. 0.6.16
PoE: standalone 3.10.0/f English

**Comment by kartelusm** [comment]
I can concur, but for me crashes are always happening when using an overlay browser. Strangely, never on the trade site, at least none that I remember, but always on poedb or poe.ninja, for example.

**Comment by mhzcorp** [comment]
Are you having random crashes of PoE Overlay or Random Crashes of PoE Game? I'm having random crashes of PoE Overlay, I can detect when the programa crashes because my mouse lags and the program just closes itself. Since there is no log (or at least i can't find one) I don't know what's happening.

**Comment by OmikronGamma** [comment]
> Are you having random crashes of PoE Overlay or Random Crashes of PoE Game? I'm having random crashes of PoE Overlay, I can detect when the programa crashes because my mouse lags and the program just closes itself. Since there is no log (or at least i can't find one) I don't know what's happening.

Same issue. My mouse stops, actually whole system freezes. Im about to press reset button, but its simply poe-overlay crashed and caused whole system freeze.

**Comment by azarel41** [comment]
> 
> 
> Are you having random crashes of PoE Overlay or Random Crashes of PoE Game? I'm having random crashes of PoE Overlay, I can detect when the programa crashes because my mouse lags and the program just closes itself. Since there is no log (or at least i can't find one) I don't know what's happening.

i'm facing random crashes of POE while using POE overlay. it stopped only after i stopped running it. just to share my feedback.

**Comment by umn-anon** [comment]
I got overlay recently and ever since, my game has crashed half a dozen times at least, I think I'll just uninstall it
