### ISSUE TITLE
Control scroll/mouse scroll doesn't work at all

### ISSUE THREAD

**Issue by Jenson-co-in** [Kyusung4698/PoE-Overlay#547]
The program and videos show an option to scroll values to change them. Even with scrolling disabled in-game, the overlay doesn't scroll through any values. Not really sure if I'm doing something wrong or if the feature is broken.

**Comment by Jinxed45** [comment]
I can support this claim. Installed POE overlay for the first time a week ago and all but these scrolling features for the currency of choice or values and mods dont function. (Windows 7, MX Master Mouse with default settings).

**Comment by donj10** [comment]
I couldn't get it working either, still waiting an update on this one.
