### ISSUE TITLE
Negative value of resistance not recognized

### ISSUE THREAD

**Issue by Rohatej** [Kyusung4698/PoE-Overlay#55]
![negative res](https://user-images.githubusercontent.com/49788153/72204423-10280700-3478-11ea-8668-b1da7c98ada7.png)

**Comment by Kyusung4698** [comment]
Can you please share the Item? (CTRL + C while hovering) Thanks!

**Comment by Kyusung4698** [comment]
Could be fixed with #62 Can you check 0.4.4? Thank you!

**Comment by Rohatej** [comment]
Thread of Hope negative resistance is now detected properly
In case you stil need ctrl+c of this item

Rarity: Unique
Thread of Hope
Crimson Jewel
--------
Radius: Variable (augmented)
--------
Item Level: 86
--------
Affects Passives in Medium Ring
Passives in Radius can be Allocated without being connected to your tree
-15% to all Elemental Resistances
--------
Though we cannot touch; one thought, one wish, through centuries alone in darkness.
--------
Place into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.

**Comment by Rohatej** [comment]
Found another issue with "% reduced Intelligence" mod in Brawn jewel

Rarity: Unique
Brawn
Crimson Jewel
--------
Requirements:
Level: 48
--------
Item Level: 83
--------
You cannot be Cursed with Silence (implicit)
--------
6% increased Strength
4% increased Dexterity
13% reduced Intelligence
--------
"Take your time, make all your plans. 
Then tell me which plan
pulls my axe from your ribs."
- Barkhul, the Butcher
--------
Place into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.
--------
Corrupted

![brawn](https://user-images.githubusercontent.com/49788153/72274823-275c2580-362d-11ea-8b2a-428b09969763.png)

**Comment by Kyusung4698** [comment]
Negated mods are now supported with 0.5.1. Please report back! Thanks for reporting the issue tho 👍

**Comment by Kyusung4698** [comment]
I'll close this for now. Feel free to re-open if it's still not working.
