### ISSUE TITLE
Limit reached. Please try again later.

### ISSUE THREAD

**Issue by Brunoofr** [Kyusung4698/PoE-Overlay#551]
Every item that im trying to evaluate doesn't give me any results, instead i always get that message, and the overlay asks me to lower the fetched item count if this keep happening, which i already did, from 30 to 100.

- OS: Win10 Home x64
- Version: 0.6.17
- PoE: Steam 3.10 - English

![poe-overlay_KONCnUEHZi](https://user-images.githubusercontent.com/63024433/78302805-ef6ccc00-7511-11ea-98a5-bab37585d0cd.png)

**Comment by Brunoofr** [comment]
One thing that i noticed is that, after some time, i can evaluate normally but if i filter any of the item mods, this error comes back.

**Comment by ITesserakt** [comment]
Try to increase debounce time in `evaluate` settings. If the error still happens, wait some time (e.g. 30 minutes) and try to search again with new debounce settings.

**Comment by Brunoofr** [comment]
Already tried that, doesn't work.

**Comment by Destrictor** [comment]
Please do note that by going from 30 to 100 items you more than tripled the fetched item count.
You might want to consider putting that back (or even lower).

**Comment by Kyusung4698** [comment]
> Please do note that by going from 30 to 100 items you more than tripled the fetched item count.
> You might want to consider putting that back (or even lower).

This. Basically per 10 items a extra request is fired. The default value is 30 items which result in 1 search request + 3 detail requests. Based on the current api load the api rate is lowered dynamically by GGG. I think the lowest is following:

4 requests every 8 seconds over 10 seconds, 8 requests every 30 seconds over 1 minute (per account)
4 requests every 4 seconds over 10 seconds, 8 requests every 12 seconds over 5 minutes, 10 requests every 30 seconds over 1 hour (per IP)

as you see using a account will grant you a higher rate. you can log into your account using the internal browser. this will send the authorized requests.

**Comment by Brunoofr** [comment]
Alright, thank you guys, I logged into my account via the internal browser and im using 30 item count and it seems to work now, ill maintain at 30 for now then.
