### ISSUE TITLE
0.6.17 Mouse lags heavily on start, PoE overlay message on bottom left of PoE not appearing

### ISSUE THREAD

**Issue by lapease** [Kyusung4698/PoE-Overlay#553]
Upon starting PoE overlay, my mouse lags heavily and will make small steps instead of smooth motions for about a minute. Also, the message saying "PoE Overlay 0.6.17" that is supposed to appear at the bottom left corner of PoE is not appearing, thus i am unable to use this program. Perhaps I'm not giving it enough time? I've waited about 5 minutes

**Comment by spelworm** [comment]
For me this happens when OBS is open.

**Comment by fooey** [comment]
seems to be conflicting with Xenon like this for me

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. My app registers iohook on start in order to listen to the mousewheel event. There are some issue if multiple apps using the same iohook - freezing your pc etc. You can avoid this behavior by disabling the stash navigation the settings menu > misc.
