### ISSUE TITLE
Suggestion: Allow us to move the settings window

### ISSUE THREAD

**Issue by Chad711** [Kyusung4698/PoE-Overlay#559]
I'd like to move this window to my 2nd monitor and keep it open. However I cannot grab this window with my mouse.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Changed settings are not applied unless the `Save` button is pressed. I don't see any real use for this feature. Also this has been requested #128 but not implemented cause the current code base does not support this.

**Comment by Kyusung4698** [comment]
## 0.6.18 (2020-04-08)

- update settings dialog
  - is now an actual window which can be resized
  - has now a responsive design to support smaller viewports
  - ui language is now directly affected
  - zoom is now applied directly
