### ISSUE TITLE
Stuck at analyzing data

### ISSUE THREAD

**Issue by vadash** [Kyusung4698/PoE-Overlay#560]
Poe.ninja changed IP and now inaccessible in my country (works only with vpn). Any search gets stuck for 30+ seconds thanks to it. Is it possible to add some setting about it ?
☑Use poe.ninja

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. poe.ninja is required to convert currencies and other stuff. What do you suggest?

**Comment by vadash** [comment]
I see. Thats fine for me
