### ISSUE TITLE
 An error occurs when trying to evaluate

### ISSUE THREAD

**Issue by NieEonliv** [Kyusung4698/PoE-Overlay#561]
🐞 bug report

Describe the bug:
trying to evaluate something gives an error

This problem was originally after downloading this program. I tried to change the configuration, but the error came out statically, tried to reinstall the (old and new) versions

Expected behavior:
I expected the program to work :D

Screenshots:
![image](https://user-images.githubusercontent.com/63141394/78421216-952d5180-765e-11ea-8bcc-fd23a048e708.png)

🌍  My Environment

- OS: Win10 x64
- Version: 0.6.17 
- PoE: Steam 3.10.1c Russian

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Can you please post the application log. Can be found at `%appdata%/poe-overlay/logs/main.log`. Also this may be related to #560
