### ISSUE TITLE
Suggestion: Setting to use ~b/o instead of ~price when using quick tagging

### ISSUE THREAD

**Issue by nbanyan** [Kyusung4698/PoE-Overlay#562]
I'd like an option to use a "negotiable" price instead of an "exact" price when quick tagging since most of what I try to sell I'm willing to accept alternate currency and/or a slightly lower price (the market does change a lot).

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. A double click will set the negotiable price instead. See #191

**Comment by nbanyan** [comment]
Thank you!
