### ISSUE TITLE
An error occured

### ISSUE THREAD

**Issue by Bazeloth** [Kyusung4698/PoE-Overlay#567]
# 🐞 bug report

**Describe the bug**

I press ctrl + D to evaluate a price, but an error message occurs.

**To Reproduce**
Press ctrl + d on an item

**Expected behavior**
Currency info

**Screenshots**
![image](https://user-images.githubusercontent.com/19928782/78461646-35b95b00-76cb-11ea-99d0-21e4872e875b.png)

## 🌍  Your Environment

- OS: windows
- Version: 0.6.17 (2020-04-02) (setup exe)
- PoE: Steam 3.10.0 English

**Logs**
Its probably this JSON error (pulled from `main.log`):
`[2020-04-04 23:19:01.362] [warn] {
  constructor: 'SyntaxError',
  stack: 'SyntaxError: Unexpected end of JSON input\n' +
    '    at JSON.parse (<anonymous>)\n' +
    '    at a.project (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:18003332)\n' +
    '    at a._tryNext (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16931268)\n' +
    '    at a._next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16931170)\n' +
    '    at a.next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919301)\n' +
    '    at a._next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919630)\n' +
    '    at a.next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919301)\n' +
    '    at a._next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:17060310)\n' +
    '    at a.next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16919301)\n' +
    '    at a.notifyNext (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.ac79add26f2595fa8561.js:1:16931705)'`

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This seems to be related to poe.ninja. Are you able to visit the page in your browser?

**Comment by Bazeloth** [comment]
Yes i am:

![image](https://user-images.githubusercontent.com/19928782/78473686-e44cb280-7742-11ea-97a9-ea67374cf374.png)

**Comment by Kyusung4698** [comment]
Hi, it this still present in the latest version? Could you please give it a quick check? Thanks! 🚀

**Comment by Bazeloth** [comment]
This is 6.20:
![image](https://user-images.githubusercontent.com/19928782/79046419-224d4900-7c11-11ea-8c07-ff77da5a949d.png)

So no it isnt working.

Latest logs:

`[2020-04-11 16:25:26.275] [info] Checking for update
[2020-04-11 16:25:28.353] [info] Update for version 0.6.20 is not available (latest version: 0.6.20, downgrade is disallowed).
[2020-04-11 16:26:25.379] [warn] {
  constructor: 'TypeError',
  stack: "TypeError: Cannot read property 'lines' of null\n" +
    '    at a.project (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.79cd72f2fa558b4052b3.js:1:18010623)\n' +
    '    at a._tryNext (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.79cd72f2fa558b4052b3.js:1:16938926)\n' +
    '    at a._next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.79cd72f2fa558b4052b3.js:1:16938828)\n' +
    '    at a.next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.79cd72f2fa558b4052b3.js:1:16926959)\n' +
    '    at a._next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.79cd72f2fa558b4052b3.js:1:16927288)\n' +
    '    at a.next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.79cd72f2fa558b4052b3.js:1:16926959)\n' +
    '    at a._next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.79cd72f2fa558b4052b3.js:1:16936526)\n' +
    '    at a.next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.79cd72f2fa558b4052b3.js:1:16926959)\n' +
    '    at a._next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.79cd72f2fa558b4052b3.js:1:17067975)\n' +
    '    at a.next (file:///C:/Program%20Files/poe-overlay/resources/app.asar/dist/main.79cd72f2fa558b4052b3.js:1:16926959)'
}
`

**Comment by Bazeloth** [comment]
Ive found the issue. It was doing a request to poe.ninja:

https://poe.ninja/api/data/itemoverview?league=**Metamorph**&type=UniqueArmour&language=en

Metamorph was last league. Any idea why it chose this value over Delerium? I went to settings and saved the Delerium as my new league and it all worked again..

**Comment by Kyusung4698** [comment]
> Ive found the issue. It was doing a request to poe.ninja:
> 
> https://poe.ninja/api/data/itemoverview?league=Metamorph&type=UniqueArmour&language=en
> 
> **Metamorph** was last league. Any idea why it chose this value over Delerium? I went to settings and saved the Delerium as my new league and it all worked again..

Glad you got it working! There is a check which should prevent this from happening. I dunno why this was happening. I'll keep an eye open for the next league launch.
