### ISSUE TITLE
Price is wrong when looking for corruptions on items, see pictures below

### ISSUE THREAD

**Issue by Haroldyolo** [Kyusung4698/PoE-Overlay#57]
Overlay showing median at 40c

[https://imgur.com/a/tMB0ZuU](https://imgur.com/a/tMB0ZuU)

But actual price on site is a lot lower

[https://imgur.com/a/SJn79va](https://imgur.com/a/SJn79va)

**Comment by Kyusung4698** [comment]
Seems good for me. See: https://academy.datawrapper.de/article/136-histogram-min-max-median-mean.

**Comment by Kyusung4698** [comment]
I'll close this now. Feel free to re-open if needed.
