### ISSUE TITLE
Map Mod: Player chance to Dodge is Unlucky

### ISSUE THREAD

**Issue by neo6633** [Kyusung4698/PoE-Overlay#574]
![2020-04-05_15-38-08_poe-overlay](https://user-images.githubusercontent.com/1337267/78468542-ef5c0e80-7753-11ea-82e4-49d29f6a859b.png)

There is no option "Player chance to Dodge is Unlucky"

its important to dodge build.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. `Player chance to Dodge is Lucky` is the same mod as `Player chance to Dodge is Unlucky` - just using different values internally.

**Comment by Kyusung4698** [comment]
Uh, I just checked my stats export and this stat is indeed missing.
