### ISSUE TITLE
Oni-Goroshi Charan's Sword not recognize as an item

### ISSUE THREAD

**Issue by Dragomitch** [Kyusung4698/PoE-Overlay#575]
# 🐞 bug report

**Describe the bug**
Oni-Goroshi Charan's Sword not recognize as an item, the app error is : "Item can not be parserd. Please make sure you have the correct langage selected"

**To Reproduce**
Try to analyze/price an Oni-Goroshi sword 

**Expected behavior**
Should analyze and price the item naturally.

**Screenshots**
https://i.imgur.com/78EUuHi.jpg

## 🌍  Your Environment

- OS:  Win10 Familly x64
- Version:  10.0.18363 num 18363
- PoE:  Poe English standalone client

**Comment by Kyusung4698** [comment]
## 0.6.18 (2020-04-08)

- fix `Oni-Goroshi Charan's Sword` unable to parse (#575)
