### ISSUE TITLE
Question: How to debug the application?

### ISSUE THREAD

**Issue by JasonMarechal25** [Kyusung4698/PoE-Overlay#576]
Sorry to bother you with this but I couldn't debug the application with either Intellij IDEA or Visual studio code.

For example in Intellij:
1. I use: npm start to launch the application. (I can see the version number in the bottom left corner of PoE)
2. I start debug of the angular Application but no breakpoint is hit and in fact I get an error (Cannot read property 'getCurrentWindow' of undefined at new WindowService (http://localhost:4200/main.js:1884:32)
For VS Code:
1. Npm run start
2. Exit application
3. Start "Debug main application". Breakpoints are greyed (breakpoint ignored generated source map not found)

I've already tried a few things from the internet but to no avail :/

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Electron uses multiple processes. 1 main process which is defined in at the top level main.ts - can be debugged with the "Debug main application" profile. All other processes are renderer processes. They can only be debugged using the chrome developer tools. Those should open as an extra window after the application has started.

**Comment by JasonMarechal25** [comment]
Thanks for the answer. I had oped I could debug the angular part in an IDE I'm not a fan of debugging in chrome developer tools.
