### ISSUE TITLE
Price check hotkeys stopped working with 0.4.2

### ISSUE THREAD

**Issue by FeelsAmazingMan** [Kyusung4698/PoE-Overlay#58]
The hotkeys for price checking stopped working for me since 0.4.2(same on 0.4.3) and on 0.4.1 it still works fine. It seems to only affect price checking because the hideout and dnd hotkeys work fine.

- Windows 10 Pro 64bit 1909
- PoE does not run as admin and is not in a folder that requires admin

Edit: I have price check on Alt + D like 766b

**Comment by 766b** [comment]
I changed my modifier hotkey from `Ctrl` to `Alt`, and it stopped working as well. If I change it back to `Ctrl`+`D` then it works.

**Comment by NitriusX** [comment]
Also noticed that changing the keybind to use Alt instead did not work.

**Comment by Kyusung4698** [comment]
The ALT-Key is currently unsupported. I've used another method to capture the keybindings in order to get a passive listener mode without blocking other applications.

**Comment by Kyusung4698** [comment]
Should be fixed with 0.4.4. Let me know if it works! Thanks.

**Comment by FeelsAmazingMan** [comment]
0.4.4 works! Thanks for the quick fix
