### ISSUE TITLE
Limit Reached

### ISSUE THREAD

**Issue by MariChally** [Kyusung4698/PoE-Overlay#581]
Just started happening this evening, for any search at all it gives me the "Limit reached. Please try lowering your fetched item count" error, no matter how low I set the count. Even for items where it's only fetching 2 entries anyway. So I can't search for anything anymore.
Tried relaunching PoE and the overlay. Please let me know if there's some way to fix this.

**Comment by ITesserakt** [comment]
Hello, maybe this issue could help you: #551

**Comment by MariChally** [comment]
Thanks for the link but that doesn't help in any way. My fetch count is as low as it will go and even when it's fetching only 1 item it gives the "reached limit" error message.

**Comment by saraneth0o** [comment]
Keeps happening to me too. Is there some kind of hourly limit or something?
