### ISSUE TITLE
poe-overlay not working or not detecting my games.

### ISSUE THREAD

**Issue by 0a0w0z** [Kyusung4698/PoE-Overlay#582]
Poe-overlay not working or not detecting my game.

I run poe-overlay in admin mode then run PoE, then wait and wait, but the bottom left doesn't have anything. I can see that poe-overlay is running in task manager but they are not doing anything

![image](https://user-images.githubusercontent.com/43979492/78615536-686a7b80-78a4-11ea-874f-224b9bd476ac.png)

![image](https://user-images.githubusercontent.com/43979492/78615579-7fa96900-78a4-11ea-8932-e8860001555f.png)

- OS: Win10 x64
- Version: 0.6.17 local
- PoE: 3.10.1c directly downloaded from GGG

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. PoE Overlay checks the name of the active window and the executable name. Following names of executables are whitelisted: 
```
    'pathofexile_x64_kg.exe', 'pathofexile_kg.exe',
    'pathofexile_x64steam.exe', 'pathofexilesteam.exe',
    'pathofexile_x64.exe', 'pathofexile.exe',
```

and following window names
```
    'Path of Exile'
```

Please check those for your names. If your name is not present please post them here. Also i assume PoE runs in windowed mode?

**Comment by 0a0w0z** [comment]
The picture attached shows PoE in task manager as "**PathOfExile_x64**", I don't know if poe-overlay is case sensitive, but the capital letters in "**PathOfExile_x64**" is exactly the same as in the task manager.
![poe in task manager](https://user-images.githubusercontent.com/43979492/79755383-9c857800-834b-11ea-8c52-64e81137a945.png)

The window name is exactly "**Path of Exile**", no problem there.
![poe window](https://user-images.githubusercontent.com/43979492/79755776-38af7f00-834c-11ea-919a-aa8b78dcf53b.png)


I run the game in **Fullscreen Windowed** mostly, I have tried **windowed**, but it still doesn't work.

**Comment by Kyusung4698** [comment]
I've added some alternative names in the 0.6.24 version. Maybe this fixed this issue. If not please post the full path of your PathOfExile_64 executable. Thanks!

**Comment by z4nn486** [comment]
Sorry for jumping in but I have the same issue.

I have the steam version of path of exile, but the overlay does not working. I run the game in fullscreen mode, the overlay program is running on my computer, but does not display in game.

Any help is appreciated.

Thanks!

**Comment by 0a0w0z** [comment]
The newest update has fixed the issue for me!

Thank you very much!
