### ISSUE TITLE
Suggestion: map syndicate

### ISSUE THREAD

**Issue by igorcastroo** [Kyusung4698/PoE-Overlay#583]
include the syndicate image with the best choices

**Comment by ITesserakt** [comment]
You can bind a site with this image to keyboard shortcut using 'bookmarks' tab in the settings.

**Comment by igorcastroo** [comment]
ok, i will try, thank you very much

**Comment by Kyusung4698** [comment]
> You can bind a site with this image to keyboard shortcut using 'bookmarks' tab in the settings.

Thanks! Closed.
