### ISSUE TITLE
DPS/PhysicalDPS/ElementalDPS Min-Max Bug

### ISSUE THREAD

**Issue by igorcastroo** [Kyusung4698/PoE-Overlay#584]
the minimum and maximum damage in the search is changed

at pathofexile.com/trade it looks the same ...

![1](https://user-images.githubusercontent.com/39240321/78718754-39cac000-78f9-11ea-8f16-d638f9a98db4.png)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This will be fixed with the new version. I did not account for the `to quality` stat nor the fossil 30% craft.

**Comment by Kyusung4698** [comment]
## 0.6.18 (2020-04-08)

- fix quality higher than 20% showing a lower value as max (#584)
