### ISSUE TITLE
Game being pushed to the background

### ISSUE THREAD

**Issue by kartelusm** [Kyusung4698/PoE-Overlay#587]
After the latest 0.6.18 update, with KB support on (Windows 7) the game is being pushed to the background (windows taskbar popping up), making it unplayable.

If I turn the KB support off, it does not happen, but the overlay is then, more or less, unusable because of the inability to adjust the stat ranges.

**Comment by Fred-Vaniss** [comment]
Having a bit the same kind of bug on Windows 10

After inspecting item or opening map info, the game just lose focus, loing control of the keyboard and the game apply my low framerate setting in background.

The only workaround to stop this right now is to spam the click on the game's window

**Comment by Speedy-VonGofast** [comment]
Having a bit the same kind of bug on Windows 10

After inspecting item or opening map info, the game just lose focus, losing control of the keyboard and the game apply my low framerate setting in background.

The only workaround to stop this right now is to spam the click on the game's window

**Comment by Kessus** [comment]
What also happened to me was that the overlay window with item description re-appears after I focus on the game again. However it becomes untargetable and I am unable to close it or interact with it in any other way. The only way I found to get rid of it is to ctrl + D any item and then quickly close it with esc.

**Comment by CrayonCodeGit** [comment]
This happens especially often when I'm doing this in the stash. Unusable in the current state!

**Comment by SchmutzigerStefan** [comment]
same problems here. unusable in since the last update.

**Comment by DaLeberkasPepi** [comment]
unfortunately the same problem for me. You can easily see it by the behavior of the poe overlay version number in the bottom left. 
It is shown for a splitsecond and then its already gone again.

**Comment by LongJohnDude** [comment]
Same problem here - after each search game focus going crazy :(

**Comment by Wiella** [comment]
Same issue here, happens for me under Windows 8.1 and Windows 10.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I'm currently investigating. Sorry for the inconveniences.

**Comment by Kyusung4698** [comment]
## 0.6.19 (2020-04-10)

- fix poe overlay not visible after focus change (#587)

A timing issue caused this behavior. It should be fixed. Please let me know! Thanks

**Comment by Kyusung4698** [comment]
## 0.6.21 (2020-04-12)

- fix move poe overlay to top after focusing poe (#608)
