### ISSUE TITLE
Missing Cancel and Save buttons

### ISSUE THREAD

**Issue by Culdur** [Kyusung4698/PoE-Overlay#588]
With the update to 0.6.18 and the new window format the Cancel and Save buttons have vanished.
This applies to all tabs, screenshots are exemplary of the Map tab.

Neither restarting, resizing, maximizing, reinstalling poe-overlay or reinstalling Visual C++ fixed it.

Expected behavior: 
Version 0.6.17
![0 6 17](https://user-images.githubusercontent.com/63364972/78814038-4ec55300-79ce-11ea-9caf-bb081c3605e4.png)

Bug with Version 0.6.18
![0 6 18](https://user-images.githubusercontent.com/63364972/78814181-87652c80-79ce-11ea-982f-f803f756b5de.png)

- OS: Win10 x64
- Version: 0.6.18
- Resolution: tested with 1920x1080 and 1920x2160 (2*1920x1080)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Those buttons are no longer required. Closing the window will save the settings.

**Comment by Culdur** [comment]
Oh, i see. Then i'll happily close, thanks for the timely answer and your work!
