### ISSUE TITLE
Control+T is a default shortcut in PoE and Overlay. Need to change because I can't cast it in game.

### ISSUE THREAD

**Issue by NITRO86sp** [Kyusung4698/PoE-Overlay#590]
**Describe the bug**
Control+T is a default shortcut in PoE and I am using it. I want to disable/change the overlay from using it because I can't cast it in game.

**To Reproduce**
I just installed it and tried using it. Then went to combat..

**Expected behavior**
Shortcut works or doesn't override the game's.

- OS: windows 10
- PoE: latest official

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. The evaluate translate command is using the shortcut. You can change it in the settings menu > evaluate. I'll change the default shortcut in the next version.

**Comment by Kyusung4698** [comment]
## 0.6.19 (2020-04-10)

- update `evaluate-translate` default shortcut to `Alt + T` (#590)
