### ISSUE TITLE
Stat evaluation doesn't work

### ISSUE THREAD

**Issue by cheul0518** [Kyusung4698/PoE-Overlay#595]
Hi,

Thank you for the great work. I've started using this awesome third party app a couple of days ago. Everything in it is excellent and perfect except that I cannot modify the value of an affix. Check this out: https://imgur.com/dc72f88
According to the explanation video, affix value should be something like "# - #", not just single "#" (I don't see any hyphen in any case) As a result, I cannot modify stat values with my mouse wheel (hover and scroll up/down), regardless if my mousewheel zoom's turned off/on. I'm currently running Windwos 10 and PoE (windowed fullscreen as recommended), and the app on my laptop's up-to-date. Any insight?

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. If both values are marked as '#' it will only show one '#'. You'd need to scroll in order to show both values again. I'll display both '#' in the next version because i think this is a bit more innovativ.

**Comment by Kyusung4698** [comment]
## 0.6.23 (2020-04-18)

- update value range component (#595)
  - is now showing both values on hover/ focus even if those are the same
  - is now fully operatable via scrolling (# -> default -> #)
  - change scrolling directions to feel more natural
