### ISSUE TITLE
In game buttons not working (escape/right click + more) after pressing f8 / prt screen 

### ISSUE THREAD

**Issue by poeplayer** [Kyusung4698/PoE-Overlay#596]
Over lay was working perfectly until I pressed f8 then print screen to screen shot something and poe overlay popped up and asked for permission to do stuff.  afterwards buttons will randomly not work. I won't be able to click items, stash or move. Enter won't work and poe overlay hot keys wont work.  When I'm pressing a button Poe.overlay pops up on the bottom left of the screen in small yellow text where the health display is.  I've uninstalled and reinstalled several times and the issue persists. Please help!

**Comment by poeplayer** [comment]
I'm also getting limit reached when I've never had that problem before..

**Comment by poeplayer** [comment]
I'm pretty sure it's just opening itself when this happens because my game also slows down and fps drps while the poeoeverlay logo keeps popping up on the bottom left. and the channelog pops up when I relaunch it which never happened before.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. F8 is the default button for closing the overlay. I assume there was an update which would show the installer after closing the overlay. You can unbind this at the setting menu > general.
