### ISSUE TITLE
Suggestion: Please let me bind mouse button

### ISSUE THREAD

**Issue by dozerwad10** [Kyusung4698/PoE-Overlay#598]
The program won't let me bind my mouse button #4 or #5 to /oos macro. Please make this feature available. Aside from that loving it so far :)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Unfortunately this is not support by Electron. Please see following issue:

https://github.com/electron/electron/issues/22939

As an workaround you could bind another key on those buttons (if your mouse supports this). eg. mouse4 => ctrl + d

**Comment by dozerwad10** [comment]
All good thank you very much.
