### ISSUE TITLE
nothing happens after start

### ISSUE THREAD

**Issue by Supportic** [Kyusung4698/PoE-Overlay#6]
After executing the .exe nothing happens. I can press CTRL+D ingame to get the overlay but cannot close it or anything.
The only thing I can see is this (bottom left corner): https://imgur.com/a/4gnrjhn
It opens a 32 bit background process and 4 other poe-overlay instances.

Windows 10  pro x64 v1909

**Comment by SudhanshuAggarwal** [comment]
I am seeing the exact same issue on alpha 0.4 version.

**Comment by Supportic** [comment]
Since I have a icon in the system tray where I can open the settings now with right click my issue solved I guess.
