### ISSUE TITLE
Bug in the last version

### ISSUE THREAD

**Issue by freddirty** [Kyusung4698/PoE-Overlay#600]
**Describe the bug**
Since last version, the popup window opens in the background. 

**To Reproduce**
Default settings in POE overlay.
Windowed POE mode. (I have two monitors)
Custom resolution. (16:9 on a 16:10 monitor)
After POE overlay restart first popup is OK.
Second popup will open in background.

Most probably this is the consequence of bug reports that the game pushed back to background causing performance problems. (Option limit performance is on for those.)
![sshot](https://user-images.githubusercontent.com/62114155/78975052-96a1c280-7b13-11ea-9a80-8210e20a8fa6.png)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. The latest version 0.6.19 should contain a fix for #587. Maybe this fixed your issue as well. Could you please give it a quick check? Thanks!

**Comment by freddirty** [comment]
Hello Kyusung,

Thanks for the quick reacktion! I've refreshed the app. First I thought now it is OK, but after a few uses similar issue happened. A little bit different, because now the app is still in background but the surruoinding is black.
![sshot2](https://user-images.githubusercontent.com/62114155/78988546-86004500-7b31-11ea-84a7-351840615b37.png)

**Comment by yxbengt** [comment]
Had the same issue since last patch, changed to open window in center instead of on cursor and that fixed it.
After changing back to cursor again it seems to have fixed the issue completely!

**Comment by Facebeef** [comment]
I'm still having this issue, or something related to it atleast. 
When I go to check maps(alt + q) I can't check more than 1 at a time. Once I get the window for the first one I can't Alt+q another since the game isn't focused.

![Uploading image.png…]()

**Comment by Kyusung4698** [comment]
## 0.6.22 (2020-04-13)

- fix multi dialogs not working
