### ISSUE TITLE
KB experimental feature issue

### ISSUE THREAD

**Issue by kartelusm** [Kyusung4698/PoE-Overlay#602]
With the KB option enabled, whenever the overlay i clicked in order to use the KB/wheel, it disappears for a brief second, then reappears again, but the KB/wheel is not working.
This occurs every time when the overlay is clicked.

When the KB option is turned off, this does not happen, and, strangely enough, after maybe 4 versions, the wheel left/right swivel again changes the numeric values of affixes.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I've marked the new release as pre-release. I'll look into this asap. Please do not use the KB feature for now if possible.

**Comment by Kyusung4698** [comment]
## 0.6.20 (2020-04-10)

- fix poe overlay losses focus after clicking on it (#602)

Should be fixed. Please report back! Thanks 🚀
