### ISSUE TITLE
Suggestion: Allow the user to adjust the opacity of the overlay window

### ISSUE THREAD

**Issue by Rasmusmp** [Kyusung4698/PoE-Overlay#607]
Hi,

I sometimes have a hard time reading the item description on the overlay window if I'm in a bright map or hideout. It would be nice if we had the option to change the opacity of the overlay window, either as a slider or a toggle between fully opaque or translucent. 

Thank you for the good work.

**Comment by Kyusung4698** [comment]
## 0.6.21 (2020-04-12)

- add item frame opacity setting (#607)
