### ISSUE TITLE
Hide Poe-Overlay in left corner?

### ISSUE THREAD

**Issue by NitriusX** [Kyusung4698/PoE-Overlay#61]
Would it be possible with an option to hide the PoE-Overlay text in the bottom left corner?

**Comment by SiliticX** [comment]
Especially outside the game where it seems to block the auto-hide option of the windows bar.

**Comment by Kyusung4698** [comment]
## 0.5.5 (2020-01-23)
* add autohiding overlay if poe is not active (#60, #61, #122)

The text is now only visible if the game is active and should no longer be distrative.
