### ISSUE TITLE
Restrictive search behavior for defense values

### ISSUE THREAD

**Issue by ymyt** [Kyusung4698/PoE-Overlay#611]
# 🐞 bug report

Hi! I'm a new user of PoE-Overlay and really liking it so far. Thanks for developing this tool!

Here's a report for an adverse behavior I noticed, which I wasn't able to work around. I'm assuming it's a bug (apologies if I'm mistaken), but if not, then this could be a feature request instead.

## 📝 **Desription**

When filtering searches based on total defense values (AR/EV/ES), specifying the range doesn't work the same way as in other modifiers. This is unintuitive, and forces search based on flat/percent/hybrid defense modifiers, which is not very useful for e.g. rare items.

The minimum value is capped at the raw defense value(s) for the given item base (even if the item base is not filtered for). The maximum value can't be increased beyond the current modified defense value(s) of the item.

**To Reproduce**

Bring up a search for any armor piece, and scroll up/down on the value range for defenses. In the example in the screenshot, the range can't be expanded further than 246 (Slink Boots base EV) ~ 490 (the current EV on the item) in either direction.

**Expected behavior**

I would expect range specification for defenses to work in exactly the same way as modifiers. The user should be able to search in the range (#, current value) ~ (current value, #), with the corresponding handles on the configuration interface to set default search behavior.

**Screenshots**

![image](https://user-images.githubusercontent.com/13857410/79054522-2055ab00-7c4e-11ea-8a31-b48b26db703c.png)

## 🌍  My Environment

- OS: Windows 10 Pro x64
- Version: 0.6.20
- PoE: Steam 3.10.1c English

**Comment by tragicnate** [comment]
Thank you so much for posting this. I am in a similar boat. I love this program and want to use it. However, not being able to auto select a defensive value like energy shield and setting the minimum value to like -10% and max value to uncapped is the biggest hurdle that is keeping me from being able to use this program exclusively over poe trade macro.

**Comment by Kyusung4698** [comment]
## 0.6.21 (2020-04-12)

- add own min max range settings for properties
- add preselect attack and defense as setting
- remove quality min/ max restriction (#611)

**Comment by tragicnate** [comment]
> ## 0.6.21 (2020-04-12)
> * add own min max range settings for properties
> * add preselect attack and defense as setting
> * remove quality min/ max restriction (#611)

Thank you so much for this update. This is amazing tool and these changes are huge! I feel like this is the best tool out there now and no reason to use anything else. The ability to set min-max ranges separately for defensive values and stat values is also a great feature. Thank you!

**Comment by Kyusung4698** [comment]
> Thank you so much for this update. This is amazing tool and these changes are huge! I feel like this is the best tool out there now and no reason to use anything else. The ability to set min-max ranges separately for defensive values and stat values is also a great feature. Thank you!

You're welcome! Thanks for your positive feedback. Closed.
