### ISSUE TITLE
Min-Max Range not applying to Properties

### ISSUE THREAD

**Issue by tragicnate** [Kyusung4698/PoE-Overlay#615]
# 🐞 bug report

**Describe the bug**
The min-max value is not being applied to properties. It seems like defense values are getting a default -10% on min value and uncapped value on max regardless of settings.

**To Reproduce**
1. Set any min-max value for properties to any values.
2. Ranges seems to go to default settings regardless of sliders.

**Expected behavior**
Would expect the min-max range in properties to apply to defensive values such as energy shield total, evasion, ect.

**Screenshots**
Set to 0-# and 0-# for testing
![2020-04-12_16-25-13](https://user-images.githubusercontent.com/63524723/79082375-46289180-7cda-11ea-95b2-f63d8857534d.png)

Item for testing
![2020-04-12_16-26-56](https://user-images.githubusercontent.com/63524723/79082389-71ab7c00-7cda-11ea-9a99-22a75f643f86.png)

Results - Range applied to stats correctly, Range does not seem to be applied to total ES
![2020-04-12_16-28-03](https://user-images.githubusercontent.com/63524723/79082406-9b64a300-7cda-11ea-9d86-a6bf280c1634.png)

## 🌍  Your Environment

- OS:  Win7 x64
- PoE:  Standalone Version 3.10.1c

**Comment by MalakaJones** [comment]
Got the same issue

**Comment by barbarolucente** [comment]
Same with gem levels, not for quality tho

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Will be fixed with the next version. Also those slider should only alter values that are related to the attack/ defense stats. Item Level, Quality etc. should be unaffected.

**Comment by LongJohnDude** [comment]
Look like normalization %Quality for items that not at 20%+ not applying too

**Comment by Kyusung4698** [comment]
## 0.6.22 (2020-04-13)

- fix default range values applied on properties (#615)
