### ISSUE TITLE
Unable to install.

### ISSUE THREAD

**Issue by Aeiro** [Kyusung4698/PoE-Overlay#616]
I'm not sure if this is the correct spot to post this, but I've tried and failed to find any information about my problem. I was using poe overlay, but it stopped auto updating, so I tried re-installing.  I deleted everything (I think) but when I try to install a new version, I get a message that says "Installation Aborted *Setup was not completed successfully*  I've tried install vc redist, tried installing older versions of poe overlay, all to no avail.  The first time I installed poe overlay a month or so ago it worked first try.  Now nothing seems to work, and I've no idea why. Any suggestions or help would be greatly appreciated. 

 -Aeiro

**Comment by Kyusung4698** [comment]
> Hi, thanks for creating an issue. This seems related to #336. Please see the [solution](https://github.com/Kyusung4698/PoE-Overlay/issues/336#issuecomment-600087939) given there.

**Comment by Aeiro** [comment]
Hmm, I've figured our the problem thanks to that link, I needed to remove overlay via Uninstall.  Unfortunately I didn't do that, I deleted the files first, and now I am unable to uninstall the program because it can't FIND the files, and I'm stuck in limbo.  I'm trying to figure out how to remove overlay from my Apps and Features list, but I may need a product code.  Do you have such a thing for poe overlay?

**Comment by Aeiro** [comment]
Cancel that, I finally found a program  to help me clean up apps that wont uninstall, without the need for a product code.  Thanks for your help Kyusung!

**Comment by Kyusung4698** [comment]
> Cancel that, I finally found a program to help me clean up apps that wont uninstall, without the need for a product code. Thanks for your help Kyusung!

Awesome! Glad you got it working 👍 Closed.
