### ISSUE TITLE
Patch 0.6.21 has broken gem price check

### ISSUE THREAD

**Issue by pkulas** [Kyusung4698/PoE-Overlay#617]
# 🐞 bug report

**Describe the bug**
It doesn't pick right gem level when it comes to valuate gem. For example it shows you a price of gem 18/20 instead of gem 21/20 which is totally wrong.

**To Reproduce**
Check price for any leveled gem
**Expected behavior**
Show prices for gems with at least same stats

**Screenshots**

![image](https://user-images.githubusercontent.com/444427/79107423-a10ec700-7d74-11ea-9166-99d1aeeda6f2.png)
![image](https://user-images.githubusercontent.com/444427/79107439-a9ff9880-7d74-11ea-8550-99aa632ddc37.png)
![image](https://user-images.githubusercontent.com/444427/79107461-b2f06a00-7d74-11ea-8189-42946596045f.png)
![image](https://user-images.githubusercontent.com/444427/79107529-cf8ca200-7d74-11ea-9b39-d9d5ae2999cb.png)

## 🌍  Your Environment

- OS: Win 10
- Version:  0.6.21
- PoE: 3.10.0 English

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Will be fixed with the next version.

**Comment by Kyusung4698** [comment]
## 0.6.22 (2020-04-13)

- fix apply range only on attack/ defense properties (#617)
