### ISSUE TITLE
Tray bar pops up after every interaction

### ISSUE THREAD

**Issue by Nikeri** [Kyusung4698/PoE-Overlay#618]
Hello! Since the release of new version once i'm pricechecking something the windows tray bar pops up. In order to minimize it again i need to switch from the game to something by pressing ALT+TAB and then switching to the game.

Im using windowed mode with two monitors. Send help please <3

Screen capture with this bug: https://www.youtube.com/watch?v=kxOPZLSl1yc

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Will be fixed with the next version.

**Comment by Kyusung4698** [comment]
## 0.6.22 (2020-04-13)

- fix poe overlay does not skip the task bar (#618)

**Comment by Nikeri** [comment]
Thank you very much! You've got +1 on Patreon :)
