### ISSUE TITLE
Clipboard was empty. Yo may need to start POE Overlay with privileged rights.

### ISSUE THREAD

**Issue by Kixxs** [Kyusung4698/PoE-Overlay#619]
# 🐞 bug report

**Describe the bug**
When I use ALT+W or Alt+G in POE Overlay, then I get the above/below issue. I installed VC_redist and start program as an admin. I use german keyboard overlay.

**Screenshots**

 
![image](https://user-images.githubusercontent.com/63591627/79119941-da096480-7d91-11ea-8201-bd6f319ace3f.png)

## 🌍  Your Environment

- OS:  Windows 10 X64
- Version:  e.g. 0.6.9 portable
- PoE:  Steam english

**Comment by Valdis444** [comment]
Having this issue as well with an english keyboard, ran program as administrator, when trying to price check it spams the screenshotted error as well as the ctrl button (flips between the keybinds)

**Comment by crash0verwr1te** [comment]
I use cont. + D or Contr. + alt + d and the screen is flickering like hell. 

Change to shif+d and i cant write big letter in chatt.

The most preferred inputs don't work well.

**Comment by crash0verwr1te** [comment]
Okay when i press ctrl. + c the game is flicker and the clipboard error  pop up 1000 time and flips between the keybinds.

The thing is i dont bind ctrl+c on anything.

Looks like a loop the overlay try to use ctrl + c by it self continyously.

**Comment by crash0verwr1te** [comment]
Hmmm weird,
i changed all keybindings from ctrl.+alt+letter, to ctrl.+shift+letter back to my original key binding and now its work without problem.

**Comment by conetopia** [comment]
Sometimes when I start POE-Overlay it doesn't load correctly, and or if i close it, it doesnt' close correctly, and then i think im opening a fresh version, and im actually opening it a 2nd time, and then i get the same error message that you are. I have noticed this recently in the last 2 versions, because every time i try to close it, it asks me if i want to install it lol....
