### ISSUE TITLE
Suggestion: Add the option to disable keyboard support, again.

### ISSUE THREAD

**Issue by MissingL-tter** [Kyusung4698/PoE-Overlay#620]
With keyboard support disabled PoE Overlay was working as expected, after the most recent update (with the option to disable it removed) its now behaving weirdly with iCue again.

Focus detection seems to be working but sometimes it seems to not switch on first click, or have a delayed switch. Its hard to identify the exact issue but I have absolutely no use for keyboard support and would much rather have it working as expected than have a feature I don't use.

For now I'm just downgrading to 0.6.20 until all this is sorted.

**Comment by mrDimMak** [comment]
I think this issue is also causing my taskbar appearance to be delayed when I alt tab. It very noticable in an alt tab heavy game such as PoE

**Comment by Kyusung4698** [comment]
## 0.6.23 (2020-04-18)

- add focusable (keyboard support) as general setting (#620)

**Comment by MissingL-tter** [comment]
Seems to be working as expected now, ty
