### ISSUE TITLE
Spacebar to close

### ISSUE THREAD

**Issue by allnameschosen** [Kyusung4698/PoE-Overlay#622]
Before the last update you could close the overlay with spacebar. Plz bring that option back! Thanks for your tool

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. What version are you using 0.6.21 or 0.6.22? There was a bug in the 0.6.21 which prevented the spacebar hotkey to register correctly. Should be fixed with 0.6.22

**Comment by allnameschosen** [comment]
Thanks newest version is working again!

**Comment by Kyusung4698** [comment]
> Thanks newest version is working again!

Alright, thanks for your feedback. Closed.
