### ISSUE TITLE
Suggestion: Make 20% quantity as a maximum value for left(minimum) search field

### ISSUE THREAD

**Issue by dimonyas** [Kyusung4698/PoE-Overlay#624]
According to issue #136, It hasn't been resolved at all. 
What does commit that resolves #136? It only places the attribute value for the item, like it has 20%Q as a maximum value for the search. And what? How this should help? The main issue - I can't scroll the left(minimum) value higher than it has initially. 
So the issue can be resolved in 2 ways:
1. Enable scrolling left(minimum) value higher than initial item has(to calculated 20%Q)
2. Initially show left value(for Min-max range 0~#%) as an item with 20q%. (sure you should track if it has >20%q then use the value from item)

I definitely prefer second option. And remove the previous fix, it does nothing and really funny.

**Comment by dimonyas** [comment]
Link #594

**Comment by LongJohnDude** [comment]
ATM 20%Q not work at all :(

**Comment by dimonyas** [comment]
First of all, the previous fix(which places 20q value to the max value of the search) should be removed. Because it does nothing at all.

**Comment by LongJohnDude** [comment]
> First of all, the previous fix(which places 20q value to the max value of the search) should be removed. Because it does nothing at all.

It already removed

**Comment by dimonyas** [comment]
So the next step is my suggestion.

**Comment by Kyusung4698** [comment]
## 0.6.26 (2020-04-29)

- add normalize quality for attack and defense properties (#624)
