### ISSUE TITLE
Weapon pDPS not working correctly

### ISSUE THREAD

**Issue by gingirvitis** [Kyusung4698/PoE-Overlay#626]
# 🐞 bug report

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

## 🌍  Your Environment

- OS:  e.g. Win7 x64
- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by gingirvitis** [comment]
when you inspect the items stats and price check it, it does not show the correct pDPS on the item. This might be due to it simply not calculating the quality in at all.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. It does, but there is default setting called property stat range which will reduce the actual value by 10%. You can either turn set this setting to 0% or hold down right click to show the range.

**Comment by gingirvitis** [comment]
> Hi, thanks for creating an issue. It does, but there is default setting called property stat range which will reduce the actual value by 10%. You can either turn set this setting to 0% or hold down right click to show the range.

Hi! thanks for the response. can you give me a step by step guide on how to get to it?

**Comment by Kyusung4698** [comment]
I've attached a screenshot below. Settings > Evaluate > Scroll down > Properties: Min-Max Range 

![image](https://user-images.githubusercontent.com/38520678/79993953-9d3a1d80-84b5-11ea-91e0-1e695d9f90ca.png)

**Comment by conetopia** [comment]
@gingirvitis  once you click any stat, you can scroll with your mouse to adjust the range of stats , also if you right click any of the stats/dmg/itemlvl ect,  you can compare directly to your same stats ect.
