### ISSUE TITLE
단축키 리셋을 하고 싶습니다.

### ISSUE THREAD

**Issue by seonghohan55** [Kyusung4698/PoE-Overlay#628]
I'd like to reset the shortcut key.
Reinstallation of the program is inconvenient because it is saved with the previous settings.
How do I reset my settings?

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. There is currently no UI way of doing this but you can uninstall the app and remove the folder at `%appdata%/poe-overlay`. This will reset all settings. Let me know if this helps!
