### ISSUE TITLE
UI scaling 

### ISSUE THREAD

**Issue by salbeithymian** [Kyusung4698/PoE-Overlay#630]
# 🐞 bug report

**Describe the bug**
To me UI scaling does not work. Playing on 4k. UI is to small. Ingame item-evaluate as well as Menu.
If I read the change logs correctly this would have been added on march 15.

## 🌍  Your Environment

- OS: Win10
- Version: 0.6.9 non-portable
- PoE: Steam 3.10.0 English Windowed Fullscreen

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. The UI does not scale automatically. There is a zoom settings you'd need to modify in the settings menu.

**Comment by salbeithymian** [comment]
Thanks, this solved the "issue".

**Comment by Kyusung4698** [comment]
Awesome! Closed.
