### ISSUE TITLE
Values Reset/Disappear/Change on Click or After Typing

### ISSUE THREAD

**Issue by egocarib** [Kyusung4698/PoE-Overlay#632]
In the latest version (0.6.22), I notice that the typing cursor / insertion point appears by default in the item's top selected stat input immediately after pressing the main hotkey. In the image examples below, my typing cursor appears in the Armor section at the end of "1,242". I assume this is meant to allow me to change the value at the beginning of the range with my own custom value. However, in practice, I've observed some weird/buggy behavior with this new feature.

First, for this item, whenever I open the item overlay, immediately after I click one time _anywhere_ on the item overlay, the armor value gets cleared out and replaced by a #

Before:
![image](https://user-images.githubusercontent.com/3429497/79406586-189f4a80-7f5d-11ea-87ef-58315272a292.png)

After clicking one time anywhere on the overlay:
![image](https://user-images.githubusercontent.com/3429497/79406610-2654d000-7f5d-11ea-8c54-b90e66169eb0.png)

This results in undesirable searches, because the search now finds any body armor with any kind of armor/evasion/ES value at all.

I can reproduce this issue consistently every time with this specific item, but I haven't been able to reproduce it with other items. I suspect it might only occur with values over 1,000 - maybe because they include a comma in the value? I'm not sure and I have no other items with an armor/eva/ES value over 1000 to test with.

Secondly, I noticed that if I _do_ try to edit the values where my text cursor is, POE Overlay often doesn't respect the new value I typed, and replaces it with a different value that usually includes some of the digits from the number I typed but is shorter in length.

These issues did not occur as far as I know on 0.6.20 (I don't think it was even possible to edit values because I could never get my typing cursor to appear in that version. Or maybe I didn't have the option enabled...)

I'm on Win 10 playing POE through Steam.

**Comment by egocarib** [comment]
Using another character, I confirmed that this issue seems to occur for any body armor with armor higher than 1000 (all the ones I tested were 6-link if that matters)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Will be fixed with the next version.

**Comment by Kyusung4698** [comment]
## 0.6.23 (2020-04-18)

- fix values over 1000 reseting to # (#632)
