### ISSUE TITLE
Font Changes After Game Restart

### ISSUE THREAD

**Issue by egocarib** [Kyusung4698/PoE-Overlay#635]
# 🐞 bug report

If I leave POE Overlay running for a long time (usually I leave it on as long as my computer's running), eventually the font changes from POE font to a different system font.

This seems to occur after closing Path of Exile and then restarting Path of Exile when I want to play again at a later time (POE Overlay stays running the entire time).

I can resolve the issue by restarting POE Overlay, which restores the game-style font.

Here's the "correct" font that I expect to see:

![image](https://user-images.githubusercontent.com/3429497/79618788-a6e80d80-80d0-11ea-9636-7dd86cf9c92a.png)

Here's the font as it looks after restarting the game / after time has passed:

![image](https://user-images.githubusercontent.com/3429497/79618799-ac455800-80d0-11ea-8309-6750e0c14a59.png)

## 🌍  Your Environment

- OS: Win10 x64
- Version: 0.6.22 full install
- PoE: latest Steam, English

**Comment by Kyusung4698** [comment]
## 0.6.23 (2020-04-18)

- fix font not loading by adding a local fallback (#635)

**Comment by egocarib** [comment]
I have not encountered this issue since upgrading. It appears to be fixed. Thanks!
