### ISSUE TITLE
Changing Leauges

### ISSUE THREAD

**Issue by nappy1877** [Kyusung4698/PoE-Overlay#636]
I am not sure if I am doing something wrong, but I switched from the current league to Standard in the app...but I can not change it back to the temporary leauge in the app. When I try to change the settings, none of them seems to save. Is there not a save feature in the settings menu. I tried to relaunch the app, but my old settings just come back.....am I doing something wrong?

Thanks in advance 

# 🐞 bug report

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

## 🌍  Your Environment

- OS:  e.g. Win10 x64
- Version:  e.g. 0.6.22 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by tkfkdenf2** [comment]
OS : 예 : Win10 x64
버전 : 예 : poe-overlay-Setup-0.6.23.exe

PoE : 예 : kakao 3.10.0 / korea

 앱을 다시 시작하려고했지만 이전 설정이 다시 나타납니다

**Comment by tkfkdenf2** [comment]
버그 설명
 언어변경 설정 변경후 설정 저장하기가 안보임 앱을 다시 시작하기 를 눌러 다시시작 하면 설정이 초기화 되어있음

재현하기

예상되는 행동
초기화

스크린 샷

운영체제 : 예 : Win10 x64
버전 : 예 : poe-overlay-Setup-0.6.23.exe

PoE : 예 : kakao 3.10.0 / 대한민국

**Comment by nappy1877** [comment]
Close this issue...will rewrite new issue to make more clear
