### ISSUE TITLE
Evaluating non-relic items with relic-variants returns incorrect data from poe.ninja

### ISSUE THREAD

**Issue by bhaesler** [Kyusung4698/PoE-Overlay#639]
# 🐞 bug report

**Describe the bug**
When evaluating an item that has a relic variant (https://pathofexile.gamepedia.com/Relic), the price and trend data from poe.ninja will be for the relic version, which is typically much higher than the regular price.

**To Reproduce**
1. Find any item which has a relic variant
2. Use the evaluate command. Take note of the price and trend in the poe.ninja section
3. Click the poe.ninja section to open the website (ensure you are in the right league, since the link defaults to Delirium, and this behaviour was observed in standard)
4. Filter to the item you evaluated on, and observe that the price returned is for the wrong league or relic variant

**Expected behavior**
The price returned should match whether or not the item being evaluated is a relic.

**Screenshots**
![image](https://user-images.githubusercontent.com/14072487/79677884-06612d00-8239-11ea-9182-c935fc38f36b.png)

## 🌍  Your Environment

- OS: Win10 x64
- Version: 0.6.23
- PoE: Steam 3.10.0/e English

**Comment by Kyusung4698** [comment]
## 0.6.24 (2020-04-22)

- fix poe.ninja showing the relic price variant (#639)
