### ISSUE TITLE
Lag: When having Stream open on second screen

### ISSUE THREAD

**Issue by CiiDyY** [Kyusung4698/PoE-Overlay#640]
**Describe the bug**
PoE Overlay works completely fine as long as I dont have a stream open on my second screen, but as soon as I do, the game feels choppy and laggy.
If I move the stream to my main screen and its not visible anymore PoE is back to normal.
Tried disabling and enabling Hardware Acceleration, didnt have a change.
Disabling Hardware Acceleration on Chrome helped with this issue in the past, but doesnt help while using PoE Overlay.

## 🌍  Your Environment
- OS:  Win10 x64
- Version: 0.6.23 (Non Portable)
- PoE: 3.10.1d (Non Steam)
- Monitors: 144Hz Main Screen, 60Hz Second Screen

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This is mostly caused be the Chromium Engine which is used to render the overlay. I've updated the embedded Chromium version in the new version 0.6.24. Maybe this has resolved this issue.

**Comment by CiiDyY** [comment]
Hi, installed the update, but sadly it didn't fix the issue. I am certain its the issue that both my screens have different refresh rates. I had this issue with streams on second screen making my games lag, but disabling Hardware Acceleration in Chrome resolved it. I guess I'll have to live with that for now and disable poe overlay once I'm watching a stream on my second screen. Thanks for the help.

**Comment by Kyusung4698** [comment]
Thanks for the fast feedback. I'll close this issue for now. Please let me know if you found a working fix.
