### ISSUE TITLE
Bug/annoyance: only allow keybinding overrides when PoE is focussed

### ISSUE THREAD

**Issue by Bazeloth** [Kyusung4698/PoE-Overlay#641]
# 🐞 bug report

**Describe the bug**
Poe Overlay takes over my keyboard when i dont want it to.

**To Reproduce**
-  Have Poe Overlay running
- Have PoE open
- Price check an item with ctrl + D to get this dialog:
![image](https://user-images.githubusercontent.com/19928782/79683192-9054ca00-8228-11ea-93bf-1d3789a48209.png)
- Focus your Chrome browser and press ctrl + t to open a new tab (while having the ctrl + D popup from Poe Overlay open)
- Poe overlay catches all your input.. (spacebar, ctrl + t etc)

**Expected behavior**
When my previously focussed window _isnt_ PoE, i expect it not to catch any hotkeys assigned in PoE Overlay

**Screenshots**
See reproduce steps
## 🌍  Your Environment

- OS: windows
- Version: 0.6.22
- PoE: 3.10

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This has been fixed with 0.6.23. Also see #627
