### ISSUE TITLE
Hotkeys not working in game and settings not being saved (Fixed)

### ISSUE THREAD

**Issue by Alfian961** [Kyusung4698/PoE-Overlay#643]
Hi! I've been enjoying the addon so far but suddenly all hotkeys stopped working. The version and stuff still shows on bottom left. 
I tried messing around with settings but everytime I change a setting and relaunch, it would change back to the previous setting. 
For example I would try to disable Focusable and I would relaunch but it would go back to being enabled. Any help would be appreciated thanks

Edit: I reinstalled redist and it works. Probably an error on my end. Will leave this up in case anyone else wants to see it

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Glad you got it resolved. Also the settings are saved/ applied once you close the settings menu. The next version will have a separate save button.
