### ISSUE TITLE
Can't get it to work at all?

### ISSUE THREAD

**Issue by vikrum2083** [Kyusung4698/PoE-Overlay#647]
# 🐞 bug report

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

## 🌍  Your Environment

- OS:  e.g. Win7 x64
- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by vikrum2083** [comment]
Hello. I unfortunately can't get anything to work with PoE-Overlay.

Sometimes F7 will bring up the options but other than that nothing else works.

The scroll function doesn't scroll even though I've gone into settings and set it to normal. F5 doesn't take me to hideout. I've tried uninstalling the PoE-Overlay and reinstalling a few times. I've ran everything as admin.

I've installed both versions of vc_redistribute.

I feel like I've got to be missing something major.

Anyone else have these problems? Thanks.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Seems like the game is not correctly detected. Is the yellow version text displayed at the bottom left? Also could you please attach the application log. This can be found at `%appdata%/poe-overlay/logs/main.log`

![image](https://user-images.githubusercontent.com/38520678/79992849-53046c80-84b4-11ea-8f86-7de6c79f27e3.png)

**Comment by vikrum2083** [comment]
I appreciate the reply.

The text is and has always been in yellow. After creating the ticket originally and Google not helping I finally uninstalled PoE Overlay and went back to Trade Macro.

When I saw your reply I followed the same steps I've always followed, installed PoE Overlay, and it's working flawlessly all the sudden. Sorry to have wasted your time as I have no idea what's changed to make this work. I keep Windows pretty up to date and I don't recall it updating any time recently.

Would you still like to see the log? Thanks again for all your help and the great program.

**Comment by Kyusung4698** [comment]
Awesome! Glad it's working now.

> Would you still like to see the log?

Yes, please! Hopefully i'll find a useful error log what caused this.

**Comment by vikrum2083** [comment]
Apologies for the delay. Just saw your reply. Here you are.

[main.log](https://github.com/Kyusung4698/PoE-Overlay/files/4529310/main.log)

**Comment by Kyusung4698** [comment]
Thanks for your logs. It seems like the error was caused by iohook. I'll keep an eye open if this same error occurs again. Closed.
