### ISSUE TITLE
Enchants appear to be searched as implicits

### ISSUE THREAD

**Issue by SiliticX** [Kyusung4698/PoE-Overlay#65]
I was so hyped when i saw that nobody had this raised zombies enchant on the market until i went and opened in the browser that it looked up by [implicit], not by [enchant]

**Comment by Kyusung4698** [comment]
Will be continued here #68 Thanks for reporting!

**Comment by Kyusung4698** [comment]
Possible fixed with 0.5.0-alpha.0. Please report back. Thank you!
