### ISSUE TITLE
6.23 made poe overlay EXTREMELY slow

### ISSUE THREAD

**Issue by EzequielD11** [Kyusung4698/PoE-Overlay#652]
Pretty much tittle, it stays for almost 10 seconds in the "analyzing data", guess ill just fall back to 6.21 till this is fixed.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Could you please attach your application logs? They can be found at `%appdata%/poe-overlay/logs/main.log`. Thanks!

**Comment by Tortorion** [comment]
Same problem. Analyzing Data takes 8-10 seconds. Updating to newest 0.6.24 didn't help.

Log: 
[main.log](https://github.com/Kyusung4698/PoE-Overlay/files/4518445/main.log)

**Comment by Kyusung4698** [comment]
## 0.6.25 (2020-04-24)

- fix optimize analyze function (#652)
