### ISSUE TITLE
Handle Leak

### ISSUE THREAD

**Issue by cactus888** [Kyusung4698/PoE-Overlay#654]
I noticed that 0.6.23 and 0.6.24 seems to have a handle leak of around 2 handles per second

Here are two screenshots a few seconds apart:

![Annotation 2020-04-22 170414](https://user-images.githubusercontent.com/47116608/80033848-67983300-84bb-11ea-874e-08708882b2f8.jpg)
![Annotation 2020-04-22 170347](https://user-images.githubusercontent.com/47116608/80033851-68c96000-84bb-11ea-91c5-3b707fb17980.jpg)

The handles never seems to be released; I had over 100 000 before I killed the process.

**Comment by cactus888** [comment]
Two hours after:

![Annotation 2020-04-22 184804](https://user-images.githubusercontent.com/47116608/80041221-e09e8700-84c9-11ea-9916-3de6d9ec001c.jpg)

**Comment by SnosMe** [comment]
https://github.com/sentialx/node-window-manager/pull/46

**Comment by Kyusung4698** [comment]
## 0.6.25 (2020-04-24)

- fix handle leak (#654)

Thanks to @SnosMe
