### ISSUE TITLE
Currency stack above 1k report incorrect price for bulk in poe ninja section

### ISSUE THREAD

**Issue by barbarolucente** [Kyusung4698/PoE-Overlay#656]
# 🐞 bug report

**Describe the bug**

If evalueted, a stack above 1k of any currency will report an incorrect price for the entire bulk, this happens because the program read the quantity as 1.000 and not as 1'000

**To Reproduce**

 Evaluate any currency stack above 1k

**Expected behavior**

**Screenshots**

![jeweller](https://user-images.githubusercontent.com/61647841/80072847-17ff4900-8547-11ea-9cd1-15e777cab800.png)

## 🌍  Your Environment

- OS:  e.g. Win10 x64
- Version:  latest
- PoE:  e.g. Steam

**Comment by Kyusung4698** [comment]
## 0.6.25 (2020-04-24)

- fix stack size over 1000 wrong value used (#656)
