### ISSUE TITLE
Erroneously Selecting Crit When Checking Skill Gems

### ISSUE THREAD

**Issue by livejamie** [Kyusung4698/PoE-Overlay#658]
When price checking any skill gem that has crit, overlay will select the crit by default and bring up zero results.

Example 1:

![image](https://user-images.githubusercontent.com/49513/80160758-3f740700-8583-11ea-809c-4e0b43e5b792.png)

turns into

![image](https://user-images.githubusercontent.com/49513/80160772-4c90f600-8583-11ea-8b75-3b192545747a.png)

Example 2:

![image](https://user-images.githubusercontent.com/49513/80160806-616d8980-8583-11ea-8d7c-0eaa030af8f3.png)

turns into

![image](https://user-images.githubusercontent.com/49513/80160819-6af6f180-8583-11ea-86db-8de59325cf03.png)

---

If I deselect the crit it brings up prices as expected.

![image](https://user-images.githubusercontent.com/49513/80160864-88c45680-8583-11ea-8d40-7eab9367ae78.png)

**Comment by Kyusung4698** [comment]
## 0.6.25 (2020-04-24)

- add properties query restriction based on item category (#658)
