### ISSUE TITLE
Node-Window-Manager dependency prevents the application from starting on Linux

### ISSUE THREAD

**Issue by thorsten-passfeld** [Kyusung4698/PoE-Overlay#662]
# 🐞 bug report

**Describe the bug**

The module "node-window-manager" seemingly cannot be found when running "npm run start".

**To Reproduce**

**Error log**

>
> poe-overlay@0.6.25 start /home/USER/Programming/Anderes/PoE-Overlay
> npm-run-all -p ng:serve electron:serve
>
>
> poe-overlay@0.6.25 ng:serve /home/USER/Programming/Anderes/PoE-Overlay
> ng serve
>
>
> poe-overlay@0.6.25 electron:serve /home/USER/Programming/Anderes/PoE-Overlay
> wait-on http-get://localhost:4200/ && npm run electron:serve-tsc && electron . --serve
>
>
>chunk {main} main.js, main.js.map (main) 14.7 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 165 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 604 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 917 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 8.12 MB [initial] [rendered]
Date: 2020-04-24T21:44:33.202Z - Hash: 8c5c3335ce7f9be17d0d - Time: 19361ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.
>
> poe-overlay@0.6.25 electron:serve-tsc /home/USER/Programming/Anderes/PoE-Overlay
> tsc -p tsconfig.serve.json
>
> electron/window.ts:2:38 - error TS2307: Cannot find module 'node-window-manager'.
>
>2 import { addon, windowManager } from 'node-window-manager';
>                                       ~~~~~~~~~~~~~~~~~~~~~
>
>
> Found 1 error.
>
>npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! poe-overlay@0.6.25 electron:serve-tsc: `tsc -p tsconfig.serve.json`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the poe-overlay@0.6.25 electron:serve-tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
>npm ERR! A complete log of this run can be found in:
npm ERR!     /home/USER/.npm/_logs/2020-04-24T21_44_35_438Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! poe-overlay@0.6.25 electron:serve: `wait-on http-get://localhost:4200/ && npm run electron:serve-tsc && electron . --serve`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the poe-overlay@0.6.25 electron:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
>npm ERR! A complete log of this run can be found in:
npm ERR!     /home/USER/.npm/_logs/2020-04-24T21_44_35_477Z-debug.log
ERROR: "electron:serve" exited with 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poe-overlay@0.6.25 start: `npm-run-all -p ng:serve electron:serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the poe-overlay@0.6.25 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
>npm ERR! A complete log of this run can be found in:
npm ERR!     /home/USER/.npm/_logs/2020-04-24T21_44_35_648Z-debug.log

**How to temporarily fix**
After a bit of troubleshooting, I was able to get it running again. The logs were a bit confusing to me, since I'm not too familiar with this framework, but looking back at this commit: https://github.com/Kyusung4698/PoE-Overlay/commit/4d0f3d93a22643d0894553b35c9a64b5b8dfa1bb

I saw something was up with "node-window-manager" and how it appeared in "package.json".
My local file contained this line:
> "node-window-manager": "git+https://github.com/SnosMe/node-window-manager.git#61330b0769bfdd09976f6186afe3a55d2b0b4ce8",

Then I changed it to:
> "node-window-manager": "^2.2.1",

This fixed the issue, it seems. I still need to test it out ingame, but at least the application started (although with a couple of errors/exceptions, but they would be the topic for another minor issue, as they don't seem to be causing any trouble)

## 🌍  Your Environment

- OS:  Manjaro Linux
- Version:  0.6.25

**Comment by nydn** [comment]
Hey,

Are you sure that's the only thing you changed? Because the problem persist for me even after changing the "node-window-manager" line.

Version 0.6.25 on Arch Linux

**Comment by thorsten-passfeld** [comment]
> Hey,
> 
> Are you sure that's the only thing you changed? Because the same problem persist for me even after changing the "node-window-manager" line.
> 
> Version 0.6.25 on Arch Linux

Yeah, that was the only thing. After that, you should rm -rf node_modules, then "npm install", "npm run electron:rebuild" and finally "npm run start". That's all I did.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I've added a local version of this package because there was a critical fix which was not available at the published npm package. In the meantime the latest version has been published and i can remove the local version with the next version.

**Comment by nydn** [comment]
> > Hey,
> > Are you sure that's the only thing you changed? Because the same problem persist for me even after changing the "node-window-manager" line.
> > Version 0.6.25 on Arch Linux
> 
> Yeah, that was the only thing. After that, you should rm -rf node_modules, then "npm install", "npm run electron:rebuild" and finally "npm run start". That's all I did.

Thanks, I'm not really familiar with nodejs and npm and tought npm install would automagically take care of that. Will try that on the afternoon, if the new version is still problematic. Thanks @Kyusung4698

**Comment by nydn** [comment]
Just tested the develop branch, works correctly on Arch Linux.

**Comment by Kyusung4698** [comment]
## 0.6.26 (2020-04-29)

- remove local package version (#662)
