### ISSUE TITLE
Open PoEDB Hotkeys For Helmets Uses Wrong CN Value

### ISSUE THREAD

**Issue by RoryTate** [Kyusung4698/PoE-Overlay#663]
When pressing Ctrl + G or Ctrl + Alt + G after hovering over a helmet to look at the possible mods on PoEDB, the application uses the incorrect CN "Helmets" in the URL instead of the correct "Helmet" value.

An example of the **incorrect** URL – as currently done by the application – is:

https://poedb.tw/us/mod.php?cn=Helmets&an=dex_armour

The correct URL for the page should read:

https://poedb.tw/us/mod.php?cn=Helmet&an=dex_armour

Note the absence of the "s" on "Helmet" in the second URL.

**To Reproduce**

1. Hover over a helmet
2. Press Ctrl + G or Alt + Ctrl + G
3. Note that the page displayed on PoEDB is a default one for life flasks, which is incorrect, and the Helmet page should display instead

**Comment by Kyusung4698** [comment]
## 0.6.26 (2020-04-29)

- fix poedb using wrong cn value for helmets (#663)
