### ISSUE TITLE
[Uniques] -# Reduced Mods Can't Be searched ! 

### ISSUE THREAD

**Issue by conetopia** [Kyusung4698/PoE-Overlay#669]
![86864e006ab381f2faaadf393993ac3e](https://user-images.githubusercontent.com/4310295/80448826-218c0680-88e3-11ea-990d-a8495da2cfa9.png)
![8738148c6cf4635189d4ec7f99eb0c33](https://user-images.githubusercontent.com/4310295/80448829-25b82400-88e3-11ea-8eb3-641c28f546f1.png)
![6b62fecfe876fa823688546482121c60](https://user-images.githubusercontent.com/4310295/80448832-281a7e00-88e3-11ea-98b9-f5a6edd045b1.png)

Poe-overlay, automatically selects all the options, and shows no results for sales.
I can click to highlight any option and or all options , and un-highlight the reduced minnion speed option, and then all of the sudden I have lots of results.

Not sure if this was intended, or possibly something that can be updated/upgraded/fixed in the future? 
at least if poe-overlay can't calculate reduced movement speed by Currency values backwards... being example 100% reduced movement speed would be worth Example 1 chaos...
and 1% speed reduced, be worth 10 exalts ect .... then at least have it so that when you CTRL+D , that it don't automatically highlight the reduced speed on that item/items ect.

Hope to hear some decently good news, thank you for reading.

**Comment by conetopia** [comment]
![46a2fe1ef756541dbbd200c76e032be81](https://user-images.githubusercontent.com/4310295/80671185-bb33ef00-8a6e-11ea-84d8-e8aa230af5fc.png)
Another Example is " The Broken Crown"
20% reduced mana regeneration rate.
POE-Overlay says no results , open browser
Clicked the search in the POE website...
-# Is not a valid search. 
-20 is not a valid search
0 or 20 is a valid search !
Not sure if this is something that GGG should fix on their search page, and if or its something that can be adjusted/fixed  in poe-overlay?

**Comment by conetopia** [comment]
Hello? Is this Visible to anyone?

**Comment by egocarib** [comment]
Already reported in #568 

Just noticed today that Quill Rain is also affected (-27 - #, when the mod is a static -30)

**Comment by conetopia** [comment]
So this issue has been known for over 30 days? and we have had like 10 updates?
why hasn't this been fixed yet? it seems like such an easy fix !

**Comment by conetopia** [comment]
Bump, 30 days later, Still an issue.

**Comment by conetopia** [comment]
It appears that GGG calls it increased reduced (stat/mod)
So instead of like 8% reduced mana reserved
They call it -8% increased mana reserved

**Comment by lxsli** [comment]
It'd be really helpful to get this fixed!
