### ISSUE TITLE
Suggestion: bring back pricing

### ISSUE THREAD

**Issue by Nchi** [Kyusung4698/PoE-Overlay#675]
did you get  direct contact from GGG? There is no way your pricing macro is ANY worse than a logout macro besides using a right click event (since somehow the keyboard rclick doesnt work)

If the click is actually an issue, just change the feature to fire on next right click instead with a new keybind, so ctrl g> wait for rclick> price window opens with the target box under it already so after you choose a price its ONLY the typing, no mouse event. 

If a stupid logout macro that breaks hardcore at its core is somehow OK for 8 years then a price macro gets to stay.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. The feature can be enabled in the settings. See screenshot below:
![image](https://user-images.githubusercontent.com/38520678/80683858-20b2ca80-8ac5-11ea-97a5-bf8cde5b4128.png)

**Comment by Nchi** [comment]
Ah, the phrasing confused me.
