### ISSUE TITLE
Option to disable pre-selectin of item modifiers

### ISSUE THREAD

**Issue by datoml** [Kyusung4698/PoE-Overlay#676]
Hello there,
First of all. Thanks for this great tool. It works really well and it's my go-to app for pricing things in POE. :)

The only thing for me that is missing would be an option to disable all pre-selection of item modifiers at the first query with CTRL+D.
Most of the time I have to disable all selections first and then pin down certain mods to achieve an accurate price.
Would this be possible?

Thanks. :)

**Comment by Nchi** [comment]
its in the options already

**Comment by datoml** [comment]
Ohh. I missed that completely. Sorry for wasting your time. :)
