### ISSUE TITLE
System requirements? Program won't display or run properly.

### ISSUE THREAD

**Issue by HiPoEGH** [Kyusung4698/PoE-Overlay#677]
# 🐞 bug report

Program launches fine. However no popups display properly, hotkeys don't seem to work. Context menu doesn't seem to work, except for 'About', which brings up a white blank window. Hardware acceleration toggle doesn't affect anything.

Are there more system requirements to install additional packages that are not apparent? I already installed the updated VC_distributable as recommended but that did not change anything.

## 🌍  Your Environment

- OS:  Win7 x64 SP1
- Version:  0.6.26
- PoE:  3.10.0/e English

**Comment by conetopia** [comment]
Yes POE Overlay 0.6.26 Requires game version 3.10.1f lol

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This seems like the overlay does not detect your game properly. You can try running the program as administrator. Also please make sure once you tabbed into PoE there should be a yellow version text at the bottom left. If this text is not visible the overlay could not detect PoE properly.

**Comment by HiPoEGH** [comment]
Running the standalone version (as regular user) seems to work. I'll test the installer version later today.
I might have had issues with the program not playing nice with my firewall application.

**Comment by Kyusung4698** [comment]
> Edit: _Seems hardware acceleration makes an invisible window. Any info on how to adjust/fix this?_

Hardware acceleration can be disabled at the tray menu. Although the overlay window should be transparent.
