### ISSUE TITLE
searching......

### ISSUE THREAD

**Issue by potato404** [Kyusung4698/PoE-Overlay#678]
when i search for the price it just never loads and the poe ninja chart for this jewel is way wrong on the value

![overlay bug](https://user-images.githubusercontent.com/23662853/80717735-d4648c00-8abe-11ea-9abf-4951727ed4db.png)

**Comment by tirabi** [comment]
i have the same issue on some items.  Searching never ends and never loads results.  i haven't narrowed down which type it fails on yet.

**Comment by era3z** [comment]
Same thing goes for me...

**Comment by tirabi** [comment]
> i have the same issue on some items. Searching never ends and never loads results. i haven't narrowed down which type it fails on yet.

this appears to have been corrected.  At least it didn't happen all last night except for one rare axe.

**Comment by jerrymathew** [comment]
This is still happening to me for a lot of items.

**Comment by drjaos** [comment]
This is happening to me for most (all?) items, but only within the past few days.

**Comment by Kyusung4698** [comment]
## 0.6.27 (2020-05-08)

- updated rate limiting behavior (#678)
  - accounts for external requests aswell (e.g. done through the website)
  - checks current limit with a single request before sending
    multiple requests if current limit is stale
  - fails instantly if rate is limited
  - fails after 10s if rate is still reached

Looking forward to your feedback! 🚀

**Comment by MaxKruse** [comment]
i can literally only search up one item, it then refuses to do any more requests at all. i have a 10 item fetch count
