### ISSUE TITLE
0.5.0 Roadmap

### ISSUE THREAD

**Issue by Kyusung4698** [Kyusung4698/PoE-Overlay#68]
Hi, i'm currently working on the 0.5.0 version. Also named the `stats-rework`. For now there are quite some issues which are related to this. As this seems quite messy to me i'll list those and merge them into this. If you have an issue relate to stats/modifiers please report them here. Feature Request should be treated as an own issue. Thanks for your help!

* Stat type wrong ( ~~#24~~ , ~~#27~~ , ~~#36~~ , ~~#59~~ ,  ~~#65~~ )
* Stat type missing (#38 )
* Stat missing (~~#56~~, ~~#44~~ )

I'll create alpha versions of 0.5.0 as soon as possible to let you guys test.

**Comment by 766b** [comment]
`Cannot be Chilled or Frozen if you have used a Fire Skill Recently` is missing from selection once parsed.

~~~~
Rarity: Unique
Hrimnor's Resolve
Samite Helmet
--------
Armour: 602 (augmented)
--------
Requirements:
Level: 55
Str: 114
--------
Sockets: R 
--------
Item Level: 70
--------
40% increased Fire Damage
118% increased Armour
+54 to maximum Life
+30% to Cold Resistance
Cannot be Chilled or Frozen if you have used a Fire Skill Recently
--------
Hrimnor's presence was as cold as ice,
but his heart burned for vengeance.

**Comment by Kyusung4698** [comment]
> `Cannot be Chilled or Frozen if you have used a Fire Skill Recently` is missing from selection once parsed.

Thanks for reporting. The actual filter is called: '#% Chance to Avoid being Frozen or Chilled if you have used a Fire Skill Recently'. Therefore the mismatch. I'll investigate this later. There is also an issue with negated filters.

**Comment by Kyusung4698** [comment]
![value_selector](https://user-images.githubusercontent.com/38520678/72386639-075a5e00-3722-11ea-8478-87d7cca5f3dd.gif)

I'm currently working on the value range selector which works by hover + scroll wheel. Also the values are now getting "ranged" by +-10% (configurable).

* De/Increase Value by 0.1 via Alt Wheel
* De/Increase Value by 1 via Wheel
* De/Increase Value by 5 via Shift Wheel
* Reset via Wheelclick or Rightclick

The final version 0.5.0 should be released tomorrow. Depending on how much time i can spent.
