### ISSUE TITLE
Suggestion: VPN protection against banning accounts linked to an ip address

### ISSUE THREAD

**Issue by alexyo27** [Kyusung4698/PoE-Overlay#680]
We need a way to protect our IP while using the app because GGG started to lock too many accounts without giving an alternative.
After using this app is hard to go back playing without.

**Comment by thorsten-passfeld** [comment]
What stops you from using a VPN service? And what does PoE-Overlay have to do with it directly?

**Comment by ParsHere** [comment]
What an odd thing to suggest.

**Comment by silvermoona** [comment]
I don't understand this request, what does POE overlay have to do with IP addresses being banned? The request via POE overlay is made from your individual IP address, POE overlay does not have to do anything with your IP address

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. VPN support will not be added for this issue. For what it's worth GGG approved the latest version to be confirm their rules.
