### ISSUE TITLE
Suggestion: If initial search is disabled, don't trigger a search until search is selected

### ISSUE THREAD

**Issue by EhhNahNoMouse** [Kyusung4698/PoE-Overlay#682]
Hi!

I like the new ability to disable the initial search, but I noticed that when I change the search criteria, it starts automatically searching. 

It would be nice to have the ability to have no searching happen until search is selected. That way, if I want to choose 2+ different search criteria, I'm not doing extra searches before I'm "ready". 

See my amazing photo-editing skills below:
![Untitled](https://user-images.githubusercontent.com/63628669/80765710-879da700-8af8-11ea-80cd-23b9bb8c9316.png)

**Comment by conetopia** [comment]
Yeah I somewhat agree, but hopefully once you click search, you can make adjustments after, and it will auto search still, that way you don't have to click search 20 times for each adjustment.

**Comment by EhhNahNoMouse** [comment]
> 
> 
> Yeah I somewhat agree, but hopefully once you click search, you can make adjustments after, and it will auto search still, that way you don't have to click search 20 times for each adjustment.

**Query Behavior (Run initial search off)**
(A) Current:
- Initial search doesn't start until a criteria is adjusted or Search is selected

(B) Your version (Maybe it should be the default behavior):
- Initial search doesn't start until Search is selected. 
  - After that, auto-search for each adjustment.

(C) My version (It's more clicks, but potentially less searches performed):
- Searches only performed once Search is selected.

I think my preferred behavior in order of preference would be: C, B, A - But I think popular opinion would probably be for option B.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. B is definitely my intended behavior of this feature. Unfortunately I've only tested it using the setting `Debounce Time` on infinite which results in behavior C. Will be addressed with the next version.

**Comment by Kyusung4698** [comment]
## 0.6.27 (2020-05-08)

- fixed search triggered after changing filter if initial search is off (#682)
