### ISSUE TITLE
Price for non corrupted items

### ISSUE THREAD

**Issue by Orbitok** [Kyusung4698/PoE-Overlay#683]
# 🐞 bug report

**Describe the bug**

 Wrong price calculation

**To Reproduce**
Take a delirium midium cluster jewel (  Added Small Passive Skills grant: 10% increased Damage while affected by a Herald ) that is not corrupted and price check it, It will tell you the price 1-5c
The real price is 1-2 ex because the program checks the price for all items , corrupted and not , and tells you the lowest price. 
The program must calculate the price for non corrupted items all the time OR make a small button that always stays ON  "Not-corrupted"
The price is wrong for many items because of this defect.
**Expected behavior**

 Right price

**Screenshots**

## 🌍  Your Environment

- OS:  e.g. Win7 x64
- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by Orbitok** [comment]
It should always search for non-corrupted items unless the item is corrupted, but not for both in the same time like now. May be it is better to make something like a switch, by clicking on it you can switch corrupted or not, and by default it would always stays non-corrupted unless the item is corrupted. Thanks.

**Comment by joe7dust** [comment]
Honestly I WISH I could have mine behaving like you have. 90% of the time I don't care if competition is corrupted or not, I don't even see an option to use the ANY equivalent of the corrupted dropdown. For mine if it is non-corrupt it only searches non-corrupt item and vice versa. Most of the time it doesn't matter, only for certain items (usually uniques) where a certain corruption is desired and a lot of people vaal them so corrupted without this certain corruption is considered "failed".
