### ISSUE TITLE
"An error has occured while parsing the item"

### ISSUE THREAD

**Issue by Ellipsism** [Kyusung4698/PoE-Overlay#684]
Everytime I try to pull up prices on an item, this message comes up. I have tried relaunching and reinstalling the app. Additionally, the scroll function doesn't work either. Any suggestions?

**Comment by Sabiancym** [comment]
This is happening to me as well since the last update.  It seems to only happen on corrupted items though.

**Comment by matton300** [comment]
i have the same problem

**Comment by matton300** [comment]
is on some items, mine in is an starforge corrupted with white socket.

**Comment by Kyusung4698** [comment]
## 0.6.27 (2020-05-08)

- fixed corrupted weapons unable to parse (#684, #688)
