### ISSUE TITLE
Overlay app starts, however cannot access Settings, cannot Exit and not working in PoE

### ISSUE THREAD

**Issue by zuekut** [Kyusung4698/PoE-Overlay#686]
**Describe the bug**
I just installed version 0.6.26 via the setup and all went fine, it got installed. However when I started PoE Overlay as administrator, non of the menus work (Settings, Exit), only opening the Changelog works. When in game, I tried hitting F7 as mentioned in the readme.md, but nothing worked, I tried alt-D on an item, still same story. The things I tried thus far and non of them working:
1. Install version 0.6.26 via setup
2. Running it directly from the standalone portable exe
3. Tried it with version 0.6.25
4. Installed vc_redist, no change

**To Reproduce**
1. Start PoE Overlay as administrator
2. Click on Settings -> nothing pops up
3. Click on Exit -> does not exit
4. Click on Relaunch -> does not relaunch
5. Start path of exile in fullscreen windowed mode and hit F7, nothing happens. Also the PoE Overlay 0.6.26, is not shown in the bottom left corner.

**Expected behavior**
App runs, I can access Settings and also use it in game.

## 🌍  Your Environment
- OS: Win10 x64
- Version: 0.6.26
- PoE: PoE Launcher Version 3.10.1f English

**Comment by NickZaranis** [comment]
Are you running PoE in windowed fullscreen mode?

**Comment by zuekut** [comment]
Yea, it somehow got resolved by itself in the morning, all works fine now, go figure ^^.
