### ISSUE TITLE
Suggestion: Add a button to change fetch count on that search.

### ISSUE THREAD

**Issue by MateusRoscoe** [Kyusung4698/PoE-Overlay#692]
🚀 feature request

**Is your feature request related to a problem? Please describe.**
When you're searching for an item that is being price fixed the search already groups the same seller but it still counts every item as one for the maximum item searched. Meaning you can have situations like the screenshot below (not necessarily a price fixed item but describes the issue), you have maybe 1~5 sellers and you can't gouge the price.

**Describe the solution you'd like**
A button to change just for that search how many it will fetch when running the query. It could also be just a scroll feature on the 40/269 shown in the picture.

**Describe alternatives you've considered**
Automatically considering multiple items from the same seller (red marked entries) as just one but that is probably more work than it's worth.

**Additional context**
![githubFetchCount](https://user-images.githubusercontent.com/39682681/81301394-5fa9c880-904f-11ea-81ca-f201d4f934ee.png)

**Comment by Kyusung4698** [comment]
## 0.6.28 (2020-05-09)

- added fetch count at the option menu (#692)

**Comment by MateusRoscoe** [comment]
Works great, exactly what I wanted. Thank you.
