### ISSUE TITLE
Cannot pricecheck anything (Item parsing error)

### ISSUE THREAD

**Issue by ShadowTrolll** [Kyusung4698/PoE-Overlay#697]
#Hi.
I just installed this app for the first time but I cannot pricecheck anything. It just says "Could not parse item" or something like that for everything I have tried (rare cluster jewel, blighted map, gloves and wand)
How do I make it work ? Thanks

Windows 10
Standalone PoE client
Windowed Fullscreen
Delirium League

**Comment by staixe** [comment]
try to enable "run initial search" on TAB "evaluate"

**Comment by ShadowTrolll** [comment]
I tried that. Didn't help.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Could you please post the item data (Ctrl + C while hovering) of those failing items? Thanks! Also please make sure you have the correct language selected. This should be the same as your client language.

**Comment by ShadowTrolll** [comment]
Hi. I did all those things and even exitted/reopened the app but nothing helped. Then I went turned off my PC because I went to do something else and when I came back and started it the app started working. Strange, but it is okay now.
