### ISSUE TITLE
Add pseudo filters for total values etc.

### ISSUE THREAD

**Issue by josemariafs** [Kyusung4698/PoE-Overlay#7]
A required feature for incoming updates must to be a selector of total values, example:

Armor with:
+ 60 Life
+ 50 Strength

Total Life: 85 Life

From Wiki:
Every 10 strength grants an additional 5 maximum life.

Then we are allowed to click to filter life properly. Same for "Total Fire Damage" (fire damage + elemental damage + etc.)

Thanks for your great work.

**Comment by Kyusung4698** [comment]
Seems reasonable. Do you have a compiled list of such total filters with their corresponding values? Thanks!

**Comment by josemariafs** [comment]
No sorry :(

Did you check RePoE? Maybe this information is there:

https://github.com/brather1ng/RePoE

**Comment by vadash** [comment]
There should be more advanced logic. App should sum all res on item it, substruct a bit (10%) and prefill it as minimum value in search. For example we have two toned boots with extra 30 res. (12+12+30)-10% = 51% pseudo res

**Comment by livejamie** [comment]
Thanks so much for your hard work

**Comment by Kyusung4698** [comment]
0.5.1 now supports the most common filters. As this requires manual mapping i did not include all. If you need any other pseudo filters make sure to report back. Thanks for your great suggestion!

**Comment by Kyusung4698** [comment]
I'll close this for now. As said - If there are any missing pseudo filters please create a new issue. Thanks!
