### ISSUE TITLE
Avast is detecting 0.4.4 as virus.

### ISSUE THREAD

**Issue by Haroldyolo** [Kyusung4698/PoE-Overlay#70]
Hi Kyusung,
I am not saying it actually contains a virus, but avast is detecting it as one. (Maybe some new hooks that you used?)

The antivirus didn't have any problems with the previous versions.

Could you please investigate?

Thanks.

**Comment by Kyusung4698** [comment]
Starting from version 0.4.2 i've changed the keybinding method from build-in to a custom one using a keyboard hook. The AV probably detects this hook. As this is the same as you would use in a keylogger. Also to support the ALT key i needed a more low level solution - so this may why it is now detecting it as a virus.

I'm not happy with the current keybinding solution - may change again in the future.
