### ISSUE TITLE
Can't Price Tag items

### ISSUE THREAD

**Issue by rsxownes** [Kyusung4698/PoE-Overlay#708]
Cannot Price items using the Tagging method. Upon clicking on a price using the bar graph view. A message appears at the bottom stating the following. 

**"Only items without an existing note can be fast tagged. Note has been copied instead."**

I am not sure what does means, and I am not seeing anything in the settings about a note. Please help.

I am running windows 10 and using windowed full screen in the game
![82170231-d6399800-9891-11ea-85d7-c1d2ac5ee14e](https://user-images.githubusercontent.com/65521394/82170339-2153ab00-9892-11ea-8593-105f5f3f26df.png)

**Comment by DavidRehm** [comment]
Same here. This is like the #1 functionality-feature of PoE-Overlay compared to other alternatives and it currently doesn't work. :(

**Comment by ishid4** [comment]
I'm wondering what would CTRL+V do? Can you try, please?
