### ISSUE TITLE
Unable to bind mouse buttons for commands

### ISSUE THREAD

**Issue by kringell** [Kyusung4698/PoE-Overlay#71]
On trademacro i had one of the side mouse buttons bound as the hideout button. When i try to bind it on the overlay it doesnt register the input and i cant manually set it either.

**Comment by Kyusung4698** [comment]
For now only F1-F24, 0-9, numpad 0-9 and a-z are supported. As a workaround you can change the pressed button on your mouse to be like F5 and then it'll also work.
