### ISSUE TITLE
Compile for linux got issue

### ISSUE THREAD

**Issue by AndyHoang** [Kyusung4698/PoE-Overlay#712]
# 🐞 bug report

**Describe the bug**
I understand that we dont support linux for most of the time. With recent update of proton ge, poe seem playable now so Its really worth to make a try, sadly its wont compile..
I dont have much exp with nodejs so I cant tweaking around with it, hoping you can point me some ways
Compile with linux env
Thanks for your plugin, I used it in window everytime!

**To Reproduce**
```
npm install
npm run electron:rebuild
npm run electron:linux

```

Log
```
chunk {} runtime.689ba4fd6cadb82c1ac2.js (runtime) 1.45 kB [entry] [rendered]
chunk {1} main.d2fa638ade7df5e43a72.js (main) 17.5 MB [initial] [rendered]
chunk {2} polyfills.379ccc7ba2ab471a50f2.js (polyfills) 44.3 kB [initial] [rendered]
chunk {3} polyfills-es5.ccb007650eb5767d1c79.js (polyfills-es5) 127 kB [initial] [rendered]
chunk {4} styles.1ffe51b5bdb9f9807d5e.css (styles) 173 kB [initial] [rendered]
Date: 2020-05-26T14:14:04.557Z - Hash: 1312bd788b83fb8d736b - Time: 51549ms

WARNING in budgets: Exceeded maximum budget for initial. Budget 10 MB was not met by 7.88 MB with a total of 17.9 MB.
  • electron-builder  version=21.2.0 os=5.4.42-1-lts
  • loaded configuration  file=/home/andyhoang/workplace/clone/PoE-Overlay/electron-builder.json
  • writing effective config  file=release/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=extract-file-icon@0.3.2, node-window-manager@2.2.2, robotjs@0.6.0 platform=linux arch=x64
  • install prebuilt binary  name=robotjs version=0.6.0 platform=linux arch=x64
  • build native dependency from sources  name=robotjs
                                          version=0.6.0
                                          platform=linux
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.3
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for cached prebuild @ /home/andyhoang/.npm/_prebuilds/71407d-robotjs-v0.6.0-electron-v76-linux-x64.tar.gz
    prebuild-install http request GET https://github.com/octalmage/robotjs/releases/download/v0.6.0/robotjs-v0.6.0-electron-v76-linux-x64.tar.gz
    prebuild-install http 404 https://github.com/octalmage/robotjs/releases/download/v0.6.0/robotjs-v0.6.0-electron-v76-linux-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=8.2.3 runtime=electron arch=x64 libc= platform=linux)

  • packaging       platform=linux arch=x64 electron=8.2.3 appOutDir=release/linux-unpacked
  • building        target=AppImage arch=x64 file=release/poe-overlay-0.6.28.AppImage
  ⨯ image /home/andyhoang/workplace/clone/PoE-Overlay/dist/favicon.png must be at least 256x256
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poe-overlay@0.6.28 electron:linux: `npm run build:prod && electron-builder build --linux`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the poe-overlay@0.6.28 electron:linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/andyhoang/.npm/_logs/2020-05-26T14_14_15_566Z-debug.log


```

## 🌍  Your Environment
                    /-                      andyhoang@andyhoang-pc
                   ooo:                     ----------------------
                  yoooo/                    OS: ArcoLinuxD
                 yooooooo                   Kernel: 5.4.42-1-lts
                yooooooooo                  Uptime: 1 hour, 47 mins
               yooooooooooo                 Packages: 1218 (pacman)
             .yooooooooooooo                Shell: zsh 5.8
            .oooooooooooooooo               Resolution: 1920x1080
           .oooooooarcoooooooo              DE: KDE5
          .ooooooooo-oooooooooo             WM: KWin
         .ooooooooo-  oooooooooo            Theme: Breeze Dark [KDE5], Breeze [GTK2/3]
        :ooooooooo.    :ooooooooo           Icons: breeze-dark [KDE5], breeze-dark [GTK2/3]
       :ooooooooo.      :ooooooooo          CPU: AMD Ryzen 5 2600 (12) @ 3.400GHz
      :oooarcooo         .oooarcooo         GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590
     :ooooooooy           .ooooooooo        Memory: 7121MiB / 16027MiB

- Version: master branch
- PoE: Lutris 3.10.0/e English

**Comment by Sabotaz** [comment]
`  ⨯ image /home/andyhoang/workplace/clone/PoE-Overlay/dist/favicon.png must be at least 256x256`

i modified the src/favicon.png accordingly, and it works.

**Comment by AndyHoang** [comment]
Thanks, I passed the error, file compiled sucessfully and started ok.

But the functionality is off. I can Ctrl +D, open wiki, go to hideout anything, feel like it doesn't catch the hotkey pressed.

I tried window mode and all others (to make sure its not the vulkan problem)
