### ISSUE TITLE
Not working with Vulkan

### ISSUE THREAD

**Issue by Petusillos** [Kyusung4698/PoE-Overlay#715]
After installation of this patch:

https://www.pathofexile.com/forum/view-thread/2866812

The tool is not able to be displayed on front if Vulkan is selected (works fine if I switch to DX11)

**Comment by Reithan** [comment]
It displays for me, but the behavior is very odd, window loses focus and it doesn't swap back to the window after the overlay popup.

**Comment by Reithan** [comment]
I think this has something to do with the Vulkan window forcing focus on the game window?

FWIW other overlays are having similar issues atm.

**Comment by xire28** [comment]
As a temporary workaround:
- Set "Windowed" instead of "Windowed fullscreen" in the configuration
- Use an external borderless fullscreen software like https://github.com/Codeusa/Borderless-Gaming

Most reliable way I found to fix the focus stealing problem and have a similar result

**Comment by Reithan** [comment]
FYI, it also isn't a problem in actual windowed mode - just fullscreen windowed.

**Comment by C1rdec** [comment]
Hey guys I'm the father of [Poe Lurker](https://github.com/C1rdec/Poe-Lurker) and I'm currently investigating the issue... @Reithan I'll keep you posted here.

**Comment by AngryRoleplayer** [comment]
can confirm the issue
completely hides the GUI in Vulkan

**Comment by C1rdec** [comment]
@Kyusung4698 I found a work around you need to change the `Window Style` of Path of Exile.
I dont know how you will achieve this with Electron but here is what I've done in C#. 

https://github.com/C1rdec/Poe-Lurker/blob/5055a1032f02a0f7993a0228b23a86e5bf88e0a9/src/Lurker/Helpers/DockingHelper.cs#L143-L146

**Comment by Kyusung4698** [comment]
> @Kyusung4698 I found a work around! You need to change the `Window Style` of Path of Exile.

@C1rdec Thanks for your input! This does seems more of a Vulkan issue. Hopefully this gets fixed by GGG soon.

I'm also working on the new 1.0 version of this tool which will be released on 10th of June. This will be working in native fullscreen mode. So should no longer be an issue.

**Comment by SinisterGenocide** [comment]
this is happening to me but it wont work with directx11 only works with vulkan for me
