### ISSUE TITLE
Cloud gaming support

### ISSUE THREAD

**Issue by rax4r** [Kyusung4698/PoE-Overlay#719]
Im' playing PoE using Beeline Gaming, and I can copy items information into my clipboard, so I'm able to use Trade Macro and Awakened Trade Macro, but poeoverlay not working. I think it because my game window name is "Beeline Gaming", not "Path of Exile" (that was the issue with other trade programs, and i solved it). So i'm curious if I can use poeoverlay.

**Comment by yoinx** [comment]
You could always try adding it to the array here and build yourself to see if it fixes it?

https://github.com/Kyusung4698/PoE-Overlay/blob/ba5e001825017e0873abf47c2929db4f0f0dc64f/electron/game.ts
