### ISSUE TITLE
suggestion: option to open the query in my default browser instead in the tool browser window

### ISSUE THREAD

**Issue by Xebtria** [Kyusung4698/PoE-Overlay#73]
would be nice, sometimes you get a better picture of the price range when seeing the stuff on the trade page itself.

edit: found it, but would be nice if an option for opening it in my own browser would exist. changed titel accordingly.

**Comment by Kyusung4698** [comment]
CTRL + Click opens the query in the default browser.

**Comment by Xebtria** [comment]
I see, thanks. :)
