### ISSUE TITLE
Poe overlay in vulkan

### ISSUE THREAD

**Issue by javijec** [Kyusung4698/PoE-Overlay#730]
# 🐞 bug report

**Describe the bug**
Poe overlay 1.0 dont work in Path of Exilen with Vulkan en windowed fullcreen

**To Reproduce**

Turn on Poe overlay
turn on Path of Exile with Vulkan
Poe Overlay dont start
Turn off Poe overlay
Changue Path of Exile to Directx11
turn off Path of Exile
Turn on Poe overlay
turn on Path of Exile
Poe Overlay works fine

## 🌍  Your Environment

- Version: 1.0.0
- PoE: non-Steam 3.10.2c/ English

**Comment by ShizuneHakamichi** [comment]
GGG has to update their game to allow for this. There is NOTHING Script devs can do at this time.
