### ISSUE TITLE
Stash Scrolling is broken since v1.0.0

### ISSUE THREAD

**Issue by WhiteFang5** [Kyusung4698/PoE-Overlay#731]
# 🐞 bug report

**Describe the bug**

Stash Scrolling is broken

**To Reproduce**

1. Move you mouse off the stash window
2. Hold down CTRL and scroll the mouse wheel
3. Notice it not scrolling through the stashes

**Expected behavior**

You can scroll the stash where ever your mouse is located on the screen.

**Screenshots**

## 🌍  Your Environment

- Version: v1.0.0

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Overwolf currently does not support hotkeys bound to the MouseWheel. I've create a [feature request at their forum](https://discuss.developers.overwolf.com/t/capture-mousewheel-input/632). Til then i'm working on a workaround.

**Comment by Tikia** [comment]
> 
> Hi, thanks for creating an issue. Overwolf currently does not support hotkeys bound to the MouseWheel. I've create a [feature request at their forum](https://discuss.developers.overwolf.com/t/capture-mousewheel-input/632). Til then i'm working on a workaround.

Hi,
I tried v0.6, it was so great !
I just discover v1, which is so much better, what a great job !!!

Before Overwolf add this feature, can you make it with keyboaord ?

Thanks :)

**Comment by Bawon** [comment]
I'm not a dev, but if you have AHK you can put this 
``` 
^WheelUp::
Send, ^{Left}
return

^WheelDown::
Send, ^{Right}
return 
```

into a file and name it "something.ahk"
simply maps ctrl+scroll wheelup to ctrl + arrow left and vica versa for scroll down.
