### ISSUE TITLE
Alt+F in v1.0.0?

### ISSUE THREAD

**Issue by MegaEzik** [Kyusung4698/PoE-Overlay#733]
The item highlighting function (Alt + F) in update v1.0.0 has disappeared.

Sorry for my bad English)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Will be added again with the next version.

**Comment by MegaEzik** [comment]
Thanks)

**Comment by Kyusung4698** [comment]
## 1.0.2 (2020-06-16)

- added misc module
  - stash highlight on `alt+f`

has been added. you should see a quick hint on how to use it once it's updated.
