### ISSUE TITLE
Overwolf: PoE Overlay could not be loaded.

### ISSUE THREAD

**Issue by fuba82** [Kyusung4698/PoE-Overlay#737]
# 🐞 bug report
The Overwolf Version is broken and not able to load.
I can click "Try again" 1000+ Times but... -> See Screenshot

**Screenshots**

![image](https://user-images.githubusercontent.com/11580974/84730126-aa472a80-af95-11ea-8470-503b396b19f9.png)

## 🌍  Your Environment

- Version:  1.0 Overwolf Version 
- PoE:  Steam 3.10.2d English

**Comment by conetopia** [comment]
:( Might be a steam compatibility issue.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This can occur if the GGG Api is currently not reachable. The newest version has a cached version of those requests to prevent this. If this is still an issue please attach your application logs. See following post on how to do so.
https://support.overwolf.com/support/solutions/articles/9000176827-how-to-get-your-overwolf-logs

**Comment by fuba82** [comment]
Yes your're right, seems to be the GGG Api!
Let see of the error happens again

**Comment by NavanBethrax** [comment]
Same bug here. Tried restarting, reinstalling for 3 days now.

`2020-06-21 10:18:39,611 (WARN) </dist/poe-overlay-overwolf/main.d988df2af755987b7523.js> (:1) - An unexpected error occured while loading PoE Overlay. 
`

My firewall is disabled too.
