### ISSUE TITLE
Banned 6/16/2020

### ISSUE THREAD

**Issue by conetopia** [Kyusung4698/PoE-Overlay#739]
Did anyone else get banned 4 hours after using the new OverWolf verson of Poe-Overlay?

Not only was it extremely annoying to use, because it sounded like someone was tapping on a microphone every time someone wanted to trade, and boxes took up like half the screen... with no adjustable's...   But causes bans? RIP

Was on for like 6 hours yesterday, didn't really use poe-overlay much.
but was on for like 3-4 hours today, and started messing with the new trade buttons 
then got banned. so beware the new poe trade features? idk

**Comment by Hyve747** [comment]
Did you recive an email from GGG about the ban reason?
