### ISSUE TITLE
Suggestion: Option to remove item base from query altogether

### ISSUE THREAD

**Issue by Xebtria** [Kyusung4698/PoE-Overlay#74]
Example usecase: Labyrith enchants. I want to see all helmets with a certain helm enchant to evaluate the enchant price on its own, instead of only hubris circlets with this enchant. I guess there are some more use cases, but that is the one I have on my mind

**Comment by Kyusung4698** [comment]
Added with [0.5.0](https://github.com/Kyusung4698/PoE-Overlay/releases/tag/0.5.0). Thanks for your suggestion!
