### ISSUE TITLE
[4K Support] Windows Be Giant

### ISSUE THREAD

**Issue by conetopia** [Kyusung4698/PoE-Overlay#742]
Version 0.6.28 Had these nice somewhat decent size windows, Settings window was slightly too big, not a huge big deal......

Now Using  version 1.02
HOLY WOW ! THE WINDOWS ARE LIKE SUPER HUGE !!!!!!!!!!!!!!!!!!!!!!!!!
Example instead of Ctrl+D , now using alt+D
That window is 4x as big now.... not needed, takes up almost 1/3'rd of my screen.
Settings window is 2.5x as big, takes up 80% of my screen.
When I first went to use this, and hit F7.... I didn't even know there was the medium sized window behind it telling me tutorial instructions...  Because the settings window took up the whole screen, and it was hard to figure out i had to click the top and drag the settings window down, so that i can read/fallow the instructions window in the background.

Place Make support for 4k resolution??? so that the windows are so huge? you would think they would be smaller? One would think " wow i can't imagine would 1080 would look like." Would it even fit the screen? ha ha ha.

But anyways, yeah all the windows need to be like half if not 1/3'rd of the size they are now.
Please make the current size 100% - with a scale going from 10-200% 
Would be nice.
Size may matter depending on setup.

**Comment by conetopia** [comment]
[https://i.gyazo.com/6bdd92b305944c1fdccfcfbc41cdd407.jpg](url)
In addition to that, I would really like to see the market window... zoomed out...
so i can see more results, and such, maybe expand outwards and do 2 rows instead of just the 1 row?

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. The UI currently only scales based on the Windows DPI setting. It does look fine on a normal full hd screen. A UI scale factor has been requested here: #740 

The market feature has the same size as the stash window. This was a intentionally design for following effect: Open your stash and then the market. The chat window is now at the right border of the market and you can see your chat will requesting items. 
BUT multiple layouts has been requested and will be added later.
