### ISSUE TITLE
Doesn't it work at Korea(KAKAO) Server anymore?

### ISSUE THREAD

**Issue by YouMeanUMin** [Kyusung4698/PoE-Overlay#746]
After update PoE-Overlay to 1.0.0(currently 1.0.3), it doesn't work Korea(KAKAO) Server.

When I turn on this program(with OVERWOLF), it just load and search POE Client nevertheless I did it.

it's not operated, just remaining that window(screenshot).
![image](https://user-images.githubusercontent.com/67117935/85053657-d224d100-b1d5-11ea-96b9-37c80796dbcb.png)

How can I use this program at KR Server?

Please give me some advise. :(

**Comment by RevBlue86** [comment]
Did you try launching the game?
You should get the first time user manual when you launch, or just press F7 in-game to open the main settings screen

**Comment by YouMeanUMin** [comment]
yes, of course i did launch the game, POE but it didn't work...
I tried to press F7 key a few seconds ago, but it didn't work too. :(

But it works well when I running POE Global Server. just did not KOREA Server.

How should I do that?

**Comment by sunghlim** [comment]
Same problem here

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Overwolf is used to detect the running game. You can try renaming the executable for now:

**x64**
PathOfExile_x64_KG.exe -> PathOfExile_x64.exe

**x86**
PathOfExile_KG.exe -> PathOfExile.exe

I'll check with Overwolf and report back asap.

**Comment by sunghlim** [comment]
Thanks for the fast reply.
I'll be waiting for your feedback on the issue.

One thing I would like to note is that your temporary solution actually
doesn't work with the Korean server (changing the name of the execution
file).
The Korean server only opens with _KG names files, when I changed the name,
the server just downloaded a new PathOfExile_x64_KG.exe file.
