### ISSUE TITLE
Ctrl+mousewheel does not work when not over the stashtab

### ISSUE THREAD

**Issue by Xebtria** [Kyusung4698/PoE-Overlay#75]
mouse has to be over the stashtab in order to scroll the tabs. via trade macro it used to work when mouse was anywhere, like in the inventory.

**Comment by Haroldyolo** [comment]
Works fine for me.

**Comment by Xebtria** [comment]
I restarted a couple of times both poe and the tool, and sometimes it works and sometimes it doesn't. can't pinpoint if there is an exact trigger when it doesnt work :(

**Comment by Haroldyolo** [comment]
Hmm it actually started playing up on mine too. Sometimes it will simply not work. I will open new issue.

**Comment by Kyusung4698** [comment]
See #76.
