### ISSUE TITLE
Overwolf's launcher can't detect PoE KAKAO

### ISSUE THREAD

**Issue by SJCubed** [Kyusung4698/PoE-Overlay#750]
# 🐞 bug report

**Describe the bug**

The launcher cannot detect that POE client is running, probably due to my client being the KR server client through Daum/Kakao publisher.

**To Reproduce**

1. PoE Overlay launched.
2. Wait for overlay launcher to show waiting for poe to launch.
3. Launch PoE through https://poe.game.daum.net/ launcher
/////
1A. Launch PoE through https://poe.game.daum.net/ launcher
2A. start overwolf PoE overlay

In either case, PoE Overlay cannot detect that PoE is up and running.

**Expected behavior**

PoE Overlay should run.

**Screenshots**

![f723ab87cc2511b631acd6b48cbd102b](https://user-images.githubusercontent.com/46447029/85140241-f4732900-b27f-11ea-9d1d-3cca71a5db28.jpg)

## 🌍  Your Environment

- Version:  e.g. 0.6.9 portable
Not sure where to find the version, but I'm guessing it's 1.0.2 overwolf since I downloaded it on 19 Jun 2020.
- PoE:  e.g. Steam 3.10.0/e English
KakaoGames 3.10.2d English locale

**Comment by SJCubed** [comment]
checking the program files, it tells me PoE Overlay version was 1.0.3

**Comment by cheonmux** [comment]
Same problem for me.

**Comment by SnuK87** [comment]
Same here

**Comment by ShooBear** [comment]
Same here too

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. The KAKAO version is currently unsupported. Overwolf is working on a fix. It should be working soon 1-3 days.

**Comment by SJCubed** [comment]
> 
> 
> Hi, thanks for creating an issue. The KAKAO version is currently unsupported. Overwolf is working on a fix. It should be working soon 1-3 days.

thank you, will it be included in the next patch in 1.0.3 or hotfixed?

**Comment by Kyusung4698** [comment]
> thank you, will it be included in the next patch in 1.0.3 or hotfixed?

This should get hotfixed. It's a small change at the Overwolf client which should get this over the air. They're already working and testing it. They just need to make sure everything works correctly. I'll keep you updated.

**Comment by Kyusung4698** [comment]
Overwolf just pushed an update for this to be supported. You may need to restart the Overwolf client once. Can you please report back? Thanks!

**Comment by SJCubed** [comment]
> Overwolf just pushed an update for this to be supported. You may need to restart the Overwolf client once. Can you please report back? Thanks!

it's working fine now! thank you
