### ISSUE TITLE
Poe Overlay not working with 3.11 update

### ISSUE THREAD

**Issue by mygod23** [Kyusung4698/PoE-Overlay#752]
# 🐞 bug report

**Describe the bug** I have test PoE Overlay 1.0 yesterday at its worked. However, today after update to 3.11 it is not working atm. The program still turned on but all of its commands are disabled

**To Reproduce**

**Expected behavior**

**Screenshots**

## 🌍  Your Environment

- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by lxsli** [comment]
Some commands are working for me, EG scroll stash and go to hideout. Price item isn't though.

**Comment by Sheodar** [comment]
Scrolling stash doesn't work for me. It works strange. It could work on now. GGG added "lock" option for tabs, and it conflicts with poe overlay

**Comment by RVLBLACK** [comment]
I am having the same issues. Seems to only allow me to f5 to hideout and nothing else.. No trade macro...

**Comment by lxsli** [comment]
Works for me now.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Do you get any visible error notifications? If not you can generate a application log package and send it to `kyusung4698@gmail.com`. See following topic on how to do so:
https://support.overwolf.com/support/solutions/articles/9000176827-how-to-get-your-overwolf-logs

On the scroll part. This is currently not support but will be added soon. The behavior you're experiencing is the games natural one.

**Comment by RVLBLACK** [comment]
It seems to not function while trying to run poe in vulkan. Directx11 seems to allow the program to function as intended.

**Comment by mygod23** [comment]
> Hi, thanks for creating an issue. Do you get any visible error notifications? If not you can generate a application log package and send it to `kyusung4698@gmail.com`. See following topic on how to do so:
> https://support.overwolf.com/support/solutions/articles/9000176827-how-to-get-your-overwolf-logs
> 
> On the scroll part. This is currently not support but will be added soon. The behavior you're experiencing is the games natural one.

Hi
This is the log file I generated. And yes, I use Vulkan and it worked if I turned to Directx11. However, Vulkan is better for my game performance atm so I'm wonder can it be fixed? 
[OverwolfLogs_2020-06-24_09-39-54.zip](https://github.com/Kyusung4698/PoE-Overlay/files/4822943/OverwolfLogs_2020-06-24_09-39-54.zip)

**Comment by Kyusung4698** [comment]
> This is the log file I generated. And yes, I use Vulkan and it worked if I turned to Directx11. However, Vulkan is better for my game performance atm so I'm wonder can it be fixed?
> [OverwolfLogs_2020-06-24_09-39-54.zip](https://github.com/Kyusung4698/PoE-Overlay/files/4822943/OverwolfLogs_2020-06-24_09-39-54.zip)

Thank you for the logs. Unfortunately Vulkan is not fully supported yet. It works on most machines but some are having issues. A fix is been working on and should hopefully go live this week.

**Comment by ZiiLosDiiDu** [comment]
Hi,I'm playing on both a desktop and a laptop with dx11 on the desktop and vulkan on the laptop.Until yesterday it was working on the desktop but it wasn't working on the laptop.Today I realised that it't not working anymore on the desktop but solved it by switching to vulkan.

**Comment by Kyusung4698** [comment]
To update on this topic. Overwolf just released a new client version which now supports the Vulkan renderer.
