### ISSUE TITLE
Trade window - whisper and invite not working

### ISSUE THREAD

**Issue by Phonts** [Kyusung4698/PoE-Overlay#754]
After 3.11 whenever I try to invite or whisper someone that I'm trading, the chat box flashes like it's trying to type out the command and then immediately closes.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This has been reported lately and it seems like there is an issue with accessing the clipboard. It's used to copy the text into the chat window. Do you have any other application running modifying/ accessing the clipboard?

**Comment by GrenRT** [comment]
> Hi, thanks for creating an issue. This has been reported lately and it seems like there is an issue with accessing the clipboard. It's used to copy the text into the chat window. Do you have any other application running modifying/ accessing the clipboard?

I have same problem. Don`t have other application modifying clipboard. What other information will help solve the problem?

**Comment by RightClickHarder** [comment]
> > Hi, thanks for creating an issue. This has been reported lately and it seems like there is an issue with accessing the clipboard. It's used to copy the text into the chat window. Do you have any other application running modifying/ accessing the clipboard?
> 
> I have same problem. Don`t have other application modifying clipboard. What other information will help solve the problem?

I had the same issue, I read Kyusung4698's reply and i closed down any auto hotkey programs i had running (even though the hotkeys were suspended), this worked.

**Comment by Phonts** [comment]
Disabling autohotkey functions worked.
