### ISSUE TITLE
Suggestion: Allow Us to Disable Outgoing Trades

### ISSUE THREAD

**Issue by livejamie** [Kyusung4698/PoE-Overlay#755]
Love the trade functionality but only want it for incoming trades.

Thanks!

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Will be added with the next version.

**Comment by Kyusung4698** [comment]
## 1.0.5 (2020-06-23)

- added trade filter setting (Incoming & Outgoing, Incoming)

Has been added with the new version.
