### ISSUE TITLE
Massive FPS drop after running poe-overlay. steam/3.11.0d 

### ISSUE THREAD

**Issue by Kalik93** [Kyusung4698/PoE-Overlay#757]
Oh hi there! 😄

**Describe the bug**
I installed PoE overlay for PoE 3.11 at first day of league and everything worked fine. Second day it started to cutting my fps hard, from 100+ to 28-29, and when poe is running in background FPS drops to 3. 
Shortcuts are not working - F7 to show settings doesn't work, ALT+D also, many others doesn't work. However, default '/hideout' and '/dnd' bindings work fine. 

**To Reproduce**
1. Run Poe Overlay
2. Run Poe

**Expected behavior**
No FPS drops, shortcuts working as supposed to do.

Environment

- Version: Client version: 0.148.0.4 (64-bit)
 PoE: Steam 3.11.0/d English

**Comment by aizaku** [comment]
I have the same issue. Fresh installation too.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Can you please generate an application logs package and send it to `kyusung4698@gmail.com`. I'll look into it ASAP. See following article on how to do so 
https://support.overwolf.com/support/solutions/articles/9000176827-how-to-get-your-overwolf-logs

A few questions beforehand:
Do you use Vulkan? If yes does switching to DirectX increase your fps while using the tool?
Also do you have Death Capture/ Kill Capture enable? If yes try turning it off.

**Comment by aizaku** [comment]
I will try sending logs shortly.
I am using Vulkan and had death and kill capture enabled. I cannot turn it off now, the settings (and other shortcuts) are not working.
Is there a manual way to reset settings?

**Comment by Kyusung4698** [comment]
@aizaku Overwolf released a new client version with Vulkan support. Hopefully this fixes all your issues. 

On topic. The new client should also improve the FPS for the Vulkan renderer. Please report back. Thanks!
