### ISSUE TITLE
POE overlay not starting up.

### ISSUE THREAD

**Issue by TBroderick99** [Kyusung4698/PoE-Overlay#758]
# 🐞 bug report

**Describe the bug**
when i launch POE overlay the overwolf launcher loads but POE launcher doesn't appear. in my app tray i can see overwolf is running but POE overlays small launcher window doesn't show up. Even when i open POE it doesn't start up. i have restarted my pc and terminated overwolf process and opened again several times.

**To Reproduce**
1. PoE Overlay launched.
2. wait for Overwolf loading
3. Overwolf loads but not POE overlay

**Expected behavior**
POE overlay "waiting for poe to launch" window should appear. and poe overlay should be usable in game.

## 🌍  Your Environment

-Overwolf Version: 0.148.0.4 (64 bit)
- PoE: e.g. Steam 3.10.0/e English

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. What client are you using? The KAKAO version is currently not supported but should be working soon.

**Comment by Kyusung4698** [comment]
Support for the KAKAO version is now rolling out. Please report back if everything works. Thanks!
