### ISSUE TITLE
how to watch replay?

### ISSUE THREAD

**Issue by KiriGitter** [Kyusung4698/PoE-Overlay#759]
I don't find any way to watch my death highlight even though I turned the feature on. I even received the notification that "The capture of events has been started". In the video, I see a replay overlay, but I did not get any.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Unfortunately the game events which are required to capture the replay are currently down. They should be working again soon.

**Comment by Kyusung4698** [comment]
Game events are back online. You should be able to replay your death.
