### ISSUE TITLE
Overlay will randomly stop working after last update

### ISSUE THREAD

**Issue by Haroldyolo** [Kyusung4698/PoE-Overlay#76]
I am trying to reproduce the issue but its hard. Some time it will happen after the first price check. After pressing CTRL+D it will simply not come up with the overlay window. Other times it will stop after 3 or 4 price check. As I like using my default browser maybe that is the issue? After pressing CTRL+Click it gets stuck somewhere?
Mouse scroll wheel randomly stops working too. Tried restarting the tool and PoE few times.

**Comment by Kyusung4698** [comment]
I think i figured it out. Try pressing ALT + any key if this happens (while game is focused). Basically the ALT state got stuck by using ALT+TAB.

**Comment by Kyusung4698** [comment]
0.5.0-alpha.0 should fix this. Please let me know if it is!

**Comment by Haroldyolo** [comment]
This was indeed a case of ALT stucking on ALT+TAB. Thanks for fixing so quick.
