### ISSUE TITLE
POE overlay Not Work

### ISSUE THREAD

**Issue by igorcastroo** [Kyusung4698/PoE-Overlay#761]
Describe the bug

The overlay poe doesn't work with the game,

when I open the game the overlay closes "/

I went back to version 0.6.29

which is working normally for me

**Comment by ParsHere** [comment]
Unfortunately the author took this great addon and pretty much ruined it with Overwolf.  Fortunately there is an overwolf free fork available. Just search reddit.

Overwolf leeches user data and has an overall history of scummy practices.

**Comment by igorcastroo** [comment]
I agree with you friend, it works much better before

I'll look for the fork link, thank you very much!

**Comment by RevBlue86** [comment]
You're using Vulkan? It's not fully supported yet but will be coming soon(hopefully this week)
Try changing to dx11 and see if that works
