### ISSUE TITLE
Suggestion: Hi, so i realized when i installed the new poe overlay with overwolf that the control + center mouse button rotation was only working whenb my mouse was hovering over my stash and was wondering why it wasn't like in the old poe overlay and worked everywhere in particular over my inventory ? Ty very much for your work anyways :)

### ISSUE THREAD

**Issue by neometaz** [Kyusung4698/PoE-Overlay#764]
# 🚀 feature request

Hi, so i realized when i installed the new poe overlay with overwolf that the control + center mouse button rotation was only working whenb my mouse was hovering over my stash and was wondering why it wasn't like in the old poe overlay and worked everywhere in particular over my inventory ? Ty very much for your work anyways :)

**Comment by Kyusung4698** [comment]
Hi, thank you for creating an issue. The current version does not support this feature yet. The current behavior you're experiencing is actually how the game natural handles it.

**Comment by zymox** [comment]
You can use a simple AHK script for that:

```
^WheelUp::
Send, ^{Left}
return

^WheelDown::
Send, ^{Right}
return
```

This just binds mousewheel to CTRL+Left and CTRL+Right (which is what you want)

**Comment by neometaz** [comment]
You are my hero !
Thank you so much and good luck in whatever you are doing x)

**Comment by Kyusung4698** [comment]
## 1.0.9 (2020-07-29)

- added stash navigation on ctrl + mousewheel
