### ISSUE TITLE
Suggestion: Add option to skip to initial tutorial

### ISSUE THREAD

**Issue by lucasbaile** [Kyusung4698/PoE-Overlay#765]
Today I noticed the app updated and I got prompted for the tutorial once again

The issue here is the tutorial is quite long and is quite obnoxious if you already use the app for quite a while

This feature would be much appreciated :)

**Comment by conetopia** [comment]
Yes I agree, I've had to uninstall , and install a fresh copy twice. I don't like having to rush through he tutorial either ha ha.

**Comment by Kyusung4698** [comment]
## 1.0.10 (2020-08-02)

- added skip button at the tutorial (#765)
