### ISSUE TITLE
Cann't use evaluate option

### ISSUE THREAD

**Issue by FelipeChante** [Kyusung4698/PoE-Overlay#766]
The evaluate option is not working, I tried several itens and always shows this massage.
I already tried to change the languages and none of them worked. I also tried mess with the evaluate option but it not worked as well.
![image](https://user-images.githubusercontent.com/67375932/85567780-84f69400-b607-11ea-9460-6c0938b62840.png)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. What item are you trying to parse? Is it failing for all type of items or just some? If so please post the item data (CTRL + C while hovering). Thanks!

**Comment by FelipeChante** [comment]
it is failing in all itens (currency, unique, rare) to be honest any check option (inspect, evaluate, translate) are not working, the only shortcut I can use is the market alt+M. It always pops up this messagem to check the language.

**Comment by maui1911** [comment]
I have the same problem

**Comment by Kyusung4698** [comment]
Can you post the copied item data from on of your items? Thanks!

**Comment by maui1911** [comment]
I tried it again, and it works now. Maybe the api service was down or something?
