### ISSUE TITLE
Suggestion: Add ability to drag pricecheck overlay window not just by the dark window header

### ISSUE THREAD

**Issue by Wiella** [Kyusung4698/PoE-Overlay#768]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

Before switching to Overwolf - overlay window was always draggable by any part of the window, now it's only the dark header part that allows you to drag it. It's really annoying because you often have to move it around into a more convenient spot and it takes extra effort to do it now.

**Describe the solution you'd like**

Allow overlay to be draggable by any part once again, make it optional for people who might not like it. Although it might be worth making it draggable by the overlay window header (that contains item name) at all times.

**Describe alternatives you've considered**

Allow overlay to be draggable by the overlay window header (that contains item name). It's not the best solution, but the first thing I try to drag window with after not being able to drag it using a random point is that exact title, and only after I remember that it's not the actual window title.

**Additional context**

The main problem is, most probably, the fact that the dark overlay window header often blends with the game, for example look at this item pricecheck (especially from a new user standpoint) and think about what would you try to drag the overlay window with:

![image](https://user-images.githubusercontent.com/26770339/85703643-3a007d80-b6e8-11ea-86de-a26e9de90b58.png)

Item title, in most cases, stands out the most and probably would be the first thing to try and drag the window by.

**Comment by Kyusung4698** [comment]
## 1.0.9 (2020-07-29)

- updated windows to be draggable by their content (#768)
