### ISSUE TITLE
Suggestion: Alternative pricecheck overlay window layout

### ISSUE THREAD

**Issue by Wiella** [Kyusung4698/PoE-Overlay#769]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

Some items have quite a lengthy list of mods that makes them take a lot of vertical screen space, here is an example (by far not the worst case) of such item:

![image](https://user-images.githubusercontent.com/26770339/85707567-fc9def00-b6eb-11ea-89ef-bf926dca2450.png)

In this case price list is only slightly outside of the screen, but in some cases it can be almost fully pushed out of the screen.

**Describe the solution you'd like**

An alternative layout option for the pricecheck window. 
I've a bit of "photoshopping" to showcase one of the possible options:

![image](https://user-images.githubusercontent.com/26770339/85707960-5bfbff00-b6ec-11ea-84e7-e25255562299.png)

This way you can fit long lists of item mods at the same time as 30+ listings.

**Describe alternatives you've considered**

A compromise of hiding the item mods when you've performed the search (only after manual mods selection or manually pressing search) could be implemented, but I don't think it will be anywhere near the level of convenience the alternative layout provides. It can be a valuable additional option for the single-column (current) layout users though.

**Comment by Kyusung4698** [comment]
## 1.0.9 (2020-07-29)

- added experimental horizontal layout (enableable at the settings) for the evaluate dialog (#769)

Has been added but needs to be toggled in the settings. I've marked this as an experimental feature. Looking forward to your feedback 🚀
