### ISSUE TITLE
Suggestion: seller name inside market

### ISSUE THREAD

**Issue by prokn4h** [Kyusung4698/PoE-Overlay#773]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

Sometimes when buying stuff, like maps, you want to see seller's name, because same guy can be selling same maps and appear multiple times in the market list. You don't want to whisper him 3 times in a row.

**Describe the solution you'd like**

Add seller's name near each item in market search results.

**Comment by DinoMC** [comment]
This is required and high priority imho.
Sometimes one guy is selling 10 one of the same map, so I end up spamming him with 10 messages since the market list them as separate with no name, and I get reported.

**Comment by Kyusung4698** [comment]
## 1.0.8 (2020-07-09)

- added the seller name for items and bulk exchanges at the market (#773)

Has been added with the current version. Thanks for your suggestion!
