### ISSUE TITLE
Suggestion: Optional kick/leave party after done

### ISSUE THREAD

**Issue by Firedrops** [Kyusung4698/PoE-Overlay#774]
Feels quite rude to kick people immediately after a deal, just hoping we could toggle this on/off.

**Comment by Hyve747** [comment]
This is an intended feature, because there are some trolls out there, which go into your map after a trade. So by kicking them after thanking them, prevents this.

**Comment by Firedrops** [comment]
I get that, I was around during perandus and early bestiary and whatnots where this scam was going around, but it may be better to be optional with default "on" (to kick) so players can decide.

**Comment by zocke1r** [comment]
another thing is this might actually be a ToS violation, as one could argue that it is more than 1 action at once, one to send the message one to kick, and these days there is a setting to preventing people from going into your portals

**Comment by Hyve747** [comment]
That`s right, but to be honest, nobody from GGG cared about that fact on the other Trade Tools. This part is not giving an advantage compared to, for example 1 Button press = all Flasks used.

**Comment by zocke1r** [comment]
as far as i'm aware most other trade tools stick to the 1 button = 1 action rule. Where as this one not only breaks that rule but doesn't even give you the option not to. Short of not using it. And even if you correctly assume that ggg doesn't care about this specific instance of break the rule, but do you really feel comfortable risking every single users account on that assumption?

**Comment by Hyve747** [comment]
As you could have read on reddit, Overwolf checks all apps to be within TOS of the games. So seems like it´s fine how it is now.

**Comment by zocke1r** [comment]
So after reading through the overwolf reddit thread the only mention of overwolf checking seems to be in reference to them verifying that it's not a virus not that it actually abides by the TOS of the game and let's face it the rules on macros are quite simple 1 button = 1 action 1 chat message is one action, so sending 2 chat messages is a violation of that rule. But that is just my interpretation of what i read, and i'm a kinda cautious person who prefers to be on the safe side.

**Comment by Kyusung4698** [comment]
## 1.0.8 (2020-07-09)

- added a toggle to disable the leaving of a party via kick using the trade finished action (#774)

Can be disabled with the new update. Thanks for creating an issue.
