### ISSUE TITLE
Overwolf's launcher can't detect poe steam

### ISSUE THREAD

**Issue by happyish** [Kyusung4698/PoE-Overlay#775]
# 🐞 bug report

**Describe the bug**

the launcher cannot detect that POE client is running, it always says waiting for poe to launch. I have tried both windows fullscreen and fullscreen.

**To Reproduce**

in every case overlay says waiting poe to start. 

**Expected behavior**

poe overlay should detect the issue
**Screenshots**

![1](https://user-images.githubusercontent.com/58402012/85925145-29dece80-b89f-11ea-8b4c-c5c0909a48d7.jpg)

## 🌍  Your Environment

- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by happyish** [comment]
the problem have been solved. I suggest those who encounter with this problem that delete overwolf and install it back. it is something about overwolf, not poe overlay.

**Comment by regneel** [comment]
I had the same issue, fixed it by going into overwolf settings and finding that the overlay for poe was disabled. Also toggled auto launch for poe to on, restarted overwolf and then it was working
