### ISSUE TITLE
New Tutorial Bugged out on Evaluate

### ISSUE THREAD

**Issue by Neuroticgrim** [Kyusung4698/PoE-Overlay#777]
# 🐞 bug report

**Describe the bug**
It appears that on some PC's the POE Overlay Tutorial is not able to be completed. It appears that the tutorial is unable to read when a PC performs the evaluate. (Example, I was able to evaluate 12 items successfully, but the tutorial popup will not move to the next step or allow itself to be skipped.

https://imgur.com/eoEjhSY
https://imgur.com/Etx0ytA
https://imgur.com/bDlGy4N

## 🌍  Your Environment

- Version: Latest Overwolf Version
- PoE: Steam 3.11 e

**Comment by packrat2488** [comment]
Same. Never was able to complete tutotrial. Stuck at this point. Tried uninstall and reinstall. Tutorial resumed at the same stuck spot.
