### ISSUE TITLE
Unique Maps aren't searching correctly Based on Tier.

### ISSUE THREAD

**Issue by conetopia** [Kyusung4698/PoE-Overlay#778]
Went to price check a T14 Unique Atoll Map.
Said 1-3 chaos

Went on official website, nothing less than 6 chaos?
Searched for T11 on official website, and eventually realized....

In-game poe-overlay has T14 highlighted, but its searching all tiers....

**Comment by Kyusung4698** [comment]
## 1.0.7 (2020-07-01)

- fixed an issue querying the map tier
