### ISSUE TITLE
Poe overlay suddenly stopped working for me

### ISSUE THREAD

**Issue by Primegaminggg** [Kyusung4698/PoE-Overlay#779]
# 🐞 bug report

**Describe the bug**

 When I launch Poe Overlay it successfully loads and closes but then no overlay pops up in game. It was working yesterday when I first downloaded it but earlier this morning when I woke up it stopped working for some reason. Does anyone know how to solve this? I have the latest version as I downloaded it just yesterday and I'm playing in fullscreen windowed mode. I've tried reinstalling multiple times but the problem persists :/ Thanks all

**Comment by tamaroth** [comment]
I'm in the same boat. Since the most recent patch, nothing shows up for me. When there is an incoming trade, the sound is present (meaning overlay is working in the background), however no part of the UI is visible anywhere.
