### ISSUE TITLE
Request: Option to search online only

### ISSUE THREAD

**Issue by novabuckeye** [Kyusung4698/PoE-Overlay#78]
Please add an option to search online items only, not all items.  Thanks!

**Comment by Kyusung4698** [comment]
Added with [0.5.0](https://github.com/Kyusung4698/PoE-Overlay/releases/tag/0.5.0). Thanks for the request!

![image](https://user-images.githubusercontent.com/38520678/72469679-36370980-37e0-11ea-9200-172fa2192ca6.png)
