### ISSUE TITLE
Suggestion: Add indicator at the market of an already whispered offer.

### ISSUE THREAD

**Issue by TheMusicMeister** [Kyusung4698/PoE-Overlay#780]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

When using the market functionality in the overlay, whispering a trader should mark that you've sent them a message in order to avoid confusion as to who has already been contacted.

**Describe the solution you'd like**

A marker or some text notifying the user that this trader has already been contacted through the overlay.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This seems like a neat idea to add.

**Comment by Kyusung4698** [comment]
## 1.0.8 (2020-07-09)

- added a lower opacity for market results once they have been requested (#780)

Requested results are now displayed with a lower opacity to be distinct able. Thanks for your suggestion!
