### ISSUE TITLE
Trade module does not work on 3.11

### ISSUE THREAD

**Issue by rctunisi** [Kyusung4698/PoE-Overlay#782]
having issues with trade module on POE Overlay 

On the intro tutorial, the trade worked just fine (was able to capture  whispers and display on the trade overlay, with all the fancy alerts and sounds). After that, it simply does not work

using steam version 3.11 and a fresh install of both poe overlay and overwolf

-- checked for whispers on client.txt file, they are being logged
-- file permissions on client.txt
-- overwolf logs
-- poe overlay logs
-- sending whispers to myself to try to trigger the trade module doesnt work either
-- behavior is the same on both dx11 and vulkan
-- switched to windowed fullscreen to fullscreen, same issue

really dont know what to check next. Can you please point me into a direction here? thanks!

**Comment by conetopia** [comment]
Steam is like a virus, Best bet to uninstall, and install the stand-alone game.

**Comment by MalakaJones** [comment]
> Steam is like a virus, Best bet to uninstall, and install the stand-alone game.

Wut?
