### ISSUE TITLE
shortcut problem!

### ISSUE THREAD

**Issue by RenoLV** [Kyusung4698/PoE-Overlay#784]
just got poe overlay. tried to rebind shortcut for map info warning. i cant set it up for ctrl + c.

**Comment by Hyve747** [comment]
This may be because ctrl + c/v/x are copy/past/cut commands. Ctrl + c is used in poe too, for extracting item info from the client. You can try it your self. Press ctrl + c and then open notepat and press ctrl + v and you see what was copied by poe.
