### ISSUE TITLE
Suggestion: Allow us to change trade notification sound

### ISSUE THREAD

**Issue by argosreality** [Kyusung4698/PoE-Overlay#786]
I personally cant stand the default bass pulse notification sound as its not that noticeable over other audio. Please let us change it to a sound file of our choice

**Comment by theCrius** [comment]
+1 to this. I missed quite some trade requests because I was playing and the sound of the game where drowning the sound of the trade request.

If not "choosing one" at least provide some alternative or just one that is high pitched.

**Comment by windjammer32** [comment]
+1 i suggest this one https://youtu.be/CPNEj9-XvaM

**Comment by Kyusung4698** [comment]
## 1.0.8 (2020-07-09)

- added a audio button at the trade settings to customize the notification sound (#786)

Thanks for creating an issue! The sound can now be customized at the settings.

**Comment by windjammer32** [comment]
🤙

Make it a great day!
George Nicholson
951.269.3292

________________________________
