### ISSUE TITLE
Irregular unresponsiveness to input - 0.4.4 (Will close if working in 0.5.0

### ISSUE THREAD

**Issue by Scott-Norwood** [Kyusung4698/PoE-Overlay#79]
The program is not recognized as unresponsive by the OS itself, its fully functional. It becomes unresponsive to input like Ctrl+ D, F7, it stops accepting input at random times and you have to hard restart the program, only cropped up with 0.4.4, which was installed today.

------------Specs if needed--------------
OS: Windows 10
RAM: 42Gb
CPU: AMD Ryzen 1600X 2.4gHz

**Comment by Kyusung4698** [comment]
Seems related to #76. Can you check 0.5.0-alpha.0? Thanks!

**Comment by Scott-Norwood** [comment]
Just put it through its paces, works great. It's now a nonissue, to be honest its actually more responsive when it brings windows up. Will be in touch if I break it more. Thanks for all your work, I love bar graphs and this just works great for me.
