### ISSUE TITLE
Suggestion: Hide Trade UI until incoming or outgoing trade is requested

### ISSUE THREAD

**Issue by SinisterGenocide** [Kyusung4698/PoE-Overlay#791]
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**
<Trade UI stays on the screen all the time>

**Describe the solution you'd like**
<Can it be made to where the Trade UI only appears when an incoming or outgoing trade is requested?>

**Describe alternatives you've considered**

**Additional context**

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This has been added with a recent update but the trade ui window needs to be sticked (pressing the needle). Once the window is sticked it will be displayed as transparent if there are no trades available.
