### ISSUE TITLE
PoE Overlay - Terrible In-game browser performance 

### ISSUE THREAD

**Issue by Converge57** [Kyusung4698/PoE-Overlay#792]
Hello,

Using the in-game browser (i'm guessing it's an overwolf one?) when opening from an evaluate has terrible performance. It takes 5-10 seconds for the browser to open, to register a click, to show each character you type, or to select anything on the PoE Trade site. Is there a way for it to use an external browser rather than an internal one? or can this be added as an option please?

Also, please add the enchantment jewel socket type for cluster jewels when possible on evaluates.

Thank you.

**Comment by MalakaJones** [comment]
Yup it's horrendous
