### ISSUE TITLE
Searching the market and filtering for Two-Handed Mace return an error "unknown category"

### ISSUE THREAD

**Issue by theCrius** [Kyusung4698/PoE-Overlay#793]
# 🐞 bug report

**Describe the bug**
When using the overlay to search the market, selecting the `Type Filter->Item Category -> Two-Handed Mac`, produce an error `2: Unknown Category`. I don't know the inner working of this project but, as a developer, that typo in the list seems suspicious. If the search is done by using the string `two-handed mace` it's probably just a matter of fixing that typo.

**To Reproduce**
On a fresh installation:

1. Open the market (default ALT+M on Windows)
2. Open the filters
3. Expand `Type Filters`
4. Click on `Item Category`
5. Select `Two-Handed Mac`
6. Click `search` in the main window 

**Expected behavior**
Items belonging to the category `Two-Handed Mace`

**Screenshots**
![image](https://user-images.githubusercontent.com/2202141/86523212-faacfc00-be60-11ea-933c-dd319e60117f.png)

## 🌍  Your Environment
- Version: 1.0.7/installer from Overwolf website
- PoE: Steam/3.11.1/Eng

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This will be fixed with the upcoming version.

**Comment by theCrius** [comment]
Hey, thanks to you guys.

After reporting this I checked the code and noticed it's made in Angular 9 which incidentally is my main frontend development language too. Is there somewhere I can get some instruction on how to build and run this in development mode? The readme is for end users and if you could point me in the right direction I can spend some time trying to figure this out and help with some small merge requests when I can :)

**Comment by Kyusung4698** [comment]
## 1.0.8 (2020-07-09)

- fixed an issue at the market type filter resulting in a unknown category error (#793)

@theCrius you can hit me up on discord and we get it started. there is currently no official way of setting the project up.

**Comment by theCrius** [comment]
I'll ping you on discord most probably over the weekend, thanks for the quick fix btw :)
