### ISSUE TITLE
Suggestion: Tutorial disable button

### ISSUE THREAD

**Issue by Johny256** [Kyusung4698/PoE-Overlay#794]
I just redownloaded PoE on my pc and had to re install this app, which made me redo the tutorial again. I have two problems:
1. There is no way to tell the app to skip the tutorial since I already know how to use it.
2. I can't finish the tutorial because one of the features, I assumed, was changed. It's asking me to press alt+q on an item but when I do I get the prompt "this is not a map". Using alt+q on a map does not allow the tutorial to continue so I'm now stuck with the prompt on my screen.

**Comment by oegeak** [comment]
Yes, pretty please! I had to reinstall overlay a few times because there were problems with my pc or when I installed it on my laptop too. It's quite lengthy and I already understand.

**Comment by Kyusung4698** [comment]
Duplicate of #765
