### ISSUE TITLE
Suggestion: Currency market - modifier key to increment by 10/100

### ISSUE THREAD

**Issue by DinoMC** [Kyusung4698/PoE-Overlay#797]
# 🚀 feature request

Sometimes, you want to buy a bunch of currency (eg. 200 alt), but the seller as it listed by 1 (eg. 1 chaos for 5 alt), so you have to press the + button 40 times to get there. The button to set it as max can help, but not if the seller has too much stock, you'll then have to press the - button even more times.

One solution would be to set up modifiers keys, eg. holding CTRL while pressing the button to add 10, and SHIFT to add 100.
Alternatively, having an field where you can just type a number to set how many you want. Or both options.

I suspect there might already be something implemented or an open issue about this, sorry if that's the case, I couldn't find it with the keywords I could think of.

**Comment by Kyusung4698** [comment]
Hi, thanks for your suggestion. This seems definitely useful. Will be added with the next version.

**Comment by Kyusung4698** [comment]
## 1.0.9 (2020-07-29)

- added different step sizes at the exchange market (CTRL 50, SHIFT 25, ALT 5) (#797)
