### ISSUE TITLE
Error while trying to open POE overlay

### ISSUE THREAD

**Issue by C4LLZ** [Kyusung4698/PoE-Overlay#801]
![image](https://user-images.githubusercontent.com/33510329/87342965-691e4800-c54c-11ea-9473-ff9d1a55d421.png)
I get this error when I try to open the Overlay via Overwolf. 
Sometimes it works but stops working after x amount of time then I get the same error again.

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Can you please attach your application logs? See following topic on how to do so. 
https://support.overwolf.com/support/solutions/articles/9000176827-how-to-get-your-overwolf-logs
