### ISSUE TITLE
PoE overlay not working, nothing comes up.

### ISSUE THREAD

**Issue by ioakie** [Kyusung4698/PoE-Overlay#809]
I'm trying to open POE overlay and nothing happens. Either by shortcut or using the widget one the left side.

I hit Ctrl+Tab to bring widget up, hit more apps, and then click on POE overlay. However, nothing happens.

Overlay should open up or shortcuts should work. I have tried turning Vulcan engine off/on. Still same result.

- PoE: Steam 3.11.1e

**Comment by tikeyike** [comment]
Same issue but I'm using the non-Steam version 3.11.1e

**Comment by Kyusung4698** [comment]
Hi, thanks for reporting this issue. To help me narrow down the issue - can you please answer following question:
- Is the launcher window starting? (Try open PoE Overlay before PoE there should be an launcher window)

If this is not the case can you send me your Overwolf logs. See following topic on how to do so:
https://support.overwolf.com/support/solutions/articles/9000176827-how-to-get-your-overwolf-logs

Thanks!

**Comment by tikeyike** [comment]
@Kyusung4698 Looks like the issue is gone. It's working for me again. I didn't explicitly change/update anything.

And yes - when I was having the issue, the PoE Overlay launcher would pop up, then just disappear without any in-game overlays showing up.
