### ISSUE TITLE
Suggestion: Add option to start tool with windows directly

### ISSUE THREAD

**Issue by Xebtria** [Kyusung4698/PoE-Overlay#81]
could always do this manually, but if the tool gives an option to do it by itself, would be nice QoL

**Comment by Kyusung4698** [comment]
Won't be supported for now. The client is currently released as a portable version. There may be later a installer version + auto update. But as an alternative you can always create a shortcut and put in the autostart folder. See:
https://support.microsoft.com/en-us/help/4026268/windows-10-change-startup-apps

**Comment by Kyusung4698** [comment]
## 0.6.0 (2020-03-12)

- add auto launch on boot/ login (#81)
