### ISSUE TITLE
Overlay Market Interface Problem; Cant send pm

### ISSUE THREAD

**Issue by Zachrane** [Kyusung4698/PoE-Overlay#811]
# 🐞 bug report

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

## 🌍  Your Environment

- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by Zachrane** [comment]
![Capture](https://user-images.githubusercontent.com/69088407/89108179-6e81fa80-d447-11ea-8c17-d86b1362c8ce.PNG)

**Comment by MalakaJones** [comment]
![image](https://user-images.githubusercontent.com/15826583/89111700-fd324f80-d426-11ea-9eba-f9a14e11d337.png)
This is most-likely a resultion issue

**Comment by Kyusung4698** [comment]
## 1.0.10 (2020-08-02)

- fixed an issue on lower resolution having invisible market prices (#811)
