### ISSUE TITLE
The ability to see price and send whisper is cropped out

### ISSUE THREAD

**Issue by recca84** [Kyusung4698/PoE-Overlay#814]
![overlay issue](https://user-images.githubusercontent.com/69404488/89720830-73ddc880-d9a4-11ea-80e9-102996c0fe54.jpg)

**To Reproduce**
My computers resolution is 1600x900 on a 17" monitor with a ratio aspect of 16:9. This issue only started a week ago.

**Expected behavior**
Realistically I should be able to see the price of all times that I search and send a whisper

**Screenshots**

## 🌍  Your Environment

- Version:  1.0.10
- PoE:  3.11.1e English

**Comment by songoo** [comment]
hi , same issue, play at 1080 resolution, cant scroll to get to message button

**Comment by zezyz** [comment]
same issue here(1920x1080), several items with long modifiers don't fit the box margin making whisper/price not visible and inaccessible.

**Comment by Kyusung4698** [comment]
## 1.0.11 (2020-09-20)

- fixed an issue with too long stats at the market window (#814)
