### ISSUE TITLE
Settings window moves when interacting with form elements (slider, text input)

### ISSUE THREAD

**Issue by iTob191** [Kyusung4698/PoE-Overlay#815]
# 🐞 bug report

**Describe the bug**
When dragging a slider or trying to select text in an input box in the settings, the whole settings window moves around. This prevents normal interaction with these form elements. It is however still possible to adjust them to the desired values (slider: click at the desired position; text input: using arrow keys, delete key and shift to select).

**To Reproduce**
1. Open the settings window (F7)
2. Try dragging the slider for the Dialog Opacity option.
3. Select the Trade tab.
4. Try to select the text in one of the "Messages" options.

**Expected behavior**
The window should only move when clicking outside of any form elements (text input, slider, ...) or alternatively only when dragging the title bar.

## 🌍  Your Environment

- Version: 1.0.10
- PoE: 3.11.1/e English

**Comment by iTob191** [comment]
The described problem does still occur with the latest version (still 1.0.10).

**Comment by Kyusung4698** [comment]
Hi, thanks for reporting this issue. This is a bug indeed and will be fixed with the next version. 👍

**Comment by Kyusung4698** [comment]
## 1.0.11 (2020-09-20)
- fixed an issue using the slider at the settings window (#815)

New version is now available 🚀
