### ISSUE TITLE
Suggestion: save the replay files

### ISSUE THREAD

**Issue by bjbeare** [Kyusung4698/PoE-Overlay#818]
# 🚀 feature request

I'd like to be able to save my replay files (if it is already a feature... how do I find them?).
It probably isn't a good idea to save all such files... perhaps the last 10 (or a set-able number of them).

**Comment by bjbeare** [comment]
Ok... I found the files. They are saved. Is this documented anywhere?

C:\Users\$USER\Videos\Overwolf\PoE Overlay

**Comment by bjbeare** [comment]
Found this in the settings. lol.

**Comment by Kyusung4698** [comment]
Thanks for the heads-up. The new version will show the replay location at the settings. 👍
