### ISSUE TITLE
PoE Overlay could not be loaded error

### ISSUE THREAD

**Issue by OblancC** [Kyusung4698/PoE-Overlay#819]
I get this error when i try to open the Overlay.

(I don't know if I put the file right)
[OverwolfLogs_2020-09-01_12-27-19.zip](https://github.com/Kyusung4698/PoE-Overlay/files/5157268/OverwolfLogs_2020-09-01_12-27-19.zip)

**Comment by Kyusung4698** [comment]
Hi, thanks for reporting the issue and providing the required files. Unfortunately I could not located the causing problem but I've fixed some stability issue which may have caused with in the next version. 👍

**Comment by Kyusung4698** [comment]
## 1.0.11 (2020-09-20)

- fixed an issue freezing the launcher

If this still occurs please check following comment: https://github.com/Kyusung4698/PoE-Overlay/issues/826#issuecomment-695351004
