### ISSUE TITLE
Item price should be converted from chaos to exalts when it surpasses exalt price

### ISSUE THREAD

**Issue by mediaticamente** [Kyusung4698/PoE-Overlay#82]
When using ctrl+d on an item, it should auto select my currency to exalt if the price it gets is more than the current exalt to chaos exchange.

For example if the price is 1250 chaos, it should show the price as 10 exalts instead.
This would remove the need go to the settings, select exalts, and look again everytime when checking a high value item. Same for looking the value of a low value item with exalts.

Or you can show 2 currencies at the same time, showing both chaos and exalts. Maybe put a checkbox for each currency in the settings.
What do you think?

Thank you for your hard work!

**Comment by Kyusung4698** [comment]
Added with with [0.5.0](https://github.com/Kyusung4698/PoE-Overlay/releases/tag/0.5.0). You can add as many currencies as you like! The min currency with atleast 1 will be used. Thanks for the great idea!
![image](https://user-images.githubusercontent.com/38520678/72469540-ea846000-37df-11ea-95b0-fe9d59756f72.png)
