### ISSUE TITLE
Market tab cuts off send message button

### ISSUE THREAD

**Issue by mocyhomes** [Kyusung4698/PoE-Overlay#821]
# 🐞 bug report

**Describe the bug**

when you load the market tab, some times it cuts off the message button (like it got shoved to the side out of view):

**To Reproduce**

1. Go to '...' market tab
2. Click on '....' search unending hunger

**Screenshots**

## 🌍  Your Environment

- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by Kyusung4698** [comment]
Duplicate of #814
