### ISSUE TITLE
Waiting for poe to launch

### ISSUE THREAD

**Issue by GamerysHD** [Kyusung4698/PoE-Overlay#824]
Hello,

# 🐞 bug report

**Describe the bug**

My game is lauched and the overlay doesn't seem to detect it

**To Reproduce**

I launched the game throught steam
lauched the overlay 

![image](https://user-images.githubusercontent.com/71444943/93473049-cee4d280-f8f5-11ea-8188-d7f1a21a121c.png)

![image](https://user-images.githubusercontent.com/71444943/93473084-ddcb8500-f8f5-11ea-9ec8-dbae50633558.png)

## 🌍  Your Environment

i'm using the last version of poe and poe overlay by overwolf

Can you help me ?

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Can you please generate a log package and attach it here? See following topic on how to do so. 
https://support.overwolf.com/en/support/solutions/articles/9000176827-how-to-get-your-overwolf-logs

**Comment by GamerysHD** [comment]
[OverwolfLogs_2020-09-17_23-03-20.zip](https://github.com/Kyusung4698/PoE-Overlay/files/5241799/OverwolfLogs_2020-09-17_23-03-20.zip)

**Comment by GamerysHD** [comment]
So after 3 on off of my computer, my problem seems gone, thank you for you respond, have a good day

**Comment by Kyusung4698** [comment]
Thanks for the update. I'm glad it's working now but it seems like there is an actual underlying issue which caused this. Did you change anything on how the start-up order for the latest try? e.g first poe overlay than poe or vice versa? Thanks! 👍

**Comment by GamerysHD** [comment]
I lauched poe first and then during the loading screen of my caracter (to enter in the game) it appeared so I guess uninstall, reinstall and then relaunch the computer works
