### ISSUE TITLE
poe overlay did not recognize my poe. 

### ISSUE THREAD

**Issue by rnecron666** [Kyusung4698/PoE-Overlay#826]
# 🐞 bug report

**Describe the bug**
poe overlay did not start when poe is active. it says : waiting for game to launch. 
poe is running via steam 64bit version.

![poe bug](https://user-images.githubusercontent.com/71509123/93600561-23548480-f9c0-11ea-962e-d69f064ce700.PNG)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Can you please generate a log package and attach it here? See following topic on how to do so. 
https://support.overwolf.com/en/support/solutions/articles/9000176827-how-to-get-your-overwolf-logs

Also I have a idea what may cause this. Can you test if it makes any difference starting PoE Overlay before PoE and vice versa? Thanks 🚀

**Comment by rnecron666** [comment]
i started both ways ... nothing changed.
i get the overwolf log in a moment

**Comment by rnecron666** [comment]
[OverwolfLogs_2020-09-18_23-48-12.zip](https://github.com/Kyusung4698/PoE-Overlay/files/5248375/OverwolfLogs_2020-09-18_23-48-12.zip)

**Comment by Kyusung4698** [comment]
Thanks for the logs. It seems like PoE gets detected correctly but it's not transmitted to the App. Can you check if following toggle is enabled: 
![image](https://user-images.githubusercontent.com/38520678/93649926-6be65f00-fa0d-11ea-8c90-ee87c8dca785.png)

**Comment by rnecron666** [comment]
![poe bug2](https://user-images.githubusercontent.com/71509123/93652487-802e5a00-fa15-11ea-9ccd-3cb1d455381a.PNG)

**Comment by rnecron666** [comment]
its activated

**Comment by Kaisernx** [comment]
I'm having the same issue... I've done the above, I've re-installed Overwolf and Poe Overlay.  I don't think the app is recognizing the game

**Comment by Kyusung4698** [comment]
Hi, thanks for the feedback. I've create a Overwolf support ticket. I'll keep you updated.
https://discuss.developers.overwolf.com/t/game-detection-for-path-of-exile-does-not-work-for-everyone/1010

@Kaisernx please attach your logs as well 👍

**Comment by Kyusung4698** [comment]
Hi, just got a workaround from Overwolf. They will roll-out the fix on Monday. 
1. Download the [Workaround_826.zip](https://github.com/Kyusung4698/PoE-Overlay/files/5250548/Workaround_826.zip)
2. Replace ```GamesList.8963158.xml``` at ```%localappdata%/overwolf```, and restart Overwolf.
Please let me know if this works! Thanks for your help 🚀

**Comment by Veliur** [comment]
> Hi, just got a workaround from Overwolf. They will roll-out the fix on Monday.
> 
> 1. Download the [Workaround_826.zip](https://github.com/Kyusung4698/PoE-Overlay/files/5250548/Workaround_826.zip)
> 2. Replace `GamesList.8963158.xml` at `%localappdata%/overwolf`, and restart Overwolf.
> 
> Please let me know if this works! Thanks for your help 🚀

It helped to my problem #828

**Comment by rnecron666** [comment]
Great Job ... works fine :))

**Comment by RaDeleon** [comment]
I had the same issue but then I kept trying launching poe overlay and different times like when starting game or selecting character and if eventually worked. Will try workaround if anything stops working again
