### ISSUE TITLE
Number input fields in price window are cut off

### ISSUE THREAD

**Issue by zymox** [Kyusung4698/PoE-Overlay#827]
See screenshot:

![image](https://user-images.githubusercontent.com/18327640/93664817-f52f7d00-fa71-11ea-869d-19204dff053e.png)

**Comment by zymox** [comment]
Maybe a resolution thing? I'm playing on 2560*1440 windowed fullscreen

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. I had this issue as well but was unable to pin point the reason. As fair as i know it's not related to the resolution. Can you try restarting the Overwolf process?

**Comment by zymox** [comment]
Restarted Overwolf, restarded PoE - same result :/

**Comment by Kyusung4698** [comment]
Will be fixed with the next version. Thanks for reporting the issue! 👍

**Comment by Kyusung4698** [comment]
## 1.0.11 (2020-09-20)
- fixed an issue causing values at the evaluate dialog to be cut off

New version is now available 🚀
