### ISSUE TITLE
Can't launch poe overlay

### ISSUE THREAD

**Issue by Veliur** [Kyusung4698/PoE-Overlay#828]
In new league noticed that Overlay in bootloop. I think that problem in Overwolf, coz i have strange image insted PoE icon. 
on image u can see that PoE is launched (tried open Overlay befor and after PoE launch), but Overlay is on bootloop.

![image](https://user-images.githubusercontent.com/54943467/93666227-1483d580-fa85-11ea-8e55-f1911a52c642.png)

[OverwolfLogs_2020-09-19_14-37-51.zip](https://github.com/Kyusung4698/PoE-Overlay/files/5249777/OverwolfLogs_2020-09-19_14-37-51.zip)

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Unfortunately your logs look exactly like #826 and this issue is currently under investigation from Overwolf. Hopefully they'll find a fix soon.

**Comment by flacostec** [comment]
Why did you release a tool that is depending on another thing such as Overwolf ? What's the point ?

**Comment by bloddymane** [comment]
i have the same issue

**Comment by Kyusung4698** [comment]
@Veliur, @bloddymane Overwolf has provided a workaround for the poe detection mechanic. Please see following comment on how to install it: https://github.com/Kyusung4698/PoE-Overlay/issues/826#issuecomment-695351004

@flacostec Overwolf provides a advanced development kit for game overlays. They manage all low-level system functionality like hooking into the game renderer to display a fullscreen overlay. Furthermore they provide a platform to release apps with a integrated installation and update system. I'm using their man-power to spend more time on developing actual features for the app.
