### ISSUE TITLE
[Bug] Window Size Stat Values, covered/hidden?

### ISSUE THREAD

**Issue by conetopia** [Kyusung4698/PoE-Overlay#829]
![05e683533cb0237291abca7763a4420e](https://user-images.githubusercontent.com/4310295/93688134-3a12de00-fa89-11ea-93d7-bc10cd1cafec.png)

Any way to fix this?
 3%
4%
2%

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. This will be fixed with the next version. Should be available tomorrow.

**Comment by Kyusung4698** [comment]
## 1.0.11 (2020-09-20)
- fixed an issue causing values at the evaluate dialog to be cut off

New version is now available. Thanks for reporting the issue! 🚀
