### ISSUE TITLE
Suggestion: some QOL tweaks

### ISSUE THREAD

**Issue by vadash** [Kyusung4698/PoE-Overlay#83]
1. Sockets on small items should be never selected. Only body / 2H that can roll 5L+
2. Add some setting to pre filling min range like OG trade macro (-10% is a good start while we dont have config). MAX range should be left empty. That feature was useless
3. Auto choose all influence specific rolls like Elusive, Tailwind, +1 gems etc

**Comment by Visteras** [comment]
-10% is bad, if we used only current tier i think better, becouse w can used down and up barrier for current tier and see real price for real item... 
P.S. Sorry, my english is bad :(

**Comment by vadash** [comment]
Depends on affix. Only notable exceptions are % attributes and + strength

**Comment by Kyusung4698** [comment]
> 1. Sockets on small items should be never selected. Only body / 2H that can roll 5L+

You can disable the default select logic in the menu. Also with 0.5.0 i've added a quick select for sockets by pressing `Shift + Click`.

> 2. Add some setting to pre filling min range like OG trade macro (-10% is a good start while we dont have config). MAX range should be left empty. That feature was useless

Pre filling has been added with 0.5.0. Also mod ranges have been introduced.

> 3. Auto choose all influence specific rolls like Elusive, Tailwind, +1 gems etc

Won't be supported for now. But I plan on add a user based settings to let him decide what to auto choose.

**Comment by 766b** [comment]
Regarding Min/Max values, it's a nice feature, but when I click and select values, overlay loading up changes based on my selection, it's all nice, the only problem is that overlay size changes when chart is loading, causing mis-clicks because everything moves around

**Comment by Kyusung4698** [comment]
> Regarding Min/Max values, it's a nice feature, but when I click and select values, overlay loading up changes based on my selection, it's all nice, the only problem is that overlay size changes when chart is loading, causing mis-clicks because everything moves around.
> 
> Also, it would be nice to have setting for leaving max value unbounded.

Done and Done! Thanks for reporting. I've added a min-width to prevent the size changes during loading. Also i've added a settings to disable the max range initial.

**Comment by Kyusung4698** [comment]
I'll close this for now as most of this has been fulfilled. Please open an new issue if there are still some things you want to be improved.
