### ISSUE TITLE
poe 3.12--Error in price inquiry in traditional Chinese

### ISSUE THREAD

**Issue by zqf3940** [Kyusung4698/PoE-Overlay#831]
# 🐞 bug report

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

## 🌍  Your Environment

- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Can you please add a screenshot of the error? Thanks! 👍

**Comment by zqf3940** [comment]
![20200922152147](https://user-images.githubusercontent.com/3402968/93854697-bda91680-fca5-11ea-9563-63a5ce64c48f.png)
