### ISSUE TITLE
PoE is Crashing with PoE Overlay 

### ISSUE THREAD

**Issue by unitlol** [Kyusung4698/PoE-Overlay#832]
Hey there,

Ever since 3.12 Heist league my game has been crashing a lot and I seem to be having memory leaks or not enough memory issues. It would never happen in the previous leagues

My game would crash, google chrome, discord, wallpaper engine. I first thought that a stick of RAM has gone bad but I checked, everything is still fine. I reinstalled PoE and the game is still crashing. Then I realized, my PoE Overlay was frozen. From then on, I realized, everytime PoE Overlay initalizes, or when I turn it on. It would cause my computer to run out of memory. All those programs listed above would crash and freeze. Poe would freeze as well.

Any reason for this or how I would be able to fix this?

My computer specs:

Intel i7-9700k
Corsair Vengeance Pro 16GB
Geforce RTX 2080 Super
Windows 10 64bit

Thanks!

**Comment by Kyusung4698** [comment]
Hi, thanks for reporting the issue. Can you please attach your application logs so i can further debug it? Thanks 👍 
See following topic on how to generate them:
https://support.overwolf.com/en/support/solutions/articles/9000176827-how-to-get-your-overwolf-logs

**Comment by unitlol** [comment]
Hey, 

I have attached the logs. I am not sure if it is PoE Overlay itself. Or it could be Overwolf? I am not too sure.

My PoE is also running at 60% CPU usage even though I am still around not doing anything


[OverwolfLogs_2020-09-21_16-36-40.zip](https://github.com/Kyusung4698/PoE-Overlay/files/5258006/OverwolfLogs_2020-09-21_16-36-40.zip)

**Comment by Kyusung4698** [comment]
So checking the logs there is indeed a memory issue. This low-level code is handled by Overwolf. So I'm gonna let a Overwolf developer check your logs. He should have an idea what could cause this. This will probably take some time. Until then can you further try to explain how this is triggered? e.g using a specific feature of the overlay or any action you do at the game? Thanks again for your input.

**Comment by unitlol** [comment]
So currently I am running Direct X11 thinking it is a Vulkan issue.

But since this patch, even with a 2080 Super, I need to play on lowest graphics to get 150+ fps (1440p) . At highest graphics I get <60 fps. Previous seasons of the game I would run no problem with highest settings.

Usually this is triggered from me just playing the game, and having only a few google chrome tabs open, with PoB open as well. It would work for maybe like 30minutes, then it would PoE would crash. Google chrome - ggg trade would say something like not enough memory.

I do have Discord Overlay, I will try disabling it

**Comment by Kyusung4698** [comment]
> I do have Discord Overlay, I will try disabling it

Hey, just wanted to follow up on this. Did this change anything on the crashing?

Also I've create a Overwolf ticket. I'll keep you update.
https://discuss.developers.overwolf.com/t/out-of-memory-after-30-minutes/1018

**Comment by Kyusung4698** [comment]
So just got the first feedback from a developer. He asked what YoloMouse is used for and if possible disabled it and test again. Thanks 🚀

**Comment by unitlol** [comment]
I have disabled the Discord Overlay and still was getting crashes.

Yolomouse is for changing your cursor ingame so its different colors / and can be bigger than the default one in game

I will disable it now and let you know if it still causes issues.

I have used the same setup for the past 3 leagues with no issues. It's just this league

**Comment by unitlol** [comment]
Hey,

Just to keep you updated I think I have the issue resolved.

Yesterday I had memory issues just running poe itself, and got a BSOD. 

I increased the Virtual Memory for paging files in Win 10 and it solved everything

Thanks for your help!

**Comment by Georgexproplayer** [comment]
Great job 
[img]https://rpglvl.com/image/catalog/path%20of%20exile/path_of_exile_logo.png[/img]
