### ISSUE TITLE
Reply while busy gets unknown area

### ISSUE THREAD

**Issue by corinbz** [Kyusung4698/PoE-Overlay#834]
# 🐞 bug report

**Describe the bug**
When i replay to a player that i am busy, it always says that i am in unknown area. probably an issue with @zone comand

## 🌍  Your Environment

- Version: 1.0
- PoE 3.12.1

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Yes, this is related to the ```@zone``` command. The used Overwolf events were under a downtime after the new PoE update. The latest Overwolf update should have fixed this tho. Can you test if restarting PoE fixes it?

**Comment by corinbz** [comment]
Restarting poe does not fix the issue. And my overwolf client is the
latest version. Thx for the quick response.

**Comment by Kyusung4698** [comment]
Hi, sorry I've misread a Overwolf announcement. They changes weren't live then but they should be now. You can also check the event statuses here:
https://overwolf.github.io/docs/status/path-of-exile
