### ISSUE TITLE
Can't see trade infomation

### ISSUE THREAD

**Issue by LingboCN** [Kyusung4698/PoE-Overlay#837]
# 🐞 bug report

**Describe the bug**
cant see trade infomation

**Screenshots**
![image](https://user-images.githubusercontent.com/38290378/93894804-aaff0380-fcde-11ea-85cd-8eac83fbdebe.png)

## 🌍  Your Environment
win10 x64
- Version: 1.0.11
- PoE: 3.12.1

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. Is this only occurring for outgoing requests? If so, please make sure you're filter is set to Incoming & Outgoing. See screenshot below:
![image](https://user-images.githubusercontent.com/38520678/93972374-76d52280-fd72-11ea-8ce6-119a4f538242.png)

If that's not the case please send me your Client.txt. You can find it at the PoE directory\logs\Client.txt

Thanks! 👍

**Comment by LingboCN** [comment]
im sure i set to  Incoming & Outgoing
![image](https://user-images.githubusercontent.com/38290378/94009634-469e7b80-fd94-11ea-9cab-83c629ca9c8e.png)

see the logs, thanks!
[logs.zip](https://github.com/Kyusung4698/PoE-Overlay/files/5267965/logs.zip)

**Comment by LingboCN** [comment]
> Hi, thanks for creating an issue. Is this only occurring for outgoing requests? If so, please make sure you're filter is set to Incoming & Outgoing. See screenshot below:
> ![image](https://user-images.githubusercontent.com/38520678/93972374-76d52280-fd72-11ea-8ce6-119a4f538242.png)
> 
> If that's not the case please send me your Client.txt. You can find it at the PoE directory\logs\Client.txt
> 
> Thanks! 👍

im sure i set to  Incoming & Outgoing
![image](https://user-images.githubusercontent.com/38290378/94009634-469e7b80-fd94-11ea-9cab-83c629ca9c8e.png)

see the logs, thanks!
[logs.zip](https://github.com/Kyusung4698/PoE-Overlay/files/5267965/logs.zip)

**Comment by csw699** [comment]
same issue to me

**Comment by LingboCN** [comment]
somehow,this bug fix on poe client update 3.12.2.  : )

**Comment by nexost** [comment]
Similar issue for me. Notifications don't work for players with Korean/Russian names.  I am on POE 3.12.2

**Comment by Alistair1231** [comment]
I have the issue *sometimes*
Dunno about incoming but definetly outgoing

**Comment by ThatGuyEUW** [comment]
I have same problem with ingoing messages not being recognized by the Overlay. I have not found a pattern yet, first I thought it was foreign characters only but now it appears to happen randomly

**Comment by sgcroteau** [comment]
I am having the same issue. The Overlay is not picking up any incoming trade requests. I have the 3.12.4d PoE patch on PoE client and Overlay version 1.0.11.
[Client.txt](https://github.com/Kyusung4698/PoE-Overlay/files/5511071/Client.txt)

**Comment by ThatGuyEUW** [comment]
Issue is not resolved.
