### ISSUE TITLE
Suggestion: Use Bulk Exchange View for Currency

### ISSUE THREAD

**Issue by vadash** [Kyusung4698/PoE-Overlay#84]
Compare this
![image](https://user-images.githubusercontent.com/1397582/72299827-0d453600-3673-11ea-8667-36aab74cc479.png)

To
![image](https://user-images.githubusercontent.com/1397582/72299867-2b129b00-3673-11ea-80da-52fa65afd4d5.png)

Grab it from other sources. Thats should be easy fix

**Comment by ishinome** [comment]
+1
It should get the prices from the bulk trade, not the regular item search one.

**Comment by pj4533** [comment]
I ran into this with Ancient Orb pricing.  I think its more to do with changes in price, and the fact this tool uses offline also (so had older prices)

**Comment by Visteras** [comment]
I think 1 ex + 13 c is better then 1.12 ex, and this can create as option function ?)
Becouse if i see 1.12 ex i need check real price for ex, this require few action and more time for trading...

**Comment by Kyusung4698** [comment]
![value](https://user-images.githubusercontent.com/38520678/73141310-05c65980-4083-11ea-9060-cc12483483b4.gif)

I've added the values from poe.ninja and decided agains using the bulk exchange. Let me know if this meets your requirements! Thanks for your suggestion.

**Comment by Kyusung4698** [comment]
I'll close this for now. Feel free to re-open if needed. Thanks!
