### ISSUE TITLE
EGS PoE Executable Name Needs Whitelist

### ISSUE THREAD

**Issue by BadLuckJ** [Kyusung4698/PoE-Overlay#843]
# 🐞 bug report
**Describe the bug**

PoE Overlay Launcher Doesn't Work with EGS version of POE as it has a different  executable name

**To Reproduce**

1. Install PoE on EGS
2. Install PoE Overlay Via Overwolf
3. Launch Both PoE Overlay & PoE

**Expected behavior**

PoE Overlay Still Shows " Waiting for PoE To Launch"
**Screenshots**

![POEEGS](https://user-images.githubusercontent.com/71956062/94355751-592cf380-00b9-11eb-821c-f5543764aac3.png)

## 🌍  Your Environment

- Version: P.s Am Not Able to get App Version Via OverWolf.
- PoE:  EGS 3.12.2/e English

**Comment by iluminaqua** [comment]
Im having the same issue since i started trying to install the App yesterday,

**Comment by Kyusung4698** [comment]
Hi, thanks for creating an issue. The EGS client was indeed not on the whitelist. Overwolf has update the whitelist in the meantime. Can you check if it's working now?

**Comment by BadLuckJ** [comment]
Yes, It's working now.
