### ISSUE TITLE
POE Overlay Trade periodically don't want to send messages

### ISSUE THREAD

**Issue by Metilar** [Kyusung4698/PoE-Overlay#851]
POE Overlay Trade periodically don't want to send messages when you click on buttons, invite to a group, visit a shelter, trade, send responses, etc.it does not work, as I noticed, it does not work, Everything that is done through the command in the chat, the search button in the chest works properly. Sometimes restarting the game helps.

**Comment by crash0verwr1te** [comment]
Same here.

**Comment by popers** [comment]
Same here

**Comment by fudgewaffle** [comment]
Same

**Comment by 99TonyStark99** [comment]
just started using this program yesterday, and after a while it won't send whispers from the market search interface
