### ISSUE TITLE
Box for show item in stash is off after new update

### ISSUE THREAD

**Issue by Cmp21** [Kyusung4698/PoE-Overlay#858]
# 🐞 bug report

**Describe the bug**

When highlighting an item in stash that a buyer has whispered you for, the alignment of that box to show the item is now off after the stash affinity update yesterday.

**To Reproduce**

1. Buyer whispers for item
2. Click the eye button on the trade interface to highlight item
3. Box is not aligned properly

**Expected behavior**

Box is aligned properly

**Screenshots**

![YoloMouse_2020-11-05_12-24-15](https://user-images.githubusercontent.com/13479481/98286971-f48b7100-1f61-11eb-88d1-7a1a50d3dccc.png)

## 🌍  Your Environment

- Version:  1.0.10
- PoE:  Steam 3.12.4d English

**Comment by uranmorte** [comment]
I have similar problem. It is happen inside quad tab. I use QHD resolution (2560 x 1440).
