### ISSUE TITLE
Support: Captured Beasts as Item Type

### ISSUE THREAD

**Issue by Rohatej** [Kyusung4698/PoE-Overlay#86]
For example

```
Rarity: Rare
Shadowdrool
Infested Rhoa
--------
Genus: Rhoas
Group: Avians
Family: The Sands
--------
Item Level: 83
--------
Blood Geyser
Allies Resist Elemental Damage
Extra Life
Life Regen
Accurate
--------
Right-click to add this to your bestiary.
--------
```

Error msg
![beasts err](https://user-images.githubusercontent.com/49788153/72345860-0222f200-36d5-11ea-9b9f-1842d85e153c.png)

**Comment by Kyusung4698** [comment]
Beasts are currently not supported. They are missing in the base item export. Will be added soon.

**Comment by Kyusung4698** [comment]
Added with 0.5.3 (2020-01-21)
* add beast support (#86)
