### ISSUE TITLE
Overlay starts, can be seen on screen and clicked but keyboard commands don't interact with it

### ISSUE THREAD

**Issue by tingpatrick41** [Kyusung4698/PoE-Overlay#862]
Overlay shows on the screen when I start POE. It loads the tutorial slide "press F7" or something but I can't proceed. Tried other commands (eg. Alt+D) but realized that nothing I type on the keyboard is registered by Overlay.

Running the latest Steam client and just downloaded the latest Overlay.

**Comment by MalakaJones** [comment]
Try ctrl+d. Alt+d seems to be problematic.
