### ISSUE TITLE
Highlight grid not "centralised" like its kind of a few mm away from it 

### ISSUE THREAD

**Issue by Elezen514** [Kyusung4698/PoE-Overlay#869]
![image](https://user-images.githubusercontent.com/59316216/104856504-0b92fb80-58e1-11eb-966b-f13dca1a833a.png)

As you can see the grid isnt realy on top of the right grid i mean yes i can still use it but is there a setting to modify the highlight grid location ? like move it a few mm to the top/right/left/bottom

Thank you

**Comment by KalleWetterberg** [comment]
Same issue for me, but mine is almost a whole square wrong. Would be nice with a calibration option.
