### ISSUE TITLE
Suggestion: Item links/sockets shouldn't be selected by default

### ISSUE THREAD

**Issue by Rohatej** [Kyusung4698/PoE-Overlay#87]
Item links/sockets shouldn't be selected in pricecheck window (after pressing CTRL+D) by default

Unless you are looking for price of six linked armour of weapon, number of sockets and their links are irrelevant. (in most cases)

**Comment by Kyusung4698** [comment]
There is a toggle inside the evaluate settings tab to disable this behaviour. Although there will be an advanced query configurator soon.
