### ISSUE TITLE
Poe Overlay wont detect my Game

### ISSUE THREAD

**Issue by SufferMyDear** [Kyusung4698/PoE-Overlay#876]
Hey

I got the same issue or similar as discussed here:

https://github.com/Kyusung4698/PoE-Overlay/issues/582

It just dont detect my Game since the new League

in 3.12 it  worked perfect. but now i need to restart everything like thousand times too get it working once.

- Version: 1.0.13
- PoE: 3.13.0c from GGG

**Comment by Wasabi375** [comment]
I have the same issue
