### ISSUE TITLE
Commands overwrite clipboard

### ISSUE THREAD

**Issue by vhbert** [Kyusung4698/PoE-Overlay#89]
Would be nice if , after running a shortcut command, you could restore the previous contents of the clipboard.
Since right now it's quite annoying to get my clipboard overwritten everytime I go to my hideout.
Guess this should be an easy fix.

**Comment by Kyusung4698** [comment]
Thanks for the report! It's indeed an easy fix.

**Comment by Kyusung4698** [comment]
Fixed with [0.5.0](https://github.com/Kyusung4698/PoE-Overlay/releases/tag/0.5.0).
