### ISSUE TITLE
POE Overlay doenst recognize the Game

### ISSUE THREAD

**Issue by Itoukun0** [Kyusung4698/PoE-Overlay#891]
# 🐞 bug report

**Describe the bug**
Every time i start POE Overlay it doesnt, connect to the game. i already tried reinstalling and restarting everything.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/79527766/108884710-2f93dc00-7607-11eb-9fc9-f59598d533ab.png)

## 🌍  Your Environment

- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by lweiler77** [comment]
I have the same issue since today.

**Comment by Dddsasul** [comment]
Same issue since poe's last update

**Comment by Hrodwolff** [comment]
same

**Comment by ReAnIm8TeD** [comment]
same here, doesnt work anymore, started on my laptop, and then it also wont work 2 days later on my main rig. so i guess there was no poe update arround, its must be a programm failure itself

**Comment by DarkDynamix** [comment]
Same issue: 2 days ago it didnt work on one of my PCs but on the other, today it's the other way around. Both reinstalled, both tried different starting order.

**Comment by distermaer** [comment]
Same happening to me since today morning, tried reinstalling overwolf and POE overlay but the issue remains. Also starting POE 1st or 2nd to overlay changes nothing.

**Comment by distermaer** [comment]
I reinstalled overwolf again and now everything works, even after pc restart. I didn't uninstall and then reinstall, I just did an overwrite installation basically. I hope that helps someone.

**Comment by ReAnIm8TeD** [comment]
> 
> 
> I reinstalled overwolf again and now everything works, even after pc restart. I didn't uninstall and then reinstall, I just did an overwrite installation basically. I hope that helps someone.

Thank you that fixed it for me, i reinstalled overwolf, and keep the existing data. not even a reboot and all works again

**Comment by escaflownfr** [comment]
I have the same problem unable to use your app since the last league have you planned a solution?
