### ISSUE TITLE
Waiting for poe to launch

### ISSUE THREAD

**Issue by feuerdino** [Kyusung4698/PoE-Overlay#892]
# 🐞 bug report

**Describe the bug**
Poe overlay is running and waiting for POE to start. Even after POE is fully loaded and im standing in my hideout Poe overlay doesn't start. 

**To Reproduce**
Start POE overlay 
Start POE
done

**Expected behavior**
Poe Overlay launches and I can use the overlay as I could before

**Screenshots**

Here u can see Poe launched but the Overlay still wont Start as well.

![befbbbf0cf4b7c788657d4cc3136188f](https://user-images.githubusercontent.com/79646966/109163614-cc768680-7779-11eb-96a7-fa5bd57b06f4.png)

## 🌍  Your Environment

- Version: Overwolf version
- PoE: Steam 3.13 English client

**Comment by r0nner** [comment]
Same here.... ist the new Nvidia Driver a Problem?

**Comment by feuerdino** [comment]
> Same here.... ist the new Nvidia Driver a Problem?

haven't updated so that cant be a problem no. I think it has something to do with the latest PoE patch. I think I have the problem after patch 2 Days ago.

**Comment by r0nner** [comment]
I have updatet Overwolf .... POE Overlay works fine. But the Update Function in Overwolf doesent work, dowload on Homepage the OverwolfInstaller.exe and install the New Version.

**Comment by feuerdino** [comment]
> I have updatet Overwolf .... POE Overlay works fine. But the Update Function in Overwolf doesent work, dowload on Homepage the OverwolfInstaller.exe and install the New Version.

did the same worked for me as well redownload overwolf and everything works again thanks alot
