### ISSUE TITLE
POE Overlay not working in latest release of POE

### ISSUE THREAD

**Issue by Azounstone** [Kyusung4698/PoE-Overlay#897]
# 🐞 bug report

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

## 🌍  Your Environment

- Version:  e.g. 0.6.9 portable
- PoE:  e.g. Steam 3.10.0/e English

**Comment by feupeu** [comment]
Is this being worked on?

**Comment by Azounstone** [comment]
I should add that I launched the market (alt +m) and then it crashed and since then will not load in the game.

**Comment by The-Atheist** [comment]
Same here, I hit alt +m, it crashed and I've been getting "Something went wrong" error ever since.

**Comment by Azounstone** [comment]
Instead of marking this as stale perhaps feedback on this being fixed is more appropriate?
