### ISSUE TITLE
evaluate feature only adding certain stats

### ISSUE THREAD

**Issue by Necklor** [Kyusung4698/PoE-Overlay#898]
Since the new release the evaluate feature no longer adds certain stats, it shows they exist but amounts need to be manually put it. note this is not the case for all stats

![image](https://user-images.githubusercontent.com/12386508/115118567-cf1f7c00-9f71-11eb-9b55-0361f95ae270.png)

**Comment by BarnOwlet** [comment]
Same here
![image](https://user-images.githubusercontent.com/60470422/115120875-aca85580-9fa7-11eb-9bfe-3c8e007a5f65.png)
Super annoying. It even goes to the trouble of adding the value "0" for the max value, which you have to manually remove too if you still want to search by adding in min values

**Comment by MarkWHodgson** [comment]
I have the same issue. I will pull some stats as implicits, but not explicits:
![image](https://user-images.githubusercontent.com/72420471/115127286-56391800-9fa3-11eb-951a-edbdd12620bf.png)
