### ISSUE TITLE
The suggest price must to be the most repeated price, not the average one.

### ISSUE THREAD

**Issue by josemariafs** [Kyusung4698/PoE-Overlay#9]
Example:

![image](https://user-images.githubusercontent.com/719068/71864439-12990280-3100-11ea-9c2a-f320e7e20f81.png)

suggested price: 604c
correct price: 170c

This example is because there are corrupted versions of kaom's that more expensive that the mine one, but anyway this issue is easy to see with others items:

![image](https://user-images.githubusercontent.com/719068/71864754-f6499580-3100-11ea-8620-a325d059a671.png)

suggested price: 38.86c
correct price: 25-30c (there are price fixers and people that published a extremly high price)

**Comment by zaafar** [comment]
Actually show everything, average, repeated, min max etc etc.

**Comment by josemariafs** [comment]
I meant this value:

![image](https://user-images.githubusercontent.com/719068/71866361-1d569600-3106-11ea-8d05-a6499cb20cdc.png)

![image](https://user-images.githubusercontent.com/719068/71866346-116ad400-3106-11ea-8662-ce0209902a9f.png)

If it will be "always" wrong, it have no sense to show it... it have a easy fix to work properly

**Comment by IeUDE** [comment]
> Actually show everything, average, repeated, min max etc etc.

Indeed -- Median would be good too (even better then average, in my opinion)

**Comment by Kyusung4698** [comment]
I'll change it to 'most repeated price' for the next release and plan on adding customization for it. Can you please share what kind of price/math funcs you'd like to see. Thanks!

**Comment by IeUDE** [comment]
You want to see other metrics besides the mean, when you have skewed data, which happens here for most of the items ...

So having the min, max, median and mean displayed, will give a better insight about how to price an item ...

https://academy.datawrapper.de/article/136-histogram-min-max-median-mean

**Comment by Kyusung4698** [comment]
> You want to see other metrics besides the mean, when you have skewed data, which happens here for most of the items ...
> 
> So having the min, max, median and mean displayed, will give a better insight about how to price an item ...
> 
> https://academy.datawrapper.de/article/136-histogram-min-max-median-mean

Thank you. That was an interesting read. Also seems pretty doable for the next release.

**Comment by Kyusung4698** [comment]
preview:
![image](https://user-images.githubusercontent.com/38520678/71994924-ea152380-3239-11ea-890e-cab4746ccbc0.png)

let me know what you think!

**Comment by IeUDE** [comment]
Looks good for me, although I have a Economics/Statistics background, and maybe the Mode might bring more problems/questions than solutions/answers for the average user ...

But it is a good start, let's see what others think about this change, i.e. what to add or remove as metrics ...

Another good metric would be the (total) 'count' of the results coming back from the query/search/site ...

**Comment by zaafar** [comment]
What does the graph represent?
I wonder if we can get these stats for top 5, top 10 and second 10 etc etc. Or would it be too much to ask.

Also, how do we take care of flippers?

**Comment by IeUDE** [comment]
> I wonder if we can get these stats for top 5, top 10 and second 10 etc etc. Or would it be too much to ask.
> 
> Also, how do we take care of flippers?

In regards to your first suggestion, does the distribution/bar-plot not answer that?

**Comment by zaafar** [comment]
-> In regards to your first suggestion, does the distribution/bar-plot not answer that?

It’s not readable/user friendly. I mean x-axis and y-axis aren’t explained...no units, no description..

**Comment by Kyusung4698** [comment]
I'll close this issue for now as the original request has been fulfilled. Please open up a new issue if there are still things you'd like to have added! Thank you all for your contributions.
