### ISSUE TITLE
Remove item name from rare items in search

### ISSUE THREAD

**Issue by ishinome** [Kyusung4698/PoE-Overlay#90]
It messes the price and results up when you put the rare items name into the advanced search.

**Comment by Kyusung4698** [comment]
Can you please post an example item data? (CTRL + C) while hovering. Normally the item name should be stripped and only the "base item name" will be used.
But i guess you want to search by category? Like #74.

**Comment by ishinome** [comment]
Oh yeah, I meant to remove the base item name.
For example this item shows the price to be over 12 exalts when in reality it is under 10. Correct prices come when it shows only 2 handed maces.

Rarity: Rare
Chimeric Ruin
Plated Maul
--------
Two Handed Mace
Physical Damage: 62-92
Critical Strike Chance: 5.00%
Attacks per Second: 1.20
Weapon Range: 13
--------
Requirements:
Level: 72
Str: 164
Dex: 68
Int: 159
--------
Sockets: R-B-R-B-R-G 
--------
Item Level: 69
--------
30% increased Stun Duration on Enemies (implicit)
--------
+1 to Level of Socketed Gems
Minions deal 104% increased Damage
Can have up to 3 Crafted Modifiers (crafted)
+2 to Level of Socketed Support Gems (crafted)
Minions have 25% increased Attack Speed (crafted)
Minions have 28% increased Cast Speed (crafted)

**Comment by Kyusung4698** [comment]
no problem. it's added with [0.5.0](https://github.com/Kyusung4698/PoE-Overlay/releases/tag/0.5.0).
