### ISSUE TITLE
The evaluation doesn't work correctly

### ISSUE THREAD

**Issue by svinomatrica** [Kyusung4698/PoE-Overlay#901]
# 🐞 bug report

**Describe the bug**

The evaluation doesn't work correctly

**To Reproduce**
Press ALT + D
All stats = 0

**Expected behavior**

**Screenshots**

https://skr.sh/s7e8KVpRcHt?a

## 🌍  Your Environment

- Version: 1,1,3
- PoE:  e.g. Steam 3.14.0/e English

**Comment by LakiG1** [comment]
same problem here

**Comment by ImpalaPUA** [comment]
Same

**Comment by PeppeJ** [comment]
Same

**Comment by xXDarkNovaXx** [comment]
Same Problem
At first I thought it might be because I was playing in German, but it doesn't matter whether it is German or English
