### ISSUE TITLE
Latest release makes mouse clicks to call the game back, also scroll stopped working

### ISSUE THREAD

**Issue by AtrujanoX** [Kyusung4698/PoE-Overlay#912]
# 🐞 Bug report

**Describe the bug**

Newest version makes my character to walk with clicks made on market tab. Also I used to manipulate values with the scroll wheel in order to raise/lower values, now it does nothing but to zoom in and out the camera in PoE but no interactions on market.

**To Reproduce**

1. Alt+M to market tab
2. Click anywhere inside the tab
3. Watch character move
4. Use scroll wheel on filters
5. Camera will zoom in or out depending on scroll direction

**Expected behavior**

Camera and character not moving while interacting inside the market tab.

## 🌍  Your Environment

- Version:  1.1.14 (2021-05-10)
- PoE:  Steam 3.14.1c English

**Comment by QRage** [comment]
Same here. I cant even evaluate any item.

**Comment by QRage** [comment]
Work well for me now, thanks, dont know what happened.

**Comment by Krullis1** [comment]
Im having similiar issues, however mine is not fixed magically like your's..
Search window closes as soon as you try check/uncheck item filters for price checking items.
also using the popup dropdown menu from whispers doesnt not work properly, it seems to have some issues related to clicking with the mouse.
Everytime i try click while using any inbedded tools my character wants to move to that spot.
