### ISSUE TITLE
Error when inspecting conqueror map

### ISSUE THREAD

**Issue by iTob191** [Kyusung4698/PoE-Overlay#929]
# 🐞 bug report

**Describe the bug**
When trying to inspect (alt+q) a conqueror map, I get the following JS error:
![grafik](https://user-images.githubusercontent.com/8921465/131534748-7bb6fce2-d4a8-49d1-8a80-d81f41eb27ae.png)
(reconstructed from 2 screenshots; white map)

When inspecting a rare map, it looks like this:
![grafik](https://user-images.githubusercontent.com/8921465/131505686-eaa7bca8-03a9-4941-b43c-5f486cf4a32a.png)

Other maps (even ones with an enchantment) work just fine.

**To Reproduce**

1. Open the menu to do a conqueror map at zana.
2. Alt + Q on the map.

**Expected behavior**
Inspect menu works normally and no error is shown.

**Screenshots**
Example map
<img src="https://user-images.githubusercontent.com/8921465/131533782-f7e3da59-f5ac-4f8b-b4e6-c3ddb1143a5b.png" width="500" />

```
Item Class: Maps
Rarity: Normal
Desert Map
--------
Map Tier: 15
Atlas Region: Haewark Hamlet
--------
Item Level: 82
--------
Map contains Drox's Citadel (enchant)
Item Quantity increases amount of Rewards Drox drops by 20% of its value (enchant)
--------
Travel to this Map by using it in a personal Map Device. Maps can only be used once.
--------
Warlord Item
```

## 🌍  Your Environment

- Version: 1.2.4 (2021-08-29)
- PoE: Steam 3.15.3 English

**Comment by Antorell** [comment]
Same issue here when I look up a map.

**Comment by iTob191** [comment]
Tested it and couldn't reproduce it. Not sure if it is somehow dependent on the map or if it has been fixed. I'll close the issue for now.
