### ISSUE TITLE
Ctrl+D not working for me

### ISSUE THREAD

**Issue by ralphony** [Kyusung4698/PoE-Overlay#93]
i have had this prob after 0.4.3 update, i dont know what im doing wrong, Before the 0.4.3 update, i have to use Ctrl+C, then Ctrl+D to make the evaluation to work. Now nothing is working.

**Comment by livejamie** [comment]
I had to run it as admin to get it to work

**Comment by Kyusung4698** [comment]
The hotkey system got reworked in 0.4.2. There were some early issues which have been fixed in the latest version 0.5.0. Please try that version and report back. Thank you! Also try running it as admin.

**Comment by Kyusung4698** [comment]
I'll close this for now. Please re-open if it's still not working. Thanks!
