### ISSUE TITLE
Min/Max values are not handled correctly

### ISSUE THREAD

**Issue by 766b** [Kyusung4698/PoE-Overlay#94]
1. If  `#` selected as min or max value, then both min/max filter values are filled with the same value if second value is whole number and not a range.

Range values are a bit not intuitive. At least for me.

2. In case of `+85 to maximum Life` on belt, value more than 85 can not be set. This case does not really fall into price check category, but more of a look up case. For example if user wants to pull up his gear in order to look for an upgrade. 

3. Edit: some values do not need to be editable, but those are related to unique items, since some of them have static values.
~~~~~~
Rarity: Rare
Enthralling Bite
Searching Eye Jewel
--------
Abyss
--------
Requirements:
Level: 54
--------
Item Level: 75
--------
Adds 2 to 36 Lightning Damage to Attacks
Adds 3 to 28 Lightning Damage to Wand Attacks
Adds 12 to 22 Cold Damage to Wand Attacks
--------
Place into an Abyssal Socket on an Item or into an allocated Jewel Socket on the Passive Skill Tree. Right click to remove from the Socket.

====================

Rarity: Rare
Foe Lash
Stygian Vise
--------
Requirements:
Level: 68
--------
Sockets: A 
--------
Item Level: 86
--------
Has 1 Abyssal Socket (implicit)
--------
+14 to Strength
+493 to Armour
+23 to maximum Energy Shield
+85 to maximum Life
+10% to Cold and Chaos Resistances (crafted)

**Comment by Kyusung4698** [comment]
Thanks for reporting. I'll try my best to clarify the issue.

We need to seperate mods with different value counts. Let's start with a single value:

`Grants Level 20 Death Aura Skill` becomes:
![image](https://user-images.githubusercontent.com/38520678/72671961-cf6d5680-3a52-11ea-91c5-8c193a6c5473.png)
This will query with: min: 18 and max: 999.

Before i can change the range i must enable the max value. This can be done using the `Right` click while hovering over the max value or by hovering over the text. But by hovering over the text - all values are executing the action. This can be used for eg. as a fast toggle for all values.

![image](https://user-images.githubusercontent.com/38520678/72672012-c2049c00-3a53-11ea-9007-c19f2c7cdfc7.png)

Once all values are enable we can expand the range with `Scroll + Up` while hovering over the stat text. If you want to change only the min or max value you need to do so while hovering over the corresponding value.

![image](https://user-images.githubusercontent.com/38520678/72672025-2162ac00-3a54-11ea-8e99-2a12a9bc6d61.png)
This will query with min: 10 and max 30.

Okay. Let's have a look at an another example with multiple values: 
`You take 450 Chaos Damage per second for 3 seconds on Kill` becomes:
![image](https://user-images.githubusercontent.com/38520678/72672053-abab1000-3a54-11ea-9d87-889033d98eb5.png)
And will query with min: 204 and max 999. Why? `405 + 3 = 408 / 2 = 204` This seems pretty strange in the beginning but this is how the query system works. All values are getting merged into two fields the min and max and to do so they need to be averaged. This is also the reason why all fields are editable even tho they are static - to let the user see what he's seaching. 

I hope this helps. Please let me know.
