### ISSUE TITLE
Some mods are not being recognized by parser

### ISSUE THREAD

**Issue by bMiquelin** [Kyusung4698/PoE-Overlay#97]
Using version 0.5.0.
This one seems very stable, and it is helping my price-checking a lot. (much faster than trade-macro) Thank you for making that overlay!

------

I've looked up in my stash tabs and found some mods not being shown in the overlay.

1. (enchant) `Holy Flame Totem fires 2 additional Projectiles` (whitespace at the end of the regex)
2. (enchant) `Ethereal Knives Pierces an additional Target` (whitespace at the end of the regex)
3. `18% reduced Attribute Requirements` (reduced, not increased)
4. (useless/unique) `With at least 40 Intelligence in Radius, Magma Orb` `has 10% increased Area of Effect per Chain` (line break)
5. (useless/unique) `Projectiles Pierce 5 additional Targets while you have Phasing` (not present)
6. `15% reduced Attack Speed` (reduced, not increased)
7. (flask) `11% reduced Mana Cost of Skills during Flask Effect` (reduced, not increased)
8. (flask) `25% reduced Duration` (reduced, not increased)
9. (flask) `Immune to Curses during Flask effect`  `Removes Curses on use` (line break)
10. (flask) `Immunity to Freeze and Chill during Flask effect` `Removes Freeze and Chill on use` (line break)
11. (flask) `Recharges 5 Charges when you take a Critical Strike` (charges in plural)
12. (flask) `Immunity to Bleeding during Flask effect` `Removes Bleeding on use` (line break)

I've seen that the [stats.json file](https://raw.githubusercontent.com/Kyusung4698/PoE-Overlay/master/src/assets/poe/stats.json) has some \\\\\\\\n for the regex of those mods.
I do not know how you made up that giga-file, but when encoding JSON, you need to escape the "\\n" to "\\\\n", but not "\\\\\\\\n"
I think that some of these are not being recognized because of that, like the items 4, 9, 10, 12.
Others like "reduced attack speed", "reduced duration" are not present in the file, but the increased version are.
I gave one example for a plural issue, but I'm almost sure there might be more cases.
![image](https://user-images.githubusercontent.com/8808338/72660356-71d1ff00-39ab-11ea-9c62-7c5b4852c380.png)

I have no idea on the projectiles pierce one.

**Comment by Kyusung4698** [comment]
Thank you for your detailed report! Makes the development so much easier. Most of this will be fixed with the new 0.5.1 version. Also can you please open a new issue with the catalyst quality problem? Thanks! (Helps other people to find this easier)

**Comment by bMiquelin** [comment]
I've moved the catalyst part to a [new issue](https://github.com/Kyusung4698/PoE-Overlay/issues/98)

**Comment by Kyusung4698** [comment]
0.5.1 is now released and should fix those issues. Can you please report back? Thank you!

**Comment by bMiquelin** [comment]
Working as intended on 0.5.1
