### ISSUE TITLE
Catalyst quality property not being recognized 

### ISSUE THREAD

**Issue by bMiquelin** [Kyusung4698/PoE-Overlay#98]
Moved from [issue 97](https://github.com/Kyusung4698/PoE-Overlay/issues/97)

Version 0.5.0
The properties parser is not handling catalyst quality correctly
(Maybe I should've created another issue for that)
Example:
Normal items have `Quality: +20% (augmented)`
But with catalysts, there are different types of qualities, example:
`Quality (Elemental Damage): +1% (augmented)`
`Quality (Attack Modifiers): +1% (augmented)`
There are 7 types of catalysts, and not only those 2 ones. [Link to the list](https://pathofexile.gamepedia.com/List_of_catalysts)
It seems that the item-section-properties-parser is looking for the world "Quality" with a ":" right after it. The `getPhrases()` does not have these quality variants.

**Comment by Kyusung4698** [comment]
Thanks for reporting/suggesting. Added with 0.5.3. Please report back! 👍

**Comment by 766b** [comment]
`+#% Quality to {X} Modifiers` is silently added to jewelry search query without a way to toggle it, this messes up search results. 

Version 0.5.3

**Comment by Kyusung4698** [comment]
> `+#% Quality to {X} Modifiers` is silently added to jewelry search query without a way to toggle it, this messes up search results.
> 
> Version 0.5.3

Currently the pseudo mod is bound to the quality property. I'll seperate them in the next version.

**Comment by Kyusung4698** [comment]
I'll close this for now. Feel free to re-open if needed. Thanks.
